src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_ChamberOfCommerceNumber__c</fullName>
        <description>KvK No.</description>
        <label>National ID number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LG_Footprint__c</fullName>
        <description>Defining Footprint to which a Lead/Company/Account belongs</description>
        <label>Footprint</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UPC</fullName>
                </value>
                <value>
                    <fullName>Ziggo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitCountry__c</fullName>
        <label>Visit Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                    <default>true</default>
                    <label>Germany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    
    <fields>
        <fullName>LG_MACAddress__c</fullName>
        <label>MAC Address</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>B2B_Care_Affected_Services__c</fullName>
        <description>It will capture the affected services from USMS.</description>
        <label>Affected Services</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>B2B_Care_Created_Ticket_From_USMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This will be checked when a ticket is created from USMS.</description>
        <label>Created Ticket From USMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>B2B_Care_Element_Id__c</fullName>
        <description>It captures the element id from USMS.</description>
        <label>Element Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Estimated_Start_Time__c</fullName>
        <description>This field gives information about the estimated start time of the JOB.</description>
        <label>Estimated Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LG_Estimated_resolution_time__c</fullName>
        <description>This field tells you about the estimated resolution time of the JOB.</description>
        <label>Estimated Resolution Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>USMS_Ticket_ID__c</fullName>
        <externalId>true</externalId>
        <label>USMS Ticket ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>LG_B2B_Care_Mass_Outage_Request_UM</fullName>
        <active>true</active>
        <businessProcess>B2B Care Planned And Network</businessProcess>
        <description>Mass Outage</description>
        <label>Outage/Network Incident</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
   
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>LG_ServiceExternalId__c</fullName>
        <label>Billing Service External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ServiceStatus__c</fullName>
        <description>Pick-list to save the status of the service provisioning.</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                  <fullName>LG_SecondaryProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services (Secondary Product Configuration)</relationshipLabel>
        <relationshipName>Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_ProvisioningServiceExternalId__c</fullName>
        <label>Provisioning Service External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Subscription.</description>
        <inlineHelpText>The Account that governs this Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_Care_PM_Outage_Case_from_USMS_Test.cls
@isTest
public class LG_Care_PM_Outage_Case_from_USMS_Test {
    public static RestRequest req;
    public static RestResponse res;
    
    @testSetUp static void setUpMethod() {
        User careAgent=LG_Care_TestRunAsUser.testRunAs();
        System.RunAs(careAgent) {
            No_Triggers__c noTriggers = new No_Triggers__c();
            noTriggers.setUpOwnerId = UserInfo.getUserId();
            noTriggers.Flag__c = true;
            insert noTriggers;
            
            system.debug(noTriggers);
        }
    }
    
    private static JSONGenerator createJSON(String type, Integer switchType, String serviceType) {
        Boolean flag = true;
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        if(type.equalsIgnoreCase('insert')) {
            gen.writeFieldName('setIncident');
            gen.writeStartObject();
            gen.writeStringField('Action','insert');
            if(serviceType == 'B2B VPN DE PROD') {
                gen.writeStringField('service',serviceType);
                gen.writeStringField('Impacted_service_ids','112233');
                gen.writeStringField('Impacted_equipment_ids','112233mac,112233mac2');
                
            }
        }
        else if(type.equalsIgnoreCase('update') || type.equalsIgnoreCase('delete')) {
            gen.writeFieldName('updateIncident');
            gen.writeStartObject();
            if(type.equalsIgnoreCase('update')) {
                gen.writeStringField('Action','update');
            }
            else if(type.equalsIgnoreCase('delete')) {
                gen.writeStringField('Action','delete');
                flag = false;
            }
        }
        if(switchType == 1) {
            gen.writeStringField('Outage_id','CRQ7777');
        }
        else if(switchType == 2) {
            gen.writeStringField('Outage_id','INC7777');
        }
        if(flag) {
            gen.writeStringField('Description','testing');
            gen.writeStringField('Estimated_start_time','2050-09-18T00:07:00+02:00');
            gen.writeStringField('Estimated_end_time','2051-06-18T00:07:00+02:00');
            gen.writeStringField('Priority','Critical');
            gen.writeStringField('Status','Scheduled');
            gen.writeStringField('Element_id','Element_idTest');
            gen.writeStringField('affected_services','affected_servicesTest');
            //gen.writeStringField('service','Not BDS');
        }
        gen.writeEndObject();
        gen.writeEndObject();
        return gen;
    }
    
    @isTest public static void recordCreation() {
        User careAgent= [SELECT Id from User where UserName='careagent.testuser@unityMediaorg.com' limit 1];
        System.runAs(careAgent) 
        {
            res = new restResponse();
            JSONGenerator gen = LG_Care_PM_Outage_Case_from_USMS_Test.createJSON('insert',1,'');
            req = new RestRequest();
            req.requestURI = '/services/apexrest/ticketinsalesforce/';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueOf(gen.getAsString());
            //req.addParameter('request', gen.getAsString());
            RestContext.request = req;
            RestContext.response = res;
            LG_Care_PM_Outage_Case_from_USMS.create_Update_Case();
            system.assertEquals(200, res.statusCode);
        }
    }
    @isTest public static void recordCreationBDSService() {
        User careAgent= [SELECT Id from User where UserName='careagent.testuser@unityMediaorg.com' limit 1];
        System.runAs(careAgent) 
        {
            // creating a service
            Datetime dateTimeInstance = Datetime.now();
            csord__Order_Request__c orderRequest = new csord__Order_Request__c();
            orderRequest.Name = 'Test Order Request';
            orderRequest.csord__Module_Name__c = 'Test Module';
            orderRequest.csord__Module_Version__c = 'Test v1.0';
            orderRequest.csord__Process_Status__c = 'Testing';
            orderRequest.csord__Request_DateTime__c = dateTimeInstance;
            insert orderRequest;
            
            Account acc = new Account();
            acc.Name = 'Planned Maintenance Account';
            acc.LG_VisitCountry__c = 'Germany';
            acc.LG_ChamberOfCommerceNumber__c = '7';
            acc.LG_Footprint__c = 'UPC';
            insert acc;
            
            csord__Subscription__c sub = new csord__Subscription__c();
            sub.Name = 'Business Broadband';
            sub.csord__Account__c = acc.id;
            sub.csord__Identification__c = 'Test Identification';
            sub.csord__Order_Request__c = orderRequest.id;
            insert sub;
            
            csord__Service__c service = new csord__Service__c();
            service.csord__Subscription__c = sub.id;
            service.LG_ServiceExternalId__c = '112245 testing';
            //service.LG_Address__c = address.id;
            service.Name = 'Test Service';
            service.LG_ServiceStatus__c = 'Active';
            service.csord__Order_Request__c = orderRequest.Id;
            service.csord__Identification__c ='test Identification';
            service.UM_ProvisioningServiceExternalId__c='112233';
            insert service;
                        
            Asset a = new Asset();
            a.name = 'hardware';
            a.AccountId = acc.Id;
            a.LG_MACAddress__c = '112233mac';
            a.csord__Service__c = service.Id;
            insert a;
            
            res = new restResponse();
            JSONGenerator gen = LG_Care_PM_Outage_Case_from_USMS_Test.createJSON('insert',1,'B2B VPN DE PROD');
            req = new RestRequest();
            req.requestURI = '/services/apexrest/ticketinsalesforce/';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueOf(gen.getAsString());
            //req.addParameter('request', gen.getAsString());
            RestContext.request = req;
            RestContext.response = res;
            LG_Care_PM_Outage_Case_from_USMS.create_Update_Case();
            system.assertEquals(200, res.statusCode);
        }
    }
    @isTest public static void recordUpdation() {
        try{
            User careAgent= [SELECT Id from User where UserName='careagent.testuser@unityMediaorg.com' limit 1];
            System.runAs(careAgent) {
                Case c = new Case();
                RecordType rtOutage = [SELECT id,Name FROM RecordType WHERE DeveloperName = 'LG_B2B_Care_Mass_Outage_Request_UM'];
                c.RecordTypeId = rtOutage.Id;
                c.USMS_Ticket_ID__c = 'INC7777';
                c.Description = 'test';
                DateTime dt = Datetime.now();
                dt = dt.addDays(1);
                c.LG_Estimated_Start_Time__c = dt;
                c.LG_Estimated_resolution_time__c = dt.addDays(1);
                c.priority = 'Escalated';
                c.status = 'Critical';
                c.B2B_Care_Element_Id__c = 'Element Ids';
                c.B2B_Care_Affected_Services__c = 'Affected Services';
                c.B2B_Care_Created_Ticket_From_USMS__c = true;
                insert c;
                
                res = new restResponse();
                
                JSONGenerator gen = LG_Care_PM_Outage_Case_from_USMS_Test.createJSON('update',2,'');
                req = new RestRequest();
                req.requestURI = '/services/apexrest/ticketinsalesforce/';
                req.httpMethod = 'POST';
                req.requestBody = Blob.valueOf(gen.getAsString());
                //req.addParameter('request', gen.getAsString());
                RestContext.request = req;
                RestContext.response = res;
                LG_Care_PM_Outage_Case_from_USMS.create_Update_Case();
                system.assertEquals(200, res.statusCode);
            }
        }
        catch(exception e)
        {
            
        }
    }
    @isTest public static void recordDeletion() {
        try{
            User careAgent= [SELECT Id from User where UserName='careagent.testuser@unityMediaorg.com' limit 1];
            System.runAs(careAgent) {
                Case c = new Case();
                RecordType rtOutage = [SELECT id,Name FROM RecordType WHERE DeveloperName = 'LG_B2B_Care_Mass_Outage_Request_UM'];
                c.RecordTypeId = rtOutage.Id;
                c.USMS_Ticket_ID__c = 'INC7777';
                c.Description = 'test';
                DateTime dt = Datetime.now();
                dt = dt.addDays(1);
                c.LG_Estimated_Start_Time__c = dt;
                c.LG_Estimated_resolution_time__c = dt.addDays(1);
                c.priority = 'Escalated';
                c.status = 'Critical';
                c.B2B_Care_Element_Id__c = 'Element Ids';
                c.B2B_Care_Affected_Services__c = 'Affected Services';
                c.B2B_Care_Created_Ticket_From_USMS__c = true;
                insert c;
                
                
                res = new restResponse();
                
                JSONGenerator gen = LG_Care_PM_Outage_Case_from_USMS_Test.createJSON('delete',2,'');
                req = new RestRequest();
                req.requestURI = '/services/apexrest/ticketinsalesforce/';
                req.httpMethod = 'POST';
                req.requestBody = Blob.valueOf(gen.getAsString());
                //req.addParameter('request', gen.getAsString());
                RestContext.request = req;
                RestContext.response = res;
                LG_Care_PM_Outage_Case_from_USMS.create_Update_Case();
                system.assertEquals(200, res.statusCode);
            }
        }
        catch(exception e){}
    }
}