src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>LG_ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>csconta__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending activation</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending disconnection</fullName>
                </value>
                <value>
                    <fullName>Disconnected</fullName>
                </value>
		<value>
                    <fullName>Deactivation Requested</fullName>
                </value>
		<value>
                    <fullName>Deactivation Pending</fullName>
                </value>
		<value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KenanServiceConnection__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Authentication_Token__c</fullName>
        <label>Authentication Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_URL__c</fullName>
        <label>Connection URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>REST_Application_Base__c</fullName>
        <defaultValue>&quot;/kenan-salesforce-api&quot;</defaultValue>
        <inlineHelpText>must start with /</inlineHelpText>
        <label>REST Application Base</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Timeout__c</fullName>
        <defaultValue>&quot;120000&quot;</defaultValue>
        <inlineHelpText>Number in milliseconds</inlineHelpText>
        <label>Session Timeout</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stored_Language_Code__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <description>When an enumeration is converted to display value, we need to understand what the stored language value is.</description>
        <label>Stored Language Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>KenanServiceConnection</label>
</CustomObject>

src/objects/UM_BillingAccountItem__c.object
<CustomObject>
    <fields>
        <fullName>UM_BillingAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Billing Account Items</relationshipLabel>
        <relationshipName>Billing_Account_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_BillingCode__c</fullName>
        <label>Billing Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UM_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Billing External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_ItemType__c</fullName>
        <label>Item Type</label>
        <picklist>
            <picklistValues>
                <fullName>Discount</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>One-time Charge</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UM_Percentage__c</fullName>
        <label>Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UM_StartDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Billing Account Item</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>Billing Account Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Account Items</pluralLabel>
    <recordTypes>
        <fullName>Discount</fullName>
        <active>true</active>
        <label>Discount</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UM_BillingAccountItemsSyncTest.cls
@isTest
private class UM_BillingAccountItemsSyncTest
{

    @testSetup static void setupData(){
        No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
        noTriggers.Flag__c = true;
        noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
        upsert noTriggers;
        
        String language, userLanguage = UserInfo.getLanguage();
        for(PicklistEntry value: User.LanguageLocalekey.getDescribe().getPicklistValues()) {
            if(value.getValue() == userLanguage) {
                language = value.getLabel();
                    break;
            }
        }
        
        Account masterAcc = LG_GeneralTest.CreateAccount('TestAcc','123123','123123',true);

        csconta__Billing_Account__c billAcc = LG_GeneralTest.createBillingAccount('1234',masterAcc.id,true,true);
        billAcc.LG_ExternalId__c = '123';
        billAcc.csconta__Status__c = 'Active';
        update billAcc;

        noTriggers.Flag__c = false;
        upsert noTriggers;

    }

    static testMethod void  testExecute(){
       
       KenanServiceConnection__c kenanSettings = KenanServiceConnection__c.getInstance();
          system.debug(kenanSettings.Stored_Language_Code__c);
        kenanSettings.Stored_Language_Code__c='1';
        kenanSettings.Authentication_Token__c='Authorization';
      
        kenanSettings.Session_Timeout__c='120000';
        kenanSettings.Connection_URL__c='https://uat-aws-oag-pe.upc.biz';
        kenanSettings.REST_Application_Base__c='/kenan-salesforce-api';
        insert kenanSettings;
       
        system.debug(userinfo.getDefaultCurrency());
        system.debug(kenanSettings.Stored_Language_Code__c);
        csconta__Billing_Account__c billAcc = [select id from csconta__Billing_Account__c WHERE csconta__Status__c='Active' limit 1];
        system.debug(billAcc.id);
        //User adminUser = [SELECT id FROM USER WHERE profile.name='System Administrator' and isActive= true LIMIT 1];
        Id discountRecordTypeId = Schema.SObjectType.UM_BillingAccountItem__c.getRecordTypeInfosByName().get('Discount').getRecordTypeId();
        UM_BillingAccountItem__c billAccItem = new UM_BillingAccountItem__c();
        //system.RunAs(adminUser)
        //{
            
            billAccItem.UM_BillingAccount__c = billAcc.id;
            billAccItem.UM_BillingCode__c = '1905';
            billAccItem.UM_EndDate__c = Date.Today()+5;
            billAccItem.UM_StartDate__c = Date.Today();
            billAccItem.UM_Percentage__c = 10;
            billAccItem.UM_ItemType__c = 'Discount';
            billAccItem.recordTypeId = discountRecordTypeId ;
            insert billAccItem;
        //}
       system.debug(billAccItem);
          Test.startTest();
        list<sobject> itemsList=NEW list<sobject>();
        itemsList.add(billAccItem);
        
        //KenanAccountItem
        KenanAccountItem ksi = new KenanAccountItem();
        ksi.serviceExternalId = 'serviceExternalId';
        ksi.serviceExternalIdType = 2;
        ksi.itemId = 1302;
        ksi.itemType = 1;

        KenanAccountItemCalloutMock accountItemMock = new KenanAccountItemCalloutMock();
        accountItemMock.numberOfRecords = 3;
        Test.setMock(HttpCalloutMock.class, accountItemMock);

        
    /*  KenanConnectorService service = new KenanConnectorService();
        List<KenanAccountItem> returnAccountItems = service.accountItemCreate(ksi); 
        Test.stopTest();
    
        System.assertNotEquals(null, returnAccountItems);
        System.assert(!returnAccountItems.isEmpty());
        System.assertEquals(accountItemMock.numberOfRecords, returnAccountItems.size());

        for (KenanAccountItem accountItem: returnAccountItems) {
            System.assertEquals('Test Annotation', accountItem.annotation);
            System.assertEquals('Test Annotation 2', accountItem.annotation2);
            System.assertEquals('EUR', accountItem.currencyCode);
            System.assertEquals(0.0, accountItem.rate);
            System.assertEquals('1', accountItem.salesforceId);
        }*/
    
        
        
        
        UM_BillingAccountItemsSync S1=NEW UM_BillingAccountItemsSync();
        S1.execute(itemsList);
        Test.stopTest();
        //system.assertEquals(, );

       // System.assertNotEquals(null,[select id,UM_External_Id__c from UM_BillingAccountItem__c where id = :billAccItem.id].UM_External_Id__c);
    }
}