src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_ChamberOfCommerceNumber__c</fullName>
        <description>KvK No.</description>
        <label>National ID number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LG_Footprint__c</fullName>
        <description>Defining Footprint to which a Lead/Company/Account belongs</description>
        <label>Footprint</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UPC</fullName>
                </value>
                <value>
                    <fullName>Ziggo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitCountry__c</fullName>
        <label>Visit Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                    <default>true</default>
                    <label>Germany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Basket__c.object
<CustomObject>
    <description>Basket to supercede bundles...</description>
    <fields>
        <fullName>LG_CreatedFrom__c</fullName>
        <label>Created From</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Web</fullName>
                    <default>true</default>
                    <label>Web</label>
                </value>
                <value>
                    <fullName>Tablet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Basket</label>
    <nameField>
        <label>Product Basket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Baskets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Basket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of associated Product Basket.</inlineHelpText>
        <label>Product Basket</label>
        <referenceTo>cscfga__Product_Basket__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Product Definition from which this Configuration was derived.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Definition__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product Category that this Product Definition belongs to.</inlineHelpText>
        <label>Product Category</label>
        <referenceTo>cscfga__Product_Category__c</referenceTo>
        <relationshipLabel>Product Definitions</relationshipLabel>
        <relationshipName>Product_Definitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_TelephoneUtilitytest.cls
@istest
public class LG_TelephoneUtilitytest {
    
    public static testmethod void utiltest(){
             Account acc = new Account();
        acc.Name = 'Planned Maintenance Account';
        acc.LG_VisitCountry__c = 'Germany';
        acc.LG_ChamberOfCommerceNumber__c = '7';
        acc.LG_Footprint__c = 'UPC';
        insert acc;
        
          Account account = LG_GeneralTest.CreateAccount('AccountSFDT', '12345678', 'Ziggo', true);
        
        Opportunity opp = LG_GeneralTest.CreateOpportunity(account, true);
        
        cscfga__Product_Basket__c basket = LG_GeneralTest.createProductBasket('PC Test Basket', account, null, opp, false);
        
        basket.LG_CreatedFrom__c = 'Tablet';
        insert basket;
        
        cscfga__Product_Category__c productCategory = LG_GeneralTest.createProductCategory('PC Test Category', true);
        cscfga__Product_Definition__c productDefinition = LG_GeneralTest.createProductDefinition('PC Test Product', false);
        
        productDefinition.cscfga__Product_Category__c = productCategory.Id;
        
        insert productDefinition;
        cscfga__Product_Configuration__c pc = LG_GeneralTest.createProductConfiguration('Test', 12, basket, productDefinition, true);

        
        Opportunity tmpOpp = LG_GeneralTest.CreateOpportunity(acc);
        system.debug(tmpOpp.id);
       test.startTest();
        LG_TelephoneUtility.CreatePortingStructure('SOHO Telephony', '{"Existing_Phone_Numbers_0": "true" ,"Telephone_Number_0": "1234567891"}', pc.id,tmpOpp.id );
       test.stopTest();
        
    }
   
      public static testmethod void porttest(){
        
       test.startTest();
          LG_TelephoneUtility.CreatePortingStructure('SOHO Telephony', '{"Extra_Line_Porting_Number_0": "true"}',' pPCId', 'pOppId');
       test.stopTest();
        
    }
      public static testmethod void structtest(){
            Account acc = new Account();
        acc.Name = 'Planned Maintenance Account';
        acc.LG_VisitCountry__c = 'Germany';
        acc.LG_ChamberOfCommerceNumber__c = '7';
        acc.LG_Footprint__c = 'UPC';
        insert acc;
          
           Account account = LG_GeneralTest.CreateAccount('AccountSFDT', '12345678', 'Ziggo', true);
        
        Opportunity opp = LG_GeneralTest.CreateOpportunity(account, true);
        
        cscfga__Product_Basket__c basket = LG_GeneralTest.createProductBasket('PC Test Basket', account, null, opp, false);
        
        basket.LG_CreatedFrom__c = 'Tablet';
        insert basket;
        
        cscfga__Product_Category__c productCategory = LG_GeneralTest.createProductCategory('PC Test Category', true);
        cscfga__Product_Definition__c productDefinition = LG_GeneralTest.createProductDefinition('PC Test Product', false);
        
        productDefinition.cscfga__Product_Category__c = productCategory.Id;
        
        insert productDefinition;
        cscfga__Product_Configuration__c pc = LG_GeneralTest.createProductConfiguration('Test', 12, basket, productDefinition, true);


        
        Opportunity tmpOpp = LG_GeneralTest.CreateOpportunity(acc);
        system.debug(tmpOpp.id);
       test.startTest();
          LG_TelephoneUtility.CreatePortingStructure('Mobile Telephony', '[{"simType": "port number","contractType":"contract"},{"contractType":"contract1"}]',pc.id, tmpOpp.id);
       test.stopTest();
        
    }
     public static testmethod void util(){
        
       test.startTest();
       LG_TelephoneUtility.CreatePortingStructure('Mobile Telephony', 'JSONString',' pPCId', 'pOppId');
       test.stopTest();
        
    }
}