src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_BankAccountHolder__c</fullName>
        <label>Bank Account Holder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_BankAccountNumberIBAN__c</fullName>
        <label>Bank Account Number (IBAN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_BillingEmailAddress__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LG_ChamberOfCommerceNumber__c</fullName>
        <description>KvK No.</description>
        <label>National ID number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LG_PaymentType__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self-payer</fullName>
                    <default>true</default>
                    <label>Self-payer</label>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_PostalCity__c</fullName>
        <description>Postal City</description>
        <label>Postal City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalHouseNumberExtension__c</fullName>
        <label>Postal House Number Extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalHouseNumber__c</fullName>
        <label>Postal House Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalPostalCode__c</fullName>
        <label>Postal Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalStreet__c</fullName>
        <label>Postal Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SoHo</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
                <value>
                    <fullName>LE</fullName>
                </value>
                <value>
                    <fullName>Wholesale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VIP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UM_Legal_Name__c</fullName>
        <label>Account Name Extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_VisitStateProvince__c</fullName>
        <label>Visit State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_BankAccountHolder__c</fullName>
        <description>Name registered to the Bank Account number</description>
        <label>Bank Account Holder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_BankAccountNumberIBAN__c</fullName>
        <label>Bank Account Number (IBAN)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_BillingEmailAddress__c</fullName>
        <label>Billing Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LG_HouseNumberExtension__c</fullName>
        <label>House Number Extension</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_HouseNumber__c</fullName>
        <label>House Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PaymentType__c</fullName>
        <description>Payment Type / Method used by the customer</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Self-payer</fullName>
                    <default>true</default>
                    <label>Self-payer</label>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_BillFormatOptions__c</fullName>
        <label>Bill Format Option</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Summary</fullName>
                    <default>true</default>
                    <label>Summary</label>
                </value>
                <value>
                    <fullName>With itemized bill - masked last 3 digits</fullName>
                </value>
                <value>
                    <fullName>With itemized bill - full unmasked numbers</fullName>
                </value>
                <value>
                    <fullName>Summary - no itemized bill</fullName>
                    <isActive>false</isActive>
                    <label>Summary - no itemized bill</label>
                </value>
                <value>
                    <fullName>With itemized bill - full unmasked numbers - full EVN</fullName>
                    <isActive>false</isActive>
                    <label>With itemized bill - full unmasked numbers - full EVN</label>
                </value>
                <value>
                    <fullName>With itemized bill - masked last 3 digits - partial EVN</fullName>
                    <isActive>false</isActive>
                    <label>With itemized bill - masked last 3 digits - partial EVN</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_Billing_State_Province__c</fullName>
        <description>State\Province field</description>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csconta__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csconta__Billing_Channel__c</fullName>
        <label>Billing Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paper</fullName>
                    <default>true</default>
                    <label>Paper</label>
                </value>
                <value>
                    <fullName>E-Mail PDF</fullName>
                </value>
                <value>
                    <fullName>Paper + E-Mail PDF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csconta__City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csconta__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csconta__Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly 1st - 30 days payment term</fullName>
                </value>
                <value>
                    <fullName>M02 - Test</fullName>
                </value>
                <value>
                    <fullName>M09 - Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csconta__Postcode__c</fullName>
        <label>Postcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csconta__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending activation</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending disconnection</fullName>
                </value>
                <value>
                    <fullName>Disconnected</fullName>
                </value>
		<value>
                    <fullName>Deactivation Requested</fullName>
                </value>
		<value>
                    <fullName>Deactivation Pending</fullName>
                </value>
		<value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csconta__Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>LG_HouseNumberExtension__c</fullName>
        <description>US SFDT-54 - House Number extension data</description>
        <label>House Number Extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_HouseNumber__c</fullName>
        <description>Standard House Number</description>
        <label>House Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csconta__Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Billing Account to use for this Subscription.</description>
        <inlineHelpText>The Billing Account to use for this Subscription.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KenanServiceConnection__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Authentication_Token__c</fullName>
        <label>Authentication Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_URL__c</fullName>
        <label>Connection URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>REST_Application_Base__c</fullName>
        <defaultValue>&quot;/kenan-salesforce-api&quot;</defaultValue>
        <inlineHelpText>must start with /</inlineHelpText>
        <label>REST Application Base</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Timeout__c</fullName>
        <defaultValue>&quot;120000&quot;</defaultValue>
        <inlineHelpText>Number in milliseconds</inlineHelpText>
        <label>Session Timeout</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stored_Language_Code__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <description>When an enumeration is converted to display value, we need to understand what the stored language value is.</description>
        <label>Stored Language Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>KenanServiceConnection</label>
</CustomObject>

src/classes/UM_Deactivate_Billing_Account_Test.cls
@isTest
public class UM_Deactivate_Billing_Account_Test{

  @testsetup
   private static void setupTestData()
   {
        KenanServiceConnection__c ksc = new KenanServiceConnection__c();
        ksc.Authentication_Token__c = 'Basic YWRtaW46YWRtaW4=';
        ksc.Session_Timeout__c = '120000';
        ksc.Connection_URL__c = 'https://dev-aws-oag-pe.upc.biz';
        ksc.REST_Application_Base__c = '/kenan-salesforce-api/rest';
        ksc.Stored_Language_Code__c = '1';
        insert ksc; 
        
//Insert Account:
        Account mAccount = new Account(Name='Test Account');
        mAccount.LG_BillingEmailAddress__c='ra.su@infy.com';
        mAccount.LG_PostalStreet__c = 'Aachener Str.';
        mAccount.LG_PostalCity__c = 'Köln';
        mAccount.UM_VisitStateProvince__c = 'NRW';
        mAccount.LG_PostalPostalCode__c = '50933';
        mAccount.LG_PostalHouseNumber__c = '746';
        mAccount.LG_PostalHouseNumberExtension__c = '-750';
        mAccount.LG_Segment__c='SME';
        mAccount.LG_ChamberOfCommerceNumber__c = 'C12685333';
        mAccount.LG_VIP__c=false;
        mAccount.UM_Legal_Name__c='abc';
        insert mAccount;
        
//insert Billing contact:
        Contact billingContact = new Contact(FirstName = 'First', LastName = 'Last', AccountId = mAccount.id, Salutation='Mr.');
        insert billingContact;
        
//Insert BA:
        csconta__Billing_Account__c billingAccount = new csconta__Billing_Account__c (csconta__Account__c = mAccount.id);
        billingAccount.csconta__Status__c = 'Deactivation Requested'; 
        billingAccount.csconta__Billing_Channel__c = 'Paper'; 
        billingAccount.UM_BillFormatOptions__c = 'Summary';
        billingAccount.Billing_Contact__c = billingContact.id; 
        billingAccount.LG_PaymentType__c = 'Direct debit';
        billingAccount.LG_BankAccountNumberIBAN__c = 'DE85604500500002819471';
        billingAccount.LG_BankAccountHolder__c='Test BA';
        billingAccount.csconta__Payment_Terms__c = 'M02 - Test'; 
        billingAccount.csconta__Street__c='Aachener Str.'; 
        billingAccount.LG_HouseNumber__c='746';
        billingAccount.LG_HouseNumberExtension__c ='-750'; 
        billingAccount.csconta__City__c= 'Köln'; 
        billingAccount.csconta__Country__c= 'Germany'; 
        billingAccount.UM_Billing_State_Province__c= 'NRW'; 
        billingAccount.csconta__Postcode__c = '50933';
        insert billingAccount;
    
        csord__Order_Request__c coreq = new csord__Order_Request__c(csord__Module_Name__c = 'TestM', csord__Module_Version__c = '1.0');
            insert coreq;
        
    csord__Subscription__c sub = new csord__Subscription__c(csord__Account__c=mAccount.id,csord__Identification__c = 'TestIdentM',csord__Status__c='Active', csord__Order_Request__c = coreq.Id, csconta__Billing_Account__c=billingAccount.Id);
    insert sub;
    
    cscrm__Address__c add= new cscrm__Address__c(cscrm__Street__c = 'TestStreetM');
    insert add;
    csord__Service__c intService = new csord__Service__c(csord__Identification__c = 'TestIdentSubM', csord__Order_Request__c = coreq.Id,csord__Status__c='Inactive',
                              csord__Subscription__c = sub.Id, csord__Deactivation_Date__c=Date.Today()-1, LG_Address__c = add.Id, LG_ProductFamily__c = 'Internet');
    insert intService;
    
    /** --Second Records--**/
    //Insert BA:
        csconta__Billing_Account__c billingAccount2 = new csconta__Billing_Account__c (csconta__Account__c = mAccount.id);
        billingAccount2.csconta__Status__c = 'New'; 
        billingAccount2.csconta__Billing_Channel__c = 'Paper'; 
        billingAccount2.UM_BillFormatOptions__c = 'Summary';
        billingAccount2.Billing_Contact__c = billingContact.id; 
        billingAccount2.LG_PaymentType__c = 'Direct debit';
        billingAccount2.LG_BankAccountNumberIBAN__c = 'DE85604500500002819471';
        billingAccount2.LG_BankAccountHolder__c='Test BA';
        billingAccount2.csconta__Payment_Terms__c = 'M02 - Test'; 
        billingAccount2.csconta__Street__c='Aachener Str.'; 
        billingAccount2.LG_HouseNumber__c='746';
        billingAccount2.LG_HouseNumberExtension__c ='-750'; 
        billingAccount2.csconta__City__c= 'Köln'; 
        billingAccount2.csconta__Country__c= 'Germany'; 
        billingAccount2.UM_Billing_State_Province__c= 'NRW'; 
        billingAccount2.csconta__Postcode__c = '50933';
        insert billingAccount2;
    
        csord__Order_Request__c coreq2 = new csord__Order_Request__c(csord__Module_Name__c = 'TestM', csord__Module_Version__c = '1.0');
            insert coreq2;
        
    csord__Subscription__c sub2 = new csord__Subscription__c(csord__Account__c=mAccount.id,csord__Identification__c = 'TestIdentM',csord__Status__c='Active', csord__Order_Request__c = coreq2.Id, csconta__Billing_Account__c=billingAccount2.Id);
    insert sub2;
    
    csord__Service__c intService2 = new csord__Service__c(csord__Identification__c = 'TestIdentSubM', csord__Order_Request__c = coreq2.Id,csord__Status__c='Inactive',
                              csord__Subscription__c = sub2.Id, csord__Deactivation_Date__c=Date.Today(), LG_Address__c = add.Id, LG_ProductFamily__c = 'Internet');
    insert intService2;
    
    /** --Third Records--**/
    //Insert BA:
        csconta__Billing_Account__c billingAccount3 = new csconta__Billing_Account__c (csconta__Account__c = mAccount.id);
        billingAccount3.csconta__Status__c = 'New'; 
        billingAccount3.csconta__Billing_Channel__c = 'Paper'; 
        billingAccount3.UM_BillFormatOptions__c = 'Summary';
        billingAccount3.Billing_Contact__c = billingContact.id; 
        billingAccount3.LG_PaymentType__c = 'Direct debit';
        billingAccount3.LG_BankAccountNumberIBAN__c = 'DE85604500500002819471';
        billingAccount3.LG_BankAccountHolder__c='Test BA';
        billingAccount3.csconta__Payment_Terms__c = 'M02 - Test'; 
        billingAccount3.csconta__Street__c='Aachener Str.'; 
        billingAccount3.LG_HouseNumber__c='746';
        billingAccount3.LG_HouseNumberExtension__c ='-750'; 
        billingAccount3.csconta__City__c= 'Köln'; 
        billingAccount3.csconta__Country__c= 'Germany'; 
        billingAccount3.UM_Billing_State_Province__c= 'NRW'; 
        billingAccount3.csconta__Postcode__c = '50944';
        insert billingAccount3;
       
           
    /** --Fourth Records--**/
    //Insert BA:
        csconta__Billing_Account__c billingAccount4 = new csconta__Billing_Account__c (csconta__Account__c = mAccount.id);
        billingAccount4.csconta__Status__c = 'New'; 
        billingAccount4.csconta__Billing_Channel__c = 'Paper'; 
        billingAccount4.UM_BillFormatOptions__c = 'Summary';
        billingAccount4.Billing_Contact__c = billingContact.id; 
        billingAccount4.LG_PaymentType__c = 'Direct debit';
        billingAccount4.LG_BankAccountNumberIBAN__c = 'DE85604500500002819471';
        billingAccount4.LG_BankAccountHolder__c='Test BA';
        billingAccount4.csconta__Payment_Terms__c = 'M02 - Test'; 
        billingAccount4.csconta__Street__c='Aachener Str.'; 
        billingAccount4.LG_HouseNumber__c='746';
        billingAccount4.LG_HouseNumberExtension__c ='-750'; 
        billingAccount4.csconta__City__c= 'Köln'; 
        billingAccount4.csconta__Country__c= 'Germany'; 
        billingAccount4.UM_Billing_State_Province__c= 'NRW'; 
        billingAccount4.csconta__Postcode__c = '00001';
        insert billingAccount4;
}
   
   /**This will test the method deactiavteBA if Service Deactivate Date is less than Today's date**/
   static testMethod void testDeactivateBATrue ()
   {
     csconta__Billing_Account__c  billAcc =[SELECT id,csconta__Status__c FROM csconta__Billing_Account__c 
                                                     WHERE csconta__Status__c ='Deactivation Requested' LIMIT 1];
     String BillingId = billAcc.Id;
     Test.startTest();
     UM_Deactivate_Billing_Account.deactivateBA(BillingId);
     billAcc.csconta__Status__c = 'New';
     update billAcc;
     UM_Deactivate_Billing_Account.deactivateBA(BillingId);
     test.stopTest();
     
   }
 
   /**This will test the method deactiavteBA if Service Deactivate Date is equal or greater than Today's date**/
   static testMethod void testDeactivateBAForGreaterDate ()
   {
     csconta__Billing_Account__c  billAcc =[SELECT id,csconta__Status__c FROM csconta__Billing_Account__c 
                                                     WHERE csconta__Status__c ='New' LIMIT 1];
     String BillingId = billAcc.Id;
     Test.startTest();
     UM_Deactivate_Billing_Account.deactivateBA(BillingId);
     test.stopTest();
     
   }
   
   /**This will test the method deactiavteBA if No Service is attached with the BA **/
   static testMethod void testDeactivateBANoService()
   {
    csconta__Billing_Account__c  billAcc =[SELECT id,csconta__Status__c FROM csconta__Billing_Account__c 
                                                     WHERE csconta__Status__c ='Deactivation Requested' LIMIT 1];
     String BillingId = billAcc.Id;
     Test.startTest();
    // UM_Deactivate_Billing_Account.deactivateBA(BillingId);
     billAcc.csconta__Status__c = 'Deactivation Pending';
     update billAcc;
     UM_Deactivate_Billing_Account.deactivateBA(BillingId);
     test.stopTest();
     
   }
    
     /**This will test the method deactiavteBA if Associated Services does not meet the criteria **/
   static testMethod void testDeactivateBANoFilteredService()
   {
     csconta__Billing_Account__c  billingAccount3 =[SELECT id,csconta__Status__c FROM csconta__Billing_Account__c 
                                                     WHERE csconta__Postcode__c ='50944' LIMIT 1];
     String BillingId = billingAccount3.Id;
    
       Account mAccount = [Select id FROM Account where UM_Legal_Name__c = 'abc'];
       csord__Order_Request__c coreq3 = new csord__Order_Request__c(csord__Module_Name__c = 'TestM', csord__Module_Version__c = '1.0');
            insert coreq3;
        
    csord__Subscription__c sub3 = new csord__Subscription__c(csord__Account__c=mAccount.id,csord__Identification__c = 'TestIdentM',csord__Status__c='Active', csord__Order_Request__c = coreq3.Id, csconta__Billing_Account__c=billingAccount3.Id);
    insert sub3;
     cscrm__Address__c add= new cscrm__Address__c(cscrm__Street__c = 'TestStreetM');
    insert add;
    csord__Service__c intService3 = new csord__Service__c(csord__Identification__c = 'TestIdentSubM', csord__Order_Request__c = coreq3.Id,csord__Status__c='Active',
                              csord__Subscription__c = sub3.Id, csord__Deactivation_Date__c=Date.Today()-1, LG_Address__c = add.Id, LG_ProductFamily__c = 'Internet');
    insert intService3;
       
     Test.startTest();
     UM_Deactivate_Billing_Account.deactivateBA(BillingId);
     test.stopTest();
     
   }
    
    /**This will test the method deactiavteBA and will check BA status**/
   static testMethod void testDeactivateBAStatus()
   {
     csconta__Billing_Account__c  billAcc =[SELECT id,csconta__Status__c FROM csconta__Billing_Account__c 
                                                     WHERE csconta__Status__c ='Deactivation Requested' LIMIT 1];
     String BillingId = billAcc.Id;
     Test.startTest();
     billAcc.csconta__Status__c = 'Deactivation Pending';
     update billAcc;
     UM_Deactivate_Billing_Account.deactivateBA(BillingId);
     billAcc.csconta__Status__c = 'Inactive';
     update billAcc;
     UM_Deactivate_Billing_Account.deactivateBA(BillingId);
     test.stopTest();
     
   }
  
}