src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_ContractualOrganization__c</fullName>
        <label>Contractual Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LG_ContractualOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_LegalEntityType__c</fullName>
        <label>Legal Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LG_LegalEntityType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SoHo</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
                <value>
                    <fullName>LE</fullName>
                </value>
                <value>
                    <fullName>Wholesale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitCountry__c</fullName>
        <label>Visit Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                    <default>true</default>
                    <label>Germany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitPostalCode__c</fullName>
        <label>Visit Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_IndustryClassification__c</fullName>
        <label>Industry Classification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UM_IndustryClassification</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_Legal_Name__c</fullName>
        <label>Account Name Extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_VisitStateProvince__c</fullName>
        <label>Visit State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>LG_ContractualOrganization__c</fullName>
        <label>Contractual Organization</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LG_ContractualOrganization</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_LegalEntityType__c</fullName>
        <label>Legal Entity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LG_LegalEntityType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_MatchingAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field on Lead to Account</description>
        <inlineHelpText>When a matching account is found please convert lead to an existing account without the creation of an opportunity</inlineHelpText>
        <label>Matching Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SOHO</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
                <value>
                    <fullName>LE</fullName>
                </value>
                <value>
                    <fullName>Wholesale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitCountry__c</fullName>
        <label>Visit Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                    <default>true</default>
                    <label>Germany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitPostalCode__c</fullName>
        <label>Visit Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_IndustryClassification__c</fullName>
        <label>Industry Classification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UM_IndustryClassification</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_Legal_Name__c</fullName>
        <label>Account Name Extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_Product__c</fullName>
        <description>Field to capture selected product from web form</description>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UM_Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_VisitStateProvince__c</fullName>
        <label>Visit State/Province</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BW</fullName>
                </value>
                <value>
                    <fullName>HSN</fullName>
                </value>
                <value>
                    <fullName>NRW</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Assignment_Table__c.object
<CustomObject>
    <fields>
        <fullName>Assign_to_Queue__c</fullName>
        <label>Assign to Queue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Assignee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Lead_Assignment_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Company Internet</fullName>
                </value>
                <value>
                    <fullName>Company Fiber</fullName>
                </value>
                <value>
                    <fullName>Virtual Voice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lead Assignment Table</label>
    <nameField>
        <displayFormat>LAT-{000000}</displayFormat>
        <label>Lead Assignment Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Assignment Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>QueueID__c</fullName>
        <label>QueueID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Queue Name</label>
</CustomObject>

src/globalValueSets/LG_ContractualOrganization.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Baden-Württemberg (BAW)</fullName>
    </customValue>
    <customValue>
        <fullName>Hessen (HSN)</fullName>
    </customValue>
    <customValue>
        <fullName>Nordrhein-Westfalen (NRW)</fullName>
    </customValue>
    <customValue>
        <fullName>Hessen</fullName>
        <isActive>false</isActive>
        <label>Hessen</label>
    </customValue>
    <customValue>
        <fullName>BW</fullName>
        <isActive>false</isActive>
        <label>BW</label>
    </customValue>
    <customValue>
        <fullName>NRW</fullName>
        <isActive>false</isActive>
        <label>NRW</label>
    </customValue>
    <masterLabel>Contractual Organization</masterLabel>
</GlobalValueSet>

src/globalValueSets/LG_LegalEntityType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Adoer</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AG &amp; Co. KG</fullName>
    </customValue>
    <customValue>
        <fullName>AG &amp; Co. KGaA</fullName>
    </customValue>
    <customValue>
        <fullName>Andere</fullName>
    </customValue>
    <customValue>
        <fullName>e. G./eG.</fullName>
    </customValue>
    <customValue>
        <fullName>e. K./e. Kfm./e. Kffr.</fullName>
    </customValue>
    <customValue>
        <fullName>e. V.</fullName>
    </customValue>
    <customValue>
        <fullName>gAG</fullName>
    </customValue>
    <customValue>
        <fullName>GbR</fullName>
    </customValue>
    <customValue>
        <fullName>gGmbH</fullName>
    </customValue>
    <customValue>
        <fullName>GmbH</fullName>
    </customValue>
    <customValue>
        <fullName>GmbH &amp; Co. KG</fullName>
    </customValue>
    <customValue>
        <fullName>GmbH &amp; Co. KGaA</fullName>
    </customValue>
    <customValue>
        <fullName>GmbH  &amp; Co. OHG</fullName>
    </customValue>
    <customValue>
        <fullName>G-REIT</fullName>
    </customValue>
    <customValue>
        <fullName>i. G.</fullName>
    </customValue>
    <customValue>
        <fullName>InvAG</fullName>
    </customValue>
    <customValue>
        <fullName>kdöR/K. d. ö. R.</fullName>
    </customValue>
    <customValue>
        <fullName>KG</fullName>
    </customValue>
    <customValue>
        <fullName>KGaA</fullName>
    </customValue>
    <customValue>
        <fullName>Ltd.</fullName>
    </customValue>
    <customValue>
        <fullName>OHG</fullName>
    </customValue>
    <customValue>
        <fullName>PartG</fullName>
    </customValue>
    <customValue>
        <fullName>UG</fullName>
    </customValue>
    <customValue>
        <fullName>UG &amp; Co. KG</fullName>
    </customValue>
    <customValue>
        <fullName>VVaG</fullName>
    </customValue>
    <customValue>
        <fullName>GmbH/Ges. m. b. H.</fullName>
    </customValue>
    <customValue>
        <fullName>GmbH, GbR</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <masterLabel>Legal Entity Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

src/classes/LG_LeadUpdateTriggerTest.cls
@isTest
public class LG_LeadUpdateTriggerTest {
    
    // Lead with (Product Family, Postal code) And Lead Assignee Table with (Lead Assigee, Product Family & Postal code)
    static testmethod void testTrigger1(){
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
        User usr = new User(LastName = 'testUser',
                            FirstName='FirstName',
                            Alias = '242793',
                            Email = 'abc@asdf1.com',
                            Username = 'abc@asdf11.com',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US',
                            CompanyName = 'testComp'
                           );
        insert usr; 
        
        //List<Group> smeQueueID = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperNAME = 'SME_Queue'];
        //ID queueID = Queue_Name__c.getInstance('QueueName').QueueID__c;
        
        Queue_Name__c cs = new Queue_Name__c(Name = 'QueueName', QueueID__c = '00G58000002n2wS');
        insert cs;
        
        Lead_Assignment_Table__c LAT = new Lead_Assignment_Table__c();
        LAT.Product_Family__c = 'Company Internet';
        LAT.Postal_Code__c = 'BW-720';
        LAT.Lead_Assignee__c = usr.Id; //'00558000001m361';
        insert LAT;
        
        Lead lead = new Lead();
        lead.OwnerId = cs.QueueID__c;//smeQueueID[0].Id;	//'00G58000002n2wS';
        lead.UM_Legal_Name__c = 'testAcc';
        lead.Status = 'New';
        lead.LG_LegalEntityType__c = 'AG';
        lead.LastName = 'testLead';
        lead.Email = 'test@test.com';
        lead.Phone = '0711111111';
        lead.LG_VisitPostalCode__c = 'BW-720';
        lead.UM_Product__c = 'Company Internet';
        lead.UM_IndustryClassification__c = 'F BAUGEWERBE';
        lead.LG_Segment__c  = 'SME';
        lead.LG_ContractualOrganization__c = 'Baden-Württemberg (BAW)';
        lead.UM_VisitStateProvince__c = 'BW';
        lead.LG_VisitCountry__c = 'Germany';
        lead.Company = 'testComapny';
        insert lead;
    }
    
    // Lead with (Product Family, Postal code) And Lead Assignee Table with (Assign to Queue, Product Family & Postal code)
    static testmethod void testTrigger2(){ 
        
        //List<Group> smeQueueID = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperNAME = 'SME_Queue'];
        Queue_Name__c cs = new Queue_Name__c(Name = 'QueueName', QueueID__c = '00G58000002n2wS');
        insert cs;
        
        Lead_Assignment_Table__c LAT = new Lead_Assignment_Table__c();
        LAT.Product_Family__c = 'Company Internet';
        LAT.Postal_Code__c = 'BW-720';
        LAT.Assign_to_Queue__c = cs.QueueID__c;//smeQueueID[0].id;//'00558000001m361';
        insert LAT;
        
        Lead lead = new Lead();
        lead.OwnerId = cs.QueueID__c;//smeQueueID[0].id;//'00G58000002n2wS';
        lead.UM_Legal_Name__c = 'testAcc';
        lead.Status = 'New';
        lead.LG_LegalEntityType__c = 'AG';
        lead.LastName = 'testLead';
        lead.Email = 'test@test.com';
        lead.Phone = '0711111111';
        lead.LG_VisitPostalCode__c = 'BW-720';
        lead.UM_Product__c = 'Company Internet';
        lead.UM_IndustryClassification__c = 'F BAUGEWERBE';
        lead.LG_Segment__c  = 'SME';
        lead.LG_ContractualOrganization__c = 'Baden-Württemberg (BAW)';
        lead.UM_VisitStateProvince__c = 'BW';
        lead.LG_VisitCountry__c = 'Germany';
        lead.Company = 'testComapny';
        insert lead;
    }
    
    // Lead with (Postal code only, no Product Family) And Lead Assignee Table with (Lead Assigee & Postal code)
    static testmethod void testTrigger3(){
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
        User usr = new User(LastName = 'testUser',
                            FirstName='FirstName',
                            Alias = '242793',
                            Email = 'abc@asdf1.com',
                            Username = 'abc@asdf11.com',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US',
                            CompanyName = 'testComp'
                           );
        insert usr; 
        
        //List<Group> smeQueueID = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperNAME = 'SME_Queue'];
        Queue_Name__c cs = new Queue_Name__c(Name = 'QueueName', QueueID__c = '00G58000002n2wS');
        insert cs;
        
        Lead_Assignment_Table__c LAT = new Lead_Assignment_Table__c();
        //LAT.Product_Family__c = 'Company Internet';
        LAT.Postal_Code__c = 'BW-720';
        LAT.Lead_Assignee__c = usr.Id; //'00558000001m361';
        insert LAT;
        
        Lead lead = new Lead();
        lead.OwnerId = cs.QueueID__c;//smeQueueID[0].id;//'00G58000002n2wS';
        lead.UM_Legal_Name__c = 'testAcc';
        lead.Status = 'New';
        lead.LG_LegalEntityType__c = 'AG';
        lead.LastName = 'testLead';
        lead.Email = 'test@test.com';
        lead.Phone = '0711111111';
        lead.LG_VisitPostalCode__c = 'BW-720';
        //lead.UM_Product__c = 'Company Internet';
        lead.UM_IndustryClassification__c = 'F BAUGEWERBE';
        lead.LG_Segment__c  = 'SME';
        lead.LG_ContractualOrganization__c = 'Baden-Württemberg (BAW)';
        lead.UM_VisitStateProvince__c = 'BW';
        lead.LG_VisitCountry__c = 'Germany';
        lead.Company = 'testComapny';
        insert lead;
    }
    
	// Lead with (Postal code only, no Product Family) And Lead Assignee Table with (Assign to Queue & Postal code)
    static testmethod void testTrigger4(){
        
        //List<Group> smeQueueID = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperNAME = 'SME_Queue'];
        Queue_Name__c cs = new Queue_Name__c(Name = 'QueueName', QueueID__c = '00G58000002n2wS');
        insert cs;
        
        Lead_Assignment_Table__c LAT = new Lead_Assignment_Table__c();
        //LAT.Product_Family__c = 'Company Internet';
        LAT.Postal_Code__c = 'BW-720';
        LAT.Assign_to_Queue__c = cs.QueueID__c;//smeQueueID[0].id; //'00558000001m361';
        insert LAT;

        Lead lead = new Lead();
        lead.OwnerId = cs.QueueID__c;//smeQueueID[0].id;//'00G58000002n2wS';
        lead.UM_Legal_Name__c = 'testAcc';
        lead.Status = 'New';
        lead.LG_LegalEntityType__c = 'AG';
        lead.LastName = 'testLead';
        lead.Email = 'test@test.com';
        lead.Phone = '0711111111';
        lead.LG_VisitPostalCode__c = 'BW-720';
        //lead.UM_Product__c = 'Company Internet';
        lead.UM_IndustryClassification__c = 'F BAUGEWERBE';
        lead.LG_Segment__c  = 'SME';
        lead.LG_ContractualOrganization__c = 'Baden-Württemberg (BAW)';
        lead.UM_VisitStateProvince__c = 'BW';
        lead.LG_VisitCountry__c = 'Germany';
        lead.Company = 'testComapny';
        insert lead;
    }
    
    // lead with existing account
    static testmethod void testTrigger5(){
        
        //List<Group> smeQueueID = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperNAME = 'SME_Queue'];
		Queue_Name__c cs = new Queue_Name__c(Name = 'QueueName', QueueID__c = '00G58000002n2wS');
        insert cs;
        
        Account acc = new Account(Name='testAccount');
        insert acc;
        
        Lead lead = new Lead();
        lead.OwnerId = cs.QueueID__c;//smeQueueID[0].id;//'00G58000002n2wS';
        lead.UM_Legal_Name__c = 'testAcc';
        lead.Status = 'New';
        lead.LG_LegalEntityType__c = 'AG';
        lead.LastName = 'testLead';
        lead.Email = 'test@test.com';
        lead.Phone = '0711111111';
        lead.LG_VisitPostalCode__c = 'BW-720';
        //lead.UM_Product__c = 'Company Internet';
        lead.UM_IndustryClassification__c = 'F BAUGEWERBE';
        lead.LG_Segment__c  = 'SME';
        lead.LG_ContractualOrganization__c = 'Baden-Württemberg (BAW)';
        lead.UM_VisitStateProvince__c = 'BW';
        lead.LG_VisitCountry__c = 'Germany';
        lead.Company = 'testComapny';
        lead.LG_MatchingAccount__c = acc.id;
        insert lead;
    }
    
    // Lead with (miltiple same Product Family, Postal code) And Lead Assignee Table with (Lead Assigee, Product Family & Postal code)
    static testmethod void testTrigger6(){
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
        User usr = new User(LastName = 'testUser',
                            FirstName='FirstName',
                            Alias = '242793',
                            Email = 'abc@asdf1.com',
                            Username = 'abc@asdf11.com',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US',
                            CompanyName = 'testComp'
                           );
        insert usr; 
        
        //List<Group> smeQueueID = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperNAME = 'SME_Queue'];
        Queue_Name__c cs = new Queue_Name__c(Name = 'QueueName', QueueID__c = '00G58000002n2wS');
        insert cs;
        
        List<Lead_Assignment_Table__c> latList = new List<Lead_Assignment_Table__c>();
        Lead_Assignment_Table__c LAT = new Lead_Assignment_Table__c();
        LAT.Product_Family__c = 'Company Internet';
        LAT.Postal_Code__c = 'BW-720';
        LAT.Lead_Assignee__c = usr.Id; //'00558000001m361';
        latList.add(LAT);
        Lead_Assignment_Table__c LAT2 = new Lead_Assignment_Table__c();
        LAT2.Product_Family__c = 'Company Internet';
        LAT2.Postal_Code__c = 'BW-721';
        LAT2.Lead_Assignee__c = usr.Id;
        latList.add(LAT2);
        insert latList;
        
        Lead lead = new Lead();
        lead.OwnerId = cs.QueueID__c;//smeQueueID[0].Id;	//'00G58000002n2wS';
        lead.UM_Legal_Name__c = 'testAcc';
        lead.Status = 'New';
        lead.LG_LegalEntityType__c = 'AG';
        lead.LastName = 'testLead';
        lead.Email = 'test@test.com';
        lead.Phone = '0711111111';
        lead.LG_VisitPostalCode__c = 'BW-720';
        lead.UM_Product__c = 'Company Internet';
        lead.UM_IndustryClassification__c = 'F BAUGEWERBE';
        lead.LG_Segment__c  = 'SME';
        lead.LG_ContractualOrganization__c = 'Baden-Württemberg (BAW)';
        lead.UM_VisitStateProvince__c = 'BW';
        lead.LG_VisitCountry__c = 'Germany';
        lead.Company = 'testComapny';
        insert lead;
    }
    
    // Lead with (miltiple same Product Family, Postal code) And Lead Assignee Table with (Assign to Queue, Product Family & Postal code)
    static testmethod void testTrigger7(){
        
        //List<Group> smeQueueID = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperNAME = 'SME_Queue'];
        Queue_Name__c cs = new Queue_Name__c(Name = 'QueueName', QueueID__c = '00G58000002n2wS');
        insert cs;
        
        List<Lead_Assignment_Table__c> latList = new List<Lead_Assignment_Table__c>();
        Lead_Assignment_Table__c LAT = new Lead_Assignment_Table__c();
        LAT.Product_Family__c = 'Company Internet';
        LAT.Postal_Code__c = 'BW-720';
        LAT.Assign_to_Queue__c = cs.QueueID__c;//smeQueueID[0].Id; //'00558000001m361';
        latList.add(LAT);
        Lead_Assignment_Table__c LAT2 = new Lead_Assignment_Table__c();
        LAT2.Product_Family__c = 'Company Internet';
        LAT2.Postal_Code__c = 'BW-721';
        LAT2.Assign_to_Queue__c = cs.QueueID__c; //smeQueueID[0].Id;
        latList.add(LAT2);
        insert latList;
        
        Lead lead = new Lead();
        lead.OwnerId = cs.QueueID__c;//smeQueueID[0].Id;	//'00G58000002n2wS';
        lead.UM_Legal_Name__c = 'testAcc';
        lead.Status = 'New';
        lead.LG_LegalEntityType__c = 'AG';
        lead.LastName = 'testLead';
        lead.Email = 'test@test.com';
        lead.Phone = '0711111111';
        lead.LG_VisitPostalCode__c = 'BW-720';
        lead.UM_Product__c = 'Company Internet';
        lead.UM_IndustryClassification__c = 'F BAUGEWERBE';
        lead.LG_Segment__c  = 'SME';
        lead.LG_ContractualOrganization__c = 'Baden-Württemberg (BAW)';
        lead.UM_VisitStateProvince__c = 'BW';
        lead.LG_VisitCountry__c = 'Germany';
        lead.Company = 'testComapny';
        insert lead;
    }
    
    // Lead with (NO Product Family, No Postal code) And Lead Assignee Table with (Lead Assigee, NO Product Family & No Postal code)
    static testmethod void testTrigger8(){
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        
        User usr = new User(LastName = 'testUser',
                            FirstName='FirstName',
                            Alias = '242793',
                            Email = 'abc@asdf1.com',
                            Username = 'abc@asdf11.com',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US',
                            CompanyName = 'testComp'
                           );
        insert usr; 
        
        //List<Group> smeQueueID = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperNAME = 'SME_Queue'];
        //ID queueID = Queue_Name__c.getInstance('QueueName').QueueID__c;
        
        Queue_Name__c cs = new Queue_Name__c(Name = 'QueueName', QueueID__c = '00G58000002n2wS');
        insert cs;
        
        Lead_Assignment_Table__c LAT = new Lead_Assignment_Table__c();
        //LAT.Product_Family__c = 'Company Internet';
        //LAT.Postal_Code__c = 'BW-720';
        LAT.Lead_Assignee__c = usr.Id; //'00558000001m361';
        insert LAT;
        
        Lead lead = new Lead();
        lead.OwnerId = cs.QueueID__c;//smeQueueID[0].Id;	//'00G58000002n2wS';
        lead.UM_Legal_Name__c = 'testAcc';
        lead.Status = 'New';
        lead.LG_LegalEntityType__c = 'AG';
        lead.LastName = 'testLead';
        lead.Email = 'test@test.com';
        lead.Phone = '0711111111';
        //lead.LG_VisitPostalCode__c = 'BW-720';
        //lead.UM_Product__c = 'Company Internet';
        lead.UM_IndustryClassification__c = 'F BAUGEWERBE';
        lead.LG_Segment__c  = 'SME';
        lead.LG_ContractualOrganization__c = 'Baden-Württemberg (BAW)';
        lead.UM_VisitStateProvince__c = 'BW';
        lead.LG_VisitCountry__c = 'Germany';
        lead.Company = 'testComapny';
        insert lead;
    }
    
// Lead with (NO Product Family, No Postal code) And Lead Assignee Table with (Assign to Queue, NO Product Family & No Postal code)
    static testmethod void testTrigger9(){
                
        Queue_Name__c cs = new Queue_Name__c(Name = 'QueueName', QueueID__c = '00G58000002n2wS');
        insert cs;
        
        Lead_Assignment_Table__c LAT = new Lead_Assignment_Table__c();
        //LAT.Product_Family__c = 'Company Internet';
        //LAT.Postal_Code__c = 'BW-720';
        LAT.Assign_to_Queue__c = cs.QueueID__c; //'00558000001m361';
        insert LAT;
        
        Lead lead = new Lead();
        lead.OwnerId = cs.QueueID__c;//smeQueueID[0].Id;	//'00G58000002n2wS';
        lead.UM_Legal_Name__c = 'testAcc';
        lead.Status = 'New';
        lead.LG_LegalEntityType__c = 'AG';
        lead.LastName = 'testLead';
        lead.Email = 'test@test.com';
        lead.Phone = '0711111111';
        //lead.LG_VisitPostalCode__c = 'BW-720';
        //lead.UM_Product__c = 'Company Internet';
        lead.UM_IndustryClassification__c = 'F BAUGEWERBE';
        lead.LG_Segment__c  = 'SME';
        lead.LG_ContractualOrganization__c = 'Baden-Württemberg (BAW)';
        lead.UM_VisitStateProvince__c = 'BW';
        lead.LG_VisitCountry__c = 'Germany';
        lead.Company = 'testComapny';
        insert lead;
    }
}