src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <infoMessage>Please select the partner</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>This is the record type for Partners</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>UM_PartnerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <businessProcess>Stage</businessProcess>
        <description>Stage</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LG_AccountTriggerTest.cls
@isTest
private class LG_AccountTriggerTest
{
public static testMethod void accountTriggerTest()
{
Id RecordTypeIdContact = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
Account pacc = new Account();
    
    pacc.RecordTypeId=RecordTypeIdContact;
    pacc.Name='TestPartnerAccountProd';
    insert pacc;

Account acc = new Account();
        acc.Name='TestAccProd';
        acc.Partner_lookup__c=pacc.Id;
        insert acc;
    
    Opportunity opp = new Opportunity ();
        opp.Name='TestOppProd';
        opp.AccountId=acc.Id;
        opp.StageName='Awareness of interest';
        opp.CloseDate= System.today() + 30;
        insert opp;
    
    opp.StageName='Closed Lost';
    update opp;
    
List<Opportunity> oppsToUpdate1 = new List<Opportunity>();    
   
    for(Opportunity opp1 : [select id, StageName, UM_PartnerAccount__c from Opportunity where AccountId=: acc.Id])
     {
     //if(opp.StageName!='Ready for Order' && profileName=='UM_CSR_Profile' )
     if((opp1.StageName!='Ready for Order'||opp1.StageName!='Closed Lost' || opp1.StageName!='Pre-Installation-Cancellation') && opp1.UM_PartnerAccount__c==null)
         {
          opp1.UM_PartnerAccount__c=acc.Partner_lookup__c;
             
          oppsToUpdate1.add(opp1);
         }
     }
   // opp.StageName='Closed Lost';
   //opp.UM_PartnerAccount__c=acc.Partner_lookup__c;
            Test.StartTest();
            update oppsToUpdate1;
    Test.StopTest(); 
    
}
      

}