src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UM_LastSyncedwithBilling__c</fullName>
        <label>Last Synced with Billing</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>LG_LogicalBillingAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Logical Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Billing Accounts (Logical Billing Account)</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_IsAccountSynced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Account Synced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UM_LastSyncedwithBilling__c</fullName>
        <label>Last Synced with Billing</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>csconta__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csconta__Parent_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csconta__Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is not used</description>
        <inlineHelpText>This field is not used</inlineHelpText>
        <label>Unused</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Unused</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csconta__Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Billing Account to use for this Subscription.</description>
        <inlineHelpText>The Billing Account to use for this Subscription.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Subscription.</description>
        <inlineHelpText>The Account that governs this Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Subscription in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Replaced_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replaced Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Replacement Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UM_KenanAutoSyncAccount.cls
/*******************************************************************************************************************************************
* File Name     :  UM_KenanAutoSyncAccount
* Description   :  For Auto sync of Account and Billing Accounts with Kenan System.

* @author       :  Shubham Mittal    
* Modification Log
===================================================================================================
* Ver.    Date          Author              Modification
---------------------------------------------------------------------------------------------------
  -        -               -                    -
********************************************************************************************************************************************/

// Condtion for contact Change need to be added for which billing account send to kenan !!
public class UM_KenanAutoSyncAccount {
   @InvocableMethod(label='AccountAutoSyncToKenan' )
   public static void UM_KenanAutoSyncAccount (List<Id> accountIds)
   {
       Long currentDateTime = DateTime.now().getTime();
       List<Account> accountList=[SELECT id,name,UM_LastSyncedwithBilling__c,
                                             (SELECT id,csord__Account__c 
                                                   FROM csord__Subscriptions__r WHERE csord__Status__c='Active'),
                                             (SELECT id,Name,UM_LastSyncedwithBilling__c
                                                   FROM csconta__Billing_Accounts__r WHERE UM_IsAccountSynced__c=True AND UM_LastSyncedwithBilling__c!=null) 
                                   FROM Account 
                                   WHERE Id 
                                   IN : accountIds AND UM_LastSyncedwithBilling__c!=null];
       if(accountList!=null && !accountList.isEmpty())
       {
           for(Account act : accountList)
           {                 
               if(act.csord__Subscriptions__r!=null && !act.csord__Subscriptions__r.isEmpty())
               {
                   Long lastSyncedDateTime = act.UM_LastSyncedwithBilling__c.getTime();
                   Long milliseconds = currentDateTime - lastSyncedDateTime;
                   Long seconds = milliseconds / 1000;
                   system.debug('seconds--->'+seconds);
                   if(seconds > 5)
                       System.enqueueJob(new UM_QueueAutoSyncAccount (act.id,False));                 
               }
           }
       }
       else
       {
           List<csconta__Billing_Account__c> billAccount=[SELECT id,UM_LastSyncedwithBilling__c 
                                                               FROM csconta__Billing_Account__c 
                                                               WHERE id 
                                                               IN:accountIds AND UM_LastSyncedwithBilling__c!=null];
           for(csconta__Billing_Account__c billAcnt : billAccount)
           {
               Long lastSyncedDateTime = billAcnt.UM_LastSyncedwithBilling__c.getTime();
               Long milliseconds = currentDateTime - lastSyncedDateTime;
               Long seconds = milliseconds / 1000;
               system.debug('seconds--->'+seconds);
               if(seconds > 5)
                   System.enqueueJob(new UM_QueueAutoSyncAccount (billAcnt.id,true));
           }
        }
   }
   
   private class UM_QueueAutoSyncAccount implements System.Queueable,Database.AllowsCallouts{
       private  Id accountId;
       private  Boolean isBillingAccount;
       public  UM_QueueAutoSyncAccount(Id accountId,boolean isBillingAccount)
       {
           this.accountId=accountId;
           this.isBillingAccount=isBillingAccount;
       }
       public void execute(System.QueueableContext context)
       {            
                System.debug('***called');
                UM_KenanAccountSyncCtrl obj=new UM_KenanAccountSyncCtrl (accountId,isBillingAccount);
                obj.intiateAutoSync();
       }
    }  
    
}