src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_AddressValidated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This feld is marks the lead for a valid address</description>
        <label>Address Validated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_VisitCountry__c</fullName>
        <label>Visit Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                    <default>true</default>
                    <label>Germany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>LG_AddressID__c</fullName>
        <description>US SFDT-54 - This field contains the address ID for the address coming from Peal Integration</description>
        <label>Address ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UM_WebserviceCredentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Login__c</fullName>
        <label>Login</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>UM Webservice Credentials</label>
</CustomObject>

src/classes/UM_AddressValidationControllerTest.cls
@isTest
public class UM_AddressValidationControllerTest {

    @isTest static void testFindAddress() {

 		Account testAcc = LG_GeneralTest.CreateAccount(
 			'Recaro', 'Customer', 'SoHo', 5, 'Qualified', '049-3220919', '55107192', 'UnityMedia', 'Flughafen Allee', '25', '', '28199', 'Bremen', 'Germany'
 		);

 		UM_WebserviceCredentials__c setting = new UM_WebserviceCredentials__c();
		setting.Name = 'UM_TopasWS';
		setting.Login__c = 'tLogin';
		setting.Password__c = 'tPassword';
		insert setting;

		PageReference pageRef = Page.UM_ValidateAddress;
    	pageRef.getParameters().put('id', testAcc.Id);
    	pageRef.getParameters().put('country', testAcc.LG_VisitCountry__c);
    	pageRef.getParameters().put('returnUrl', '/'+testAcc.Id);

  		Test.setCurrentPageReference(pageRef);

 		Test.startTest();

        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new UM_AddressResponseMock());
        UM_AddressResponseMock.resmth = 'searchext';

        UM_AddressValidationController c = new  UM_AddressValidationController();

        System.assertEquals('Flughafen Allee', c.addressResponse.addressExt.get(0).street);
        System.assertEquals('25', c.addressResponse.addressExt.get(0).streetNo);
        System.assertEquals('28199', c.addressResponse.addressExt.get(0).zip);

        String bid = c.addressResponse.addressExt.get(0).buildingId;
        System.assertEquals('123654', bid);
        
        // actual activation positive test
        c.outsideAddressValidationpage = false;
        c.selectedAddressID = bid;
        c.setAddress();

        //List<Account> checkAdd = [SELECT id, LG_AddressValidated__c FROM Account WHERE id=: testAcc.Id];
        System.assertEquals(true, [SELECT id, LG_AddressValidated__c FROM Account WHERE id=: testAcc.Id].get(0).LG_AddressValidated__c);

        // test cancel btn
        PageReference actPr = c.cancel();
        PageReference pr = new PageReference('/'+testAcc.Id);
        System.assertEquals(pr.getUrl(), c.cancel().getUrl());

        Test.stopTest();
    }

    @isTest static void testFindAddressNoCountry() {

 		Account testAcc = LG_GeneralTest.CreateAccount(
 			'Recaro', 'Customer', 'SoHo', 5, 'Qualified', '049-3220919', '55107192', 'UnityMedia', 'Flughafen Allee', '25', '', '28199', 'Bremen', 'Germany'
 		);

 		UM_WebserviceCredentials__c setting = new UM_WebserviceCredentials__c();
		setting.Name = 'UM_TopasWS';
		setting.Login__c = 'tLogin';
		setting.Password__c = 'tPassword';
		insert setting;

		PageReference pageRef = Page.UM_ValidateAddress;
    	pageRef.getParameters().put('accountId', testAcc.Id);
        pageRef.getParameters().put('country', testAcc.LG_VisitCountry__c);        
    	pageRef.getParameters().put('returnUrl', '/'+testAcc.Id);

  		Test.setCurrentPageReference(pageRef);

 		Test.startTest();

        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new UM_AddressResponseMock());
        UM_AddressResponseMock.resmth = 'searchext';

        UM_AddressValidationController c = new  UM_AddressValidationController();
        system.debug('--+ c: '+c);

        Test.stopTest();
    }

    @isTest static void testFindAddressCountry() {

        Account testAcc = LG_GeneralTest.CreateAccount(
            'Recaro', 'Customer', 'SoHo', 5, 'Qualified', '049-3220919', '55107192', 'UnityMedia', 'Flughafen Allee', '25', '', '28199', 'Bremen', 'Germany'
        );

        UM_WebserviceCredentials__c setting = new UM_WebserviceCredentials__c();
        setting.Name = 'UM_TopasWS';
        setting.Login__c = 'tLogin';
        setting.Password__c = 'tPassword';
        insert setting;

        PageReference pageRef = Page.UM_ValidateAddress;
        pageRef.getParameters().put('accountid', testAcc.Id);
        pageRef.getParameters().put('returnUrl', '/'+testAcc.Id);

        Test.setCurrentPageReference(pageRef);

        Test.startTest();

        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new UM_AddressResponseMock());
        UM_AddressResponseMock.resmth = 'searchext';

        UM_AddressValidationController c = new  UM_AddressValidationController();
        system.debug('--+ c: '+c);

        Test.stopTest();
    }

    @isTest static void testInvalidSetting() {

        Account testAcc = LG_GeneralTest.CreateAccount(
            'Recaro', 'Customer', 'SoHo', 5, 'Qualified', '049-3220919', '55107192', 'UnityMedia', 'Flughafen Allee', '25', '', '28199', 'Bremen', 'Germany'
        );
        cscrm__Address__c testAddr = LG_GeneralTest.crateAddress(
            'New address', 'Flughafen Allee', 'Bremen', '25', '', '28199', 'Germany', testAcc, true
        );

        PageReference pageRef = Page.UM_ValidateAddress;
        pageRef.getParameters().put('id', testAddr.Id);
        pageRef.getParameters().put('isQuickCreatePremise', 'true');
        Test.setCurrentPageReference(pageRef);

        Test.startTest();

        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new UM_AddressResponseMock());
        UM_AddressResponseMock.resmth = 'searchext';
        
        UM_AddressValidationController c = new  UM_AddressValidationController();

        System.assertEquals(true, c.invalidSetting, 'Invalid setting');
        Test.stopTest();
    } 

    @isTest static void testQuickCreatePremise() {

 		Account testAcc = LG_GeneralTest.CreateAccount(
 			'Recaro', 'Customer', 'SoHo', 5, 'Qualified', '049-3220919', '55107192', 'UnityMedia', 'Flughafen Allee', '25', '', '28199', 'Bremen', 'Germany'
 		);
        cscrm__Address__c testAddr = LG_GeneralTest.crateAddress(
            'New address', 'Flughafen Allee', 'Bremen', '25', '', '28199', 'Germany', testAcc, true
        );

        UM_WebserviceCredentials__c setting = new UM_WebserviceCredentials__c();
        setting.Name = 'UM_TopasWS';
        setting.Login__c = 'tLogin';
        setting.Password__c = 'tPassword';
        insert setting;

		PageReference pageRef = Page.UM_ValidateAddress;
    	pageRef.getParameters().put('id', testAddr.Id);
        pageRef.getParameters().put('country', testAcc.LG_VisitCountry__c);
        pageRef.getParameters().put('isQuickCreatePremise', 'true');
        pageRef.getParameters().put('returnUrl', '/'+testAcc.Id);
  		Test.setCurrentPageReference(pageRef);

 		Test.startTest();

        // This causes a fake response to be generated
        Test.setMock(WebServiceMock.class, new UM_AddressResponseMock());
        UM_AddressResponseMock.resmth = 'searchext';
        
        UM_AddressValidationController c = new  UM_AddressValidationController();
        
        // actual activation positive test
        c.outsideAddressValidationpage = false;
        c.selectedAddressID = '123456';

        testAddr.LG_AddressID__c = '123456';
        upsert testAddr;

        c.setAddress();

        Test.stopTest();
    } 

}