src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_AddressValidated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This feld is marks the lead for a valid address</description>
        <label>Address Validated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_ChamberOfCommerceNumber__c</fullName>
        <description>KvK No.</description>
        <label>National ID number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LG_Footprint__c</fullName>
        <description>Defining Footprint to which a Lead/Company/Account belongs</description>
        <label>Footprint</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UPC</fullName>
                </value>
                <value>
                    <fullName>Ziggo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitCity__c</fullName>
        <label>Visit City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_VisitCountry__c</fullName>
        <label>Visit Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitHouseNumber__c</fullName>
        <label>Visit House Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_VisitPostalCode__c</fullName>
        <label>Visit Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_VisitStreet__c</fullName>
        <label>Visit Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Add_ToBeDel__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Address_ID__c</fullName>
        <label>Address ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Extension__c</fullName>
        <label>Extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>House_Number__c</fullName>
        <label>House Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_Code__c</fullName>
        <label>Post Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address Data(To be deleted)</label>
</CustomObject>

src/classes/LG_AddressValidationTest.cls
@isTest
public class LG_AddressValidationTest {
    @testSetup static void methodName() {
        Profile objProfile = [Select Id, Name from Profile where Name =: 'LG_NL Sales Management User' limit 1];

        User standard = new User(alias = 'standt', 
        email='tester@testingcorp.com', 
        emailencodingkey='UTF-8', 
        lastname='Testing', languagelocalekey='en_US', 
        localesidkey='en_US', 
        profileid = objProfile.ID, 
        timezonesidkey='America/Los_Angeles', 
        username='tester@testingcorp.com',
        CompanyName='Testing Corporation');
        insert standard;    
        
        list<sObject> accList = Test.loadData(Account.sObjectType, 'LG_AccountTestData');
        List<Account> accList1 = (List<Account>)accList;
        for(Account loopVar : accList1){
            loopVar.OwnerID = standard.ID;
        }
        update acclist1;
        Add_ToBeDel__c tempAddSugg = new Add_ToBeDel__c(Name='1183NW',Address_ID__c='464564', City__c='Eindhoven', Country__C='Netherlands', Post_Code__c='5611LV', Street__c='Correct Street'); 
        insert tempAddSugg;
    }
    
    static testmethod void addressValidationTest() {
        Profile objProfile = [Select Id, Name from Profile where Name =: 'LG_NL Sales Management User' limit 1];

        User standard = [Select ID from user limit 1];
        Account testAcc = [Select ID,Name,LG_ChamberOfCommerceNumber__c,LG_Footprint__c,LG_VisitCountry__c,LG_VisitPostalCode__c,LG_VisitHouseNumber__c,LG_VisitCity__c,LG_VisitStreet__c from Account limit 1];
        List<Add_ToBeDel__c> tempAddSugg = [Select Name,Address_ID__c,House_Number__C, Extension__c, City__c, Country__C, Post_Code__c, Street__c from Add_ToBeDel__c];
        
        //.runas(standard) {
      
            //List<Add_ToBeDel__c> tempAddSugg = [Select Name,Address_ID__c,House_Number__C, Extension__c, City__c, Country__C, Post_Code__c, Street__c from Add_ToBeDel__c];
            //Account testAcc = [Select ID,Name,LG_ChamberOfCommerceNumber__c,LG_Footprint__c,LG_VisitCountry__c,LG_VisitPostalCode__c,LG_VisitHouseNumber__c,LG_VisitCity__c,LG_VisitStreet__c from Account limit 1];
            System.currentPageReference().getParameters().put('id', testAcc.ID);
            System.currentPageReference().getParameters().put('country', testAcc.LG_VisitCountry__c);
            System.currentPageReference().getParameters().put('returnURL', '/'+testAcc.ID);
            
            LG_AddressValidationController controller = new LG_AddressValidationController();
            controller.outsideAddressValidationpage = false;
            controller.findAddress();
            controller.selectedAddressID = tempAddSugg[0].Address_ID__c;
            pagereference saveRed = controller.setAddress();
            
            //Evaluation of the exception part of the setAddress() method
            controller.validationRecord.put('ID','');
            saveRed = controller.setAddress();
            
            //Evaluation of custom validations
            controller.validationRecord.put('LG_ChamberOfCommerceNumber__c','543');
            saveRed = controller.setAddress();
                        
            Account updatedAcc = [Select LG_AddressValidated__c from Account Where ID = :testAcc.ID];
            system.assertNotequals(updatedAcc.LG_addressValidated__C, true);
            
            ApexPages.StandardController  stdController = new ApexPages.StandardController (testAcc);
            controller = new LG_AddressValidationController(stdController );
           // controller.findAddress();
            //controller.selectedAddressID = tempAddSugg[0].Address_ID__c;
           // controller.setAddress();
           
           
            System.currentPageReference().getParameters().put('id', '00*8E000007g6kTQAQ');
            System.currentPageReference().getParameters().put('country', testAcc.LG_VisitCountry__c);
            controller = new LG_AddressValidationController(stdController );
            controller = new LG_AddressValidationController();
            controller.cancel();
        //}
        
    }
}