src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_ChamberOfCommerceNumber__c</fullName>
        <description>KvK No.</description>
        <label>National ID number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LG_Footprint__c</fullName>
        <description>Defining Footprint to which a Lead/Company/Account belongs</description>
        <label>Footprint</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UPC</fullName>
                </value>
                <value>
                    <fullName>Ziggo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitCountry__c</fullName>
        <label>Visit Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                    <default>true</default>
                    <label>Germany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    
    <fields>
        <fullName>LG_MACAddress__c</fullName>
        <label>MAC Address</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/B2B_Care_Ext_Connections__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will contain all the records required for connecting external system   from salesforce.</description>
    <fields>
        <fullName>Authentication_Token__c</fullName>
        <label>Authentication Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_URL__c</fullName>
        <label>Connection URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Session_Timeout__c</fullName>
        <label>Session Timeout</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_No_of_Tries__c</fullName>
        <label>UM No of Tries</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Care Connections</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>B2B_Care_Affected_Services__c</fullName>
        <description>It will capture the affected services from USMS.</description>
        <label>Affected Services</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>B2B_Care_Created_Ticket_From_USMS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This will be checked when a ticket is created from USMS.</description>
        <label>Created Ticket From USMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>B2B_Care_Element_Id__c</fullName>
        <description>It captures the element id from USMS.</description>
        <label>Element Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Estimated_Start_Time__c</fullName>
        <description>This field gives information about the estimated start time of the JOB.</description>
        <label>Estimated Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LG_Estimated_resolution_time__c</fullName>
        <description>This field tells you about the estimated resolution time of the JOB.</description>
        <label>Estimated Resolution Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>USMS_Ticket_ID__c</fullName>
        <externalId>true</externalId>
        <label>USMS Ticket ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>LG_B2B_Care_Mass_Outage_Request_UM</fullName>
        <active>true</active>
        <businessProcess>B2B Care Planned And Network</businessProcess>
        <description>Mass Outage</description>
        <label>Outage/Network Incident</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
   
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>LG_Footprint__c</fullName>
        <label>Footprint</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UPC</fullName>
                </value>
                <value>
                    <fullName>Ziggo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cscrm__Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>LG_ServiceExternalId__c</fullName>
        <label>Billing Service External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Subscription.</description>
        <inlineHelpText>The Account that governs this Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_Care_getTopologyFromSBCTest.cls
@isTest(seeAllData=false)
public class LG_Care_getTopologyFromSBCTest {
    public static RestRequest req;
    public static RestResponse res;
    @testSetup public static void SetupMethod() {
        try{
            User careAgent=LG_Care_TestRunAsUser.testRunAs();
            System.runAs(careAgent) {
                List<id> Cid = new List<id>();
                Case c = new Case();
                RecordType rtOutage = [SELECT id,Name FROM RecordType WHERE DeveloperName = 'LG_B2B_Care_Mass_Outage_Request_UM'];
                c.RecordTypeId = rtOutage.Id;
                c.USMS_Ticket_ID__c = 'INC0000003865';
                c.Description = 'test';
                DateTime dt = Datetime.now();
                dt = dt.addDays(1);
                c.LG_Estimated_Start_Time__c = dt;
                c.LG_Estimated_resolution_time__c = dt.addDays(1);
                c.priority = 'Escalated';
                c.status = 'Critical';
                c.B2B_Care_Element_Id__c = 'Element Ids';
                c.B2B_Care_Affected_Services__c = 'Affected Services';
                c.B2B_Care_Created_Ticket_From_USMS__c = true;
                
                Test.setMock(HttpCalloutMock.class, new LG_Care_SBC_MockHttpResponseGenerator());
                insert c;
                
                B2B_Care_Ext_Connections__c SCon= new B2B_Care_Ext_Connections__c();
                SCon.Name='Spider External System';
                SCon.Authentication_Token__c='@23RKCARE';
                SCon.Brand__c='Unity Media';
                SCon.Connection_URL__c='https://localhost.com/api';
                SCon.Session_Timeout__c='120000';
                SCon.UM_No_of_Tries__c=3;
                insert SCon;
                
                List<Asset> assets = new List<Asset>();
                Asset a1 = new Asset();
                a1.name = 'test asset 1';
                a1.LG_MACAddress__c = 'abcd84753845';
                assets.add(a1);
                
                Datetime dateTimeInstance = Datetime.now();
                
                Account acc = new Account();
                acc.Name = 'Planned Maintenance Account';
                acc.LG_VisitCountry__c = 'Germany';
                acc.LG_ChamberOfCommerceNumber__c = '7';
                acc.LG_Footprint__c = 'UPC';
                insert acc;
                
                cscrm__Address__c address = new cscrm__Address__c();
                address.cscrm__Zip_Postal_Code__c = '761104 abc 58';
                address.Name = 'Test Address';
                insert address;
                
                 csord__Order_Request__c orderRequest = new csord__Order_Request__c();
                orderRequest.Name = 'Test Order Request';
                orderRequest.csord__Module_Name__c = 'Test Module';
                orderRequest.csord__Module_Version__c = 'Test v1.0';
                orderRequest.csord__Process_Status__c = 'Testing';
                orderRequest.csord__Request_DateTime__c = dateTimeInstance;
                insert orderRequest;
                
                csord__Subscription__c sub = new csord__Subscription__c();
                sub.Name = 'Business Broadband';
                sub.csord__Account__c = acc.id;
                sub.csord__Identification__c = 'Test Identification';
                sub.csord__Order_Request__c = orderRequest.id;
                insert sub;
                
                csord__Service__c service = new csord__Service__c();
                service.csord__Subscription__c = sub.id;
                service.LG_ServiceExternalId__c = '112245 testing';
                service.LG_Address__c = address.id;
                service.Name = 'Test Service';
                service.LG_ServiceStatus__c = 'Active';
                service.csord__Order_Request__c = orderRequest.Id;
                service.csord__Identification__c ='test Identification';
                service.LG_ProvisioningAccountNo__c = '9876543217';
                insert service;
                
                insert(assets);
                
            }
        }
        catch(DMLException e) {
            system.assertEquals(e.getMessage(), e.getMessage());
        }
        
    }
    private static JSONGenerator createJSON() {
        
        Boolean flag = true;
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        
        gen.writeStringField('outageId', 'INC0000003865');
        gen.writeStringField('Status', 'ok');
        gen.writeStringField('status_code','200');
        gen.writeFieldName('Filters');
        
        gen.writeStartObject();
        gen.writeStringField('customer_types', 'BN');
        gen.writeEndObject();
        
        gen.writeFieldName('data');
        gen.writeStartArray();
        
        gen.writeStartObject();
        gen.writeStringField('customer-number', '123456789');
        gen.writeStringField('customer-type', 'BN');
        gen.writeStringField('region', 'BW');
        gen.writeStringField('street', 'Test 1');
        gen.writeStringField('house-number', '6');
        gen.writeStringField('house-number-addition', 'A');
        gen.writeStringField('city', 'Test 1');
        gen.writeStringField('zip', 'Test 1');
        gen.writeFieldName('macs');
        gen.writeStartArray();
        gen.writeString('abcd84753845');
        gen.writeEndArray();
        gen.writeEndObject();
        
        gen.writeStartObject();
        gen.writeStringField('customer-number', '987654321');
        gen.writeStringField('customer-type', 'BN');
        gen.writeStringField('region', 'BW');
        gen.writeStringField('street', 'Test 2');
        gen.writeStringField('house-number', '');
        gen.writeStringField('house-number-addition', 'z');
        gen.writeStringField('city', 'Test ');
        gen.writeStringField('zip', 'Test 2');
        gen.writeEndObject();
        
        gen.writeStartObject();
        gen.writeStringField('customer-number', '9876543217');
        gen.writeStringField('customer-type', 'BN');
        gen.writeStringField('region', 'BW');
        gen.writeStringField('street', 'Test 3');
        gen.writeStringField('house-number', '');
        gen.writeStringField('house-number-addition', '7');
        gen.writeStringField('city', 'Test 7');
        gen.writeStringField('zip', 'Test 7');
        gen.writeFieldName('macs');
        gen.writeStartArray();
        gen.writeString('bcd87bc37466');
        gen.writeEndArray();
        gen.writeEndObject();
        
        gen.writeEndArray();
        gen.writeEndObject();
        return gen;
        
    }
    @isTest public static void testTopologyData() {
        User careAgent= [SELECT Id from User where UserName='careagent.testuser@unityMediaorg.com' limit 1];
        System.runAs(careAgent) 
        {
            
            res = new restResponse();
            JSONGenerator gen = LG_Care_getTopologyFromSBCTest.CreateJSON();
            req = new RestRequest();
            req.requestURI = '/services/apexrest/topologyfromsbc/';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueOf(gen.getAsString());
            RestContext.request = req;
            RestContext.response = res;
            
            Test.StartTest();
            LG_Care_getTopologyFromSBC.getTopologyData();
            system.assertEquals('INC0000003865',LG_Care_getTopologyFromSBC.outageId);
            Test.StopTest();
        }
    }
    @isTest public static void testTopologyData1() {
        User careAgent= [SELECT Id from User where UserName='careagent.testuser@unityMediaorg.com' limit 1];
        System.runAs(careAgent) 
        {
            
            res = new restResponse();
            JSONGenerator gen = LG_Care_getTopologyFromSBCTest.CreateJSON();
            req = new RestRequest();
            req.requestURI = '/services/apexrest/topologyfromsbc/';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueOf(gen.getAsString());
            RestContext.request = req;
            RestContext.response = res;
            
            Test.StartTest();
            LG_Care_getTopologyFromSBC.getTopologyData();
            system.assertEquals('INC0000003865',LG_Care_getTopologyFromSBC.outageId);
            Test.StopTest();
        }
    }
    /*
@isTest public static void testTopologyDataNegative() {
User careAgent= [SELECT Id from User where UserName='careagent.testuser@unityMediaorg.com' limit 1];
System.runAs(careAgent) 
{

res = new restResponse();
JSONGenerator gen = LG_Care_getTopologyFromSBCTest.CreateJSON(false);
req = new RestRequest();
req.requestURI = '/services/apexrest/topologyfromsbc/';
req.httpMethod = 'POST';
req.requestBody = Blob.valueOf(gen.getAsString());
RestContext.request = req;
RestContext.response = res;

Test.StartTest();
LG_Care_getTopologyFromSBC.getTopologyData();
Test.StopTest();
}
}*/
}