src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_ChamberOfCommerceNumber__c</fullName>
        <description>KvK No.</description>
        <label>National ID number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>LG_State__c</fullName>
        <label>Billing State</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csconta__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>LG_AddressID__c</fullName>
        <description>US SFDT-54 - This field contains the address ID for the address coming from Peal Integration</description>
        <label>Address ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PremiseNumber__c</fullName>
        <displayFormat>P{0000000}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>cscrm__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>LG_ServiceExternalId__c</fullName>
        <label>Billing Service External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ServiceStatus__c</fullName>
        <description>Pick-list to save the status of the service provisioning.</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                  <fullName>LG_SecondaryProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services (Secondary Product Configuration)</relationshipLabel>
        <relationshipName>Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_BillingProductId__c</fullName>
        <label>Billing Product Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_PhoneExtension__c</fullName>
        <description>for storing VW phone extension</description>
        <label>Phone Extension</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_SubscriberName__c</fullName>
        <label>Subscriber Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Activation_Date__c</fullName>
        <description>The date of activation.</description>
        <inlineHelpText>The date of activation.</inlineHelpText>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csord__Deactivation_Date__c</fullName>
        <description>The date of deactivation.</description>
        <inlineHelpText>The date of deactivation.</inlineHelpText>
        <label>Deactivation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Delta_Status__c</fullName>
        <label>Delta Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Continuing In Subscription</fullName>
                </value>
                <value>
                    <fullName>Added To Subscription</fullName>
                </value>
                <value>
                    <fullName>Deleted From Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csordtelcoa__Service_Number__c</fullName>
        <label>Service Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Service_Line_Item__c.object
<CustomObject>
    <description>A billable component of a Service.</description>
    <fields>
        <fullName>LG_BillingAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Service line Items</relationshipLabel>
        <relationshipName>Service_line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_BillingProductId__c</fullName>
        <label>LG Billing Product Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_BillingProductId__c</fullName>
        <label>Billing Product Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_ContractId__c</fullName>
        <label>Contract Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_DiscountEndDate__c</fullName>
        <formula>IF(VALUE(UM_Duration__c)= 0,null,
DATE(
year(csord__Service__r.csord__Activation_Date__c) + floor((month(csord__Service__r.csord__Activation_Date__c) + VALUE(UM_Duration__c)- 1)/12)
,
if( mod( month(csord__Service__r.csord__Activation_Date__c) + VALUE(UM_Duration__c), 12 ) = 0, 12 , mod( month(csord__Service__r.csord__Activation_Date__c) + VALUE(UM_Duration__c), 12 ))
,
min(
day(csord__Service__r.csord__Activation_Date__c),
case(
max( mod( month(csord__Service__r.csord__Activation_Date__c) + VALUE(UM_Duration__c), 12 ) , 1),
9,30,
4,30,
6,30,
11,30,
2,28,
31
)
)
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Discount End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UM_KenanServiceLineId__c</fullName>
        <externalId>true</externalId>
        <label>KenanServiceLineId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_NumberOfUnits__c</fullName>
        <label>Number Of Units</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_OneOffPriceDiscount__c</fullName>
        <label>One Off Price Discount (%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_Price_Override__c</fullName>
        <label>Price Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_RecurringPriceDiscount__c</fullName>
        <label>Recurring Price Discount (%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_ServiceItemType__c</fullName>
        <label>Service Item Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_UnitType__c</fullName>
        <label>Unit Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Discount_Type__c</fullName>
        <description>What type of discount to apply. The value of this field determines whether the Discount Amount or Discount Percentage value is used.</description>
        <inlineHelpText>Type of the discount applied.</inlineHelpText>
        <label>Discount Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Percentage</fullName>
                    <default>true</default>
                    <label>Percentage</label>
                </value>
                <value>
                    <fullName>Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csord__Discount_Value__c</fullName>
        <description>The value of the discount. The value in interpreted either as an amount or a percentage, depending on the Discount Type field.</description>
        <inlineHelpText>Depending on the Discount Type field either a percentage or an amount.</inlineHelpText>
        <label>Discount Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>csord__Discounted_Amount__c</fullName>
        <description>Discounted amount value</description>
        <label>Discounted Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>csord__Is_Recurring__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this line item is a recurring item.</description>
        <label>Is Recurring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>csord__Line_Description__c</fullName>
        <label>Line Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <description>The parent Service of this ServiceLineItem.</description>
        <inlineHelpText>The parent Service of this ServiceLineItem.</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Service line Items</relationshipLabel>
        <relationshipName>Service_line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>csord__Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Delta_Status__c</fullName>
        <label>Delta Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Added</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>Price Change</fullName>
                </value>
                <value>
                    <fullName>Unchanged</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csordtelcoa__Line_Item_Reference_Id__c</fullName>
        <label>Line Item Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service Line Item</label>
    <nameField>
        <label>Service Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csconta__Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Billing Account to use for this Subscription.</description>
        <inlineHelpText>The Billing Account to use for this Subscription.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Subscription in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UM_ServiceHPBX_MACDTest.cls
@istest
public class UM_ServiceHPBX_MACDTest {

    public static string queryForBatchChild;
    public static string queryForBatchParent;
    public static void dataSetup()
    {
        queryForBatchChild = 'SELECT Id, LG_ServiceExternalId__c,csord__Activation_Date__c,csord__Deactivation_Date__c, csord__Service__r.csord__Service__c,csord__Service__r.csord__Activation_Date__c,csord__Status__c, LG_ServiceStatus__c, csordtelcoa__Delta_Status__c,'+
                                            '(SELECT Id,csordtelcoa__Line_Item_Reference_Id__c,csordtelcoa__Delta_Status__c,csord__Service__r.csord__Subscription__c,'+
                                            'UM_Price_Override__c ,csord__Service__c, UM_ServiceItemType__c,'+
                                            'UM_KenanServiceLineId__c,csord__Service__r.csord__Service__c,csord__Line_Description__c,'+
                                            'csord__Service__r.csordtelcoa__Service_Number__c,LG_BillingProductId__c,UM_BillingProductId__c,'+
                                            'csord__Total_Price__c, UM_NumberOfUnits__c, UM_UnitType__c,csord__Is_Recurring__c,'+
                                            'csord__Discount_Value__c,csord__Discount_Type__c,UM_DiscountEndDate__c,'+
                                            'csord__Discounted_Amount__c, UM_ContractId__c,UM_RecurringPriceDiscount__c, '+
                                            'UM_OneOffPriceDiscount__c'+
                                        ' FROM csord__Service_Line_Items__r ORDER BY csord__Service__c)'+
                                    ' FROM csord__Service__c where csord__Service__c != null';
        
         queryForBatchParent = 'SELECT Id, LG_ServiceExternalId__c, csord__Service__c, csord__Subscription__c, csordtelcoa__Delta_Status__c,'+
                                    'csord__Status__c, LG_ServiceStatus__c, csord__Deactivation_Date__c, UM_SubscriberName__c, UM_PhoneExtension__c' +
                                    ' FROM csord__Service__c where csord__Service__c = null';
        //insert billing account and premise address
        Account acc=new Account(Name='SampleAccount',LG_ChamberOfCommerceNumber__c='1223');
        insert acc;
        
        csconta__Billing_Account__c bac=new csconta__Billing_Account__c(LG_State__c='NRW',csconta__Account__c=acc.Id);
        cscrm__Address__c lac=new cscrm__Address__c(LG_AddressID__c='10778710',cscrm__Country__c='Germany');
        
        Database.insert(new SObject[]{bac,lac});
        
        List<cscrm__Address__c> lacs=[Select Id,LG_PremiseNumber__c from cscrm__Address__c where Id=:lac.Id];
        System.debug('Auto generated number is >> ' + lacs.get(0).LG_PremiseNumber__c);
        
        List<csconta__Billing_Account__c> bacs=[Select Id,LG_BillingAccountNumber__c from csconta__Billing_Account__c where Id=:bac.Id];
        
        Date validfrom=date.today();
        
        csconta__Contract__c con =new csconta__Contract__c(csconta__Account__c=acc.Id,
                                                           csconta__Valid_From__c=validfrom,
                                                           csconta__Valid_To__c=validfrom.addYears(2));
        insert con;
        csord__Subscription__c sub=new csord__Subscription__c(name='Virtual Voice Kundensetup',
                                                              csconta__Billing_Account__c=bacs.get(0).Id,
                                                              LG_Address__c=lac.Id,
                                                              csord__Identification__c='Identification_Id',
                                                              UM_SubscriberId__c ='123445', 
                                                              csord__Account__c=acc.Id,
                                                              csord__Status__c='Active',
                                                              LG_Contract__c=con.id );
        insert sub;
        
        csord__Service__c serv1=new csord__Service__c(Name = 'Virtual Voice Kundensetup',
                                                      csord__Subscription__c=sub.Id,
                                                      csord__Identification__c='Identification'+sub.Id,
                                                      csord__Activation_Date__c=validfrom.addDays(-5),
                                                      LG_SLA__c='Bronze',
                                                      LG_ServiceExternalId__c = '35342534',
                                                      LG_ServiceStatus__c='Active',
                                                      csord__Status__c='Active',
                                                      LG_ProductFamily__c='Virtual Voice'
                                                      );
                                                      
        insert serv1;
        
        csord__Service__c serv2=new csord__Service__c(Name = 'Premium',
                                                      csord__Subscription__c=sub.Id,
                                                      csord__Identification__c='Identification'+sub.Id,
                                                      csord__Activation_Date__c=validfrom.addDays(-5),
                                                      LG_SLA__c='Bronze',
                                                      LG_ServiceStatus__c='Active',
                                                      csord__Status__c='Active',
                                                      csord__Service__c=serv1.id,
                                                      LG_ProductFamily__c='Virtual Voice'
                                                      );
    
        insert serv2;
        
        csord__Service_Line_Item__c servlinitem=new csord__Service_Line_Item__c();
        servlinitem.csord__Service__c=serv1.id;
        servlinitem.csord__Identification__c='rttuyuyu';
        servlinitem.csord__Total_Price__c=100;
        servlinitem.UM_KenanServiceLineId__c='1234';
        servlinitem.csord__Line_Description__c='abcdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
        servlinitem.UM_ServiceItemType__c='1';
        
        csord__Service_Line_Item__c servlinitem1=new csord__Service_Line_Item__c();
        servlinitem1.csord__Service__c=serv1.id;
        servlinitem1.UM_KenanServiceLineId__c='12345';
        servlinitem1.csord__Identification__c='rttu';
        servlinitem1.csord__Total_Price__c=100;
        servlinitem1.csord__Line_Description__c='abcdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
        servlinitem1.UM_ServiceItemType__c='0';
        
        csord__Service_Line_Item__c servlinitem2=new csord__Service_Line_Item__c();
        servlinitem2.csord__Service__c=serv2.id;
        servlinitem2.UM_KenanServiceLineId__c='123433';
        servlinitem2.csord__Identification__c='rttu';
        servlinitem2.csord__Total_Price__c=100;
        servlinitem2.csord__Line_Description__c='abcdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
        servlinitem2.UM_ServiceItemType__c='1';
        
        list<csord__Service_Line_Item__c> sliList =NEW list<csord__Service_Line_Item__c>();
        sliList.add(servlinitem);
        sliList.add(servlinitem1);
        sliList.add(servlinitem2);
        INSERT sliList;  
        
    }
    
    @isTest
    public static void testMethod1(){
        dataSetup();      
        List<csord__Service__c> srvList=Database.query(queryForBatchChild);
        for(csord__Service__c s:srvList){
            s.LG_ServiceStatus__c = 'Ready for Billing';
            s.csordtelcoa__Delta_Status__c='Terminate';
            s.csord__Deactivation_Date__c = system.today();         
        }
        update srvList;
        
        Test.StartTest();
        try{
        UM_ServiceHPBX_MACD hpmacd = new UM_ServiceHPBX_MACD();
        hpmacd.execute(srvList);
        }catch(Exception ex){}
        Test.StopTest();
    }
    @isTest
    public static void testMethod2(){
        dataSetup();       
        List<csord__Service__c > srvList=Database.query(queryForBatchParent);
        for(csord__Service__c s:srvList){
            s.csordtelcoa__Delta_Status__c='Terminate'; 
            s.csord__Deactivation_Date__c = system.today();
        }
        update srvList;
        
        Test.StartTest();
        try{
        UM_ServiceHPBX_MACD hpmacd = new UM_ServiceHPBX_MACD();
        hpmacd.execute(srvList);
        }catch(Exception ex){}
        Test.StopTest();
    }
    
    @isTest
    public static void testMethod3(){
        dataSetup();       
        List<csord__Service__c > srvList=Database.query(queryForBatchParent);
        for(csord__Service__c s:srvList){
            s.csordtelcoa__Delta_Status__c='Modify'; 
        }
        update srvList;
        
        Test.StartTest();
        try{
        UM_ServiceHPBX_MACD hpmacd = new UM_ServiceHPBX_MACD();
        hpmacd.execute(srvList);
        }catch(Exception ex){}
        Test.StopTest();
    }
    
    @isTest
    public static void testMethod4(){
        dataSetup();       
        List<csord__Service__c > srvList=Database.query(queryForBatchParent);
        csord__Service__c serv2;
        for(csord__Service__c s:srvList){
            serv2=new csord__Service__c(Name = 'Premium',
                                          csord__Subscription__c=s.csord__Subscription__c,
                                          csord__Identification__c='Identification1'+s.csord__Subscription__c,
                                          csord__Activation_Date__c=System.today().addDays(-5),
                                          LG_SLA__c='Bronze',
                                          csord__Service__c=s.id,
                                          csordtelcoa__Delta_Status__c='Add',
                                          LG_ServiceStatus__c = 'Ready for Billing');
        }
        
        insert serv2;
        
        csord__Service_Line_Item__c servlinitem2=new csord__Service_Line_Item__c();
        servlinitem2.csord__Service__c=serv2.id;
        servlinitem2.csord__Identification__c='rttu';
        servlinitem2.csord__Total_Price__c=100;
        servlinitem2.csord__Line_Description__c='abcdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
        servlinitem2.UM_ServiceItemType__c='1';
        
        insert servlinitem2;
        srvList=Database.query(queryForBatchChild);
        Test.StartTest();
        try{
        UM_ServiceHPBX_MACD hpmacd = new UM_ServiceHPBX_MACD();
        hpmacd.execute(srvList);
        }catch(Exception ex){}
        Test.StopTest();
    }
}