src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_VisitCountry__c</fullName>
        <label>Visit Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                    <default>true</default>
                    <label>Germany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/B2B_Care_Ext_Connections__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will contain all the records required for connecting external system   from salesforce.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_URL__c</fullName>
        <label>Connection URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>UM_No_of_Tries__c</fullName>
        <label>UM No of Tries</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Care Connections</label>
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Family__c</fullName>
        <description>This field will be mapped to the Product2.Family field at Opportunity sync time.
Default value is taken from Product_Definition__c.Name.</description>
        <inlineHelpText>Is used for better control over the process, enabling fine-grained forecasting capabilities. By default Product Defn name will auto-populate this field, overridden using Set Product Family action during config. Is mapped to Product2.Family fld at Opp sync</inlineHelpText>
        <label>Product Family</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>LG_SLA__c</fullName>
        <label>SLA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ServiceExternalId__c</fullName>
        <label>Billing Service External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Subscription.</description>
        <inlineHelpText>The Account that governs this Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Subscription in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_Care_Medallia_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It stores the values to be used in the LG_Care_MedalliaRelationshipSurvey_Batch</description>
    <fields>
        <fullName>LG_Care_Contact_Created_Date__c</fullName>
        <label>Contact Created Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_Care_Contact_Role__c</fullName>
        <label>Contact Role</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Care_Last_rNPS_Send_Date__c</fullName>
        <label>Last rNPS Send Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_Care_Max_Number_of_Contacts__c</fullName>
        <label>Max Number of Contacts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Care Medallia Settings</label>
</CustomObject>

src/classes/LG_Care_MedalliaRelation_Batch_Test.cls
@isTest
public Class LG_Care_MedalliaRelation_Batch_Test{
    
    @isTest Static void MedalliaCallRelation(){ 
        
        List<id> Mid = New List<id>();
    
        List<Contact> Cntcs= new List<Contact>();
                       
                
                Account MAcc = New Account();
                MAcc.Name='Medalia Account';
                MAcc.LG_VisitCountry__c ='Germany';
                Insert MAcc;
                   
                Contact MCon = New Contact();
                MCon.Salutation='Mr.';
                MCon.LastName='NPS Test Contact';
                MCon.Email='Nilesh_tanwar@infosys.com';
                MCon.Accountid = MAcc.id;
                MCon.LG_Role__c='Business User';
                MCon.LG_Care_Survey_Opt_Out__c=false;
                //MCon.LG_Care_Relationship_Survey_Sent_Date__c=null;
                //Insert MCon;
                Cntcs.add(MCon);
                Contact Mcon1 = New Contact();
                MCon1.Salutation='Mr.';
                MCon1.LastName='Medalia Test';
                MCon1.Email='Rishi.kapoor@infosys.com';
                MCon1.Accountid= MAcc.id; 
                MCon1.LG_Care_Survey_Opt_Out__c=false;
                MCon1.LG_Role__c='Business User';
                //MCon1.LG_Care_Relationship_Survey_Sent_Date__c=null;
                Cntcs.add(MCon1);
                Contact Mcon2 = New Contact();
                MCon2.Salutation='Mr.';
                MCon2.LastName='Medalia Test2';
                MCon2.Email='Rishi.kapoor23@infosys.com';
                MCon2.Accountid= MAcc.id; 
                MCon2.LG_Care_Survey_Opt_Out__c=false;
                MCon2.LG_Role__c='Business User';
                //MCon2.LG_Care_Relationship_Survey_Sent_Date__c=null;
              //  Insert Mcon2;
                Cntcs.add(MCon2);
      
                Insert Cntcs;
               
               
                
                csord__Subscription__c sub = new csord__Subscription__c();
                sub.Name = 'Company Fiber';
                sub.csord__Account__c = MAcc.id;
                sub.csord__Identification__c = 'Test Identification';
                sub.csord__Status__c='Active';
                insert sub;
                
                cscfga__Product_Configuration__c prodConfig= new cscfga__Product_Configuration__c();
                prodConfig.Name='Test One';
                prodConfig.cscfga__Product_Family__c='Company Fiber';
                insert prodConfig;
                
                
                cscfga__Product_Configuration__c prodConfig2= new cscfga__Product_Configuration__c();
                prodConfig2.Name='Test Two';
                prodConfig2.cscfga__Product_Family__c='Company Internet';
                insert prodConfig2;
                
                cscfga__Product_Configuration__c prodConfig3= new cscfga__Product_Configuration__c();
                prodConfig3.Name='Test Three';
                prodConfig3.cscfga__Product_Family__c='WLAN';
                insert prodConfig3;
                
                csord__Service__c service = new csord__Service__c();
                service.csord__Subscription__c = sub.id;
                service.LG_ServiceExternalId__c = '112245 testing';
                service.LG_SLA__c = 'Gold';
                service.Name = 'Company fiber';
                service.csord__Status__c = 'Active';
               
                service.csord__Identification__c ='test Identification';
                service.csordtelcoa__Product_Configuration__c=prodConfig.id;
                insert service;
                
                
                csord__Service__c service2 = new csord__Service__c();
                service2.csord__Subscription__c = sub.id;
                service2.LG_ServiceExternalId__c = '00023456';
                service2.Name = 'Company Internet';
                service2.csord__Status__c = 'Active';
                 service2.csord__Identification__c ='test Identification';
                service2.csordtelcoa__Product_Configuration__c=prodConfig2.id;
                insert service2;
                
                csord__Service__c service3 = new csord__Service__c();
                service3.csord__Subscription__c = sub.id;
                service3.LG_ServiceExternalId__c = '00007';
                service3.Name = 'WLAN';
                service3.csord__Status__c = 'Active';
             
                service3.csord__Identification__c ='test Identification';
                service3.csordtelcoa__Product_Configuration__c=prodConfig3.id;
                insert service3;
                
                
                B2B_Care_Ext_Connections__c MedalliaConnBrand = new B2B_Care_Ext_Connections__c();
                MedalliaConnBrand.Name = 'Germany';
                MedalliaConnBrand.Brand__c = 'Unitymedia Business';               
                insert MedalliaConnBrand;
                
                B2B_Care_Ext_Connections__c MedalliaConn = new B2B_Care_Ext_Connections__c();
                MedalliaConn.Name = 'Medallia Relational System Info';
                MedalliaConn.UM_No_of_Tries__c = 3;
                MedalliaConn.Connection_URL__c = 'https://libertyglobal.medallia.eu';       
                insert MedalliaConn;
                
                LG_Care_Medallia_Settings__c MedalliaRecord= new LG_Care_Medallia_Settings__c();
                MedalliaRecord.Name='Default';
                MedalliaRecord.LG_Care_Contact_Created_Date__c =-1;
                MedalliaRecord.LG_Care_Contact_Role__c='Business User';
                MedalliaRecord.LG_Care_Max_Number_of_Contacts__c=100;
                MedalliaRecord.LG_Care_Last_rNPS_Send_Date__c=-1;
                insert MedalliaRecord;
         
                Test.StartTest();
                LG_Care_MedalliaRelationshipSurvey_Batch b = new LG_Care_MedalliaRelationshipSurvey_Batch();
                 Database.executeBatch(b);
      
                
           //   Test.setMock(HttpCalloutMock.class, new LG_Care_SBC_MockHttpResponseGenerator());
              /*  LG_Care_Medallia_Relationship_Survey.Create_Medallia_NPS_JSON_Request(camp); 
                for(Contact con : [SELECT Email,LG_Care_Relationship_Survey_Sent_Date__c  from Contact limit 1]){
                    //System.debug('----------- '+ con.Email);
                    //System.debug('----------- '+ con.LG_Care_Relationship_Survey_Sent_Date__c  );
                    system.assertNotEquals(Null,con.LG_Care_Relationship_Survey_Sent_Date__c );
                }*/
                Test.StopTest();
                
                //system.assertNotEquals(Null,LG_Care_MedalliaRelationshipSurvey_Batch.RqstFile); 
            
            
            
        
    }
    
}