src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>This is the record type for Partners</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>LG_TechnicalContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.cscrm__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Premises</relationshipLabel>
        <relationshipName>Premises</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Order</description>
        <inlineHelpText>The parent Solution of this Order</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>LG_ProvisioningAccountNo__c</fullName>
        <label>Provisioning Account No</label>
        <length>75</length>
        <type>Text</type>
    </fields>
	<fields>
        <fullName>LG_RootOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services (Root Order)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_SLA__c</fullName>
        <label>SLA</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Suborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services (Suborder)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_AS_Number__c</fullName>
        <description>BGP Autonomous System Number</description>
        <inlineHelpText>BGP Autonomous System Number</inlineHelpText>
        <label>UM AS Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_Announced_prefix__c</fullName>
        <description>BGP Title of issue</description>
        <inlineHelpText>BGP Title of issue</inlineHelpText>
        <label>UM Announced prefix</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_BGP_Password__c</fullName>
        <description>Password for selection of workflow</description>
        <inlineHelpText>Password for selection of workflow</inlineHelpText>
        <label>UM BGP Password</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_DependsOnService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Depends On Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Services (Depends On)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_DownloadSpeed__c</fullName>
        <label>Download Speed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_IPv4__c</fullName>
        <description>BGP IPv4 Address space</description>
        <inlineHelpText>BGP IPv4 Address space</inlineHelpText>
        <label>UM IPv4</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_IPv6__c</fullName>
        <description>BGP IPv6 Address space</description>
        <inlineHelpText>BGP IPv6 Address space</inlineHelpText>
        <label>UM IPv6</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_JiraIssueTypeId__c</fullName>
        <label>JiraIssueTypeId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_PartnerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_Access_Active_IPv4__c</fullName>
        <label>UM Access Active IPv4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_Access_Active_IPv6__c</fullName>
        <label>UM Access Active IPv6</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_Access_Transfer_IPv4__c</fullName>
        <label>UM Access Transfer IPv4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_Access_Transfer_IPv6__c</fullName>
        <label>UM Access Transfer IPv6</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_AdditionalInformation__c</fullName>
        <description>Used in Jira Integration for description attribute.</description>
        <label>Additional Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LG_RootOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services (Root Order)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_AccountName__c</fullName>
        <description>Displaying the Account Name in Email Templates</description>
        <formula>csord__Order__r.csord__Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is created for usage in HTML Templates</inlineHelpText>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>LG_ProvisioningAccountNo__c</fullName>
        <label>Provisioning Account No</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ProvisioningWorkOrder__c</fullName>
        <externalId>true</externalId>
        <label>Provisioning Work Order</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/JiraAttributeLookupMapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Attribute_Name__c</fullName>
        <label>Attribute Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Field_Value__c</fullName>
        <label>SF Field Value</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subsitution_Value__c</fullName>
        <label>Subsitution Value</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>JiraAttributeLookupMapping</label>
    <pluralLabel>JiraAttributeLookupMappings</pluralLabel>
</CustomObject>

src/objects/JiraAttributesMapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Attribute_Name__c</fullName>
        <label>Attribute Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Constant_Value__c</fullName>
        <label>Constant Value</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Mandatory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Mandatory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Service_Child__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Service Child</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Value_Lookup__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Value Lookup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SF_Field__c</fullName>
        <label>SF Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>JiraAttributesMapping</label>
    <pluralLabel>JiraAttributesMappings</pluralLabel>
</CustomObject>

src/objects/JiraAttributesProduktMapping__mdt.object
<CustomObject>
    <description>To Map the produckt paramter in the Jira form with the SF services</description>
    <fields>
        <fullName>Download_Speed_Code__c</fullName>
        <label>Download Speed Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Download_Speed__c</fullName>
        <label>Download Speed</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Option_with_Child__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Option with Child</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Code__c</fullName>
        <label>Service Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>JiraAttributesProduktMapping</label>
    <pluralLabel>JiraAttributesProduktMappings</pluralLabel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>UM_PartnerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <businessProcess>Stage</businessProcess>
        <description>Stage</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UM_JiraCreateIssue.cls
/**
* This class is for creation of JIRA form on the fly.
*
* @author Ankur Gupta
* @ticket SFOM-2145
* @since  03/11/2017
*/
global class UM_JiraCreateIssue
{ 
    public static Map<String,String> valueLookUpMap;
    public static Map<String,JiraAttributesMapping__mdt> parameterMap;
    public static Map<Schema.SObjectType,Set<String>> missingFieldMap;
    public static Map<String, JiraAttributesProduktMapping__mdt> produktParameterMapping;
    
    public static sObject sObj;
    public static Boolean isChild;
    public static String formJson = '';    
    public static csord__service__c service;
    
    public static Set<String> childServiceNames;
    
    public static String createJiraOrder(csord__solution__c currentSolution)
    {
        Set<String> queryFieldSet = new Set<String>();
        
        missingFieldMap = new Map<Schema.SObjectType, Set<String>>();
        parameterMap    = new Map<String,JiraAttributesMapping__mdt>();
        valueLookUpMap  = new Map<String,String>();
        childServiceNames = new Set<String>();
        produktParameterMapping = new Map<String,JiraAttributesProduktMapping__mdt>();
        
        service = [SELECT Id,Name,UM_JiraIssueTypeId__c, UM_DownloadSpeed__c,LG_Suborder__c, UM_DependsOnService__r.LG_Suborder__r.LG_ProvisioningWorkOrder__c,
                   UM_DependsOnService__c, UM_DependsOnService__r.LG_Suborder__r.LG_ProvisioningAccountNo__c,LG_RootOrder__r.csordtelcoa__Opportunity__r.UM_PartnerAccount__c, 
                   csord__Service__r.csord__Service__c,UM_AS_Number__c,UM_Announced_prefix__c,UM_BGP_Password__c,UM_IPv4__c,UM_IPv6__c,LG_SLA__c,
                   UM_Access_Active_IPv4__c,UM_Access_Active_IPv6__c,UM_Access_Transfer_IPv4__c,UM_Access_Transfer_IPv6__c,LG_AdditionalInformation__c,
                   csord__service__r.LG_Suborder__r.LG_ProvisioningWorkOrder__c           // SFOM-2665
                   FROM csord__Service__c WHERE LG_Suborder__c =:currentSolution.Id AND UM_JiraIssueTypeId__c != null];
		
        if(service.Name.containsIgnoreCase('Access'))
            childServiceNames.add('Access');
        else if(service.Name.containsIgnoreCase('BGP'))
            childServiceNames.add('BGP');
        /*SFOM-2665 -- Start*/
        else if(service.Name.containsIgnoreCase('Company Cloud Fiber'))    
            childServiceNames.add('CCF');
        /*SFOM-2665 -- End*/
        else
            childServiceNames.add(service.name);
        
        // Add all the query fields of each parameter in queryFieldSet
        for(JiraAttributesMapping__mdt attr : [SELECT id, MasterLabel, DeveloperName, Attribute_Name__c, Constant_Value__c, Form_Name__c, 
                                               Is_Mandatory__c, Is_Service_Child__c, Is_Value_Lookup__c, SF_Field__c 
                                               FROM JiraAttributesMapping__mdt 
                                               WHERE Form_Name__c = :service.UM_JiraIssueTypeId__c AND Is_Service_Child__c = false])
        {
            if(attr.SF_Field__c != null){
                queryFieldSet.add(attr.SF_Field__c.toUpperCase());
            }
            parameterMap.put(attr.Attribute_Name__c, attr);
        }
        
        //Create map of lookup Values for each attribute
        for(JiraAttributeLookupMapping__mdt valueLookup : [SELECT Id, MasterLabel, DeveloperName, Attribute_Name__c, Form_Name__c, 
                                                           SF_Field_Value__c,Subsitution_Value__c FROM JiraAttributeLookupMapping__mdt 
                                                           WHERE Form_Name__c = :service.UM_JiraIssueTypeId__c ])
        {
            valueLookUpMap.put(valueLookup.Attribute_Name__c+valueLookup.SF_Field_Value__c, valueLookup.Subsitution_Value__c);
        }
        
        for(JiraAttributesProduktMapping__mdt produktMap : [SELECT Id, MasterLabel, DeveloperName, Download_Speed__c, Name__c,
                                                            Download_Speed_Code__c, Option_with_Child__c, Service_Code__c FROM 
                                                            JiraAttributesProduktMapping__mdt WHERE Name__c IN :childServiceNames])
        {
            if(produktMap.Option_with_Child__c)
                produktParameterMapping.put(produktMap.Name__c + produktMap.Download_Speed__c , produktMap);
            else
                produktParameterMapping.put(produktMap.Name__c + service.UM_DownloadSpeed__c, produktMap);
        }
        
        String serviceQuery = 'SELECT Id';
        //get the child queries (if any) and append it in the service query
        String childQuery = createChildQuery(service);
        
        if(String.isNotBlank(childQuery)){
            serviceQuery = serviceQuery + childQuery;
        }
        
        for(String field : fieldParser(queryFieldSet) )
        {
            serviceQuery = serviceQuery + ', ' + field;
        }
        
        serviceQuery = serviceQuery + ' FROM csord__service__c WHERE UM_JiraIssueTypeId__c = \'' + service.UM_JiraIssueTypeId__c + '\' AND LG_Suborder__c = \'' + currentSolution.Id + '\'';
        sObj = Database.query(serviceQuery);
        
        String srQuery = 'SELECT Id,body,Name FROM StaticResource WHERE Name = \'JiraForm_' + service.UM_JiraIssueTypeId__c + '\'';
        StaticResource sr = Database.query(srQuery);        
        formJson = sr.body.tostring();
        formJson = formJson.replaceAll('"attribute" : "' , '"attribute": "');
        formJson = formJson.replaceAll('"attribute" :"' , '"attribute": "');
        formJson = formJson.replaceAll('"attribute":"' , '"attribute": "');
        
        JSONParser parser = Json.createParser(formJson);
        Set<String> attributeSet = new Set<string>();
        
        while (parser.nextToken() != null) 
        {
            if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getCurrentName() == 'attribute')
            {    
                parser.nextToken();
                attributeSet.add(parser.getText());
            }
        } 
        
        //Set Vermittler parameters based on the availability of partner account linked to opportunity
        if(service.LG_RootOrder__r.csordtelcoa__Opportunity__r.UM_PartnerAccount__c != null)
        {
            for(String attributeKey : parameterMap.keySet())
            {
                if(parameterMap.get(attributeKey).MasterLabel.contains('Vermittler') && parameterMap.get(attributeKey).MasterLabel != 'Vermittler (Firma)')
                    parameterMap.remove(attributeKey);
            }    
        }
        
        return valueAppender(attributeSet);
    }
    
    //Append value tag for each attribute available in the Jira form
    public static String valueAppender(Set<String> attributeSet)
    {
        String replacement;
        String value;
        String attributeTag;
        String valueTag;
        String summaryValue;
        
        for(String attribute: attributeSet)
        {
            attributeTag = '"attribute": "'+ attribute +'",';
            valueTag     = '"value" : "' ;
            isChild = false;
            
            if(parameterMap.containsKey(attribute) && String.isNotBlank(parameterMap.get(attribute).SF_Field__c))
            {
                replacement = '';
                value       = '';
                
                Set<String> fieldSet = new Set<String>{parameterMap.get(attribute).SF_Field__c};    
                List<String> fields = UM_JiraCreateIssue.fieldParser(fieldSet);
                
                if(!parameterMap.get(attribute).Is_Service_Child__c)
                {
                    if(parameterMap.get(attribute).Is_Value_Lookup__c == false){
                        valueTag = valueTag + getValueTag(attribute,fields);
                    }
                    else
                    {
                        value = String.valueOf(getFieldValue(sObj, fields[0] , parameterMap.get(attribute).Is_Mandatory__c));
                        if(value != null && valueLookUpMap.containsKey(attribute+value))
                            valueTag = valueTag + valueLookUpMap.get(attribute+value) + '",';
                    }
                }
                else
                {
                    isChild = true;
                    valueTag = valueTag + getValueTag(attribute,fields);
                }
            }
            else if(parameterMap.containsKey(attribute) && String.isNotBlank(parameterMap.get(attribute).Constant_Value__c) 
                    && parameterMap.get(attribute).Is_Value_Lookup__c == false )
            {
                valuetag  = valuetag + parameterMap.get(attribute).Constant_Value__c + '",';
            }
            //if for a attribute valueTag gets appended value, then append valueTag in the form
            if(valueTag.contains(','))
            {
                if(parameterMap.get(attribute).Attribute_Name__c == 'summary'){
                  if(valueTag.substringBefore('_').containsIgnoreCase('HSN'))   
                        valueTag = valueTag.replaceFirst('HSN','HE');
                    summaryValue = valueTag;
                }
                
                if(formJson.contains(attributeTag ))
                    replacement = attributeTag + '\n' + valuetag;
                else
                {
                    attributeTag = attributeTag.removeEnd(',');
                    replacement = valuetag + '\n' + attributeTag;
                }
                
                formJson = formJson.replace(attributeTag, replacement);
            }
        }
        
        if(service.csord__service__c != null)
        {
            String key = '';
            
            if(service.Name.containsIgnoreCase('Access'))
                key = 'Access' + service.UM_DownloadSpeed__c;
            else if(service.Name.containsIgnoreCase('BGP'))
                key = 'BGP' + service.UM_DownloadSpeed__c;
            /*SFOM-2665 -- Start*/
            else if(service.Name.containsIgnoreCase('Company Cloud Fiber'))  
                key = 'CCF' + service.UM_DownloadSpeed__c;
            /*SFOM-2665 -- End*/
            else
                key = service.Name + service.UM_DownloadSpeed__c;
            
            valueTag = '"value" : "';
            attributeTag = '"attribute": "customfield_14500",';
            
            if(produktParameterMapping.containsKey(key))
            {
                if(produktParameterMapping.get(key).Option_with_Child__c)
                    valueTag += produktParameterMapping.get(key).Service_Code__c + '",\n"child" : "' + produktParameterMapping.get(key).Download_Speed_Code__c  +'",';
                else
                    valueTag += produktParameterMapping.get(key).Service_Code__c + '",';
                
                replacement = attributeTag + '\n' + valuetag;
                formJson = formJson.replace(attributeTag, replacement);
            }
            /*SFOM-2665 -- Start*/
            valueTag = '"value" : "';
            attributeTag = '"attribute": "description",';
                
            if(service.Name.containsIgnoreCase('BGP'))
            {
                if(String.isNotBlank(summaryValue))
                    formJson = formJson.replace(summaryValue, summaryValue.substringBefore('_') + '_BGP_' + summaryValue.substringAfter('_'));
                //for description attribute
                if(!String.isBlank(String.valueOf(service.UM_AS_Number__c)) && service.UM_AS_Number__c != 0)
                    valueTag += 'AS-Nummer: ' + service.UM_AS_Number__c + ' \\n ';
                if(!String.isBlank(service.UM_Announced_prefix__c))
                    valueTag += 'Announced Prefix: ' + service.UM_Announced_prefix__c + ' \\n ';
                if(!String.isBlank(service.UM_BGP_Password__c))
                    valueTag += 'BGP-Passwort: ' + service.UM_BGP_Password__c + ' \\n ';
                if(!String.isBlank(service.UM_IPv4__c))
                    valueTag += 'IPv4 PI Adressraum: ' + service.UM_IPv4__c + ' \\n ';
                if(!String.isBlank(service.UM_IPv6__c))
                    valueTag += 'IPv6 PI Adressraum: ' + service.UM_IPv6__c + ' \\n ';
                if(!String.isBlank(service.LG_AdditionalInformation__c))
                    valueTag += 'zusätzliche Information: ' + service.LG_AdditionalInformation__c ;
            }
            else if(service.Name.containsIgnoreCase('Access'))
            {
                if(String.isNotBlank(summaryValue))
                    formJson = formJson.replace(summaryValue, summaryValue.substringBefore('_') + '_IP-A_' + summaryValue.substringAfter('_'));
                //for description attribute
                if(String.isNotBlank(service.UM_Access_Active_IPv4__c))
                    valueTag += 'Wirknetz-IPv4: ' + service.UM_Access_Active_IPv4__c + ' \\n ';
                if(String.isNotBlank(service.UM_Access_Active_IPv6__c))
                    valueTag += 'Wirknetz-IPv6: ' + service.UM_Access_Active_IPv6__c + ' \\n ';
                if(String.isNotBlank(service.UM_Access_Transfer_IPv4__c))
                    valueTag += 'Transfernetz-IPv4: ' + service.UM_Access_Transfer_IPv4__c + ' \\n ';
                if(String.isNotBlank(service.UM_Access_Transfer_IPv6__c))
                    valueTag += 'Transfernetz-IPv6: ' + service.UM_Access_Transfer_IPv6__c + ' \\n ';
                if(!String.isBlank(String.valueOf(service.LG_AdditionalInformation__c)))
                    valueTag += 'zusätzliche Information: ' + service.LG_AdditionalInformation__c;
            }
            else if(service.Name.containsIgnoreCase('Company Cloud Fiber'))
            {                
                if(String.isNotBlank(summaryValue))
                    formJson = formJson.replace(summaryValue, summaryValue.substringBefore('_') + '_CFP_' + summaryValue.substringAfter('_'));
                //for description attribute                
				if(!String.isBlank(String.valueOf(service.LG_AdditionalInformation__c)))
                    valueTag += 'zusätzliche Information: ' + service.LG_AdditionalInformation__c + ' \\n ';
                if(String.isNotBlank(service.csord__service__r.LG_Suborder__r.LG_ProvisioningWorkOrder__c))
                    valueTag += 'Jira Id: ' + service.csord__service__r.LG_Suborder__r.LG_ProvisioningWorkOrder__c;
            }
              	
                if(valueTag != '"value" : "') {
                    valueTag += '",';
                    replacement = attributeTag + '\n' + valuetag;
                    formJson = formJson.replace(attributeTag, replacement);
                }
            /*SFOM-2665 -- End*/
            }
        
        else if(service.UM_DependsOnService__c != null)
        {
            if(String.isNotBlank(summaryValue))
                formJson = formJson.replace(summaryValue, summaryValue.substringBefore('_') + '_Fibre/Coax_' + summaryValue.substringAfter('_'));
            
            //Kunde(RNS)
            attributeTag = '"attribute": "customfield_15500",';
            //for CI + MWLAN
            if(String.isNotBlank(service.UM_DependsOnService__r.LG_Suborder__r.LG_ProvisioningAccountNo__c))
            {
                valueTag     = '"value" : "' + service.UM_DependsOnService__r.LG_Suborder__r.LG_ProvisioningAccountNo__c + '",';
                replacement  = attributeTag + '\n' + valuetag;
                formJson     = formJson.replace(attributeTag, replacement);
            }
            //for CF + MWLAN
            else if(String.isNotBlank(service.UM_DependsOnService__r.LG_Suborder__r.LG_ProvisioningWorkOrder__c)
                    && service.UM_DependsOnService__r.LG_Suborder__r.LG_ProvisioningWorkOrder__c.contains('BBS'))
            {
                valueTag     = '"value" : "' + service.UM_DependsOnService__r.LG_Suborder__r.LG_ProvisioningWorkOrder__c + '",';
                replacement  = attributeTag + '\n' + valuetag;
                formJson     = formJson.replace(attributeTag, replacement);
            }
        }
        
        System.debug('finalJson : ' + formJson);
        return formJson;
    }
    
    //Create Child Query for attributes with Is Service Child true
    public static String createChildQuery(csord__service__c service)
    {
        Set<String> childQueryFieldSet = new Set<String>();
        Map<String,List<String>> childQueryMap = new Map<String,List<String>>();
        String childQuery = null;
        // Add all the query fields for child objects of service
        for(JiraAttributesMapping__mdt attr: [SELECT id, MasterLabel, DeveloperName, Attribute_Name__c, Constant_Value__c, Form_Name__c, 
                                              Is_Mandatory__c, Is_Service_Child__c, Is_Value_Lookup__c, SF_Field__c 
                                              FROM JiraAttributesMapping__mdt 
                                              WHERE Form_Name__c = :service.UM_JiraIssueTypeId__c AND Is_Service_Child__c = true])
        {
            if(attr.SF_Field__c != null){
                childQueryFieldSet.add(attr.SF_Field__c.toUpperCase());
            }
            parameterMap.put(attr.Attribute_Name__c, attr);
        }
        
        for(String childField : fieldParser(childQueryFieldSet))
        {
            if(childField.contains('.')){
                List<String> token = childField.split('\\.');
                if(!childQueryMap.containsKey(token[0]))
                    childQueryMap.put(token[0], new List<String>{token[1]});
                else
                    childQueryMap.get(token[0]).add(token[1]);
            }
        }
        
        //Create query on service object using parsed field set list
        for(String obj : childQueryMap.keySet() )
        {
            if(childQuery!=null)
                childQuery = childQuery + ', (SELECT Id, ' + String.join(childQueryMap.get(obj), ',') + ' FROM ' + obj + ')';
            else
                childQuery = ', (SELECT Id, ' + String.join(childQueryMap.get(obj), ',') + ' FROM ' + obj + ') ';
        }
        return childQuery;
    }
    
    public static List<String> fieldParser(Set<String> queryFieldSet)
    {
        Set<String> fieldSet = new Set<String>();
        Set<String> tempFieldSet = new Set<String>();
        for(String field : queryFieldSet)
        {
            if(field.contains('<'))
                tempFieldSet.addall(field.split('<'));    
        }
        
        for(String field : tempFieldSet)
        {
            if(field.contains('>'))
                fieldSet.add(field.split('>')[0].toUpperCase().normalizeSpace());    
        }
        return new List<String>(fieldSet);
    }
    
    public static String getValueTag(String attribute, List<String> fields)
    {
        String value = '';
        //If SF_Field contains only one field e.g. - <LG_AccountName__c>
        if(fields.size() == 1)
        {   
            value = String.valueOf(getFieldValue(sObj, fields[0], parameterMap.get(attribute).Is_Mandatory__c));
            if(value != null) 
                return value + '",';
        }
        //If SF_Field contains more than one field e.g. - <LG_AccountName__c>_<LG_CustomerName__c> <LG_Address_c>
        else if(fields.size() > 1)
        {
            String toBeReplacedField = parameterMap.get(attribute).SF_Field__c.toUpperCase();                
            for(String multiField : fields)
            {
                value = String.valueOf(getFieldValue(sObj, multiField, parameterMap.get(attribute).Is_Mandatory__c));
                multiField = '<' + multiField + '>'; 
                toBeReplacedField = value!=null ? toBeReplacedField.replace(multiField, value) : toBeReplacedField.replace(multiField, '');
            }
            return toBeReplacedField + '",';
        }
        return value;
    }
    
    // To get field values for relationship fields e.g. [LG_Address__r.LG_TechnicalContact__r.Phone]
    public static Object getFieldValue(sObject sObj, String field, Boolean isMandatory)
    {
        if(sObj == null)
            return null;
        
        if(field.contains('.'))
        {
            String nextField = field.substringAfter('.');
            String relation = field.substringBefore('.');
            return isChild == false ?  UM_JiraCreateIssue.getFieldValue((sObject)sObj.getSObject(relation),nextField, isMandatory) : 
            UM_JiraCreateIssue.getFieldValue((sObject)sObj.getSObjects(relation)[0],nextField, isMandatory);
        }
        else{
            if(sObj.get(field) == null && isMandatory)
            {
                Schema.SObjectType key = sObj.getSObjectType();
                //String objName = key.getDescribe().getName();
                //Schema.SObjectField fld = Schema.getGlobalDescribe().get(objName).getDescribe().fields.getMap().get(field);
                if(!missingFieldMap.containsKey(key))
                    missingFieldMap.put(key, new Set<String>{field.toLowerCase()});  
                else
                    missingFieldMap.get(key).add(field.toLowerCase()); 
 
                System.debug('missingMap# ' + missingFieldMap);
            }
            
            if(sObj.get(field) instanceof Date)
                return formatDate((Date)sObj.get(field));

            return sObj.get(field);
        }
    }
    
    public static String formatDate(Date installOrWishDate)
    {
       return Datetime.newInstance(installOrWishDate.year(), installOrWishDate.month(), installOrWishDate.day()).format('dd.MM.YYYY');
    }
}