src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_VisitPostalCode__c</fullName>
        <label>Visit Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Master</fullName>
        <active>true</active>
        <description>Record type for all employees</description>
        <label>Master</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
	<fields>
        <fullName>LeadAssignmentErrorMsg__c</fullName>
        <description>Update the filed with error msg when the lead data didn&apos;t match with the data in Lead Assignment Table</description>
        <inlineHelpText>Unable to find the data(Product Family or Postal code) in Lead Assignment Table</inlineHelpText>
        <label>LeadAssignmentErrorMsg</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Analog_Availability__c</fullName>
        <label>Analog Availability</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
                <value>
                    <fullName>Not Performed</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assigned_Date__c</fullName>
        <description>This date filed will auto populate when Lead is assign to a user by LG_LeadUpdateTrigger as per the Lead Assignment table. This field will not populate when Lead is assign to a queue.</description>
        <label>Assigned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Internet_Availability__c</fullName>
        <label>Internet Availability</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
                <value>
                    <fullName>Not Performed</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Availability_Performed__c</fullName>
        <description>To check the product&apos;s availability on a given postal code</description>
        <inlineHelpText>Please click on Perform “Availability Checker” button to perform the availability check.</inlineHelpText>
        <label>Is Availability Performed?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Withdrawn__c</fullName>
	<defaultValue>false</defaultValue>
	<description>This checkbox will be checked when lead has been withdrawn</description>
	<label>Withdrawn</label>
	<type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_MatchingAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field on Lead to Account</description>
        <inlineHelpText>When a matching account is found please convert lead to an existing account without the creation of an opportunity</inlineHelpText>
        <label>Matching Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_VisitPostalCode__c</fullName>
        <label>Visit Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Availability__c</fullName>
        <label>Mobile Availability</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
                <value>
                    <fullName>Not Performed</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone_Availability__c</fullName>
        <label>Phone Availability</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Unavailable</fullName>
                </value>
                <value>
                    <fullName>Not Performed</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_Product__c</fullName>
        <description>Field to capture selected product from web form</description>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UM_Product</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Assignment_Table__c.object
<CustomObject>
    <fields>
        <fullName>Assign_to_Queue__c</fullName>
        <label>Assign to Queue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Assignee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.IsActive</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Lead_Assignment_Tables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Company Internet</fullName>
                </value>
                <value>
                    <fullName>Company Fiber</fullName>
                </value>
                <value>
                    <fullName>Virtual Voice</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lead Assignment Table</label>
    <nameField>
        <displayFormat>LAT-{000000}</displayFormat>
        <label>Lead Assignment Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Assignment Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Queue_Name__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>QueueID__c</fullName>
        <label>QueueID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Queue Name</label>
</CustomObject>

src/classes/LG_LeadUpdateTriggerHandler.cls
public with sharing class LG_LeadUpdateTriggerHandler {
    
    Set<String> prodFamilySet = new Set<String>();
    Set<String> postalCodeSet = new Set<String>();
    Set<String> accontNameSet = new Set<String>();
    Set<ID> ownerIDSet = new Set<ID>();
    
    Map<String, List<Lead_Assignment_Table__c>> prodFAndleadATMap = new Map<String, List<Lead_Assignment_Table__c>>();
    Map<String, Lead_Assignment_Table__c> postalCodeAndleadATMap = new Map<String, Lead_Assignment_Table__c>();
    Map<ID, Account> accMap;
    
    Lead_Assignment_Table__c  leadAssignTonPFnPCNull;
    List<Lead_Assignment_Table__c>  LATList;
    Boolean haveNull = false;
    
    ID queueID = Queue_Name__c.getInstance('QueueName').QueueID__c;
    
    public void createLeadAssignmentMap(List<Lead> leadList){
        for(Lead lead: leadList){
            if(lead.UM_Product__c == NULL && lead.LG_VisitPostalCode__c == NULL){
                haveNull = true;
            }
            else if(lead.UM_Product__c != NULL){
                prodFamilySet.add(lead.UM_Product__c);
            }
            else if(lead.UM_Product__c == NULL && lead.LG_VisitPostalCode__c != NULL){
                String postalcode = lead.LG_VisitPostalCode__c.substring(0, 3);
                postalCodeSet.add(postalcode);
                //postalCodeSet.add(lead.LG_VisitPostalCode__c);
            }
            if(lead.LG_MatchingAccount__c != NULL){
                accontNameSet.add(lead.LG_MatchingAccount__c);
            }
        }
        
        if(haveNull && (prodFamilySet.size() > 0 || postalCodeSet.size() > 0)){
            LATList = [SELECT Id, Product_Family__c, Postal_Code__c, Lead_Assignee__c, Assign_to_Queue__c 
                       FROM Lead_Assignment_Table__c 
                       WHERE (Product_Family__c = NULL AND Postal_Code__c = NULL)
                       OR Product_Family__c IN :prodFamilySet OR Postal_Code__c IN :postalCodeSet];
        }
        else if(haveNull){
            LATList = [SELECT Id, Product_Family__c, Postal_Code__c, Lead_Assignee__c, Assign_to_Queue__c 
                       FROM Lead_Assignment_Table__c 
                       WHERE (Product_Family__c = NULL AND Postal_Code__c = NULL)];
        }
        else if(prodFamilySet.size() > 0 || postalCodeSet.size() > 0){
            LATList = [SELECT Id, Product_Family__c, Postal_Code__c, Lead_Assignee__c, Assign_to_Queue__c 
                       FROM Lead_Assignment_Table__c 
                       WHERE (Product_Family__c IN :prodFamilySet OR Postal_Code__c IN :postalCodeSet)];
        }
        
        System.debug('LATList::'+LATList.size()+'-->'+LATList);
        
        for(Lead_Assignment_Table__c leadAssignT : LATList){
            
            ownerIDSet.add(leadAssignT.Lead_Assignee__c);
            
            List<Lead_Assignment_Table__c> ltList = new List<Lead_Assignment_Table__c>();
            
            if(leadAssignT.Product_Family__c != NULL){
                if(prodFAndleadATMap.get(leadAssignT.Product_Family__c) != null){
                    ltList.add(leadAssignT);
                    ltList.addAll(prodFAndleadATMap.get(leadAssignT.Product_Family__c));
                    prodFAndleadATMap.put(leadAssignT.Product_Family__c, ltList);
                }
                else{
                    ltList.add(leadAssignT);
                    prodFAndleadATMap.put(leadAssignT.Product_Family__c, ltList);
                }
            }
            else if(leadAssignT.Product_Family__c == NULL && leadAssignT.Postal_Code__c != NULL){
                postalCodeAndleadATMap.put(leadAssignT.Postal_Code__c, leadAssignT);
            }
            else{
                system.debug('Inside else::'+leadAssignT);
                leadAssignTonPFnPCNull = leadAssignT;
            }            
        }
        if(accontNameSet.size() > 0){
            accMap = new Map<ID, Account>([SELECT ID, OwnerId FROM Account WHERE Id IN :accontNameSet]);
        }        
    }
    
    public void automaticLeadAssign(List<lead> leadList){
        for(Lead lead:leadList){
            if(lead.OwnerId == queueID){
                if(lead.LG_MatchingAccount__c != NULL && accMap.containsKey(lead.LG_MatchingAccount__c)){
                    lead.OwnerId = accMap.get(lead.LG_MatchingAccount__c).OwnerID;
                    lead.LeadAssignmentErrorMsg__c = '';
                    lead.Assigned_Date__c = Date.Today();
                }
                else if(lead.LG_MatchingAccount__c != NULL && !accMap.containsKey(lead.LG_MatchingAccount__c)){
                    lead.LeadAssignmentErrorMsg__c = 'Account found on Lead but not under Account object';
                }
                else if(prodFAndleadATMap.size()>0 || postalCodeAndleadATMap.size()>0 || leadAssignTonPFnPCNull != NULL){
                    if(lead.UM_Product__c != NULL && prodFAndleadATMap.containsKey(lead.UM_Product__c)){
                        if(prodFAndleadATMap.get(lead.UM_Product__c).size() == 1){
                            if(prodFAndleadATMap.get(lead.UM_Product__c)[0].Lead_Assignee__c != NULL){
                                lead.OwnerId = prodFAndleadATMap.get(lead.UM_Product__c)[0].Lead_Assignee__c;
                                lead.LeadAssignmentErrorMsg__c = '';
                                lead.Assigned_Date__c = Date.Today();
                            }
                            else if(prodFAndleadATMap.get(lead.UM_Product__c)[0].Assign_to_Queue__c != NULL){
                                lead.OwnerId = prodFAndleadATMap.get(lead.UM_Product__c)[0].Assign_to_Queue__c;
                                lead.LeadAssignmentErrorMsg__c = '';
                            }
                            else{
                                lead.LeadAssignmentErrorMsg__c = 'Assignee is not available in the master table';
                            }
                        }
                        else{
                            for(Lead_Assignment_Table__c LAT : prodFAndleadATMap.get(lead.UM_Product__c)){
                                if(lead.LG_VisitPostalCode__c.substring(0, 3) == LAT.Postal_Code__c){
                                    if(LAT.Lead_Assignee__c != NULL){
                                        lead.OwnerId = LAT.Lead_Assignee__c;
                                        lead.LeadAssignmentErrorMsg__c = '';
                                        lead.Assigned_Date__c = Date.Today();
                                        break;
                                    }
                                    else if(LAT.Assign_to_Queue__c != NULL){
                                        lead.OwnerId = LAT.Assign_to_Queue__c;
                                        lead.LeadAssignmentErrorMsg__c = '';
                                        break;
                                    }
                                    else{
                                        lead.LeadAssignmentErrorMsg__c = 'Assignee is not available in the master table';
                                        break;
                                    }
                                }
                                else{
                                    lead.LeadAssignmentErrorMsg__c = 'Lead Postal Code is not available in the master table';
                                }
                            }
                        }
                    }
                    else if(lead.UM_Product__c == NULL && lead.LG_VisitPostalCode__c != NULL && postalCodeAndleadATMap.containsKey(lead.LG_VisitPostalCode__c.substring(0, 3))){
                        if(postalCodeAndleadATMap.get(lead.LG_VisitPostalCode__c.substring(0, 3)).Lead_Assignee__c != NULL){
                            lead.OwnerId = postalCodeAndleadATMap.get(lead.LG_VisitPostalCode__c.substring(0, 3)).Lead_Assignee__c;
                            lead.LeadAssignmentErrorMsg__c = '';
                            lead.Assigned_Date__c = Date.Today();
                        }
                        else if(postalCodeAndleadATMap.get(lead.LG_VisitPostalCode__c.substring(0, 3)).Assign_to_Queue__c != NULL){
                            lead.OwnerId = postalCodeAndleadATMap.get(lead.LG_VisitPostalCode__c.substring(0, 3)).Assign_to_Queue__c;
                            lead.LeadAssignmentErrorMsg__c = '';
                        }
                        else{
                            lead.LeadAssignmentErrorMsg__c = 'Assignee is not available in the master table';
                        }
                    }
                    else if(lead.UM_Product__c == NULL && lead.LG_VisitPostalCode__c == NULL){
                        if(leadAssignTonPFnPCNull.Lead_Assignee__c != NULL){
                            lead.OwnerId = leadAssignTonPFnPCNull.Lead_Assignee__c;
                            lead.LeadAssignmentErrorMsg__c = '';
                            lead.Assigned_Date__c = Date.Today();
                        }
                        else if(leadAssignTonPFnPCNull.Assign_to_Queue__c != NULL){
                            lead.OwnerId = leadAssignTonPFnPCNull.Assign_to_Queue__c;
                            lead.LeadAssignmentErrorMsg__c = '';
                        }
                        else{
                            lead.LeadAssignmentErrorMsg__c = 'Assignee is not available in the master table';
                        }
                    }
                }
                else{
                    lead.LeadAssignmentErrorMsg__c = 'No data found in the master table';
                }
            }
        }
    }
    
    //Deb-- 14 Mar, serviceability check
    public void validateLeadChanges(Map<Id,Lead> oldLeadMap,Map<Id,Lead> newLeadMap) 
    {
        system.debug('lead handler called');
        for(Lead leadObj : newLeadMap.values())
        {
            if(leadObj.LG_VisitPostalCode__c!=oldLeadMap.get(leadObj.Id).LG_VisitPostalCode__c)
            {
                leadObj.Is_Availability_Performed__c= 'No';
                leadObj.Phone_Availability__c='Not Performed';
                leadObj.Mobile_Availability__c='Not Performed';
                leadObj.Internet_Availability__c='Not Performed';
                leadObj.Analog_Availability__c='Not Performed';
                
            }           
	    // added as a part of CATGOV-490
            if(oldLeadMap.get(leadObj.Id).ownerID != leadObj.ownerID && !ownerIDSet.contains(leadObj.ownerID)){
                leadObj.Withdrawn__c = FALSE;
            }
            //end
        } 
    }
     //end
}