src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_ChamberOfCommerceNumber__c</fullName>
        <description>KvK No.</description>
        <label>National ID number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LG_Footprint__c</fullName>
        <description>Defining Footprint to which a Lead/Company/Account belongs</description>
        <label>Footprint</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UPC</fullName>
                </value>
                <value>
                    <fullName>Ziggo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitCountry__c</fullName>
        <label>Visit Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                    <default>true</default>
                    <label>Germany</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>csconta__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Kenan_Adjustment__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Reason__c</fullName>
        <label>Adjustment Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Goodwill credit invoice Complaints</fullName>
                </value>
                <value>
                    <fullName>Goodwill credited disorder</fullName>
                </value>
                <value>
                    <fullName>Goodwill credit counseling</fullName>
                </value>
                <value>
                    <fullName>Goodwill credited Installation</fullName>
                </value>
                <value>
                    <fullName>Cancellation / Termination</fullName>
                </value>
                <value>
                    <fullName>False entry in the system (correction)</fullName>
                </value>
                <value>
                    <fullName>Non provided SLA Entstֲfrist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Adjustment_Type__c</fullName>
        <label>Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>miscellaneous adjustment</fullName>
                </value>
                <value>
                    <fullName>adjustment against recurring charge</fullName>
                </value>
                <value>
                    <fullName>adjustment against non-recurring charge</fullName>
                </value>
                <value>
                    <fullName>adjustment against an adjustment</fullName>
                </value>
                <value>
                    <fullName>adjustment against nondistributed taxes</fullName>
                </value>
                <value>
                    <fullName>adjustment against usage charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>UM_InvoiceHeader__c</referenceTo>
        <relationshipLabel>Adjustments</relationshipLabel>
        <relationshipName>Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>requestStatus__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>disputed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>trackingIdServ__c</fullName>
        <label>trackingIdServ</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>trackingId__c</fullName>
        <externalId>true</externalId>
        <label>trackingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UM_InvoiceHeader__c.object
<CustomObject>
    <description>Extract from Kenan</description>
    <fields>
        <fullName>UM_Billing_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Invoice Headers</relationshipLabel>
        <relationshipName>Invoice_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_Customer_SF_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Headers1</relationshipLabel>
        <relationshipName>Invoice_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_InvoiceNumber__c</fullName>
        <description>Unique Kenan 10 digit Invoice Number</description>
        <externalId>true</externalId>
        <label>Invoice Number</label>
        <length>14</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Gross_Currency__c</fullName>
        <description>Outstanding Invoice Amount</description>
        <label>Outstanding Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Gross__c</fullName>
        <description>Outstanding Invoice Amount</description>
        <label>Outstanding Invoice Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Net_Currency__c</fullName>
        <description>Field to show real value of Invoice Amount sent by Kenan</description>
        <label>Gross Total Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Net__c</fullName>
        <description>gross total due</description>
        <label>Gross Total Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Date__c</fullName>
        <description>Date when invoice was issued</description>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UM_Payment_Due_Date__c</fullName>
        <label>Payment Due Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice Header</label>
    <nameField>
        <label>Invoice Headers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UM_PaymentInformation__c.object
<CustomObject>
    <description>Extract from Kenan</description>
    <fields>
        <fullName>UM_Billing_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Payment Information</relationshipLabel>
        <relationshipName>Payment_Information</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_Customer_SF_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Information</relationshipLabel>
        <relationshipName>Payment_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_Overpayments__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_Transaction_Amount__c</fullName>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_Transaction_Date__c</fullName>
        <description>For DD, the date a payment was sent to clearing house for DD
For REFUNDS the refund date</description>
        <label>Transaction Date</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_Transaction_ID__c</fullName>
        <description>Tracking_id and tracking_id_serv in combination uniquely identify a payment</description>
        <externalId>true</externalId>
        <label>Transaction ID</label>
        <length>14</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UM_Transaction_Status_Translation__c</fullName>
        <description>Translation of values from Transaction Status from Kenan</description>
        <label>Transaction Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_Transaction_Status__c</fullName>
        <description>0 = waiting
5 = payment reversal
1 = hold
6 = canceled
2 = sent
7 = deleted
3 = accepted
8 = posted
4 = rejected
9 = disconnected account record</description>
        <label>Transaction Status (N)</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Payment Information</label>
    <nameField>
        <label>Payment Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_Care_InvoiceInfoAccount360_Test.cls
@isTest
public class LG_Care_InvoiceInfoAccount360_Test
{
    Static testmethod void testbilling(){
        try{
            User careAgent=LG_Care_TestRunAsUser.testRunAs();
            System.runAs(careAgent) {
                
                Account acc = new Account();
                acc.Name='Infy-Test2';
                acc.LG_VisitCountry__c = 'Germany';
                acc.LG_ChamberOfCommerceNumber__c = '4';
                acc.LG_Footprint__c = 'UPC';
                
                insert acc;
                
                csconta__Billing_Account__c b1 = new csconta__Billing_Account__c();
                b1.csconta__Account__c=acc.id;
                
                insert b1;
            
                
                UM_InvoiceHeader__c InvoiceHeader1 = new UM_InvoiceHeader__c();
                InvoiceHeader1.UM_Customer_SF_ID__c = acc.Id;
                InvoiceHeader1.UM_Invoice_Date__c = Date.today().addDays(-10);
                InvoiceHeader1.UM_InvoiceNumber__c = '100';
                InvoiceHeader1.UM_Invoice_Amount_Gross_Currency__c = 100.00;
                InvoiceHeader1.UM_Invoice_Amount_Net_Currency__c = 75.00;
                InvoiceHeader1.UM_Invoice_Amount_Gross__c = 100;
                InvoiceHeader1.UM_Invoice_Amount_Net__c = 75;
                InvoiceHeader1.UM_Payment_Due_Date__c = Date.today().addDays(5);
                InvoiceHeader1.UM_Billing_Location__c = b1.Id;
                insert InvoiceHeader1 ;
                
                UM_InvoiceHeader__c InvoiceHeader2 = new UM_InvoiceHeader__c();
                InvoiceHeader2.UM_Customer_SF_ID__c = acc.Id;
                InvoiceHeader2.UM_Invoice_Date__c = Date.today().addDays(-7);
                InvoiceHeader2.UM_InvoiceNumber__c = '101';
                InvoiceHeader2.UM_Invoice_Amount_Gross_Currency__c = 100.00;
                InvoiceHeader2.UM_Invoice_Amount_Net_Currency__c = 75.00;
                InvoiceHeader2.UM_Invoice_Amount_Gross__c = 100;
                InvoiceHeader2.UM_Invoice_Amount_Net__c = 75;
                InvoiceHeader2.UM_Payment_Due_Date__c = Date.today().addDays(8);
                InvoiceHeader2.UM_Billing_Location__c = b1.Id;
                insert InvoiceHeader2 ;
                
                UM_InvoiceHeader__c InvoiceHeader3 = new UM_InvoiceHeader__c();
                InvoiceHeader3.UM_Customer_SF_ID__c = acc.Id;
                InvoiceHeader3.UM_Invoice_Date__c = Date.today().addDays(-4);
                InvoiceHeader3.UM_InvoiceNumber__c = '102';
                InvoiceHeader3.UM_Invoice_Amount_Gross_Currency__c = 50.00;
                InvoiceHeader3.UM_Invoice_Amount_Net_Currency__c = 35.00;
                InvoiceHeader3.UM_Invoice_Amount_Gross__c = 50;
                InvoiceHeader3.UM_Invoice_Amount_Net__c = 35;
                InvoiceHeader3.UM_Payment_Due_Date__c = Date.today().addDays(10);
                InvoiceHeader3.UM_Billing_Location__c = b1.Id;
                insert InvoiceHeader3 ;
              
                Kenan_Adjustment__c Adj1= new Kenan_Adjustment__c();
                Adj1.trackingId__c = '100';
                Adj1.trackingIdServ__c = '1';
                Adj1.Adjustment_Reason__c = 'Incorrect  charges' ;
                Adj1.Adjustment_Type__c = 'miscellaneous adjustment';
                Adj1.RequestStatus__c = 'requested';
                Adj1.Total_Amount__c = 40.00;
                Adj1.Invoice_Header__c = InvoiceHeader1.Id;
                insert Adj1; 
                
                
                Kenan_Adjustment__c Adj2= new Kenan_Adjustment__c();
                Adj2.trackingId__c = '102';
                Adj2.trackingIdServ__c = '1';
                Adj2.Adjustment_Reason__c = 'Incorrect  charges';
                Adj2.Adjustment_Type__c = 'miscellaneous adjustment';
                Adj2.RequestStatus__c = 'requested';
                Adj2.Total_Amount__c = 15.00;
                Adj2.Invoice_Header__c = InvoiceHeader2.Id;
                insert Adj2; 
                
                Kenan_Adjustment__c Adj3= new Kenan_Adjustment__c();
                Adj3.trackingId__c = '103';
                Adj3.trackingIdServ__c = '1';
                Adj3.Adjustment_Reason__c = 'Incorrect  charges';
                Adj3.Adjustment_Type__c = 'miscellaneous adjustment';
                Adj3.RequestStatus__c = 'requested';
                Adj3.Total_Amount__c = 40.00;
                Adj3.Invoice_Header__c = InvoiceHeader3.Id;
                insert Adj3; 
                
                
                UM_PaymentInformation__c PI = new UM_PaymentInformation__c();
                PI.UM_Transaction_Date__c = '20160804183629';
                PI.UM_Transaction_Amount__c = 33.00;
                PI.UM_Transaction_ID__c = '100';
                PI.UM_Transaction_Status__c = '2';
                PI.UM_Transaction_Status_Translation__c='b1 Payment Calculate';
                PI.UM_Billing_Location__c = b1.Id;
                PI.UM_Overpayments__c = 20.00;
                insert PI;        
                
                Test.StartTest();
                ApexPages.StandardController sc = new ApexPages.StandardController(acc);
                LG_Care_InvoiceInfoAccount360_Controller c = new LG_Care_InvoiceInfoAccount360_Controller(sc);
                system.assertNotEquals(c.wrapperList.size(), 0);
                system.debug('blnc23'+c.wrapperList);
                Test.StopTest();
            }
        }
        
        catch(DMLException e) {
            system.assertEquals(e.getMessage(), e.getMessage());
        }
    }
}