src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
   
</CustomObject>

src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>csconta__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csconta__Billing_Channel__c</fullName>
        <label>Billing Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paper</fullName>
                    <default>true</default>
                    <label>Paper</label>
                </value>
                <value>
                    <fullName>E-Mail PDF</fullName>
                </value>
                <value>
                    <fullName>Paper + E-Mail PDF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csconta__Format_Type__c</fullName>
        <label>Format Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                    <label>Standard</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csconta__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending activation</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending disconnection</fullName>
                </value>
                <value>
                    <fullName>Disconnected</fullName>
                </value>
		<value>
                    <fullName>Deactivation Requested</fullName>
                </value>
		<value>
                    <fullName>Deactivation Pending</fullName>
                </value>
		<value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_EffectiveDate__c</fullName>
        <description>This is the date when the change requested in configuration was implemented from the customer perspective. Normally this translates to Start Date. If the Delta Status was delete, this would translate to End Date.</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    
    <fields>
        <fullName>LG_ServiceStatus__c</fullName>
        <description>Pick-list to save the status of the service provisioning.</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                  <fullName>LG_SecondaryProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services (Secondary Product Configuration)</relationshipLabel>
        <relationshipName>Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Suborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services (Suborder)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Activation_Date__c</fullName>
        <description>The date of activation.</description>
        <inlineHelpText>The date of activation.</inlineHelpText>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csconta__Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Billing Account to use for this Subscription.</description>
        <inlineHelpText>The Billing Account to use for this Subscription.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Subscription.</description>
        <inlineHelpText>The parent Solution of this Subscription.</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_ScheduleAppointment__c.object
<CustomObject>
    <description>This object is used to capture the Appointment details during Order management orchestration process</description>
    <fields>
        <fullName>LG_AgreedInstallDate__c</fullName>
        <label>Agreed Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LG_JobReference__c</fullName>
        <label>Job Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Slot__c</fullName>
        <label>Slot</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Morning Slot</fullName>
                </value>
                <value>
                    <fullName>Afternoon Slot</fullName>
                </value>
                <value>
                    <fullName>Evening Slot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Schedule Appointment</relationshipLabel>
        <relationshipName>Schedule_Appointment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Status__c</fullName>
        <description>To capture status of appointment</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                    <default>true</default>
                    <label>Scheduled</label>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Schedule Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_InflightChangeUtilTest.cls
/**
 * Utillity class for Inflight Change Step HLD
 *
 * @author Petar Miletic
 * @ticket SFOM-355
 * @since  20/02/2017
*/
@IsTest
public class LG_InflightChangeUtilTest {

    @testsetup
    private static void setupTestData()
    {
        No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
        noTriggers.Flag__c = true;
        noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
        upsert noTriggers;

        Account acc = LG_GeneralTest.CreateAccount('TestAccount', '321654987', 'Test', true);
		
        csconta__Billing_Account__c ba = new csconta__Billing_Account__c();
    	ba.csconta__Account__c = acc.id;
    	ba.csconta__Status__c = 'New';
    	ba.csconta__Billing_Channel__c = 'Paper';
    	ba.csconta__Format_Type__c = 'Summary';
    	insert ba;
        
        Opportunity opp = LG_GeneralTest.CreateOpportunity(acc, true);
        
		// Solution 
		csord__Solution__c sol = new csord__Solution__c(Name = 'Test Solution', csord__Identification__c = '123456789');
		insert sol;
        
	   // SFOM-427 test data starts
       //Appointment
        LG_ScheduleAppointment__c app = new LG_ScheduleAppointment__c(Name = 'Test Appointment', LG_Status__C = 'Scheduled', LG_Solution__C = sol.id, LG_AgreedInstallDate__c = Date.today(), LG_JobReference__c = 'Test Ref', LG_Slot__c= 'Morning Slot');
		insert app;
        
        // Subscripton 
		csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = '6465467986',csconta__Billing_Account__c = ba.id);
        insert sub; 

        // Service 
		csord__Service__c service = new csord__Service__c(Name='TestService0',csord__Identification__c='6465467986',csord__Activation_Date__c=Date.today(),LG_Effectivedate__c=Date.today(), LG_ServiceStatus__C = 'Provisioned', LG_Suborder__c = sol.Id, csord__Subscription__c= sub.id ) ;
        insert service;
      
        //SFOM-427 test data ends
        
        // Inflight Configuration [0]
        // Manage Numbers [1]
        // Schedule Appointment [2]
		List<RecordType> objs = [SELECT Id, Name, IsActive FROM RecordType WHERE SobjectType = 'Case' AND Name IN ('Inflight Configuration', 'Manage Numbers', 'Schedule Appointment') ORDER BY Name ASC];

        Case reScheduleCase = new Case();
        reScheduleCase.RecordTypeId = objs[2].Id;
        reScheduleCase.Status = 'New';
        reScheduleCase.LG_Solution__c = sol.Id;
        reScheduleCase.Type = 'Modify';
        
        insert reScheduleCase;
        
        Case manageNumbers = new Case();
        manageNumbers.RecordTypeId = objs[1].Id;
        manageNumbers.Status = 'Closed';
        manageNumbers.LG_Solution__c = sol.Id;
        manageNumbers.Type = 'Inflight Change';
        
        insert manageNumbers;

        noTriggers.Flag__c = false;
        upsert noTriggers;
    }
    
    @isTest
    public static void reScheduleTest() {
        
        csord__Solution__c sol = [SELECT Id, Name FROM csord__Solution__c LIMIT 1];
        
		Test.startTest();
		
        Id caseId = LG_InflightChangeUtil.reSchedule(sol.Id);

		Test.stopTest();
		
		// 'Schedule Appointment', 'Modify'
		List<Case> cases = [SELECT Id FROM Case WHERE RecordType.Name = 'Schedule Appointment' AND Type = 'Modify'];
		
		System.assertEquals(1, cases.size(), 'Invalid data');
    }
    
    @isTest
    public static void correctNumbersTest() {
        
        csord__Solution__c sol = [SELECT Id, Name FROM csord__Solution__c LIMIT 1];
        
        Test.startTest();
		
        Id caseId = LG_InflightChangeUtil.correctNumbers(sol.Id);

		Test.stopTest();
		
		// 'Manage Numbers', 'Inflight Change'
		List<Case> cases = [SELECT Id FROM Case WHERE RecordType.Name = 'Manage Numbers' AND Type = 'Inflight Change'];
		
		System.assertEquals(2, cases.size(), 'Invalid data');
    }
    
    @isTest
    public static void configureTest() {
        
        csord__Solution__c sol = [SELECT Id, Name FROM csord__Solution__c LIMIT 1];
        
        Test.startTest();
		
        Id caseId = LG_InflightChangeUtil.configure(sol.Id);

		Test.stopTest();
		
		// 'Inflight Configuration', 'Standard'
		List<Case> cases = [SELECT Id FROM Case WHERE RecordType.Name = 'Inflight Configuration' AND Type = 'Standard'];
		
		System.assertEquals(1, cases.size(), 'Invalid data');
    }
    
    @IsTest
    public static void errorTest() {
		
        Account acc = LG_GeneralTest.CreateAccount('TestAccount1', '321654989', 'Test', true);
		
        csconta__Billing_Account__c ba = new csconta__Billing_Account__c();
    	ba.csconta__Account__c = acc.id;
    	ba.csconta__Status__c = 'New';
    	ba.csconta__Billing_Channel__c = 'Paper';
    	ba.csconta__Format_Type__c = 'Summary';
    	insert ba;
        
        
        // Trigger error by sending incorrect id        
        Id accountId = '0016E000002Qmq2';
        
                
		// Solution  with service not in valid status
		csord__Solution__c sol1 = new csord__Solution__c(Name = 'Test Solution1', csord__Identification__c = '123456780');
		insert sol1;
        
        //Appointment
        LG_ScheduleAppointment__c app1 = new LG_ScheduleAppointment__c(Name = 'Test Appointment', LG_Status__C = 'Scheduled', LG_Solution__C = sol1.id, LG_AgreedInstallDate__c = Date.today(), LG_JobReference__c = 'Test Ref', LG_Slot__c= 'Morning Slot');
		insert app1;
        
        // Subscripton 
		csord__Subscription__c sub1 = new csord__Subscription__c(csord__Identification__c = '6465467986',csconta__Billing_Account__c = ba.id);
		insert sub1; 
        
        // Solution  with no valid service
		csord__Solution__c sol2 = new csord__Solution__c(Name = 'Test Solution2', csord__Identification__c = '123456789');
		insert sol2;
        
        //Appointment
        LG_ScheduleAppointment__c app2 = new LG_ScheduleAppointment__c(Name = 'Test Appointment', LG_Status__C = 'Scheduled', LG_Solution__C = sol2.id, LG_AgreedInstallDate__c = Date.today(), LG_JobReference__c = 'Test Ref', LG_Slot__c= 'Morning Slot');
		insert app2;
        
        // Solution  with vo valid appointment
		csord__Solution__c sol3 = new csord__Solution__c(Name = 'Test Solution3', csord__Identification__c = '123456789');
		insert sol3;
  
		// Solution  with appointment in the past
		csord__Solution__c sol4 = new csord__Solution__c(Name = 'Test Solution4', csord__Identification__c = '123456789');
		insert sol4;
        
        //Appointment
        LG_ScheduleAppointment__c app4 = new LG_ScheduleAppointment__c(Name = 'Test Appointment', LG_Status__C = 'Scheduled', LG_Solution__C = sol4.id, LG_AgreedInstallDate__c = Date.today()-4, LG_JobReference__c = 'Test Ref', LG_Slot__c= 'Morning Slot');
		insert app4;
        
        // Subscripton 
		csord__Subscription__c sub4 = new csord__Subscription__c(csord__Identification__c = '6465467986',csconta__Billing_Account__c=ba.id);
		insert sub4; 
               
        Test.startTest();
        
		String reschedule = LG_InflightChangeUtil.reSchedule(accountId);
		String numbers = LG_InflightChangeUtil.correctNumbers(accountId);
        String configure = LG_InflightChangeUtil.configure(accountId);
        String invalidstatus = LG_InflightChangeUtil.reSchedule(sol1.id);  //SFOM-427
        String noservice = LG_InflightChangeUtil.reSchedule(sol2.id);  //SFOM-427
        String noapp = LG_InflightChangeUtil.reSchedule(sol3.id);  //SFOM-427
        String pastapp = LG_InflightChangeUtil.reSchedule(sol4.id);  //SFOM-427
         
		Test.stopTest();
		
		System.debug(reschedule);
		System.debug(numbers);
		System.debug(configure);
		
		System.assertEquals(false, LG_Util.IsValidId(reschedule), 'Invalid data');
		System.assertEquals(false, LG_Util.IsValidId(numbers), 'Invalid data');
		System.assertEquals(false, LG_Util.IsValidId(configure), 'Invalid data');
		System.assertEquals(noservice, 'No valid service is available to update');  
        System.assertEquals(noapp, 'There is no appointment to modify'); 
        System.assertEquals(pastapp, 'Appointment cannot be modified as appointment is in the past'); 
    }
}