src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SoHo</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
                <value>
                    <fullName>LE</fullName>
                </value>
                <value>
                    <fullName>Wholesale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that currently receives this order</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Order</description>
        <inlineHelpText>The parent Solution of this Order</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>DEPRECATED. Defines the status of the order through fulfilment to delivery.</description>
        <inlineHelpText>DEPRECATED. Use Status2__c.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Provisioning</fullName>
                    <default>true</default>
                    <label>In Provisioning</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Not Provisioned</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csordtelcoa__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>UM_PartnerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Service.</description>
        <inlineHelpText>The parent Order of this Service.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    
    <fields>
        <fullName>LG_Suppress_Welcome_Pack__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox allows the user to suppress sending the Welcome Pack</description>
        <label>Suppress Welcome Pack</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_Termination__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Termination</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Solution.</description>
        <inlineHelpText>The Account that governs this Solution.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Solution.</description>
        <inlineHelpText>The parent Order of this Solution.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Solution in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <recordTypes>
        <fullName>Quantity</fullName>
        <active>true</active>
        <label>Quantity</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Subscription.</description>
        <inlineHelpText>The Account that governs this Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Subscription.</description>
        <inlineHelpText>The parent Order of this Subscription.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Subscription.</description>
        <inlineHelpText>The parent Solution of this Subscription.</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LG_PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hidden field for fetching contact email from OpportunityContactRole</description>
        <label>PrimaryContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <label>Probability(%)</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>10</fullName>
                    <default>true</default>
                    <label>10</label>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
                <value>
                    <fullName>60</fullName>
                </value>
                <value>
                    <fullName>70</fullName>
                </value>
                <value>
                    <fullName>80</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>100</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_PartnerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_QuotingDate__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Quoting Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LG_ReSendWelcomePackEmailTest.cls
@isTest
public class LG_ReSendWelcomePackEmailTest {
    @testSetup 
    static void setup() {
        account account = new account();
        account.Name = 'Test';
        account.LG_Segment__c = 'SME';
        insert account;
        
        contact con = new Contact(AccountId=account.id);
        con.firstname = 'First';
        con.LastName = 'Last';
        con.LG_PreferredCommunication__c='Call';
        con.Salutation='Mr.';
        con.Email='abcd@gmail.com';
        con.Phone='1234567890';
        insert con;
        
        //Opportunity
        Opportunity Oppty= new Opportunity();
        Oppty.Name='Nps Opportunity';
        Oppty.Accountid=account.id;
        Oppty.LG_PrimaryContact__c=con.id;
        Oppty.Type='New Business';
        Oppty.UM_QuotingDate__c=System.today();
        Oppty.StageName='Awarness of interest';
        Oppty.Probability__c='10';
        Oppty.CloseDate=system.today()+7;
        //Oppty2.UM_PartnerAccount__c=paccM3.id;
        Insert Oppty;   

        //Order
        csord__Order__c order = new csord__Order__c(Name='Test Order',csord__Identification__c = '6465467986',csord__Account__c = account.Id);
        insert order;
        
        //Order2
        csord__Order__c order2 = new csord__Order__c(Name='Test Order2',csord__Identification__c = '6465467986',csord__Account__c = account.Id, csordtelcoa__Opportunity__c=Oppty.Id);
        insert order2;
        
        //Solution
        csord__Solution__c solution = new csord__Solution__c(Name = 'test solution', LG_Termination__c = false, LG_Suppress_Welcome_Pack__c = false, csord__Identification__c = '6465467986',csord__Order__c=order.Id, csord__Status__c='Complete');
        insert solution;
        
        //Solution2
        csord__Solution__c solution2 = new csord__Solution__c(Name = 'test solution2', LG_Termination__c = false, LG_Suppress_Welcome_Pack__c = false, csord__Identification__c = '6465467986',csord__Order__c=order2.Id, csord__Status__c='Complete');
        insert solution2;

        //Subscription
        csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = 'IdentSub');
        insert sub;
        
        
        //Subscription
        csord__Subscription__c sub2 = new csord__Subscription__c(csord__Identification__c = 'IdentSub2');
        insert sub2;
        
        //Address
        cscrm__Address__c address = new cscrm__Address__c(cscrm__Street__c = 'TestStreet');
        insert address;
        
        //Address2
        cscrm__Address__c address2 = new cscrm__Address__c(cscrm__Street__c = 'TestStreet2');
        insert address2;
        
        //Service
        csord__Service__c service2 = new csord__Service__c(csord__Identification__c = 'TestService2', Name='Company Internet', csord__Subscription__c = sub.Id, LG_RootOrder__c = order.Id, csord__Solution__c=solution.Id, LG_Suborder__c=solution.Id);
        service2.LG_Address__c = address.Id;
        insert service2;
        
        //Service2
        csord__Service__c service3 = new csord__Service__c(csord__Identification__c = 'TestService3', Name='Company Internet', csord__Subscription__c = sub2.Id, LG_RootOrder__c = order2.Id, csord__Solution__c=solution2.Id, LG_Suborder__c=solution2.Id);
        service3.LG_Address__c = address2.Id;
        insert service3;
       
        //Asset
        Asset asst=new Asset();
        asst.Name='Test Asset';
        asst.csord__Service__c=service2.Id;
        asst.accountId=account.id;
        asst.LG_MACAddress__c='123';
        asst.LG_IPAddress__c='456';
        asst.Quantity=2;
        asst.Status = 'Active';
        asst.csord__Asset_Value__c = 'Test Val';
        insert asst;
        
        //Asset2
        Asset asst2=new Asset();
        asst2.Name='Test Asset2';
        asst2.csord__Service__c=service3.Id;
        asst2.accountId=account.id;
        asst2.LG_MACAddress__c='123';
        asst2.LG_IPAddress__c='456';
        asst2.Quantity=2;
        asst2.Status = 'Active';
        asst2.csord__Asset_Value__c = 'Test Val';
        insert asst2;
        
    }
    
    public static testmethod void TestSendEmail(){
        csord__Solution__c s = [select Id, csord__Order__c, csord__Order__r.Name,LG_Termination__c from csord__Solution__c where name = 'test solution' limit 1];
        csord__Service__c service = [SELECT Id,Name, csord__Status__c FROM csord__Service__c WHERE csord__Identification__c = 'TestService2' AND csord__Service__c = NULL AND LG_Suborder__c = :s.id];
        Asset astObj= [SELECT Id,Name, LG_MACAddress__c, LG_IPAddress__c  FROM Asset WHERE csord__Service__r.Id =:service.Id];
        System.assertNotEquals(null, astObj.Id, 'Asset ID should be available.');
        System.assertNotEquals(null, service.Id, 'Service ID should be available.');
          User thisUser=[select id from User where id=:UserInfo.getUserId()];
         System.runAs(thisUser){
        Test.startTest();
        PageReference pRef = Page.LG_ResendWelcomePackEmail;
        pRef.getParameters().put('id', s.Id);
        Test.setCurrentPage(pRef);
        astObj.LG_IPAddress__c='999';
        astObj.LG_MACAddress__c='888';
        update astObj;
        update service;
        update s;
        LG_ReSendWelcomePackEmail classobj = new LG_ReSendWelcomePackEmail();
        classobj.macAddress='555';
        classobj.ipAddress ='666';
        update Classobj.ast;
        classobj.sendEmail();
        //System.assertEquals(astObj.LG_MACAddress__c, classobj.macAddress , 'check for mac address');
        System.assertEquals(classobj.solId, s.Id, 'ID\'s should match');
        System.assertEquals(true, classobj.serviceAvailable, 'ID\'s should match');
        //System.assertEquals(classobj.cService, s.csord__Service__c, 'ID\'s should match');
        Test.stopTest();
         }
    }
    
    public static testmethod void TestValidationProfile(){
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // TestUser
        Profile p = [SELECT Id FROM Profile WHERE Name='UM_API_User'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
                      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                      LocaleSidKey='en_US', ProfileId = p.Id,CompanyName='Infosys',
                      TimeZoneSidKey='America/Los_Angeles',
                      UserName=uniqueUserName);
        insert u;
        csord__Solution__c s = [select Id, csord__Order__c, csord__Order__r.Name,LG_Termination__c from csord__Solution__c where name = 'test solution' limit 1];
        csord__Service__c service = [SELECT Id,Name, csord__Status__c FROM csord__Service__c WHERE csord__Identification__c = 'TestService2' AND csord__Service__c = NULL AND LG_Suborder__c = :s.id];
        Asset astObj= [SELECT Id,Name, LG_MACAddress__c, LG_IPAddress__c  FROM Asset WHERE csord__Service__r.Id =:service.Id];
        Test.startTest();
        system.runAs(u)
        {      
            PageReference pRef = Page.LG_ResendWelcomePackEmail;
            pRef.getParameters().put('id', s.Id);
            Test.setCurrentPage(pRef);
            LG_ReSendWelcomePackEmail classobj = new LG_ReSendWelcomePackEmail();
            classobj.validateScenario();
            System.assertEquals(false, classobj.validationStatus, 'False');
        }
 
    } 
    
    public static testmethod void TestValidationAssetNull(){
        csord__Solution__c s = [select Id, csord__Order__c, csord__Order__r.Name,LG_Termination__c from csord__Solution__c where name = 'test solution' limit 1];
        csord__Service__c service = [SELECT Id,Name, csord__Status__c FROM csord__Service__c WHERE csord__Identification__c = 'TestService2' AND csord__Service__c = NULL AND LG_Suborder__c = :s.id];
        Asset astObj= [SELECT Id,Name, LG_MACAddress__c, LG_IPAddress__c  FROM Asset WHERE csord__Service__r.Id =:service.Id];
          User thisUser=[select id from User where id=:UserInfo.getUserId()];
         System.runAs(thisUser){
        Test.startTest();
        PageReference pRef = Page.LG_ResendWelcomePackEmail;
        pRef.getParameters().put('id', s.Id);
        Test.setCurrentPage(pRef);
        System.assertNotEquals(null, astObj.LG_MACAddress__c, 'Asset ID should be available.');
        service.Name='Company Internet';
        update service;
        LG_ReSendWelcomePackEmail classobj = new LG_ReSendWelcomePackEmail();
        astObj.LG_IPAddress__c='999';
        astObj.LG_MACAddress__c='888';
        update astObj;
        update s;
        classobj.validateScenario();
        classobj.sendEmail();
        System.assertEquals(true, classobj.validationStatus, 'False');
         }
    }
    
    public static testmethod void TestValidationKundensetup(){
        csord__Solution__c s = [select Id, csord__Order__c, csord__Order__r.Name,LG_Termination__c from csord__Solution__c where name = 'test solution' limit 1];
        csord__Service__c service = [SELECT Id,Name, csord__Status__c FROM csord__Service__c WHERE csord__Identification__c = 'TestService2' AND csord__Service__c = NULL AND LG_Suborder__c = :s.id];
        Asset astObj= [SELECT Id,Name, LG_MACAddress__c, LG_IPAddress__c  FROM Asset WHERE csord__Service__r.Id =:service.Id];
          User thisUser=[select id from User where id=:UserInfo.getUserId()];
         System.runAs(thisUser){
        Test.startTest();
        PageReference pRef = Page.LG_ResendWelcomePackEmail;
        pRef.getParameters().put('id', s.Id);
        Test.setCurrentPage(pRef);
        service.Name='Virtual Voice Kundensetup';
        update service;
        LG_ReSendWelcomePackEmail classobj = new LG_ReSendWelcomePackEmail();
        classobj.validateScenario();
        classobj.sendEmail();
        System.assertEquals(true, classobj.validationStatus, 'False');
         }
    }
    public static testmethod void TestValidationStatus(){
        csord__Solution__c s = [select Id, csord__Order__c, csord__Order__r.Name,LG_Termination__c from csord__Solution__c where name = 'test solution' limit 1];
        csord__Service__c service = [SELECT Id,Name, csord__Status__c FROM csord__Service__c WHERE csord__Identification__c = 'TestService2' AND csord__Service__c = NULL AND LG_Suborder__c = :s.id];
        Asset astObj= [SELECT Id,Name, LG_MACAddress__c, LG_IPAddress__c  FROM Asset WHERE csord__Service__r.Id =:service.Id];
          User thisUser=[select id from User where id=:UserInfo.getUserId()];
         System.runAs(thisUser){
        Test.startTest();
        PageReference pRef = Page.LG_ResendWelcomePackEmail;
        pRef.getParameters().put('id', s.Id);
        Test.setCurrentPage(pRef);
        s.csord__Status__c='Inprogress';
        update s;
        LG_ReSendWelcomePackEmail classobj = new LG_ReSendWelcomePackEmail();
        classobj.validateScenario();
        classobj.sendEmail();
        System.assertEquals(false, classobj.validationStatus, 'False');
         }   
    }
    
    public static testmethod void TestValidationName(){
        csord__Solution__c s = [select Id, csord__Order__c, csord__Order__r.Name,LG_Termination__c from csord__Solution__c where name = 'test solution' limit 1];
        csord__Service__c service = [SELECT Id,Name, csord__Status__c FROM csord__Service__c WHERE csord__Identification__c = 'TestService2' AND csord__Service__c = NULL AND LG_Suborder__c = :s.id];
        Asset astObj= [SELECT Id,Name, LG_MACAddress__c, LG_IPAddress__c  FROM Asset WHERE csord__Service__r.Id =:service.Id];
          User thisUser=[select id from User where id=:UserInfo.getUserId()];
         System.runAs(thisUser){
        Test.startTest();
        PageReference pRef = Page.LG_ResendWelcomePackEmail;
        pRef.getParameters().put('id', s.Id);
        Test.setCurrentPage(pRef);
        service.Name='Company Fiber';
        update service;
        LG_ReSendWelcomePackEmail classobj = new LG_ReSendWelcomePackEmail();
        classobj.validateScenario();
        //classobj.sendEmail();
        System.assertEquals(false, classobj.validationStatus, 'False');
         }
    }  
    /*public static testmethod void TestValidationSuppressCheck(){
        csord__Solution__c s = [select Id, csord__Order__c, csord__Order__r.Name,LG_Termination__c from csord__Solution__c where name = 'test solution' limit 1];
        csord__Service__c service = [SELECT Id,Name, csord__Status__c FROM csord__Service__c WHERE csord__Identification__c = 'TestService2' AND csord__Service__c = NULL AND LG_Suborder__c = :s.id];
        Asset astObj= [SELECT Id,Name, LG_MACAddress__c, LG_IPAddress__c  FROM Asset WHERE csord__Service__r.Id =:service.Id];
		   User thisUser=[select id from User where id=:UserInfo.getUserId()];
         System.runAs(thisUser){       
		Test.startTest();
        PageReference pRef = Page.LG_ResendWelcomePackEmail;
        pRef.getParameters().put('id', s.Id);
        Test.setCurrentPage(pRef);
        s.LG_Suppress_Welcome_Pack__c = True;
        update s;
        LG_ReSendWelcomePackEmail classobj = new LG_ReSendWelcomePackEmail();
        classobj.validateScenario();
        classobj.sendEmail();
        System.assertEquals(false, classobj.validationStatus, 'False');
}        
    }*/
     
    public static testmethod void TestValidationTermination(){
        csord__Solution__c s = [select Id, csord__Order__c, csord__Order__r.Name,LG_Termination__c from csord__Solution__c where name = 'test solution' limit 1];
        csord__Service__c service = [SELECT Id,Name, csord__Status__c FROM csord__Service__c WHERE csord__Identification__c = 'TestService2' AND csord__Service__c = NULL AND LG_Suborder__c = :s.id];
        Asset astObj= [SELECT Id,Name, LG_MACAddress__c, LG_IPAddress__c  FROM Asset WHERE csord__Service__r.Id =:service.Id];
          User thisUser=[select id from User where id=:UserInfo.getUserId()];
         System.runAs(thisUser){
        Test.startTest();
        PageReference pRef = Page.LG_ResendWelcomePackEmail;
        pRef.getParameters().put('id', s.Id);
        Test.setCurrentPage(pRef);
        s.LG_Termination__c =True;
        update s;
        LG_ReSendWelcomePackEmail classobj = new LG_ReSendWelcomePackEmail();
        classobj.validateScenario();
        classobj.sendEmail();
         }
      //  System.assertEquals(false, classobj.validationStatus, 'True');
        
    } 
    
     public static testmethod void TestValidationPreferredCommunication(){
        csord__Solution__c s = [select Id, csord__Order__c, csord__Order__r.Name,LG_Termination__c, csord__Order__r.csordtelcoa__Opportunity__r.LG_PrimaryContact__r.LG_PreferredCommunication__c from csord__Solution__c where name = 'test solution2' limit 1];
        csord__Service__c service = [SELECT Id,Name, csord__Status__c FROM csord__Service__c WHERE csord__Identification__c = 'TestService3' AND csord__Service__c = NULL AND LG_Suborder__c = :s.id];
        Asset astObj= [SELECT Id,Name, LG_MACAddress__c, LG_IPAddress__c  FROM Asset WHERE csord__Service__r.Id =:service.Id];
          User thisUser=[select id from User where id=:UserInfo.getUserId()];
         System.runAs(thisUser){
         Test.startTest();
        PageReference pRef = Page.LG_ResendWelcomePackEmail;
        pRef.getParameters().put('id', s.Id);
        Test.setCurrentPage(pRef);
        //service.Name='Virtual Voice Kundensetup';
        //update service;
        LG_ReSendWelcomePackEmail classobj = new LG_ReSendWelcomePackEmail();
        classobj.validateScenario();
         
        //classobj.sendEmail();
        //System.assertEquals(false, classobj.validationStatus, 'False');
         }
    }
    
     public static testmethod void TestSaveAsset(){
        csord__Solution__c s = [select Id, csord__Order__c, csord__Order__r.Name,LG_Termination__c, csord__Order__r.csordtelcoa__Opportunity__r.LG_PrimaryContact__r.LG_PreferredCommunication__c from csord__Solution__c where name = 'test solution2' limit 1];
        csord__Service__c service = [SELECT Id,Name, csord__Status__c FROM csord__Service__c WHERE csord__Identification__c = 'TestService3' AND csord__Service__c = NULL AND LG_Suborder__c = :s.id];
        Asset astObj= [SELECT Id,Name, LG_MACAddress__c, LG_IPAddress__c  FROM Asset WHERE csord__Service__r.Id =:service.Id];
        Test.startTest();
        PageReference pRef = Page.LG_ResendWelcomePackEmail;
        pRef.getParameters().put('id', s.Id);
        Test.setCurrentPage(pRef);
        LG_ReSendWelcomePackEmail classobj = new LG_ReSendWelcomePackEmail();
        classobj.SaveAsset();
        
        
    }


        
}