src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_AccountNumber__c</fullName>
        <displayFormat>81{00000000}</displayFormat>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <recordTypes>
        <fullName>Partner</fullName>
        <active>true</active>
        <description>This is the record type for Partners</description>
        <label>Partner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/B2B_Care_Ext_Connections__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will contain all the records required for connecting external system   from salesforce.</description>
    <label>Care Connections</label>
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Family__c</fullName>
        <description>This field will be mapped to the Product2.Family field at Opportunity sync time.
Default value is taken from Product_Definition__c.Name.</description>
        <inlineHelpText>Is used for better control over the process, enabling fine-grained forecasting capabilities. By default Product Defn name will auto-populate this field, overridden using Set Product Family action during config. Is mapped to Product2.Family fld at Opp sync</inlineHelpText>
        <label>Product Family</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>LG_ServiceStatus__c</fullName>
        <description>Pick-list to save the status of the service provisioning.</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                  <fullName>LG_SecondaryProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services (Secondary Product Configuration)</relationshipLabel>
        <relationshipName>Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Subscription.</description>
        <inlineHelpText>The Account that governs this Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Subscription in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_Care_Medallia_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It stores the values to be used in the LG_Care_MedalliaRelationshipSurvey_Batch</description>
    <fields>
        <fullName>LG_Care_Contact_Created_Date__c</fullName>
        <label>Contact Created Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_Care_Contact_Role__c</fullName>
        <label>Contact Role</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Care_Last_rNPS_Send_Date__c</fullName>
        <label>Last rNPS Send Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_Care_Max_Number_of_Contacts__c</fullName>
        <label>Max Number of Contacts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Care Medallia Settings</label>
</CustomObject>

src/classes/LG_Care_MedalliaRelationshipSurvey_Batch.cls
/************************************************************************************************************************************
*        Class: LG_Care_MedalliaRelationshipSurvey_Batch  
*     Program : B2B CARE CATALYST PROGRAM
*  Description: This will request medallia to survey limited contacts as per the rules mentioned in the custom settings.
*    Author(s): Abhisek Mishra (Infosys Limited)
* Created Date: 08-AUG-2017
*   Test Class: LG_Care_MedalliaRelation_Batch_Test
*************************************************************************************************************************************/
global class LG_Care_MedalliaRelationshipSurvey_Batch  implements Database.Batchable<sobject>, Database.Stateful ,Database.AllowsCallouts {
    public Static String RqstFile;
    final static Map < id, Set < String >> accountToOrderMap = new Map < id, Set < String >> ();
    final static Map < id, Set < String >> accountToOrderMap2 = new Map < id, Set < String >> ();
    
    Static final LG_Care_Medallia_Settings__c myCS1 = LG_Care_Medallia_Settings__c.getInstance('Default');
    
    public static String editOrderSet(String new_product) {
       
        String temp_product='';
        
        if(new_product!=null)
        {
            if(new_product.Contains('Company Internet')){
                temp_product='Internet';
            }
            else if(new_product.Contains('Company Voice') || new_product.Contains('Virtual voice')){
                temp_product='Fixed Telephony';
            }
            else if (new_product.Contains('Company Fiber') || new_product.Contains('Wholesale Fiber')){
                temp_product='Data/VPN Services';
            }
            
            else if (new_product.Contains('Mobilfunkprodukte')){
                temp_product='Mobile';
            }
            
            else if (new_product.Contains('Digital TV')){
                temp_product='TV';
            }
            
            else if (new_product.Contains('Office')){
                temp_product='Internet';
            }
            
            else if (new_product.Contains('WLAN')){
                temp_product='Wifi';
            }
            else if (new_product.Contains('VPN')){
                temp_product='Data/VPN Services';
            }
              else if (new_product.Contains('BDS') || new_product.Contains('Connect')){
                temp_product='Data/VPN Services';
            }
           
           }
           
        
        return temp_product;
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        List<String> contactRole = myCS1.LG_Care_Contact_Role__c.split(',');
        String roleQuery = '';
        Set<String> contactRoleSet = new Set<String>();
        contactRoleSet.addAll(contactRole);
        if(!contactRoleSet.isEmpty() && contactRoleSet.size() > 0) {
            roleQuery = roleQuery + 'LG_Role__c includes ( ';
            for(String temp :contactRoleSet) {
                roleQuery = roleQuery + '\''+ temp + '\'' + ',';   
            }
            if(roleQuery.lastIndexOf(',')!=-1){
                roleQuery = roleQuery.removeEnd(',');
            }
            roleQuery = roleQuery +' ) AND';
        }
         
        
        DateTime rNPSLimitDate = DateTime.Now() - myCS1.LG_Care_Last_rNPS_Send_Date__c;
        DateTime createdDate = DateTime.now() - myCS1.LG_Care_Contact_Created_Date__c;
        Integer maxLimit = Integer.valueOf(myCS1.LG_Care_Max_Number_of_Contacts__c);
        
        String rType=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner').getRecordTypeId();
    
        
        String query = 'SELECT ID, Name,AccountID,Email,Account.Name, LG_Role__c, Account.LG_AccountNumber__c, CreatedDate, LG_Care_Relationship_Survey_Sent_Date__c FROM Contact WHERE ( '
                        +roleQuery+' LG_Care_Survey_Opt_Out__c = false) AND ((LG_Care_Relationship_Survey_Sent_Date__c = NULL) OR (LG_Care_Relationship_Survey_Sent_Date__c != NULL AND LG_Care_Relationship_Survey_Sent_Date__c < :rNPSLimitDate)) AND (CreatedDate < :createdDate) AND AccountID!=NULL AND Account.RecordType.id!=:rType LIMIT 1999';
                       
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> listOfCmps) {
        try {
         
            String record_id;
            String contact_role;
            String product_type;
            String new_product_type;
            B2B_Care_Ext_Connections__c NPSConn;
            product_type = '';
            contact_role = '';
            set < id > cntAll = new set < id > ();
            set < id > accIds = new set < id > ();
            List<Contact> filteredListOfContacts = new List<Contact>();
            Map<Id,Contact> contactMap = new Map<Id,Contact>();
            for (Contact cpm: listOfCmps) {
               
                if (cpm.accountid != null) {
                    accIds.add(cpm.accountid);
                    contactMap.put(cpm.accountid, cpm);
                }
                  
            }
           
            
            Map < id, Set < String >> accountToOrderMap = new Map < id, Set < String >> ();
            
            

            /*for(csord__Service__c actSubs :[Select id,Name,csord__Subscription__c,csordtelcoa__Product_Configuration__r.cscfga__Product_Family__c
                                            from csord__Service__c where csord__Subscription__c in (Select id from csord__Subscription__c where csord__Account__c in :accIds and csord__Status__c='Active')]){*/
            for(csord__Service__c actSubs :[Select id,Name,csord__Subscription__c,csordtelcoa__Product_Configuration__r.cscfga__Product_Family__c,csord__Subscription__r.csord__Account__c 
                                            from csord__Service__c where csord__Subscription__r.csord__Account__c in :accIds and LG_ServiceStatus__c ='Active' 
                                            and csordtelcoa__Product_Configuration__r.cscfga__Product_Family__c != null]){
            
                Id Actid=actSubs.csord__Subscription__r.csord__Account__c ;
                //Set < String > orderToAccountList = new Set < String > ();
            
                new_product_type=editOrderSet(actSubs.csordtelcoa__Product_Configuration__r.cscfga__Product_Family__c);
                if(new_product_type != null && new_product_type != ''){
                if (accountToOrderMap.containskey(Actid)) {
                    Set < String > orderToAccountList = accountToOrderMap.get(Actid);
                    orderToAccountList.add(new_product_type);
                    accountToOrderMap.put(Actid, orderToAccountList);
                } else {
                    Set < String > orderToAccountList = new Set < String > ();
                    orderToAccountList.add(new_product_type);
                    
                    accountToOrderMap.put(Actid, orderToAccountList);
                    
                }
                
                }
            
                
            }
            
            List<Contact> contactListTemp = new List<Contact>();
            Integer maxLimit = Integer.valueOf(myCS1.LG_Care_Max_Number_of_Contacts__c);
            Integer count = 1;
            for(Id accountId : accountToOrderMap.keySet()){
                if((maxLimit < 100 && count > maxLimit) || (count > 99)){
                    break;
                }
                else{
                    contactListTemp.add(contactMap.get(accountId));
                }
                count++;
            }
            system.debug('final list: '+contactMap+' '+accountToOrderMap);
            contactMap.clear();
            List < String > JFile = new List < String > ();
            List < String > Stringfor = new List < String > ();
            Set < String > setOrder = new Set < String > ();
            
            Map<String,Id> requestBodyMapContactId = new Map<String,Id>();
            
            //for (Contact cont: listOfCmps) ////use SOQL for loop
            for (Contact cont: contactListTemp) ////use SOQL for loop
            {
                //system.debug(cont.email +' ----------------- '+ cont.accountId);
                product_type = '';
                Stringfor.clear();
                
                
                if (cont.Email != null && cont.AccountId !=null & cont.Account.LG_AccountNumber__c !=null) {
                    
                    Datetime dt = Datetime.now();
                    record_id = cont.id + dt.format('yyyyMMddHHmmss');
                    
                    
                    if (Cont.LG_Role__c != Null) {
                        contact_role = cont.LG_Role__c;
                    }
                    
                    if (accountToOrderMap.get(cont.AccountId) != null) {
                        
                        Stringfor.addAll(accountToOrderMap.get(cont.AccountId));
                        String separator = ', ';
                        
                        product_type = String.join(Stringfor, separator);
                        
                    }
                    
                    JSONGenerator gen = JSON.createGenerator(true);
                    gen.writeStartObject();
                    gen.writeStringField('ACCOUNT_ID', cont.Account.LG_AccountNumber__c);
                    gen.writeStringField('ACCOUNT_NAME', cont.Account.Name);
                    gen.writeStringField('RECORD_ID', record_id);
                    gen.writeStringField('CUSTOMER_ID', cont.id);
                    gen.writeStringField('CUSTOMER_NAME', cont.Name);
                    gen.writeStringField('CUSTOMER_EMAIL', cont.Email);
                    gen.writeStringField('SURVEY_TYPE', 'Relationship');
                    gen.writeStringField('BRAND', 'Unitymedia Business');
                    gen.writeStringField('CHANNEL_ID', '');
                    gen.writeStringField('Case_Origin', '');
                    gen.writeStringField('PRODUCT_FAMILY', '');
                    gen.writeStringField('PRODUCT_DESCRIPTION', '');
                    gen.writeStringField('CASE_RECORD_TYPE', '');
                    gen.writeStringField('CASE_TYPE', '');
                    gen.writeStringField('CASE_REASON', '');
                    gen.writeStringField('SERVICE_NAME', '');
                    gen.writeStringField('SF_USER_ROLE', '');
                    gen.writeStringField('CONTACT_ROLE', contact_role);
                    gen.writeStringField('PRODUCT_TYPE', product_type);
                    //system.debug(' ----------------- '+ product_type);
                    gen.writeEndObject();
                    RqstFile = gen.getAsString();
                    JFile.add(RqstFile);
                    requestBodyMapContactId.put(rqstFile, cont.Id);
                }
            }
            system.debug('@3File'+JFile);

         
          LG_Care_Medallia_Relationship_Survey.NPSRequest(JFile,requestBodyMapContactId); 
        } catch (Exception e) {}
        
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}