src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_BillingEmailAddress__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LG_PaymentType__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Self-payer</fullName>
                    <default>true</default>
                    <label>Self-payer</label>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>LG_BillingAccountName__c</fullName>
        <description>Field is updated with Account name on creation</description>
        <label>Billing Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_BillingEmailAddress__c</fullName>
        <label>Billing Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LG_PaymentType__c</fullName>
        <description>Payment Type / Method used by the customer</description>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Self-payer</fullName>
                    <default>true</default>
                    <label>Self-payer</label>
                </value>
                <value>
                    <fullName>Direct Debit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_SConsoleBillingAccDetailsTest.cls
@isTest
public class LG_SConsoleBillingAccDetailsTest {
  @testSetup 
    static void setup() {
        
        No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
        noTriggers.Flag__c = true;
        noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
        upsert noTriggers;
        
       //Billing Account
       csconta__Billing_Account__c b = new csconta__Billing_Account__c();
        b.LG_BillingAccountName__c = 'Test Billing';
        b.LG_BillingEmailAddress__c = 'test@testmail.com';
        b.LG_PaymentType__c = '';
       insert b;
        
        
    }
    public static testMethod void TestLG_ViewAttributeDefenitionController(){
        
        csconta__Billing_Account__c b = [select Id from csconta__Billing_Account__c LIMIT 1];
        
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(b);
        LG_SConsoleBillingAccDetailsExtension controller = new LG_SConsoleBillingAccDetailsExtension(sc);
        
        System.assertEquals(b.Id, controller.getbillingAccountDetail().Id);
        controller.edit();
        controller.save();
        controller.cancel();
        Test.stopTest();
    }
}