src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_ChamberOfCommerceNumber__c</fullName>
        <description>KvK No.</description>
        <label>National ID number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LG_Footprint__c</fullName>
        <description>Defining Footprint to which a Lead/Company/Account belongs</description>
        <label>Footprint</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UPC</fullName>
                </value>
                <value>
                    <fullName>Ziggo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_VisitCountry__c</fullName>
        <label>Visit Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>LG_Footprint__c</fullName>
        <label>Footprint</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UPC</fullName>
                </value>
                <value>
                    <fullName>Ziggo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cscrm__Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that currently receives this order</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Order Request which introduced the latest changes to this Order.</description>
        <inlineHelpText>The Order Request which introduced the latest changes to this Order.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>LG_ProductFamily__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_NumberManagement__c</fullName>
        <label>Number Management</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Subscription.</description>
        <inlineHelpText>The Account that governs this Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UM_NumberBlock__c.object
<CustomObject>
    <fields>
        <fullName>UM_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Number Blocks</relationshipLabel>
        <relationshipName>Number_Blocks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_AreaCode__c</fullName>
        <label>Area Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_BlockSize__c</fullName>
        <label>Block Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_CDRIDNumber__c</fullName>
        <label>CDR ID Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_EndNumber__c</fullName>
        <label>End Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_NumberRangeService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Number Range Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Number Blocks</relationshipLabel>
        <relationshipName>Number_Blocks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_ProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Number Blocks</relationshipLabel>
        <relationshipName>Number_Blocks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_StartNumber__c</fullName>
        <label>Start Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_VoiceService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Voice Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Number Blocks (Voice Service)</relationshipLabel>
        <relationshipName>Number_Blocks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Number Block</label>
    <nameField>
        <label>Number Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Number Blocks</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UM_ServiceTriggerHandlerTest.cls
 /**
 * @author (s)      : David van 't Hooft
 * @requirement id  : UMR-499
 * @description     : Test the Numberblock inserts on providing a valid json
 * 					: Test the Opportunity set to ''Close Lost' if the last active product/services is also cancelled attached to this Opportunity
 *
 * @log:            : 10AUG2016 v1.0
 */
@isTest
private class UM_ServiceTriggerHandlerTest {

	/**
     * Test auto creation of the UM_NumberRangeService__c records on creating a Service with LG_ProductFamily__c = 'Number Range'
     */
    // static testMethod void inserNumberblockTest() {
	// 	// creating test account
	// 	Account a = new Account(name = 'Test1', LG_VisitCountry__c = 'Netherlands', LG_ChamberOfCommerceNumber__c = '03438493', LG_Footprint__c = 'UPC');
	// 	insert a;
    //
	// 	csord__Order_Request__c req = new csord__Order_Request__c(csord__Module_Name__c = 'Test', csord__Module_Version__c = '1.0');
	// 	insert req;
    //
	// 	csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = 'TestIdent', csord__Order_Request__c = req.Id, csord__Account__c = a.Id);
	// 	insert sub;
    //
	// 	cscrm__Address__c address = new cscrm__Address__c(cscrm__Street__c = 'TestStreet');
	// 	insert address;
    //
	// 	Test.startTest();
	// 	//Test insert
    // 	String numman = '{"UM_NumberBlockList": [{"UM_StartNumber__c":"222444400","UM_EndNumber__c":"222444409","UM_CDRIDNumber__c":"22244440","UM_AreaCode__c":"222","UM_BlockSize__c":"10"},{"UM_StartNumber__c":"222444410","UM_EndNumber__c":"222444419","UM_CDRIDNumber__c":"22244441","UM_AreaCode__c":"222","UM_BlockSize__c":"10"}]}';
	// 	csord__Service__c serv = new csord__Service__c(csord__Identification__c = 'TestIdentSub', csord__Order_Request__c = req.Id,
	// 														csord__Subscription__c = sub.Id, LG_Address__c = address.Id, LG_ProductFamily__c = 'Number Range', UM_NumberManagement__c = numman);
	// 	insert serv;
    //
	// 	// Test number and content of created number blocks
    // 	List<UM_NumberBlock__c> nbList = [select Id, UM_StartNumber__c, UM_EndNumber__c, UM_CDRIDNumber__c, UM_AreaCode__c, UM_BlockSize__c, UM_Account__c, UM_ProductConfiguration__c, UM_NumberRangeService__c, UM_VoiceService__c from UM_NumberBlock__c where UM_NumberRangeService__c = :serv.Id];
	// 	System.assertEquals(2, nbList.size(), '2 UM_NumberBlock__c records should have bean created!');
	// 	System.assertEquals('22244440', nbList[0].UM_CDRIDNumber__c, 'UM_CDRIDNumber__c should contain the json data!');
	// 	System.assertEquals(serv.Id, nbList[0].UM_NumberRangeService__c, 'Service Id should be filled in!');
	// 	System.assertEquals('22244441', nbList[1].UM_CDRIDNumber__c, 'UM_CDRIDNumber__c should contain the json data!');
	// 	System.assertEquals(serv.Id, nbList[1].UM_NumberRangeService__c, 'Service Id should be filled in!');
    //
	// 	//Test update
	// 	numman = '{"UM_NumberBlockList": [{"UM_StartNumber__c":"222444410","UM_EndNumber__c":"222444419","UM_CDRIDNumber__c":"22244441","UM_AreaCode__c":"222","UM_BlockSize__c":"10"}]}';
	// 	serv.UM_NumberManagement__c = numman;
	// 	update serv;
	// 	Test.stopTest();
    //
	// 	// Test number and content of created number blocks
    // 	nbList = [select Id, UM_StartNumber__c, UM_EndNumber__c, UM_CDRIDNumber__c, UM_AreaCode__c, UM_BlockSize__c, UM_Account__c, UM_ProductConfiguration__c, UM_NumberRangeService__c, UM_VoiceService__c from UM_NumberBlock__c where UM_NumberRangeService__c = :serv.Id];
	// 	System.assertEquals(1, nbList.size(), '1 UM_NumberBlock__c records should have bean created!');
	// 	System.assertEquals('22244441', nbList[0].UM_CDRIDNumber__c, 'UM_CDRIDNumber__c should contain the json data!');
    // }

	/**
	 * If a service status changes to 'Service Cancelled' then get the Opportunity reference via the order and check all
	 * services for that order if they also have the service status 'Service Cancelled'. If so set the stage to 'Closed Lost' and
	 * probability to 0% and Loss_Reason__c to 'Pre-installation cancellation (PIC)'
	 * check if Opportunity gets updated correctly
     */
    static testMethod void checkCancelOpportunityTest() {
		// creating test account
		Account a = new Account(name = 'Test1', LG_VisitCountry__c = 'Netherlands', LG_ChamberOfCommerceNumber__c = '03438493', LG_Footprint__c = 'UPC');
		insert a;

        Opportunity tmpOpportunity = new Opportunity(Name = 'Test', AccountId=a.Id, StageName = 'Awareness of interest', CloseDate=Date.today()+5);
        insert tmpOpportunity;

		csord__Order_Request__c req = new csord__Order_Request__c(csord__Module_Name__c = 'Test', csord__Module_Version__c = '1.0');
		insert req;

        csord__Order__c o = new csord__Order__c();
        o.Name = 'Test Order';
        o.csord__Account__c = a.Id;
        o.csord__Status2__c = 'Order Submitted';
        o.csord__Order_Request__c = req.Id;
        o.csord__Identification__c = 'DWHTestBatchOn_' + system.now();
        o.csordtelcoa__Opportunity__c=tmpOpportunity.Id;
        insert o;

		csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = 'TestIdent', csord__Order_Request__c = req.Id, csord__Account__c = a.Id);
		insert sub;

		cscrm__Address__c address = new cscrm__Address__c(cscrm__Street__c = 'TestStreet');
		insert address;

		Test.startTest();
		//Test insert
		list<csord__Service__c> serviceList = new List<csord__Service__c>();
    	String numman = '{"UM_NumberBlockList": [{"UM_StartNumber__c":"222444400","UM_EndNumber__c":"222444409","UM_CDRIDNumber__c":"22244440","UM_AreaCode__c":"222","UM_BlockSize__c":"10"},{"UM_StartNumber__c":"222444410","UM_EndNumber__c":"222444419","UM_CDRIDNumber__c":"22244441","UM_AreaCode__c":"222","UM_BlockSize__c":"10"}]}';
		serviceList.add(new csord__Service__c(csord__Identification__c = 'TestIdentSub1', csord__Order_Request__c = req.Id, LG_ServiceStatus__c = 'Requested', LG_RootOrder__c = o.Id,
															csord__Subscription__c = sub.Id, LG_Address__c = address.Id, LG_ProductFamily__c = 'Number Range', UM_NumberManagement__c = numman));
		numman = '{"UM_NumberBlockList": [{"UM_StartNumber__c":"222444410","UM_EndNumber__c":"222444419","UM_CDRIDNumber__c":"22244441","UM_AreaCode__c":"222","UM_BlockSize__c":"10"}]}';
		serviceList.add(new csord__Service__c(csord__Identification__c = 'TestIdentSub2', csord__Order_Request__c = req.Id, LG_ServiceStatus__c = 'Requested', LG_RootOrder__c = o.Id,
															csord__Subscription__c = sub.Id, LG_Address__c = address.Id, LG_ProductFamily__c = 'Number Range', UM_NumberManagement__c = numman));
		insert serviceList;

		serviceList[0].LG_ServiceStatus__c = 'Cancelled';
		serviceList[0].UM_PICReason__c = 'Customer cannot pay';
		update serviceList;
		tmpOpportunity = [select StageName, Probability, Loss_Reason__c from Opportunity where Id = :tmpOpportunity.Id];
		System.assertNotEquals('Closed Lost', tmpOpportunity.StageName, 'Stage name should not be changed!');

		serviceList[1].LG_ServiceStatus__c = 'Cancelled';
		serviceList[1].UM_PICReason__c = 'Customer cannot pay';
		update serviceList;
		tmpOpportunity = [select StageName, Probability, Loss_Reason__c from Opportunity where Id = :tmpOpportunity.Id];
		System.assertEquals('Closed Lost', tmpOpportunity.StageName, 'Stage name should be changed!');
		System.assertEquals(0, tmpOpportunity.Probability, 'probability should be set to 0!');
		System.assertEquals('Pre-installation cancellation (PIC)', tmpOpportunity.Loss_Reason__c, 'Loss reason incorrect!');

		// test send email
		serviceList[1].LG_ProductFamily__c = 'Company Fiber';
		serviceList[1].LG_ServiceStatus__c = 'Ready for Billing';
		serviceList[1].UM_PICReason__c = '';
		serviceList[1].csord__Activation_Date__c = Date.Today();
		update serviceList;

		Test.stopTest();
    }

	/**
     * Test replacement of the product configuration from the new service
     */
    static testMethod void checkReplacementServiceOnCreateTest() {
    	/**
		// creating test account
		Account a = new Account(name = 'Test1', LG_VisitCountry__c = 'Netherlands', LG_ChamberOfCommerceNumber__c = '03438493', LG_Footprint__c = 'UPC');
		insert a;

		csord__Order_Request__c req = new csord__Order_Request__c(csord__Module_Name__c = 'Test', csord__Module_Version__c = '1.0');
		insert req;

		csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = 'TestIdent', csord__Order_Request__c = req.Id, csord__Account__c = a.Id);
		insert sub;

		cscrm__Address__c address = new cscrm__Address__c(cscrm__Street__c = 'TestStreet');
		insert address;

		Test.startTest();
		//Test insert
    	String numman = '{"UM_NumberBlockList": [{"UM_StartNumber__c":"222444400","UM_EndNumber__c":"222444409","UM_CDRIDNumber__c":"22244440","UM_AreaCode__c":"222","UM_BlockSize__c":"10"},{"UM_StartNumber__c":"222444410","UM_EndNumber__c":"222444419","UM_CDRIDNumber__c":"22244441","UM_AreaCode__c":"222","UM_BlockSize__c":"10"}]}';
		csord__Service__c serv = new csord__Service__c(csord__Identification__c = 'TestIdentSub', csord__Order_Request__c = req.Id,
															csord__Subscription__c = sub.Id, LG_Address__c = address.Id, LG_ProductFamily__c = 'Number Range', UM_NumberManagement__c = numman);
		insert serv;

		// Test number and content of created number blocks
    	List<UM_NumberBlock__c> nbList = [select Id, UM_StartNumber__c, UM_EndNumber__c, UM_CDRIDNumber__c, UM_AreaCode__c, UM_BlockSize__c, UM_Account__c, UM_ProductConfiguration__c, UM_NumberRangeService__c, UM_VoiceService__c from UM_NumberBlock__c where UM_NumberRangeService__c = :serv.Id];
		System.assertEquals(2, nbList.size(), '2 UM_NumberBlock__c records should have bean created!');
		System.assertEquals('22244440', nbList[0].UM_CDRIDNumber__c, 'UM_CDRIDNumber__c should contain the json data!');
		System.assertEquals(serv.Id, nbList[0].UM_NumberRangeService__c, 'Service Id should be filled in!');
		System.assertEquals('22244441', nbList[1].UM_CDRIDNumber__c, 'UM_CDRIDNumber__c should contain the json data!');
		System.assertEquals(serv.Id, nbList[1].UM_NumberRangeService__c, 'Service Id should be filled in!');

		//Test update
		numman = '{"UM_NumberBlockList": [{"UM_StartNumber__c":"222444410","UM_EndNumber__c":"222444419","UM_CDRIDNumber__c":"22244441","UM_AreaCode__c":"222","UM_BlockSize__c":"10"}]}';
		serv.UM_NumberManagement__c = numman;
		update serv;
		Test.stopTest();

		// Test number and content of created number blocks
    	nbList = [select Id, UM_StartNumber__c, UM_EndNumber__c, UM_CDRIDNumber__c, UM_AreaCode__c, UM_BlockSize__c, UM_Account__c, UM_ProductConfiguration__c, UM_NumberRangeService__c, UM_VoiceService__c from UM_NumberBlock__c where UM_NumberRangeService__c = :serv.Id];
		System.assertEquals(1, nbList.size(), '1 UM_NumberBlock__c records should have bean created!');
		System.assertEquals('22244441', nbList[0].UM_CDRIDNumber__c, 'UM_CDRIDNumber__c should contain the json data!');
		**/
    }
}