src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_Huawei_Tenant_ID__c</fullName>
        <description>Created as part of BDS story SFOM-2202</description>
        <label>Huawei Tenant ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalCity__c</fullName>
        <description>Postal City</description>
        <label>Postal City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalHouseNumberExtension__c</fullName>
        <label>Postal House Number Extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalHouseNumber__c</fullName>
        <label>Postal House Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalPostalCode__c</fullName>
        <label>Postal Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalStreet__c</fullName>
        <label>Postal Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>LG_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
   
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>LG_HouseNumber__c</fullName>
        <description>Standard House Number</description>
        <label>House Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_TechnicalContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.cscrm__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Premises</relationshipLabel>
        <relationshipName>Premises</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscrm__City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__State_Province__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Street_Name__c</fullName>
        <label>Street Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that currently receives this order</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Order</description>
        <inlineHelpText>The parent Solution of this Order</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>DEPRECATED. Defines the status of the order through fulfilment to delivery.</description>
        <inlineHelpText>DEPRECATED. Use Status2__c.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Provisioning</fullName>
                    <default>true</default>
                    <label>In Provisioning</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Not Provisioned</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csordtelcoa__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Solution.</description>
        <inlineHelpText>The Account that governs this Solution.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Solution.</description>
        <inlineHelpText>The parent Order of this Solution.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Solution in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LG_PostalCity__c</fullName>
        <description>Alternative post address of the customer - city.</description>
        <label>Postal City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalHouseNumberExtension__c</fullName>
        <description>Alternative post address of the customer - house number extension.</description>
        <label>Postal House Number Extension</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalHouseNumber__c</fullName>
        <description>Alternative post address of the customer - house number.</description>
        <label>Postal House Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PostalStreet__c</fullName>
        <description>Alternative post address of the customer -street.</description>
        <label>Postal Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PrimaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hidden field for fetching contact email from OpportunityContactRole</description>
        <label>PrimaryContact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LG_ManageTenantExtension.cls
public class LG_ManageTenantExtension {
    private final Case cs { get; set; }
	public Account tenantAccount {get; set;}
	public Contact tenantContact {get; set;}
    //public csord__Solution__c solutionObject { get; set; }
    public csord__Order__c orderObject { get; set; } 
    public Boolean isClosed {get; set;}
    public Boolean isEditMode {get; set;}
    
    public LG_ManageTenantExtension (ApexPages.StandardController stdController) {
    	isEditMode = false;
    	List<String> defaultFields = new List<String>();
        if(!Test.isRunningTest())
        {
            stdController.addFields(getFieldList());
        }
        this.cs = (Case)stdController.getRecord();
        orderObject = retriveOrderRecord();

        if(orderObject.csord__Account__c != null){
        	tenantAccount = 
        	[
        		SELECT Id, Name, LG_PostalStreet__c, LG_PostalHouseNumber__c, LG_PostalHouseNumberExtension__c, LG_PostalPostalCode__c, LG_PostalCity__c, LG_Huawei_Tenant_ID__c
        		FROM Account 
        		WHERE Id =: orderObject.csord__Account__c
        	];
        }
        if(orderObject.csordtelcoa__Opportunity__r.LG_PrimaryContact__c != null){
        	tenantContact = 
        	[
        		SELECT Id, LG_UserName__c, LG_Password__c, Name, Email,	MobilePhone, Phone
        		FROM Contact 
        		WHERE Id =: orderObject.csordtelcoa__Opportunity__r.LG_PrimaryContact__c
        	];
        }
        
        if(cs.status == 'Closed'){
        	isClosed = true;
        }
        
    }
	
	private csord__Order__c retriveOrderRecord(){
		csord__Order__c order = new csord__Order__c();
		if(this.cs.LG_Order__c != null){
			order = 
        	[
	        	SELECT Id, Name, Ownerid, csord__Status__c, csord__Account__c, csord__Account__r.Name, csordtelcoa__Opportunity__r.LG_PrimaryContact__c
	        	FROM csord__Order__c 
	        	WHERE Id = :this.cs.LG_Order__c
	        ];
		}
		return order;
	}
	
	/**
    private csord__Solution__c retrieveSolutionObject() {
   		csord__Solution__c solution = new csord__Solution__c();
        if (this.cs.LG_Solution__c != null) {
        	solution = 
        	[
	        	SELECT Id, Name, Ownerid, csord__Status__c, csord__Account__c, csord__Account__r.Name, LG_Address__r.LG_TechnicalContact__c,
	        		LG_Address__r.LG_TechnicalContact__r.Name, LG_Address__r.LG_TechnicalContact__r.Email, LG_Address__r.LG_TechnicalContact__r.MobilePhone, 
	        		LG_Address__r.LG_TechnicalContact__r.Phone, LG_Address__r.cscrm__Street_Name__c, LG_Address__r.LG_HouseNumber__c, 
	        		LG_Address__r.cscrm__State_Province__c, LG_Address__r.cscrm__Zip_Postal_Code__c, LG_Address__r.cscrm__City__c
	        	FROM csord__Solution__c 
	        	WHERE Id = :this.cs.LG_Solution__c
	        ];
        }
        return solution;
    }
    **/
    
    public void updateTenantDetails(){
    	if(tenantAccount != null)
    	update tenantAccount;
    	if(tenantContact != null)
    	update tenantContact;
    	isEditMode = false;
    }
 	
 	public void setEditMode(){
 		isEditMode = true;
 	}
 	
    public String getRecordType() {
        return this.cs.RecordType.Name;
    }
    
    public List<String> getFieldList(){
    	List<String> defaultFields = new List<String>();
        defaultFields.add('LG_Order__c');
        defaultFields.add('LG_Solution__c');
        defaultFields.add('RecordType.Name');
        defaultFields.add('Status');
        return defaultFields;
    }
    
}