src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_Segment__c</fullName>
        <label>Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SoHo</fullName>
                </value>
                <value>
                    <fullName>SME</fullName>
                </value>
                <value>
                    <fullName>LE</fullName>
                </value>
                <value>
                    <fullName>Wholesale</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_IndustryClassification__c</fullName>
        <label>Industry Classification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>UM_IndustryClassification</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_IsAccountSynced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Account Synced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>csconta__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UM_ContactTriggerHandlerTest.cls
@isTest
public class UM_ContactTriggerHandlerTest {

    public static testMethod void  testContactUpdate(){
        
        account acc = new account();
        acc.Name = 'Test';
        acc.LG_Segment__c = 'SME';
        acc.UM_IndustryClassification__c = 'A_LAND_UND_FORSTWIRTSCHAFT_FISCHEREI';
        insert acc;
        
        contact con = new Contact(AccountId=acc.id);
        con.Salutation = 'Mr'; 
        con.firstname = 'First';
        con.LastName = 'Last';
		insert con;
        
       	csconta__Billing_Account__c ba = new csconta__Billing_Account__c();
        ba.csconta__Account__c = acc.id;
        ba.Billing_Contact__c = con.id;
        insert ba;
        
        con.FirstName = 'New First';
        update con;
        
        System.assertEquals(true, [select id,UM_IsAccountSynced__c from csconta__Billing_Account__c where id=:ba.id].UM_IsAccountSynced__c);
        
    }
}