src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LG_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/LG_DWHFeedStagingTable__c.object
<CustomObject>
    <fields>
        <fullName>LG_AccountExternalId__c</fullName>
        <label>Account ExternalId</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ErrorMessage__c</fullName>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LG_ProcessedDate__c</fullName>
        <label>Processed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LG_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Processed Successfully</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_TransactionIdAccountId__c</fullName>
        <formula>LG_DWHTransactionId__c  &amp; LG_AccountExternalId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TransactionIdAccountId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_TypeofRecord__c</fullName>
        <label>Type of Record</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Subscription</fullName>
                </value>
                <value>
                    <fullName>Attribute</fullName>
                </value>
                <value>
                    <fullName>Billing Account</fullName>
                </value>
                <value>
                    <fullName>Premise</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DWH Feed Staging Table</label>
    <nameField>
        <displayFormat>DWH-{000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DWH Feed Staging Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_ManuallySyncDataFromDWH.cls
/*******************************************************************************************************************************************
* File Name     :  LG_ManuallySyncDataFromDWH
* Description   :  This class is used to manually sync a single set of related records from DWH staging table to SFDC objects. 

* @author       :   Shreyas
* Modification Log
===================================================================================================
* Ver.    Date          Author              Modification
---------------------------------------------------------------------------------------------------
* 1.0     7th-Mar-16    Shreyas             Created the class for release R1*

********************************************************************************************************************************************/

public class LG_ManuallySyncDataFromDWH{
 
    public static List<Account> createacc(){
	List<Account> acc = new List<Account>([SELECT CreatedbyID,Account.Name,(SELECT name,Contact.FirstName,Contact.Salutation, Contact.LastName FROM Account.Contacts) FROM Account]); 
       system.debug(acc);
     
        
         
     for (Account ac : acc) { 
     system.debug(ac); 
  }
    return acc;    
}
    
    
/*
    static string errorMessage = '';
    /*
        Name: syncManually
        Purpose: to manually sync a single set of related records from DWH staging table to SFDC objects. 
        Argument: string
        Return type: string
    */
    /*
    webservice static string syncManually(string uniqueId){
    
        string returnString = '';
        Savepoint sp = Database.setSavepoint();
        try{
            LG_CreateDataFromDWHFeedController controllerObj = new LG_CreateDataFromDWHFeedController();
            controllerObj.manualSync = true;
            controllerObj.uniqueIdForManualSync = uniqueId;
            map<string, List<map<string, List<LG_DWHFeedStagingTable__c>> > > feedMap = new map<string, List<map<string, List<LG_DWHFeedStagingTable__c>> > >();
            feedMap = controllerObj.createMapFromFeedRecords();
            controllerObj.processFeedRecords(uniqueId);
            returnString = 'Processed Successfully';
        } 
        catch(exception e){
            
            errorMessage = errorMessage + 'Message:-- ' + e.getMessage();
            errorMessage = errorMessage + '\nStack Trace:-- ' + e.getStackTraceString();
            returnString = errorMessage;
            Database.rollback(sp);
        }       
        return returnString;
    }
    
    /*
        Name: afterSyncAction
        Purpose: to update the status of processed records after manual sync
        Argument: string
        Return type: none
    */
    /*
    webservice static string afterSyncAction(string uniqueId, string status){
        
        string returnString = '';
        List<LG_DWHFeedStagingTable__c> dwhFetchedList = new List<LG_DWHFeedStagingTable__c>();
        List<LG_DWHFeedStagingTable__c> dwhUpdateList = new List<LG_DWHFeedStagingTable__c>();
        
        dwhFetchedList = [Select Id, LG_ProcessedDate__c, LG_Status__c, LG_AccountExternalId__c, LG_ErrorMessage__c, LG_TransactionIdAccountId__c, LG_TypeofRecord__c
                         from LG_DWHFeedStagingTable__c where LG_TransactionIdAccountId__c =: uniqueId];
                   
        
        for(LG_DWHFeedStagingTable__c dwh: dwhFetchedList){
            if(status == 'Processed Successfully'){
                dwh.LG_Status__c = status;
                dwh.LG_ErrorMessage__c = null;
            }
            else{
                 if(dwh.LG_TypeofRecord__c == 'Account'){
                    dwh.LG_ErrorMessage__c = status;    
                 }
                 dwh.LG_Status__c = 'Failed';
            }
            dwh.LG_ProcessedDate__c = System.now();
            dwhUpdateList.add(dwh);
        }
        
        if(dwhUpdateList.size() > 0){
            update dwhUpdateList;
        }
        
        return returnString;
    }
*/

}