src/objects/Add_On_Widget_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Add_On_Attribute__c</fullName>
        <label>Add On Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Add_On_Definition__c</fullName>
        <label>Add On Definition</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Add_On_Fields__c</fullName>
        <label>Add On Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Attribute__c</fullName>
        <label>Parent Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Add On Widget Settings</label>
</CustomObject>

src/objects/cscfga__Attribute__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Attribute_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Attribute Definition which describes this Attribute.</inlineHelpText>
        <label>Attribute Definition</label>
        <referenceTo>cscfga__Attribute_Definition__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Configuration__c</fullName>
        <inlineHelpText>The Product Configuration to which this Attribute belongs.</inlineHelpText>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cscfga__Attribute_Definition__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <inlineHelpText>The Product Definition to which this Attribute Definition belongs.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Attribute Definitions</relationshipLabel>
        <relationshipName>Attribute_Definitions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Add_On__c</fullName>
        <label>Add On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Description__c</fullName>
        <inlineHelpText>Description of the Product Configuration. Automatically set when Product Configuration is saved.</inlineHelpText>
        <label>Description</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Product Definition from which this Configuration was derived.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Add_On__c</fullName>
        <label>Add On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Item_Attribute__c</fullName>
        <label>Price Item Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Card__c</fullName>
        <label>Rate Card</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, it indicates that this Product Definition is active and available to sales users for configuration (several other conditions must be met).</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cscfga__Description__c</fullName>
        <inlineHelpText>Description of the product visible to the sales user in the configuration process.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cspmb__Add_On_Price_Item__c.object
<CustomObject>
    <description>Describes a simple product, bolt-on, optional extra etc. which can be sold associated with a parent Price Item.</description>
    <fields>
        <fullName>cspmb__Add_On_Price_Item_Description__c</fullName>
        <label>Add On Price Item_Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cspmb__One_Off_Charge__c</fullName>
        <label>One-Off Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Add On Price Item</label>
    <nameField>
        <label>Add On Price Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Add On Price Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cspmb__Price_Item__c.object
<CustomObject>
    <description>Describes the pricing and commercial aspects of any product, service, tariff, price plan etc. which can be sold.</description>
    
    <fields>
        <fullName>cspmb__One_Off_Charge__c</fullName>
        <description>The one-off amount to be charged for this Price Item. E.g. an installation charge.</description>
        <label>One-Off Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Price Item</label>
    <nameField>
        <label>Price Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAddOnWidgetController.cls
@isTest
public class TestAddOnWidgetController {

	static testmethod void testFeatureMethods() {
		cspmb__Add_On_Price_Item__c api = new cspmb__Add_On_Price_Item__c(
			Name = 'Test'
		);
		insert api;

		cspmb__Price_Item__c priceItem = new cspmb__Price_Item__c(
			Name = 'Test'
		);
		insert priceItem;

		cspmb__Price_Item_Add_On_Price_Item_Association__c piAssoc = new cspmb__Price_Item_Add_On_Price_Item_Association__c(
			cspmb__Price_Item__c = priceItem.Id,
			cspmb__Add_On_Price_Item__c = api.Id
		);
		insert piAssoc;

		Add_On_Widget_Settings__c addOnSettings = new Add_On_Widget_Settings__c(
			Parent_Attribute__c = 'Test',
			Add_On_Attribute__c = 'Test',
			Add_On_Fields__c = 'cspmb__Add_On_Price_Item_Description__c,cspmb__One_Off_Charge__c',
			Add_On_Definition__c = 'AddOn',
			Name = 'Test'
		);
		insert addOnSettings;

		Add_On_Widget_Settings__c addOnSettings2 = new Add_On_Widget_Settings__c(
			Name = 'Test1'
		);
		insert addOnSettings2;

		cscfga__Product_Definition__c pd = new cscfga__Product_Definition__c(
			Name = 'Test',
			cscfga__Description__c = 'Test',
			Add_On__c = 'Test',
			Feature__c = 'Test',
			Rate_Card__c = 'Test',
			Price_Item_Attribute__c = 'Test',
			cscfga__Active__c = true
		);
		insert pd;

		cscfga__Attribute_Definition__c att = new cscfga__Attribute_Definition__c(
			Name = 'Test',
			cscfga__Product_Definition__c = pd.Id
		);
		insert att;

		cscfga__Product_Definition__c pd1 = new cscfga__Product_Definition__c(
			Name = 'AddOn',
			cscfga__Description__c = 'Test',
			Add_On__c = 'Test',
			Feature__c = 'Test',
			Rate_Card__c = 'Test',
			Price_Item_Attribute__c = 'Test',
			cscfga__Active__c = true
		);
		insert pd1;

		cscfga__Attribute_Definition__c att1 = new cscfga__Attribute_Definition__c(
			Name = 'Test',
			cscfga__Product_Definition__c = pd1.Id
		);
		insert att1;

		cscfga__Product_Configuration__c pc = new cscfga__Product_Configuration__c(
			cscfga__Product_Definition__c = pd.Id,
			Name = 'Test'
		);
		insert pc;


		cscfga__Attribute__c att3 = new cscfga__Attribute__c(
			cscfga__Product_Configuration__c = pc.Id,
			Name = 'Test',
			cscfga__Attribute_Definition__c = att.Id
		);
		insert att3;

		// test feature retrieval
		String features = AddOnWidgetController.getAvaialbleAddOns(priceItem.Id, 'Test', null);
	}

}