src/objects/Add_On_Widget_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Add_On_Attribute__c</fullName>
        <label>Add On Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Attribute__c</fullName>
        <label>Parent Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Add On Widget Settings</label>
</CustomObject>

src/objects/cscfga__Product_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Add_On__c</fullName>
        <label>Add On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Item_Attribute__c</fullName>
        <label>Price Item Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Card__c</fullName>
        <label>Rate Card</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Description__c</fullName>
        <inlineHelpText>Description of the product visible to the sales user in the configuration process.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBasketEditorController.cls
@isTest
public class TestBasketEditorController {

	static testmethod void controllerTest() {
		cscfga__Product_Definition__c pd = new cscfga__Product_Definition__c(
			Name = 'Test',
			cscfga__Description__c = 'Test',
			Add_On__c = 'Test',
			Feature__c = 'Test',
			Rate_Card__c = 'Test',
			Price_Item_Attribute__c = 'Test'
		);
		insert pd;

		Add_On_Widget_Settings__c addOnSettings = new Add_On_Widget_Settings__c(
			Parent_Attribute__c = 'Parent',
			Add_On_Attribute__c = 'AddOn',
			Name = 'Test'
		);
		insert addOnSettings;

		// Test constructor
		ApexPages.StandardController sc = new ApexPages.StandardController(pd);
		BasketEditorController ctrl = new BasketEditorController();
		ctrl = new BasketEditorController(sc);

		// Category and Price Item data retrieval
		String str = BasketEditorController.getCategoriesAndPriceItemAttributeName(pd.Id);
	}
}