src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>LG_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Assets (Asset)</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_EndNumber__c</fullName>
        <description>End Number of the Number Range</description>
        <label>End Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>LG_NumberRangeSize__c</fullName>
        <label>Number Range Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_NumberRangeType__c</fullName>
        <label>Number Range Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Portin</fullName>
                </value>
                <value>
                    <fullName>Port-In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_NumberRange__c</fullName>
        <label>Number Range</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PhoneNumber__c</fullName>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_SoftDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for versioning and tracking</description>
        <inlineHelpText>Indicates that the record is not relevant do to the change is active version (newer or older version exists and it is active)</inlineHelpText>
        <label>Soft Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_StartNumber__c</fullName>
        <description>Starting Number of the Number Range</description>
        <label>Start Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_TelephonyProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Telephony Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
   
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Features__c</fullName>
        <label>Features</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LG_NumberRangeSize__c</fullName>
        <label>Number Range Size</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_NumberRangeType__c</fullName>
        <label>Number Range Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Basket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of associated Product Basket.</inlineHelpText>
        <label>Product Basket</label>
        <referenceTo>cscfga__Product_Basket__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>LG_FullAddressDetails__c</fullName>
        <formula>IF( ISBLANK(cscrm__Street__c) , &apos;&apos;, cscrm__Street__c) + 
IF( ISBLANK(LG_HouseNumber__c) , &apos;&apos;, &apos; &apos; + LG_HouseNumber__c) + 
IF( ISBLANK(LG_HouseNumberExtension__c) , &apos;&apos;, &apos; &apos; + LG_HouseNumberExtension__c + &apos;,&apos;) + 
IF( ISBLANK(cscrm__Zip_Postal_Code__c) , &apos;&apos;, &apos; &apos; + cscrm__Zip_Postal_Code__c) + 
IF( ISBLANK(cscrm__City__c) , &apos;&apos;, &apos; &apos; + cscrm__City__c) + 
IF( ISBLANK(cscrm__Country__c), &apos;&apos;, &apos;, &apos; + cscrm__Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Address Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Service.</description>
        <inlineHelpText>The parent Order of this Service.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Solution.</description>
        <inlineHelpText>The parent Order of this Solution.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSPOFA__Orchestration_Process__c.object
<CustomObject>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_NumberManagementSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the settings for Number Management.</description>
    <fields>
        <fullName>LG_MaxNumberLength__c</fullName>
        <label>Max Number Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_MinNumberLength__c</fullName>
        <label>Min Number Length</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_NewDetailsFieldSet__c</fullName>
        <description>Holds the name of the Asset objects field set used on the Capture Number Preferences page (and a controller) for additional new numbers details.</description>
        <label>New Details Field Set</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PortInDetailsFieldSet__c</fullName>
        <description>Holds the name of the Asset objects field set used on the Capture Number Preferences page (and a controller).</description>
        <label>Port In Details Field Set</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PortInOperators__c</fullName>
        <description>Holds the name of a specific global picklist that holds the list of Port In Operators - currently a CSV list</description>
        <inlineHelpText>Holds the name of a specific global picklist that holds the list of Port In Operators - currently a CSV list</inlineHelpText>
        <label>Port-In Operators</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_RequireDetailsForNew__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If unchecked, validations won&apos;t be fired for new number blocks during sales process. Only Number Block Type (New or Port In) and Number Block Size fields will be required.</description>
        <inlineHelpText>If unchecked, validations won&apos;t be fired for new number blocks during sales process. Only Number Block Type (New or Port In) and Number Block Size fields will be required.</inlineHelpText>
        <label>Require Details for New</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_RequireDetailsForPortIn__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If unchecked, validations won&apos;t be fired for port-in number blocks during sales process. Only Number Block Type (New or Port In) and Number Block Size fields will be required.</description>
        <inlineHelpText>If unchecked, validations won&apos;t be fired for port-in number blocks during sales process. Only Number Block Type (New or Port In) and Number Block Size fields will be required.</inlineHelpText>
        <label>Require Details for Port In</label>
        <type>Checkbox</type>
    </fields>
    <label>Number Management Settings</label>
</CustomObject>

src/classes/LG_NumberManagementController.cls
/**
 * Used as a controller for LG_NumberManagement VF page.
 *
 * @author Tomislav Blazek
 * @ticket SFOM-106
 * @since  12/12/2016
 */
global with sharing class LG_NumberManagementController {

	public List<NumberRangeWrapper> numberRangeList {get; set;}
	public Id recordId {get; set;}
	public String caseRecordTypeName {get; set;}
	public Id solnId {get; set;}
	public Boolean basketContext {get; set;}
	public Boolean pageReadOnly {get; set;}
	public Boolean validationsRequiredForNew {get; set;}
	public Boolean validationsRequiredForPortIn {get; set;}
	public String numberLengthValidationMsg {get; set;}
	public LG_NumberManagementSettings__c numberMngSettings {get; set;}

	//fetches the portin details fields - fields dependent on the profile/custom settings
	public List<Schema.FieldSetMember> getPortInDetailsFields()
	{
		Schema.FieldSet portInDetailsFieldSet = Schema.SObjectType.Asset.fieldSets.getMap().get(numberMngSettings.LG_PortInDetailsFieldSet__c);
		return portInDetailsFieldSet != null ? portInDetailsFieldSet.getFields() : new List<Schema.FieldSetMember>();
	}

	//fetches the numbers new details fields - fields dependent on the profile/custom settings
	public List<Schema.FieldSetMember> getNewDetailsFields()
	{
		Schema.FieldSet newDetailsFieldSet = Schema.SObjectType.Asset.fieldSets.getMap().get(numberMngSettings.LG_NewDetailsFieldSet__c);
		return newDetailsFieldSet != null ? newDetailsFieldSet.getFields() : new List<Schema.FieldSetMember>();
	}

	public LG_NumberManagementController() {
		recordId      = ApexPages.currentPage().getParameters().get('id');
		basketContext = false;
		if (String.isNotBlank(recordId)) {
			if (Schema.cscfga__Product_Basket__c.SObjectType == recordId.getSObjectType()) {
				basketContext = true;
			} else if (Schema.Case.SObjectType == recordId.getSObjectType()) {
				Case caseRec = [SELECT Id, RecordType.Name, LG_Solution__r.csord__Order__c, LG_Solution__c FROM Case WHERE Id = :recordId];
				//SFOM-621,
				this.caseRecordTypeName = caseRec.RecordType.Name;
				this.solnId             = caseRec.LG_Solution__c;
				if (caseRec.RecordType.Name == 'Inflight Change') {
					recordId = caseRec.LG_Solution__c;
				} else
				{
					recordId = caseRec.LG_Solution__r.csord__Order__c;
				}
				//page should be rendered as readonly
				if (caseRec.RecordType.Name == 'Activate Service' || caseRec.RecordType.Name == 'Install' || caseRec.RecordType.Name == 'Provision') {
					pageReadOnly = true;
				}
			} else {
				recordId = null;
			}
		}
		numberMngSettings            = LG_NumberManagementSettings__c.getInstance(UserInfo.getUserId());
		validationsRequiredForNew    = numberMngSettings.LG_RequireDetailsForNew__c || !basketContext;
		validationsRequiredForPortIn = numberMngSettings.LG_RequireDetailsForPortIn__c || !basketContext;
		numberLengthValidationMsg    = numberMngSettings.LG_MinNumberLength__c == numberMngSettings.LG_MaxNumberLength__c
									   ? Label.LG_NmbrManagementMinNmbr.replace('{minNumberLength}', String.valueOf(Integer.valueOf(numberMngSettings.LG_MaxNumberLength__c)))
									   : Label.LG_NmbrManagementMinMaxNmbr.replace('{minNumberLength}', String.valueOf(Integer.valueOf(numberMngSettings.LG_MinNumberLength__c)))
									   .replace('{maxNumberLength}', String.valueOf(Integer.valueOf(numberMngSettings.LG_MaxNumberLength__c)));

		populateNmbrRangeListFromAssets();
	}

	public List<SelectOption> getPortInOperators()
	{
		List<SelectOption> portInOperators = new List<SelectOption>();
		portInOperators.add(new SelectOption('', Label.LG_Select));

		for (String portInOperator : LG_Util.commaSeparatedStringToSet(numberMngSettings.LG_PortInOperators__c)) {
			portInOperators.add(new SelectOption(portInOperator, portInOperator));

		}
		return portInOperators;
	}

	/**
	 * Updates the Number Block Asset records with the details, and updated the
	 * related phone number asset records if there was a change in the number.
	 *
	 * @author Tomislav Blazek
	 * @ticket SFOM-106
	 * @since  14/12/2016
	 */
	public void save()
	{
		Map<NumberRangeWrapper, Asset> numberRangeToNumberBlock = new Map<NumberRangeWrapper, Asset>();
		Set<Id> asseIds                                         = new Set<Id>();
		boolean donorOnly          = false;
		boolean updateOrchestrator = false;

		for (NumberRangeWrapper nw : numberRangeList) {
			nw.numberBlockAsset.Name = nw.numberBlockAsset.LG_NumberRange__c;
			numberRangeToNumberBlock.put(nw, nw.numberBlockAsset);
			asseIds.add(nw.numberBlockAsset.Id);
		}

		//SFOM-621 track type of change before updating the asset
		if (caseRecordTypeName == 'Manage Numbers') {
			donorOnly          = isDonorOnlyChange(asseIds);
			updateOrchestrator = true;

		}

		update numberRangeToNumberBlock.values();

		//update existing phone number records with valid numbers (for existing number block assets)
		updateExistingPhoneNumbers(numberRangeToNumberBlock.keySet());

		//SFOM-621
		if (updateOrchestrator) {

			updateInflightNumberProcess(solnId, donorOnly);
		}
	}

	private void updateExistingPhoneNumbers(Set<NumberRangeWrapper> numberRangeList)
	{
		List<Asset> numbersToUpsert = new List<Asset>();
		Set<Id> numberBlockIds      = new Set<Id>();
		for (NumberRangeWrapper nw : numberRangeList) {
			numberBlockIds.add(nw.numberBlockAsset.Id);
		}

		List<Asset> phoneNumbers = [SELECT Id, Name, LG_Asset__c, LG_PhoneNumber__c
									FROM Asset
									WHERE LG_Asset__c IN :numberBlockIds];

		Map<Id, List<Asset>> nmbrBlockToNumbers = new Map<Id, List<Asset>>();
		for (Asset numberAsset : phoneNumbers) {
			if (!nmbrBlockToNumbers.containsKey(numberAsset.LG_Asset__c)) {
				nmbrBlockToNumbers.put(numberAsset.LG_Asset__c, new List<Asset>());
			}
			nmbrBlockToNumbers.get(numberAsset.LG_Asset__c).add(numberAsset);
		}

		for (NumberRangeWrapper nw : numberRangeList) {
			List<String> numbers;
			Integer blockSize = Integer.valueOf(nw.numberBlockAsset.LG_NumberRangeSize__c);

			//start number not changed, so skip the update of phone numbers
			if (String.isNotBlank(nw.numberBlockAsset.LG_StartNumber__c) && String.isBlank(nw.numbers)) {
				continue;
			}
			//start number changed
			if (String.isNotBlank(nw.numberBlockAsset.LG_StartNumber__c)) {
				numbers = (List<String>)JSON.deserialize(nw.numbers, List<String>.class);
			}
			List<Asset> numberAssets = nmbrBlockToNumbers.get(nw.numberBlockAsset.Id);
			for (Integer i = 0; i < blockSize; i++) {
				Asset phoneNumber = numberAssets[i];
				phoneNumber.Name              = numbers != null ? numbers[i] : 'Not Defined';
				phoneNumber.LG_PhoneNumber__c = numbers != null ? numbers[i] : 'Not Defined';
				numbersToUpsert.add(phoneNumber);
			}
		}

		update numbersToUpsert;
	}

	private void populateNmbrRangeListFromAssets(){
		numberRangeList = new List<NumberRangeWrapper>();

		if (recordId != null) {
			String blocksMainQuery = 'Id, LG_NumberRangeType__c, LG_NumberRangeSize__c,'
									 + 'LG_StartNumber__c, LG_EndNumber__c, LG_NumberRange__c,'
									 + 'LG_TelephonyProductConfiguration__c, '
									 + 'LG_TelephonyProductConfiguration__r.Name, '
									 + 'LG_TelephonyProductConfiguration__r.LG_Address__c, '
									 + 'LG_TelephonyProductConfiguration__r.LG_Features__c, '
									 + 'LG_TelephonyProductConfiguration__r.LG_Address__r.LG_FullAddressDetails__c, '
									 + 'LG_TelephonyProductConfiguration__r.LG_Address__r.cscrm__Zip_Postal_Code__c '
									 + 'FROM Asset WHERE RecordType.Name = \'Number Block\' '
									 + 'AND LG_SoftDeleted__c = false '
									 + 'AND (LG_TelephonyProductConfiguration__r.cscfga__Product_Basket__c = :recordId '
									 + '     OR LG_TelephonyService__r.LG_RootOrder__c = :recordId '
									 + '     OR LG_TelephonyService__r.LG_Suborder__c = :recordId) '
									 + 'ORDER BY LG_TelephonyProductConfiguration__r.LG_Address__r.LG_FullAddressDetails__c,'
									 + ' LG_TelephonyProductConfiguration__r.Name, LG_StartNumber__c';

			String existingBlocksQuery = 'SELECT ';
			for (Schema.FieldSetMember f : getPortInDetailsFields()) {
				if (!blocksMainQuery.contains(f.getFieldPath()) && !existingBlocksQuery.contains(f.getFieldPath())) {
					existingBlocksQuery += f.getFieldPath() + ', ';
				}
			}
			for (Schema.FieldSetMember f : getNewDetailsFields()) {
				if (!blocksMainQuery.contains(f.getFieldPath()) && !existingBlocksQuery.contains(f.getFieldPath())) {
					existingBlocksQuery += f.getFieldPath() + ', ';
				}
			}

			existingBlocksQuery += blocksMainQuery;

			List<Asset> existingBlocks = Database.query(existingBlocksQuery);
			for (Asset numberBlock : existingBlocks) {
				numberRangeList.add(new NumberRangeWrapper(numberBlock, numberRangeList));
			}
		}
	}

	public class NumberRangeWrapper
	{
		public Asset numberBlockAsset {get; set;}
		public String addressDesc {get; set;}
		public String addressKey {get; set;}
		public String addressTooltip {get; set;}
		public Integer index {get; set;}
		public String numbers {get; set;}

		public NumberRangeWrapper(Asset asset, List<NumberRangeWrapper> numberRangeList) {
			this.numberBlockAsset = asset;
			this.index            = numberRangeList.size();
			this.addressKey       = asset.LG_TelephonyProductConfiguration__r.LG_Address__c + ', ' + asset.LG_TelephonyProductConfiguration__c;
			this.addressTooltip   = asset.LG_TelephonyProductConfiguration__r.LG_Address__r.LG_FullAddressDetails__c + ', '
									+ asset.LG_TelephonyProductConfiguration__r.Name + ', ' + asset.LG_TelephonyProductConfiguration__r.LG_Features__c;
			this.addressDesc = asset.LG_TelephonyProductConfiguration__r.Name + ', ' + asset.LG_TelephonyProductConfiguration__r.LG_Address__r.cscrm__Zip_Postal_Code__c;
			if (this.index != 0 && numberRangeList[this.index - 1].addressKey == this.addressKey) {
				this.addressDesc = null;
			}
		}
	}

	/**
	 * Track changes for donor only or other changes
	 *
	 * @param  Set<Id> asseIds Asset Ids
	 * @retrun boolean
	 * @author Minhaj Alam
	 * @ticket SFOM-621
	 * @since  24/04/2017
	 */
	public boolean isDonorOnlyChange(Set<Id> asseIds)
	{
		List<string> donorDetailsNew      = new List<string>();
		List<string> donorDetailsOldAsset = new List<string>();
		List<string> otherDetailsNew      = new List<string>();
		List<string> otherDetailsOldAsset = new List<string>();
		Map<Id, Asset> assetsMap          = new Map<Id, Asset>();
		boolean donorOnlyChange = false;

		//Fetch the old asset values which are candidate for change
		List<Asset> assets = [SELECT Id, LG_StartNumber__c, LG_EndNumber__c, LG_PortInWishDate__c, LG_PortInOperator__c, LG_PortInName__c, LG_PortInZipcode__c FROM Asset WHERE Id IN :asseIds];

		for (Asset record: assets) {
			assetsMap.put(record.Id, record);

		}

		for (NumberRangeWrapper nw : numberRangeList) {

			//identify donor only and other changes from new asset values
			String OtherChange = nw.numberBlockAsset.LG_StartNumber__c + nw.numberBlockAsset.LG_EndNumber__c + nw.numberBlockAsset.LG_PortInWishDate__c + nw.numberBlockAsset.LG_PortInOperator__c;
			otherDetailsNew.add(OtherChange.toLowerCase());
			String donor = nw.numberBlockAsset.LG_PortInName__c + nw.numberBlockAsset.LG_PortInZipcode__c;
			donorDetailsNew.add(donor.toLowerCase());

			//identify donor only and other changes from old asset values
			Asset OldAsset             = assetsMap.get(nw.numberBlockAsset.Id);
			String OtherChangeOldAsset = OldAsset.LG_StartNumber__c + OldAsset.LG_EndNumber__c + OldAsset.LG_PortInWishDate__c + OldAsset.LG_PortInOperator__c;
			otherDetailsOldAsset.add( OtherChangeOldAsset.toLowerCase());
			String donorOldAsset = OldAsset.LG_PortInName__c + OldAsset.LG_PortInZipcode__c;
			donorDetailsOldAsset.add(donorOldAsset.toLowerCase());

		}

		//if other changes are same but donor information is changed
		if (otherDetailsOldAsset.equals(otherDetailsNew) && !donorDetailsOldAsset.equals(donorDetailsNew)) {
			donorOnlyChange = true;
		}

		return donorOnlyChange;
	}


	/**
	 * update orchestrator driving variables for manage numbers case
	 *
	 * @param  Id solnId Solution ID
	 * @param  boolean donorOnly  donor only change or other change
	 * @author Minhaj Alam
	 * @ticket SFOM-621
	 * @since  24/04/2017
	 */
	Public Void updateInflightNumberProcess(Id solnId, boolean donorOnly)
	{
		List<CSPOFA__Orchestration_Process__c> processIds = new List <CSPOFA__Orchestration_Process__c>();
		List<CSPOFA__Orchestration_Step__c> processSteps  = new List<CSPOFA__Orchestration_Step__c>();
		List<csord__Solution__c> solnlist                 = new List<csord__Solution__c>();
		List<csord__Solution__c> solnListToUpdate         = new List<csord__Solution__c>();

		//Get the list of orchestration process ids and process ids for the solution
        solnList     = [SELECT id, LG_TargetDate__c, LG_Jeopardy__c, LG_EarliestInstallDate__c, LG_EarliestPortingWishDate__c,LG_LatestPortingWishDate__c, LG_AnyNumbersToPort__c, LG_InflightChange__c, LG_RetryInstall__c, LG_RetryNumberPort__c from csord__Solution__c WHERE id = :solnId];
		processIds   = [SELECT id, Name, LG_Solution__c, CSPOFA__Orchestration_Process_Template__c, CSPOFA__Process_On_Hold__c FROM CSPOFA__Orchestration_Process__c where LG_Solution__c = :solnId];
		processSteps = [select id, Name, CSPOFA__Status__c, CSPOFA__Step_Order__c,CSPOFA__Orchestration_Process__c,CSPOFA__Orchestration_Process__r.LG_Solution__r.id FROM CSPOFA__Orchestration_Step__c where CSPOFA__Orchestration_Process__c in :processIds and CSPOFA__Step_Order__c <100];

		Integer potentialGotoSeq;
		csord__Solution__c soln;


		if (!solnList.isEmpty()) {
			soln             = solnList[0];
            //SFOM-737
            //Get the orchestration process associated to a solution
            CSPOFA__Orchestration_Process__c pro = new CSPOFA__Orchestration_Process__c ();
            for (CSPOFA__Orchestration_Process__c orch : processIds){
                if(orch.LG_Solution__c== soln.id){
                    pro = orch;
                    break;
                }
            }
            //SFOM-737
            //Get the custom setting defined for a process
            LG_InflightChangeStep__c csSetting = new   LG_InflightChangeStep__c (); 
            List<LG_InflightChangeStep__c> inflightSettingList = LG_InflightChangeStep__c.getall().values();        
            for (LG_InflightChangeStep__c cs :inflightSettingList ){
                if(cs.LG_OrchestrationProcess__c == pro.CSPOFA__Orchestration_Process_Template__c){
                    csSetting = cs;
                    break;
                }
            }
            
            potentialGotoSeq = csSetting.LG_RetryProvision__c.intvalue();
			if (donorOnly) {
                potentialGotoSeq = csSetting.LG_RetryNumberPort__c.intvalue();
			}

			CSPOFA__Orchestration_Step__c inProgressProcessStep = inProgressProcessStep(processSteps, soln.id);
            if (soln.LG_Jeopardy__c != True) {
			if (inProgressProcessStep.CSPOFA__Step_Order__c >= potentialGotoSeq ) {

                    if (potentialGotoSeq == csSetting.LG_RetryNumberPort__c.intvalue()) {
					soln.LG_RetryNumberPort__c = True;
				} else {
					soln.LG_RetryProvision__c = True;
				}
					soln.LG_InflightChange__c = True;
				}
            }
            //SFOM-737
            else if (soln.LG_Jeopardy__c == True) {
                if (inProgressProcessStep.CSPOFA__Step_Order__c >= potentialGotoSeq ) {

                    if (inProgressProcessStep.CSPOFA__Step_Order__c  == csSetting.LG_NumberPortLoop__c.intvalue()) {
                        soln.LG_RetryNumberPort__c = True;
                    } else if (inProgressProcessStep.CSPOFA__Step_Order__c  == csSetting.LG_ProvisionLoop__c.intvalue()) {
                        soln.LG_RetryProvision__c = True;
                    }
                }
            }
				update soln;
			}

		}


	//Method to compute the inporgress orchestration process step
	Private static CSPOFA__Orchestration_Step__c inProgressProcessStep (List<CSPOFA__Orchestration_Step__c> inProgressProcessStep, Id solnId)
	{
		CSPOFA__Orchestration_Step__c pro = new CSPOFA__Orchestration_Step__c();
		for (CSPOFA__Orchestration_Step__c processStep : inProgressProcessStep) {
			if (processstep.CSPOFA__Orchestration_Process__r.LG_Solution__c== solnId  && (processstep.CSPOFA__Status__c == 'In Progress'  || processstep.CSPOFA__Status__c == 'Waiting For Feedback')) {
				pro = processStep;
				break;
			}
		}
		return pro;
	}
}