src/objects/Asset.object
<CustomObject>
    
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Status2__c</fullName>
        <description>The status of the Order in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>DEPRECATED. Defines the status of the order through fulfilment to delivery.</description>
        <inlineHelpText>DEPRECATED. Use Status2__c.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Provisioning</fullName>
                    <default>true</default>
                    <label>In Provisioning</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Not Provisioned</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csordtelcoa__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>LG_ProductFamily__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_PICReason__c</fullName>
        <label>PIC Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Service.</description>
        <inlineHelpText>The parent Order of this Service.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Replaced_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replaced Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Replacement Services</relationshipLabel>
        <relationshipName>Replaced_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Replacement_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replacement Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Replaced Services</relationshipLabel>
        <relationshipName>Replacement_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Subscription.</description>
        <inlineHelpText>The parent Order of this Subscription.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Subscription in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csordtelcoa__Orders_Subscriptions_Options__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>LG_OrderCanceledStatus__c</fullName>
        <defaultValue>&quot;Canceled&quot;</defaultValue>
        <description>Holds the value that would be set on the Order Status2 field when the Order is canceled.</description>
        <inlineHelpText>Holds the value that would be set on the Order Status2 field when the Order is canceled.</inlineHelpText>
        <label>Order Canceled Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_OrderCompleteStatus__c</fullName>
        <defaultValue>&quot;Closed&quot;</defaultValue>
        <description>Holds the value that will be set on the Status2 field of the Order when all suborders are complete.</description>
        <inlineHelpText>Holds the value that will be set on the Status2 field of the Order when all suborders are complete.</inlineHelpText>
        <label>Order Complete Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_OrderPartiallyCompletedStatus__c</fullName>
        <defaultValue>&quot;Some Suborders Completed&quot;</defaultValue>
        <description>Holds the value that would be set on the Order Status2 field when some of the suborders are complete, but not all of them.</description>
        <inlineHelpText>Holds the value that would be set on the Order Status2 field when some of the suborders are complete, but not all of them.</inlineHelpText>
        <label>Order Partially Completed Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ServiceDeactivatedStatus__c</fullName>
        <defaultValue>&quot;Inactive&quot;</defaultValue>
        <description>Value of the Service Status that defines Service is Deactivated</description>
        <label>Service Deactivated Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Subscription_Closed_Replaced_State__c</fullName>
        <inlineHelpText>Default &quot;Closed Replaced&quot;</inlineHelpText>
        <label>Subscription Closed Replaced State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Orders &amp; Subscriptions Options</label>
</CustomObject>

src/classes/LG_InstallBaseUtilTest.cls
@isTest
private class LG_InstallBaseUtilTest {

    @testsetup
    private static void setupTestData()
    {
        No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
        noTriggers.Flag__c      = true;
        noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
        upsert noTriggers;

        csordtelcoa__Orders_Subscriptions_Options__c osOptions = new csordtelcoa__Orders_Subscriptions_Options__c();
        osOptions.LG_OrderPartiallyCompletedStatus__c                = 'Some Suborders Completed';
        osOptions.LG_OrderCompleteStatus__c                          = 'Completed';
        osOptions.LG_OrderCanceledStatus__c                          = 'Cancelled';
        osOptions.LG_ServiceDeactivatedStatus__c                     = 'Inactive';
        osOptions.csordtelcoa__Subscription_Closed_Replaced_State__c = 'Closed Replaced';
        insert osOptions;

        Account acc = LG_GeneralTest.CreateAccount('TestAccount', '321654987', 'Test', true);

        Opportunity opp = LG_GeneralTest.CreateOpportunity(acc, false);
        insert opp;

        // Insert two Orders
        List<csord__Order__c> orders = new List<csord__Order__c>();
        csord__Order__c replacedOrder  = new csord__Order__c(Name = 'Test Replaced Order', csord__Status2__c = 'Completed', csord__Identification__c = '123456489');
        csord__Order__c canceledOrder  = new csord__Order__c(Name = 'Test Order First', csord__Status2__c = 'Cancelled', csord__Identification__c = '123456789', csordtelcoa__Opportunity__c = opp.Id);
        csord__Order__c completedOrder = new csord__Order__c(Name = 'Test Order Second', csord__Status2__c = 'Completed', csord__Identification__c = '123456799');
        orders.add(canceledOrder);
        orders.add(completedOrder);
        orders.add(replacedOrder);
        insert orders;

        csord__Subscription__c cancelSub = new csord__Subscription__c(csord__Identification__c = 'IdentSubCancel');
        insert cancelSub;

        insert new csordtelcoa__Subscription_MACDOpportunity_Association__c(csordtelcoa__Subscription__c = cancelSub.Id, csordtelcoa__Opportunity__c = opp.Id);

        csord__Subscription__c completeSub = new csord__Subscription__c(csord__Identification__c = 'IdentSubComplete');
        insert completeSub;

        csord__Subscription__c cancelReplacedSub = new csord__Subscription__c(csord__Identification__c = 'cancelReplacedSub');
        insert cancelReplacedSub;

        csord__Subscription__c completeReplacedSub = new csord__Subscription__c(csord__Identification__c = 'completeReplacedSub');
        insert completeReplacedSub;


        List<csord__Service__c> services = new List<csord__Service__c>();
        csord__Service__c cancelServiceOne = new csord__Service__c(csord__Subscription__c = cancelSub.Id,
                                                                   csord__Identification__c = 'cancelServiceOne',
                                                                   csord__Order__c = canceledOrder.Id, UM_PICReason__c = 'test',LG_ProductFamily__c='SOHO');
        csord__Service__c comServiceOne = new csord__Service__c(csord__Subscription__c = completeSub.Id,
                                                                csord__Identification__c = 'comServiceOne',
                                                                csord__Order__c = completedOrder.Id,LG_ProductFamily__c='SOHO');
        csord__Service__c cancelServiceTwo = new csord__Service__c(csord__Subscription__c = cancelSub.Id,
                                                                   csord__Identification__c = 'cancelServiceTwo',
                                                                   csord__Order__c = canceledOrder.Id, UM_PICReason__c = 'test',LG_ProductFamily__c='SOHO');
        csord__Service__c comServiceTwo = new csord__Service__c(csord__Subscription__c = completeSub.Id,
                                                                csord__Identification__c = 'comServiceTwo',
                                                                csord__Order__c = completedOrder.Id,LG_ProductFamily__c='SOHO');
        csord__Service__c replacementCancelService = new csord__Service__c(csord__Subscription__c = cancelReplacedSub.Id,
                                                                           csord__Identification__c = 'replacementCancelService',
                                                                           csord__Order__c = replacedOrder.Id,LG_ProductFamily__c='SOHO');
        csord__Service__c replacementCompleteService = new csord__Service__c(csord__Subscription__c = completeReplacedSub.Id,
                                                                             csord__Identification__c = 'replacementCompleteService',
                                                                             csord__Order__c = replacedOrder.Id,LG_ProductFamily__c='SOHO');
        services.add(cancelServiceOne);
        services.add(comServiceOne);
        services.add(cancelServiceTwo);
        services.add(comServiceTwo);
        services.add(replacementCancelService);
        services.add(replacementCompleteService);
        insert services;

        cancelServiceTwo.csordtelcoa__Replaced_Service__c              = replacementCancelService.Id;
        replacementCancelService.csordtelcoa__Replacement_Service__c   = cancelServiceTwo.Id;
        comServiceTwo.csordtelcoa__Replaced_Service__c                 = replacementCompleteService.Id;
        replacementCompleteService.csordtelcoa__Replacement_Service__c = comServiceTwo.Id;
        update services;

        Asset completeAsset = new Asset(Name = 'CompleteAsset', AccountId = acc.Id, csord__Service__c = comServiceOne.Id);
        insert completeAsset;

        Asset cancelAsset = new Asset(Name = 'CancelAsset', AccountId = acc.Id, csord__Service__c = cancelServiceTwo.Id);

        noTriggers.Flag__c = false;
        upsert noTriggers;
    }

    private static testmethod void updateInstallBaseStatuses()
    {
        Set<Id> orderIds = new Set<Id>();
        for (csord__Order__c order : [SELECT Id FROM csord__Order__c]) {
            orderIds.add(order.Id);
        }

        Test.startTest();
        LG_InstallBaseUtil util = new LG_InstallBaseUtil(orderIds);
        util.updateInstallBaseStatuses();
        Test.stopTest();

        List<Asset> assets = [SELECT Id, Status, Name FROM Asset];
        for (Asset asset : assets) {
            if (asset.Name == 'CompleteAsset') {
                System.assertEquals('Active', asset.Status, 'Asset should be Active');
            } else if (asset.Name == 'CancelAsset') {
                System.assertEquals('Inactive', asset.Status, 'Asset should be Inactive');

            }
        }

        List<csord__Service__c> services = [SELECT Id, csord__Identification__c, csord__Subscription__r.csord__Status__c, csord__Status__c
                                            FROM csord__Service__c];

        for (csord__Service__c service : services) {
            if (service.csord__Identification__c == 'cancelServiceOne') {
                System.assertEquals('Cancelled', service.csord__Status__c, 'Service status should be Cancelled');
            } else if (service.csord__Identification__c == 'cancelServiceTwo') {
                System.assertEquals('Cancelled', service.csord__Status__c, 'Service status should be Cancelled');
            } else if (service.csord__Identification__c == 'comServiceOne') {
                System.assertEquals('Active', service.csord__Status__c, 'Service status should be Active');
            } else if (service.csord__Identification__c == 'comServiceTwo') {
                System.assertEquals('Active', service.csord__Status__c, 'Service status should be Active');
            } else if (service.csord__Identification__c == 'replacementCancelService') {
                System.assertEquals('Active', service.csord__Status__c, 'Service status should be Active');
            }
        }
    }
}