src/objects/Asset.object
<CustomObject>
    
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
   
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>LG_TechnicalContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.cscrm__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Premises</relationshipLabel>
        <relationshipName>Premises</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscrm__State_Province__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account that currently receives this order</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Order</description>
        <inlineHelpText>The parent Solution of this Order</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>DEPRECATED. Defines the status of the order through fulfilment to delivery.</description>
        <inlineHelpText>DEPRECATED. Use Status2__c.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Provisioning</fullName>
                    <default>true</default>
                    <label>In Provisioning</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Not Provisioned</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Configuration lookup, basically 1:1 relationship, the lookup value is used only in Product Delivery typed orders</description>
        <inlineHelpText>Product Configuration lookup for Product Delivery typed orders</inlineHelpText>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>LG_ProvisioningAccountNo__c</fullName>
        <label>Provisioning Account No</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Service.</description>
        <inlineHelpText>The parent Order of this Service.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_EarliestInstallDate__c</fullName>
        <label>Earliest Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LG_JeopardyExplanation__c</fullName>
        <label>JeopardyExplanation</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LG_Jeopardy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Jeopardy</label>
        <type>Checkbox</type>
    </fields>
    
    <fields>
        <fullName>LG_OneStepCase_Provisioning_Account_No__c</fullName>
        <formula>(csordtelcoa__Product_Configuration__r.cscfga__Product_Basket__r.LG_BillingAccount__r.LG_BillingAccountNumber__c)+(LG_Address__r.cscrm__Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Provisioning Account No</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ProvisioningAccountNo__c</fullName>
        <label>Provisioning Account No</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ProvisioningWorkOrder__c</fullName>
        <externalId>true</externalId>
        <label>Provisioning Work Order</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_TargetDate__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Solution.</description>
        <inlineHelpText>The Account that governs this Solution.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Solution.</description>
        <inlineHelpText>The parent Order of this Solution.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Solution in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product configuration that initiated creation of this Solution</description>
        <inlineHelpText>Product configuration that initiated creation of this Solution</inlineHelpText>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_SConsoleProvOneDetailsExtensionTest.cls
public class LG_SConsoleProvOneDetailsExtensionTest{

     Public Asset assetBdsToUpdate{get;set;}
     Public Asset assetBds{get;set;}
     Public csord__Service__c bdsService{get;set;}
     Public List<csord__Service__c> listOfBds{get;set;}
     public List<asset> assetList{get;set;}
     public List<cscfga__Attribute__c> attributes{get;set;}
     public List<String> ListOfFields{get;set;}
     public List<String> ListOfAttRecords{get;set;}
   
     
    @TestVisible
    private final Case cs { get; set; }

    
    public csord__Solution__c solutionObject { get; set; }

    public String caseRecordType { get; set; }
    public boolean caseClosed {get;set;}
   // @TestVisible
   // public List<ProvisioningDetails> provisioningDetails { get; set; }
        
         //Get Service records    
     //Get Service records    
    ApexPages.StandardController stdController;
    
    LG_SConsoleProvisionOneDetailsExtension lgsc = new LG_SConsoleProvisionOneDetailsExtension(stdController);
    List<csord__Service__c> csord_ServiceRecords = lgsc.getServiceRecords();
    
    //solObject = lgsc.getSolutionRecord();
     PageReference pr = lgsc.Save();
     PageReference prEdit = lgsc.Edit();
     PageReference prCancel = lgsc.Cancel();
     PageReference prPage = lgsc.PageRefresh();
    String address = lgsc.FrameAddressInFormat('25', 'Jerus', 'New York','USA', '712345');
     
     Asset ast = lgsc.getBDSServiceAsset();
     //csord__Solution__c solutionObject = lgsc.getSolutionRecord();
    // lgsc.getAssetRecord();
   LG_SConsoleProvisionOneDetailsExtension.ProvisioningDetails provDetails = new LG_SConsoleProvisionOneDetailsExtension.ProvisioningDetails('Provision One Step',bdsService);
   
   //lgsc.provisioningDetails = provDetails.getProvisioningDetails();
   
    public csord__Solution__c getSolution() {
        if (this.solutionObject == null) {
            this.solutionObject = getSolutionRecord();
        }

        return this.solutionObject;
    }



  private csord__Solution__c getSolutionRecord() {
        csord__Solution__c solution;
        List<csord__Solution__c> solutionList = new List<csord__Solution__c>();
         List<csord__Solution__c> solutionList1 = new List<csord__Solution__c>();
        Id solId = this.cs.LG_Solution__c;
        if (solId != null) {
            solutionList = [SELECT LG_Address__r.cscrm__State_Province__c,LG_Address__r.LG_TechnicalContact__r.Phone,Id, LG_OneStepCase_Provisioning_Account_No__c,Name, LG_Address__c, csord__Account__c, csord__Order__c,
                   csord__Status__c, LG_Jeopardy__c, csordtelcoa__Product_Configuration__c, LG_JeopardyExplanation__c,
                   LG_ProvisioningWorkOrder__c,LG_ProvisioningAccountNo__c, LG_TargetDate__c, LG_EarliestInstallDate__c,
                   CreatedById, OwnerId, csord__Identification__c, csord__Order_Request__c, Jeopardy_Reason__c,
                   csord__Order__r.csordtelcoa__Opportunity__c, csord__Order__r.csordtelcoa__Opportunity__r.csordtelcoa__Change_Type__c, csord__Order__r.csord__Account__c,
                   LG_Address__r.cscrm__Country__c, LG_Address__r.LG_TechnicalContact__c,LG_Address__r.LG_FullAddressDetails__c,LG_Address__r.LG_Icomms_Premise_ID__c, LG_Address__r.LG_Icomms_Site_ID__c,
                   csord__Order__r.csord__Account__r.LG_Huawei_Tenant_ID__c
                   FROM csord__Solution__c WHERE Id = :this.cs.LG_Solution__c];
        }

        if(solutionList.size() > 0){
            solution = solutionList[0];
            //Removed as a part of SFOM-1748
            /*if (solution.LG_Jeopardy__c == true) {
                this.jeopardy = true;
            }*/
        }else {
            solution = new csord__Solution__c();
        }
                return solution;
    }
}