src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>LG_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Assets (Asset)</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_EndNumber__c</fullName>
        <description>End Number of the Number Range</description>
        <label>End Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>LG_NumberRangeType__c</fullName>
        <label>Number Range Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Portin</fullName>
                </value>
                <value>
                    <fullName>Port-In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_PortInWishDate__c</fullName>
        <label>Port-In Wish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LG_StartNumber__c</fullName>
        <description>Starting Number of the Number Range</description>
        <label>Start Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_TelephonyService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Telephony Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Assets (Telephony Service)</relationshipLabel>
        <relationshipName>LG_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>LG_Suborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services (Suborder)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_AnyNumbersToPort__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Any Numbers to Port</label>
        <type>Checkbox</type>
    </fields>
    
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Subscription.</description>
        <inlineHelpText>The parent Solution of this Subscription.</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSPOFA__Orchestration_Process__c.object
<CustomObject>
    <fields>
        <fullName>CSPOFA__Orchestration_Process_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Orchestration Process Template</label>
        <referenceTo>CSPOFA__Orchestration_Process_Template__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Service on which process instance was invoked</description>
        <inlineHelpText>Lookup to the Service on which process instance was invoked</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_AssetProcessAssociation__c.object
<CustomObject>
    <fields>
        <fullName>LG_Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Asset Process Associations</relationshipLabel>
        <relationshipName>Asset_Process_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LG_Process__c</fullName>
        <label>Process</label>
        <referenceTo>LG_PortingProcess__c</referenceTo>
        <relationshipLabel>Asset Process Associations</relationshipLabel>
        <relationshipName>Asset_Process_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Process Association</label>
    <nameField>
        <label>Asset Process Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Process Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LG_PortingProcess__c.object
<CustomObject>
    <fields>
        <fullName>LG_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Porting Processes</relationshipLabel>
        <relationshipName>Porting_Processes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_PortInWishDate__c</fullName>
        <label>Port-In Wish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LG_Response__c</fullName>
        <label>Response</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ZWA</fullName>
                </value>
                <value>
                    <fullName>NAT</fullName>
                </value>
                <value>
                    <fullName>Terminverschiebung OK</fullName>
                </value>
                <value>
                    <fullName>Storno OK</fullName>
                </value>
                <value>
                    <fullName>RNG</fullName>
                </value>
                <value>
                    <fullName>ADFPLZ</fullName>
                </value>
                <value>
                    <fullName>ADFORT</fullName>
                </value>
                <value>
                    <fullName>ADFSTR</fullName>
                </value>
                <value>
                    <fullName>ADFHSNR</fullName>
                </value>
                <value>
                    <fullName>AIF</fullName>
                </value>
                <value>
                    <fullName>WAI</fullName>
                </value>
                <value>
                    <fullName>KNI</fullName>
                </value>
                <value>
                    <fullName>VAE</fullName>
                </value>
                <value>
                    <fullName>Projektkenner unbekannt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Porting Process</label>
    <nameField>
        <label>Porting Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porting Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_ProcessRequest__c.object
<CustomObject>
    <fields>
        <fullName>LG_Process__c</fullName>
        <label>Process</label>
        <referenceTo>LG_PortingProcess__c</referenceTo>
        <relationshipLabel>Process Requests</relationshipLabel>
        <relationshipName>Process_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LG_Response__c</fullName>
        <label>Response</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LG_ProcessResponseStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Process Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Process Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/LG_ProcessResponseStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
    </customValue>
    <masterLabel>Process Response Status</masterLabel>
</GlobalValueSet>

src/classes/LG_AnalyseNumberPortingTest.cls
/**
 * Check if there are any number to port
 *
 * Scans all numbers under this Solution. If there are any numbers that
 * still require porting, set the Any Numbers to Port to True and also update the
 * Earliest and Latest porting dates if needed.
 *
 * @param  Set<Id> processesIds
 * @author Petar Miletic
 * @ticket SFOM-193, replaces (SFOM-190, SFOM-194)
 * @since  03/02/2017
*/
@IsTest
public class LG_AnalyseNumberPortingTest {

	@testsetup
	private static void setupTestData() {

        No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
        noTriggers.Flag__c = true;
        noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
        upsert noTriggers;

	    // Create record types
	    RecordType numberBlockRecordType = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Asset' AND Name = 'Number Block'];
		RecordType phoneNumberRecordType = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Asset' AND Name = 'Phone Number'];


		Account acc = new Account(Name = 'TestAcc');
		insert acc;

		// Solution
		csord__Solution__c sol = new csord__Solution__c(Name = 'Test Solution', LG_AnyNumbersToPort__c = false, csord__Identification__c = '6465467985');
		insert sol;

		// Subscripton
		csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = '6465467986');
		insert sub;

		// Service
		csord__Service__c service = new csord__Service__c(csord__Subscription__c = sub.Id, LG_Suborder__c = sol.Id, csord__Identification__c = '6465467987');
		insert service;

        List<Asset> assets = new List<Asset>();

        // Top level asset (number block)
        Asset topAssetFirst = new Asset(Name = 'Asset_0', AccountId = acc.Id, LG_NumberRangeType__c = 'Portin', RecordTypeId = numberBlockRecordType.Id, LG_TelephonyService__c = service.Id,
									    LG_StartNumber__c = '000', LG_EndNumber__c = '004', LG_PortInWishDate__c = Date.today().addDays(-5));
        insert topAssetFirst;
        
        Asset topAssetSecond = new Asset(Name = 'Asset_0', AccountId = acc.Id, LG_NumberRangeType__c = 'Portin', RecordTypeId = numberBlockRecordType.Id, LG_TelephonyService__c = service.Id,
									    LG_StartNumber__c = '000', LG_EndNumber__c = '004', LG_PortInWishDate__c = Date.today().addDays(4));
        insert topAssetSecond;
        
        for (Integer i = 1; i < 6; i++) {

            Asset obj = new Asset(Name = 'Asset_' + i, AccountId = acc.Id);

            obj.LG_NumberRangeType__c = 'Portin';
            obj.RecordTypeId = phoneNumberRecordType.Id;
            obj.LG_TelephonyService__c = service.Id;

            if (math.mod(i, 2) == 0) {
                obj.LG_Asset__c = topAssetSecond.Id;
            }
            else {
                obj.LG_Asset__c = topAssetFirst.Id;
            }

            assets.add(obj);
        }

        insert assets;

        // Insert process
        LG_PortingProcess__c pProcess = new LG_PortingProcess__c();
        pProcess.LG_Account__c = acc.Id;
        insert pProcess;
        
        LG_ProcessRequest__c request = new LG_ProcessRequest__c();
        request.LG_Process__c = pProcess.Id;
        request.LG_Response__c = 'Success';
        insert request;

        Datetime yesterday = Datetime.now().addDays(-1);
        Test.setCreatedDate(request.Id, yesterday);

        LG_ProcessRequest__c request2 = new LG_ProcessRequest__c();
        request2.LG_Process__c = pProcess.Id;
        request2.LG_Response__c = 'Rejected';
        insert request2;

        List<LG_AssetProcessAssociation__c> assetAssociations = new List<LG_AssetProcessAssociation__c>();

        for (Asset obj :assets) {

            assetAssociations.add(new LG_AssetProcessAssociation__c( LG_Asset__c = obj.Id, LG_Process__c = pProcess.Id));
        }

        assetAssociations.add(new LG_AssetProcessAssociation__c( LG_Asset__c = topAssetFirst.Id, LG_Process__c = pProcess.Id));
        assetAssociations.add(new LG_AssetProcessAssociation__c( LG_Asset__c = topAssetSecond.Id, LG_Process__c = pProcess.Id));

        insert assetAssociations;

        // Orcestrator stuff
		CSPOFA__Orchestration_Process_Template__c orcTemplate = new CSPOFA__Orchestration_Process_Template__c();
		insert orcTemplate;

		CSPOFA__Orchestration_Process__c process = new CSPOFA__Orchestration_Process__c(CSPOFA__Orchestration_Process_Template__c = orcTemplate.Id, csordtelcoa__Service__c = service.Id, LG_Solution__c = sol.Id);
		insert process;

		CSPOFA__Orchestration_Step__c step = new CSPOFA__Orchestration_Step__c(CSPOFA__Orchestration_Process__c = process.Id);
		insert step;

        noTriggers.Flag__c = false;
        upsert noTriggers;
	}

    @isTest
    private static void processTest() {

		List<SObject> steps = [SELECT Id, CSPOFA__Orchestration_Process__c, CSPOFA__Status__c FROM CSPOFA__Orchestration_Step__c];

		for(SObject obj : steps) {

			CSPOFA__Orchestration_Step__c step = (CSPOFA__Orchestration_Step__c) obj;
			System.assertNotEquals('Complete', step.CSPOFA__Status__c, 'Status should not be complete');
		}

		Test.startTest();

		LG_AnalyseNumberPorting numberPorting = new LG_AnalyseNumberPorting();
		steps = numberPorting.process(steps);

		Test.stopTest();

		for(SObject obj : steps) {

			CSPOFA__Orchestration_Step__c step = (CSPOFA__Orchestration_Step__c) obj;
			System.assertEquals('Complete', step.CSPOFA__Status__c, 'Status should be complete');
		}
	}

    @isTest
	private static void checkNumberPortingFalseTest() {

		Map<Id, CSPOFA__Orchestration_Process__c> processMap = new Map<Id, CSPOFA__Orchestration_Process__c>([SELECT Id FROM CSPOFA__Orchestration_Process__c]);

        // Get solution object before
        csord__Solution__c solBefore = [SELECT ID, LG_AnyNumbersToPort__c, LG_EarliestPortingWishDate__c, LG_LatestPortingWishDate__c FROM csord__Solution__c WHERE Name = 'Test Solution' LIMIT 1];

		Test.startTest();

        LG_NumberPorting porting = new LG_NumberPorting();
		porting.checkNumberPorting(processMap.keySet());

		Test.stopTest();

        // Get solution object after
        csord__Solution__c solAfter = [SELECT ID, LG_AnyNumbersToPort__c, LG_EarliestPortingWishDate__c, LG_LatestPortingWishDate__c FROM csord__Solution__c WHERE Name = 'Test Solution' LIMIT 1];

        // Asert before state
        System.assertEquals(false, solBefore.LG_AnyNumbersToPort__c, 'Invalid Solution data (LG_AnyNumbersToPort__c)');
        System.assertEquals(null, solBefore.LG_EarliestPortingWishDate__c, 'Invalid Solution data (LG_EarliestPortingWishDate__c)');
        System.assertEquals(null, solBefore.LG_LatestPortingWishDate__c, 'Invalid Solution data (LG_LatestPortingWishDate__c)');

        // Asert after state
        System.assertEquals(true, solAfter.LG_AnyNumbersToPort__c, 'Invalid Solution data (LG_AnyNumbersToPort__c)');
        System.assertEquals(Date.today().addDays(-5), solAfter.LG_EarliestPortingWishDate__c, 'Invalid Solution data (LG_EarliestPortingWishDate__c)');
        System.assertEquals(Date.today().addDays(4), solAfter.LG_LatestPortingWishDate__c, 'Invalid Solution data (LG_LatestPortingWishDate__c)');
	}

	@isTest
	private static void checkNumberPortingTrueTest() {

		Map<Id, CSPOFA__Orchestration_Process__c> processMap = new Map<Id, CSPOFA__Orchestration_Process__c>([SELECT Id FROM CSPOFA__Orchestration_Process__c]);

        // Get solution object before
        csord__Solution__c solBefore = [SELECT ID, LG_AnyNumbersToPort__c, LG_EarliestPortingWishDate__c, LG_LatestPortingWishDate__c FROM csord__Solution__c WHERE Name = 'Test Solution' LIMIT 1];
        solBefore.LG_AnyNumbersToPort__c = true;
        update solBefore;

        LG_ProcessRequest__c req = [SELECT Id, LG_Response__c FROM LG_ProcessRequest__c WHERE LG_Response__c = 'Rejected' LIMIT 1];
        req.LG_Response__c = 'Success';
        update req;

		Test.startTest();

        LG_NumberPorting porting = new LG_NumberPorting();
		porting.checkNumberPorting(processMap.keySet());

		Test.stopTest();

        // Get solution object after
        csord__Solution__c solAfter = [SELECT ID, LG_AnyNumbersToPort__c, LG_EarliestPortingWishDate__c, LG_LatestPortingWishDate__c FROM csord__Solution__c WHERE Name = 'Test Solution' LIMIT 1];

        // Asert before state
        System.assertEquals(true, solBefore.LG_AnyNumbersToPort__c, 'Invalid Solution data (LG_AnyNumbersToPort__c)');
        System.assertEquals(null, solBefore.LG_EarliestPortingWishDate__c, 'Invalid Solution data (LG_EarliestPortingWishDate__c)');
        System.assertEquals(null, solBefore.LG_LatestPortingWishDate__c, 'Invalid Solution data (LG_LatestPortingWishDate__c)');

        // Asert after state
        System.assertEquals(false, solAfter.LG_AnyNumbersToPort__c, 'Invalid Solution data (LG_AnyNumbersToPort__c)');
	}
}