src/objects/Asset.object
<CustomObject>
    
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_EnvironmentVariables__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Storage of system variables and hard-coded IDs.</description>
    <fields>
        <fullName>LG_CloudSenceAnywhereIconID__c</fullName>
        <description>Document ID for &apos;Open Cloudsense Anywhere&apos; icon displayed on D2D page layouts.</description>
        <label>CloudSence Anywhere Icon ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_SalesforceBaseURL__c</fullName>
        <label>Salesforce Base URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LG_ServiceAvailabilityIconID__c</fullName>
        <description>Document ID for Service Availability icon displayed on D2D page layouts.</description>
        <label>Service Availability Icon ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_VisualForceBaseURL__c</fullName>
        <label>VisualForce Base URL</label>
        <type>Url</type>
    </fields>
    <label>Environment Variables</label>
</CustomObject>

src/objects/LG_NumberManagementSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the settings for Number Management.</description>
    <fields>
        <fullName>LG_BlockSizes__c</fullName>
        <defaultValue>&quot;1,10,100,1000&quot;</defaultValue>
        <description>Holds the CSV list of available Number Range Block Sizes (i.e. 1,10,100,1000).</description>
        <inlineHelpText>Holds the CSV list of available Number Range Block Sizes (i.e. 1,10,100,1000).</inlineHelpText>
        <label>Block Sizes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_BlockTypeAttribute__c</fullName>
        <description>Holds the name of the Block Type  (New, Port-In) Attribute of the (optional) Number Range Product Definition.</description>
        <inlineHelpText>Holds the name of the  Block Type  (New, Port-In) Attribute of the (optional) Number Range Product Definition.</inlineHelpText>
        <label>Block Type Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_EndNumberAttribute__c</fullName>
        <description>Holds the name of the End Number Attribute of the (optional) Number Range Product Definition.</description>
        <inlineHelpText>Holds the name of the End Number Attribute of the (optional) Number Range Product Definition.</inlineHelpText>
        <label>End Number Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_NewDetailsFieldSet__c</fullName>
        <description>Holds the name of the Asset objects field set used on the Capture Number Preferences page (and a controller) for additional new numbers details.</description>
        <label>New Details Field Set</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_NumberRangeAttribute__c</fullName>
        <description>Holds the name of the Number Range Attribute of the (optional) Number Range Product Definition.</description>
        <inlineHelpText>Holds the name of the Number Range Attribute of the (optional) Number Range Product Definition.</inlineHelpText>
        <label>Number Range Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_NumberRangeProdConfForNew__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, a number range product configuration for New numbers would be created (while creating the assets for numbers).</description>
        <inlineHelpText>If checked, a number range product configuration for New numbers would be created (while creating the assets for numbers).</inlineHelpText>
        <label>Number Range Prod.Conf. for New</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_NumberRangeProdConfForPortIn__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, a number range product configuration for Port-In numbers would be created (while creating the assets for numbers).</description>
        <inlineHelpText>If checked, a number range product configuration for Port-In numbers would be created (while creating the assets for numbers).</inlineHelpText>
        <label>Number Range Prod.Conf. for Port-In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_NumberRangeProductDefinitionName__c</fullName>
        <description>Number Range Product Configuration&apos;s Product Definition Name</description>
        <inlineHelpText>Number Range Product Configuration&apos;s Product Definition Name</inlineHelpText>
        <label>Number Range Product Definition Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PortInDetailsFieldSet__c</fullName>
        <description>Holds the name of the Asset objects field set used on the Capture Number Preferences page (and a controller).</description>
        <label>Port In Details Field Set</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PortInOperators__c</fullName>
        <description>Holds the name of a specific global picklist that holds the list of Port In Operators - currently a CSV list</description>
        <inlineHelpText>Holds the name of a specific global picklist that holds the list of Port In Operators - currently a CSV list</inlineHelpText>
        <label>Port-In Operators</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_RequireDetailsForNew__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If unchecked, validations won&apos;t be fired for new number blocks during sales process. Only Number Block Type (New or Port In) and Number Block Size fields will be required.</description>
        <inlineHelpText>If unchecked, validations won&apos;t be fired for new number blocks during sales process. Only Number Block Type (New or Port In) and Number Block Size fields will be required.</inlineHelpText>
        <label>Require Details for New</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_RequireDetailsForPortIn__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If unchecked, validations won&apos;t be fired for port-in number blocks during sales process. Only Number Block Type (New or Port In) and Number Block Size fields will be required.</description>
        <inlineHelpText>If unchecked, validations won&apos;t be fired for port-in number blocks during sales process. Only Number Block Type (New or Port In) and Number Block Size fields will be required.</inlineHelpText>
        <label>Require Details for Port In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_SizeAttribute__c</fullName>
        <description>Holds the name of the Size Attribute of the (optional) Number Range Product Definition.</description>
        <inlineHelpText>Holds the name of the Size Attribute of the (optional) Number Range Product Definition.</inlineHelpText>
        <label>Size Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_StartNumberAttribute__c</fullName>
        <description>Holds the name of the Start Number Attribute of the (optional) Number Range Product Definition.</description>
        <inlineHelpText>Holds the name of the Start Number Attribute of the (optional) Number Range Product Definition.</inlineHelpText>
        <label>Start Number Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_TelephonyNumberRangeAttribute__c</fullName>
        <description>Holds the name of the Number Range attribute of the Telephony product definition. This attribute is a related product attribute.</description>
        <inlineHelpText>Holds the name of the Number Range attribute of the Telephony product definition. This attribute is a related product attribute.</inlineHelpText>
        <label>Telephony Number Range Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Number Management Settings</label>
</CustomObject>

src/classes/CustomButtonNumberManagementTest.cls
@isTest
private class CustomButtonNumberManagementTest {

	private static String vfBaseUrl   = 'vforce.url';
	private static String sfdcBaseUrl = 'sfdc.url';

	@testsetup
	private static void setupTestData()
	{
		No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
		noTriggers.Flag__c      = true;
		noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
		upsert noTriggers;

		LG_NumberManagementSettings__c mngSettings = new LG_NumberManagementSettings__c();
		mngSettings.LG_BlockSizes__c                       = '1,10,100';
		mngSettings.LG_NumberRangeProdConfForNew__c        = true;
		mngSettings.LG_NumberRangeProdConfForPortIn__c     = true;
		mngSettings.LG_NumberRangeProductDefinitionName__c = 'Number Range';
		mngSettings.LG_TelephonyNumberRangeAttribute__c    = 'Number Ranges';
		mngSettings.LG_BlockTypeAttribute__c               = 'Block Type';
		mngSettings.LG_EndNumberAttribute__c               = 'End Number';
		mngSettings.LG_NumberRangeAttribute__c             = 'Number Range';
		mngSettings.LG_SizeAttribute__c                    = 'Size';
		mngSettings.LG_StartNumberAttribute__c             = 'Start Number';
		mngSettings.LG_PortInOperators__c                  = 'BT,KPN';
		mngSettings.LG_RequireDetailsForNew__c             = true;
		mngSettings.LG_RequireDetailsForPortIn__c          = true;
		if (!Schema.SObjectType.Asset.fieldSets.getMap().isEmpty()) {
			String fieldSetName = '';
			for (String key : Schema.SObjectType.Asset.fieldSets.getMap().keySet()) {
				fieldSetName = key;
				break;
			}
			mngSettings.LG_PortInDetailsFieldSet__c = fieldSetName;
			mngSettings.LG_NewDetailsFieldSet__c    = fieldSetName;
		}
		insert mngSettings;

		LG_EnvironmentVariables__c envVariables = new LG_EnvironmentVariables__c();
		envVariables.LG_SalesforceBaseURL__c         = sfdcBaseUrl;
		envVariables.LG_VisualForceBaseURL__c        = vfBaseUrl;
		envVariables.LG_CloudSenceAnywhereIconID__c  = 'csaID';
		envVariables.LG_ServiceAvailabilityIconID__c = 'saIconId';
		insert envVariables;

		Account account = LG_GeneralTest.CreateAccount('Account', '12345678', 'Ziggo', true);

		Opportunity opp = LG_GeneralTest.CreateOpportunity(account, true);

		csord__Order_Request__c coreq = new csord__Order_Request__c(csord__Module_Name__c = 'Test Service Req', csord__Module_Version__c = '1.0');
		insert coreq;

		csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = 'IdentSub');
		insert sub;

		csord__Service__c service = new csord__Service__c(csord__Identification__c = 'Telephony Service', csord__Order_Request__c = coreq.Id, csord__Subscription__c = sub.Id);
		insert service;

		cscfga__Product_Basket__c basket = LG_GeneralTest.createProductBasket('Basket', account, null, opp, false);
		basket.csbb__Account__c = account.Id;
		insert basket;

		cscfga__Product_Definition__c telephonyProdDef   = LG_GeneralTest.createProductDefinition('Telephony', true);
		cscfga__Product_Definition__c prodDefNumberRange = LG_GeneralTest.createProductDefinition('Number Range', true);


		cscfga__Product_Configuration__c telephonyProdConf   = LG_GeneralTest.createProductConfiguration('Telephony', 3, basket, telephonyProdDef, true);
		cscfga__Product_Configuration__c numberRangeProdConf = LG_GeneralTest.createProductConfiguration('Number Range', 3, basket, prodDefNumberRange, true);

		cscfga__Attribute_Definition__c attDef = LG_GeneralTest.createAttributeDefinition('Number Ranges', telephonyProdDef, 'Related Product', 'String',
																						  null, null, null, true);
		LG_GeneralTest.createAttributeDefinition('Block Type', prodDefNumberRange, 'User Input', 'String', null, null, null, true);
		LG_GeneralTest.createAttributeDefinition('End Number', prodDefNumberRange, 'User Input', 'String', null, null, null, true);
		LG_GeneralTest.createAttributeDefinition('Number Range', prodDefNumberRange, 'User Input', 'String', null, null, null, true);
		LG_GeneralTest.createAttributeDefinition('Size', prodDefNumberRange, 'User Input', 'String', null, null, null, true);
		LG_GeneralTest.createAttributeDefinition('Start Number', prodDefNumberRange, 'User Input', 'String', null, null, null, true);

		LG_GeneralTest.createAttribute('Number Ranges', attDef, false, null, telephonyProdConf, false, numberRangeProdConf.Id, true);

		Id numberBlockRTId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Number Block').getRecordTypeId();
		Id phoneNumberRTId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Phone Number').getRecordTypeId();

		Asset numberBlock = new Asset();
		numberBlock.Name                                  = '090123';
		numberBlock.AccountId                             = account.Id;
		numberBlock.RecordTypeId                          = numberBlockRTId;
		numberBlock.LG_EndNumber__c                       = '090123';
		numberBlock.LG_NumberRange__c                     = '090123';
		numberBlock.LG_NumberRangeSize__c                 = Decimal.valueOf('1');
		numberBlock.LG_NumberRangeType__c                 = 'New';
		numberBlock.LG_StartNumber__c                     = '090123';
		numberBlock.LG_TelephonyProductConfiguration__c   = telephonyProdConf.Id;
		numberBlock.LG_NumberRangeProductConfiguration__c = numberRangeProdConf.Id;
		numberBlock.LG_TelephonyService__c                = service.Id;
		insert numberBlock;

		Asset numberAsset = new Asset();
		numberAsset.Name                                  = '090123';
		numberAsset.AccountId                             = account.Id;
		numberAsset.LG_Asset__c                           = numberBlock.Id;
		numberAsset.RecordTypeId                          = phoneNumberRTId;
		numberAsset.LG_PhoneNumber__c                     = '090123';
		numberAsset.LG_NumberRangeType__c                 = 'New';
		numberAsset.LG_TelephonyProductConfiguration__c   = telephonyProdConf.Id;
		numberAsset.LG_NumberRangeProductConfiguration__c = numberRangeProdConf.Id;
		insert numberAsset;

		noTriggers.Flag__c = false;
		upsert noTriggers;
	}

	private static testmethod void testPerformActionSuccess()
	{
		cscfga__Product_Basket__c basket = [SELECT Id FROM cscfga__Product_Basket__c];

		Test.startTest();
		CustomButtonNumberManagement cstBtn = new CustomButtonNumberManagement();
		String performActionResult          = cstBtn.performAction(basket.Id);
		Test.stopTest();

		System.assertEquals('{"status":"ok","redirectURL":"' + sfdcBaseUrl
							+ '/apex/LG_NumberManagement?id=' + basket.Id + '"}',
							performActionResult, 'result should match');
	}

	private static testmethod void testError()
	{
		cscfga__Product_Basket__c basket = [SELECT Id FROM cscfga__Product_Basket__c];

		delete [SELECT Id FROM cscfga__Product_Configuration__c WHERE cscfga__Product_Basket__c = : basket.Id];

		Test.startTest();
		CustomButtonNumberManagement cstBtn = new CustomButtonNumberManagement();
		String performActionResult          = cstBtn.performAction(basket.Id);
		Test.stopTest();

		System.assertEquals(CustomButtonNumberManagement.errorMsg,
							performActionResult, 'result should match');
	}
}