src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>LG_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Assets (Asset)</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_EndNumber__c</fullName>
        <description>End Number of the Number Range</description>
        <label>End Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>LG_NumberRangeSize__c</fullName>
        <label>Number Range Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_NumberRangeType__c</fullName>
        <label>Number Range Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Portin</fullName>
                </value>
                <value>
                    <fullName>Port-In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_NumberRange__c</fullName>
        <label>Number Range</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PortInWishDate__c</fullName>
        <label>Port-In Wish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LG_StartNumber__c</fullName>
        <description>Starting Number of the Number Range</description>
        <label>Start Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_TelephonyService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Telephony Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Assets (Telephony Service)</relationshipLabel>
        <relationshipName>LG_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent of this asset.</description>
        <inlineHelpText>The parent of this asset. Only one of Order, OrderLineItem, Service or ServiceLineItem can be filled in for any asset.</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Salesforce Assets</relationshipLabel>
        <relationshipName>Salesforce_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Basket__c.object
<CustomObject>
    <description>Basket to supercede bundles...</description>
    <fields>
        <fullName>csbb__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Baskets</relationshipLabel>
        <relationshipName>Product_Baskets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Basket</label>
    <nameField>
        <label>Product Basket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Baskets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>LG_Suborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services (Suborder)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Subscription.</description>
        <inlineHelpText>The parent Solution of this Subscription.</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSPOFA__Orchestration_Process__c.object
<CustomObject>
    <fields>
        <fullName>CSPOFA__Orchestration_Process_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Orchestration Process Template</label>
        <referenceTo>CSPOFA__Orchestration_Process_Template__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_AssetProcessAssociation__c.object
<CustomObject>
    <fields>
        <fullName>LG_Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Asset Process Associations</relationshipLabel>
        <relationshipName>Asset_Process_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LG_Process__c</fullName>
        <label>Process</label>
        <referenceTo>LG_PortingProcess__c</referenceTo>
        <relationshipLabel>Asset Process Associations</relationshipLabel>
        <relationshipName>Asset_Process_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset Process Association</label>
    <nameField>
        <label>Asset Process Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Process Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LG_PortingProcess__c.object
<CustomObject>
    <fields>
        <fullName>LG_PortInWishDate__c</fullName>
        <label>Port-In Wish Date</label>
        <type>Date</type>
    </fields>
    <label>Porting Process</label>
    <nameField>
        <label>Porting Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porting Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_ProcessRequest__c.object
<CustomObject>
    <fields>
        <fullName>LG_Process__c</fullName>
        <label>Process</label>
        <referenceTo>LG_PortingProcess__c</referenceTo>
        <relationshipLabel>Process Requests</relationshipLabel>
        <relationshipName>Process_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Process Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Process Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LG_AnyNumberPortReqsStepTest.cls
@isTest
private class LG_AnyNumberPortReqsStepTest {

    @testsetup
    private static void setupTestData()
    {
        No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
        noTriggers.Flag__c      = true;
        noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
        upsert noTriggers;

        Account account = LG_GeneralTest.CreateAccount('Account', '12345678', 'Ziggo', true);

        Opportunity opp = LG_GeneralTest.CreateOpportunity(account, true);

        csord__Solution__c solutionWithNumberPort = new csord__Solution__c(Name = 'testSolNmbrPort',
                                                                           csord__Identification__c = 'testsol');
        insert solutionWithNumberPort;

        csord__Solution__c solutionWoNumberPort = new csord__Solution__c(Name = 'testSolWoNmbrPort',
                                                                         csord__Identification__c = 'testsol');
        insert solutionWoNumberPort;

        cscfga__Product_Basket__c basket = LG_GeneralTest.createProductBasket('Basket', account, null, opp, false);
        basket.csbb__Account__c = account.Id;
        insert basket;

        csord__Order_Request__c coreq = new csord__Order_Request__c(csord__Module_Name__c = 'Test', csord__Module_Version__c = '1.0');
        insert coreq;

        csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = 'TestIdent', csord__Order_Request__c = coreq.Id);
        insert sub;

        csord__Service__c telephonyService = new csord__Service__c(csord__Identification__c = 'TestTelServ', csord__Order_Request__c = coreq.Id, LG_Suborder__c = solutionWithNumberPort.Id,
                                                                   csord__Subscription__c = sub.Id);
        insert telephonyService;

        csord__Service__c telephonyServiceWoNumberPort = new csord__Service__c(csord__Identification__c = 'TestTelServWoNmbr', csord__Order_Request__c = coreq.Id, LG_Suborder__c = solutionWoNumberPort.Id,
                                                                               csord__Subscription__c = sub.Id);
        insert telephonyServiceWoNumberPort;

        Id numberBlockRTId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Number Block').getRecordTypeId();

        Asset numberBlock = new Asset();
        numberBlock.Name                   = '090123';
        numberBlock.AccountId              = account.Id;
        numberBlock.RecordTypeId           = numberBlockRTId;
        numberBlock.LG_EndNumber__c        = '090123';
        numberBlock.LG_NumberRange__c      = '090123';
        numberBlock.LG_NumberRangeSize__c  = Decimal.valueOf('1');
        numberBlock.LG_NumberRangeType__c  = 'Port-In';
        numberBlock.LG_StartNumber__c      = '090123';
        numberBlock.LG_PortInWishDate__c   = Date.newInstance(2017, 2, 17);
        numberBlock.LG_TelephonyService__c = telephonyService.Id;
        insert numberBlock;

        Asset numberBlockWoNmbrPort = new Asset();
        numberBlockWoNmbrPort.Name                   = '090123';
        numberBlockWoNmbrPort.AccountId              = account.Id;
        numberBlockWoNmbrPort.RecordTypeId           = numberBlockRTId;
        numberBlockWoNmbrPort.LG_EndNumber__c        = '090123';
        numberBlockWoNmbrPort.LG_NumberRange__c      = '090123';
        numberBlockWoNmbrPort.LG_NumberRangeSize__c  = Decimal.valueOf('1');
        numberBlockWoNmbrPort.LG_NumberRangeType__c  = 'Port-In';
        numberBlockWoNmbrPort.LG_StartNumber__c      = '090123';
        numberBlockWoNmbrPort.LG_PortInWishDate__c   = Date.newInstance(2017, 2, 17);
        numberBlockWoNmbrPort.LG_TelephonyService__c = telephonyServiceWoNumberPort.Id;
        insert numberBlockWoNmbrPort;

        CSPOFA__Orchestration_Process_Template__c orcTemplate = new CSPOFA__Orchestration_Process_Template__c();
        insert orcTemplate;

        List<CSPOFA__Orchestration_Process__c> processes = new List<CSPOFA__Orchestration_Process__c>();
        CSPOFA__Orchestration_Process__c processNmbrPort = new CSPOFA__Orchestration_Process__c(CSPOFA__Orchestration_Process_Template__c = orcTemplate.Id,
                                                                                                LG_Solution__c = solutionWithNumberPort.Id);
        CSPOFA__Orchestration_Process__c processWoNmbrPort = new CSPOFA__Orchestration_Process__c(CSPOFA__Orchestration_Process_Template__c = orcTemplate.Id,
                                                                                                  LG_Solution__c = solutionWoNumberPort.Id);
        processes.add(processNmbrPort);
        processes.add(processWoNmbrPort);
        insert processes;

        List<CSPOFA__Orchestration_Step__c> steps = new List<CSPOFA__Orchestration_Step__c>();
        steps.add(new CSPOFA__Orchestration_Step__c(CSPOFA__Orchestration_Process__c = processNmbrPort.Id));
        steps.add(new CSPOFA__Orchestration_Step__c(CSPOFA__Orchestration_Process__c = processWoNmbrPort.Id));
        insert steps;

        LG_PortingProcess__c portProcess = new LG_PortingProcess__c();
        insert portProcess;

        LG_ProcessRequest__c portProcessReq = new LG_ProcessRequest__c(LG_Process__c = portProcess.Id);
        insert portProcessReq;

        LG_AssetProcessAssociation__c assWithPort = new LG_AssetProcessAssociation__c(LG_Process__c = portProcess.Id, LG_Asset__c = numberBlock.Id);
        insert assWithPort;

        LG_PortingProcess__c portProcessWoNumberPort = new LG_PortingProcess__c();
        insert portProcessWoNumberPort;

        LG_ProcessRequest__c portProcessReqWoNumberPort = new LG_ProcessRequest__c(LG_Process__c = portProcessWoNumberPort.Id, LG_Response__c = 'Rejected');
        insert portProcessReqWoNumberPort;

        LG_AssetProcessAssociation__c assWithoutPort = new LG_AssetProcessAssociation__c(LG_Process__c = portProcessWoNumberPort.Id, LG_Asset__c = numberBlockWoNmbrPort.Id);
        insert assWithoutPort;

        noTriggers.Flag__c = false;
        upsert noTriggers;
    }

    private static testmethod void testProcess()
    {
        List<SObject> steps = [SELECT Id, CSPOFA__Orchestration_Process__c, CSPOFA__Status__c FROM CSPOFA__Orchestration_Step__c];

        for (SObject obj : steps) {
            CSPOFA__Orchestration_Step__c step = (CSPOFA__Orchestration_Step__c) obj;
            System.assertNotEquals('Complete', step.CSPOFA__Status__c, 'Status should not be complete');
        }


        Test.startTest();
        LG_AnyNumberPortReqsStep checkNmbr = new LG_AnyNumberPortReqsStep();
        steps = checkNmbr.process(steps);
        Test.stopTest();

        for (SObject obj : steps) {
            CSPOFA__Orchestration_Step__c step = (CSPOFA__Orchestration_Step__c) obj;
            System.assertEquals('Complete', step.CSPOFA__Status__c, 'Status should be complete');
        }
    }

    private static testmethod void testCheckScheduleAppointment()
    {
        List<CSPOFA__Orchestration_Process__c> processes = [SELECT Id, LG_Solution__c,
                                                            LG_Solution__r.Name,
                                                            LG_Solution__r.LG_ProcessRequestsToCancel__c
                                                            FROM CSPOFA__Orchestration_Process__c
                                                            WHERE LG_Solution__c != null];

        Set<Id> processids = new Set<Id>();
        for (CSPOFA__Orchestration_Process__c process : processes) {
            processids.add(process.Id);
            System.assertEquals(false, process.LG_Solution__r.LG_ProcessRequestsToCancel__c, 'Process Requests to Cancel flag should be set to false');
        }

        Test.startTest();
        LG_AnyNumberPortReqsStep checkNmbr = new LG_AnyNumberPortReqsStep();
        checkNmbr.checkNumberPortRequests(processids);
        Test.stopTest();

        processes = [SELECT Id, LG_Solution__c,
                     LG_Solution__r.Name,
                     LG_Solution__r.LG_ProcessRequestsToCancel__c
                     FROM CSPOFA__Orchestration_Process__c];

        for (CSPOFA__Orchestration_Process__c process : processes) {
            if (process.LG_Solution__r.Name == 'testSolNmbrPort') {
                System.assertEquals(true, process.LG_Solution__r.LG_ProcessRequestsToCancel__c, 'Process Requests to Cancel flag should be set to true');
            } else if (process.LG_Solution__r.Name == 'testSolWoNmbrPort') {
                System.assertEquals(false, process.LG_Solution__r.LG_ProcessRequestsToCancel__c, 'Process Requests to Cancel flag should remain false');
            }
        }
    }
}