src/objects/B2B_Akana_Oath__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Access_Token__c</fullName>
        <label>Access Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token_Date__c</fullName>
        <label>Token Date</label>
        <type>DateTime</type>
    </fields>
    <label>Care Oath Authentication Akana</label>
</CustomObject>

src/objects/B2B_Care_Ext_Connections__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will contain all the records required for connecting external system   from salesforce.</description>
    <fields>
        <fullName>Connection_URL__c</fullName>
        <label>Connection URL</label>
        <type>Url</type>
    </fields>
    <label>Care Connections</label>
</CustomObject>

src/objects/Care_USMS_Connection__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will contain all the records required for connecting to USMS  system from salesforce.</description>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Care USMS Connection</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>LG_B2B_USMS_Categorization_Tier1__c</fullName>
        <label>Categorization Tier1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Connectivity</fullName>
                </value>
                <value>
                    <fullName>Performance</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_B2B_USMS_Categorization_Tier2__c</fullName>
        <label>Categorization Tier2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LG_B2B_USMS_Categorization_Tier1__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Signal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_B2B_USMS_Company__c</fullName>
        <label>Company</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_B2B_USMS_Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1-Extensive/Widespread</fullName>
                </value>
                <value>
                    <fullName>2-Significant/Large</fullName>
                </value>
                <value>
                    <fullName>3-Moderate/Limited</fullName>
                </value>
                <value>
                    <fullName>4-Minor/Localized</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_B2B_USMS_Service__c</fullName>
        <label>Service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ingress DE</fullName>
                </value>
                <value>
                    <fullName>IP Core Netcool Alarm DE</fullName>
                </value>
                <value>
                    <fullName>FBE Services DE</fullName>
                </value>
                <value>
                    <fullName>B2B VPN DE PROD</fullName>
                </value>
                <value>
                    <fullName>Internal Provisioning Service</fullName>
                </value>
                <value>
                    <fullName>HPBX PROD DE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_B2B_USMS_Urgency__c</fullName>
        <label>Urgency</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>csord__Service__c.csord__Subscription__r.csord__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>LG_B2B_CARE_USMS_Ticket_UM</fullName>
        <active>true</active>
        <businessProcess>USMS Ticket Care</businessProcess>
        <description>PLEASE DO NOT USE IT, CREATE A USMS TICKET FROM TECHNICAL CASE</description>
        <label>USMS Ticket</label>
    </recordTypes>
    <recordTypes>
        <fullName>LG_B2B_Care_Technical_Request_UM</fullName>
        <active>true</active>
        <businessProcess>B2B Care Enquiry</businessProcess>
        <description>Technical Case</description>
        <label>Technical Case</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
   
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>cscrm__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>LG_ProductFamily__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_ProductDescription__c</fullName>
        <label>Product Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_Care_USMS_SF_TO_USMS_Ticket_Test.cls
@isTest
public class LG_Care_USMS_SF_TO_USMS_Ticket_Test {
    
    static TestMethod void setUpMethod() {
        List<id> USMSId = new List<id>();
        try{
            User careAgent=LG_Care_TestRunAsUser.testRunAs();
            System.runAs(careAgent)
            {
                RecordType rt = [SELECT id,DeveloperName  FROM RecordType WHERE DeveloperName = 'LG_B2B_Care_Technical_Request_UM'];
                
                Account USMSAcc = New Account();
                USMSAcc.Name='USMS Test Account';
                Insert USMSAcc;
                
                Contact USMSCon= New Contact();
                USMSCon.LastName='USMS Test Contact';
                USMSCon.Email='rishi.kapoor@infosys.com';
                Insert USMSCon;
                
                csord__Subscription__c USMSSubs = new csord__Subscription__c();
                USMSSubs.Name='USMS Subs';
                USMSSubs.csord__Identification__c='101';
                Insert USMSSubs;
                
                cscrm__Address__c address = new cscrm__Address__c();
                address.cscrm__Zip_Postal_Code__c = '761104 abc 58';
                address.Name = 'Test Address';
                address.cscrm__Country__c='Germany';
                insert address;
                
                csord__Service__c USMSService = New  csord__Service__c();
                USMSService.Name='USMS Service';
                USMSService.LG_ProductFamily__c='internet';
                USMSService.UM_ProductDescription__c='High Speed Internet';
                USMSService.csord__Subscription__c=USMSSubs.id;
                USMSService.csord__Identification__c='102';
                USMSService.LG_Address__c=address.id;
                Insert USMSService;
                
                
                
                Case ParentCase = New Case();
                ParentCase.RecordTypeId=rt.id;
                ParentCase.Account=USMSAcc;
                ParentCase.Origin='Email';
                ParentCase.Contact=USMSCon;
                ParentCase.type='Service Down';
                ParentCase.Reason='Disabled';
                ParentCase.LG_Service__c=USMSService.id;
                ParentCase.Priority='P4';
                ParentCase.Subject='Test USMS';
                ParentCase.Description='Test USMS Medaliia';
                
                
                
                Insert ParentCase;
                
                Care_USMS_Connection__c USMSConn = new Care_USMS_Connection__c();
                USMSConn.Name='Germany';
                USMSConn.Company__c= 'Unity Media KB2';
                USMSConn.First_Name__c= 'SFDC';
                USMSConn.Last_Name__c= 'Interface';
                USMSConn.Source_System__c= 'SFDC';
                
                insert USMSConn;
                
                
                B2B_Akana_Oath__c USMSOath= new B2B_Akana_Oath__c ();
                USMSOath.Name='USMS Oath Akana';
                USMSOath.Access_Token__c='0AZT#$V%G$RESAWTTKVKAOZ!@23'; 
                USMSOath.Token_Date__c=system.today()+3;
                
                insert USMSOath;
                
                B2B_Care_Ext_Connections__c akana= new B2B_Care_Ext_Connections__c ();
                akana.Name='Aakana OFF Connection';
                akana.Connection_URL__c ='https://jit-api-libertyglobal-com.upc.biz/oauth/oauth20/token';
                
                insert akana;
                
                
                Case USMSCase = New Case();
                Recordtype Rtid=[Select id,developerName from Recordtype where DeveloperName = 'LG_B2B_CARE_USMS_Ticket_UM'];
                USMSCase.RecordtypeId=Rtid.id;
                USMSCase.LG_B2B_USMS_Categorization_Tier1__c='Connectivity';
                USMSCase.LG_B2B_USMS_Categorization_Tier2__c='Internet';
                USMSCase.LG_B2B_USMS_Company__c='Unity Media';
                USMSCase.Subject='Internet Connectivity is very slow';
                USMSCase.Description='Urgently fix the Internet Connectivity for the customer';
                //USMSCase.LG_B2B_USMS_Impact__c='1-Extensive/Widespread';
                USMSCase.LG_B2B_USMS_Urgency__c='High';
                USMSCase.LG_B2B_USMS_Service__c='Ingress DE';
                USMSCase.ParentId=ParentCase.Id;
                Insert USMSCase;
                
                
                
                
                USMSId.add(USMSCase.id);
                
                Test.startTest();
                
                Test.setMock(HttpCalloutMock.class, new LG_Care_USMS_MockHttpResponseGenerator());
                LG_Care_USMS_SF_TO_USMS_Ticket.CreateChildCase(USMSId);
                system.assertNotEquals(null,LG_Care_USMS_SF_TO_USMS_Ticket.createXml);
                Test.StopTest();
            }
        }
        
        catch(DMLException e) {
            system.assertEquals(e.getMessage(), e.getMessage());
        }
    }
}