src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>LG_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>csord__Service__c.csord__Subscription__r.csord__Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_accountID__c</fullName>
        <formula>Account.Company_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>account ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
   
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Product Definition from which this Configuration was derived.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscfga__Screen_Flow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used for associating a Screen Flow to the configuration. When editing Product Configuration associated Screen Flow will be displayed instead of regular Configuration Screen.</inlineHelpText>
        <label>Screen Flow</label>
        <referenceTo>cscfga__Screen_Flow__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>LG_FullAddressDetails__c</fullName>
        <formula>IF( ISBLANK(cscrm__Street__c) , &apos;&apos;, cscrm__Street__c) + 
IF( ISBLANK(LG_HouseNumber__c) , &apos;&apos;, &apos; &apos; + LG_HouseNumber__c) + 
IF( ISBLANK(LG_HouseNumberExtension__c) , &apos;&apos;, &apos; &apos; + LG_HouseNumberExtension__c + &apos;,&apos;) + 
IF( ISBLANK(cscrm__Zip_Postal_Code__c) , &apos;&apos;, &apos; &apos; + cscrm__Zip_Postal_Code__c) + 
IF( ISBLANK(cscrm__City__c) , &apos;&apos;, &apos; &apos; + cscrm__City__c) + 
IF( ISBLANK(cscrm__Country__c), &apos;&apos;, &apos;, &apos; + cscrm__Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Address Details</label>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Order</description>
        <inlineHelpText>The parent Solution of this Order</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Configuration lookup, basically 1:1 relationship, the lookup value is used only in Product Delivery typed orders</description>
        <inlineHelpText>Product Configuration lookup for Product Delivery typed orders</inlineHelpText>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>LG_ServiceStatus__c</fullName>
        <description>Pick-list to save the status of the service provisioning.</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                  <fullName>LG_SecondaryProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services (Secondary Product Configuration)</relationshipLabel>
        <relationshipName>Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Suborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services (Suborder)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Activation_Date__c</fullName>
        <description>The date of activation.</description>
        <inlineHelpText>The date of activation.</inlineHelpText>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Service.</description>
        <inlineHelpText>The parent Order of this Service.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Delta_Status__c</fullName>
        <label>Delta Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Continuing In Subscription</fullName>
                </value>
                <value>
                    <fullName>Added To Subscription</fullName>
                </value>
                <value>
                    <fullName>Deleted From Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_EarliestPortingWishDate__c</fullName>
        <label>Earliest porting wish date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LG_Jeopardy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Jeopardy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_LatestPortingWishDate__c</fullName>
        <label>Latest porting wish date</label>
        <type>Date</type>
    </fields>
    
    <fields>
        <fullName>LG_ProvisioningWorkOrder__c</fullName>
        <externalId>true</externalId>
        <label>Provisioning Work Order</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_TargetDate__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LG_Service__c</fullName>
        <label>services</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Solution.</description>
        <inlineHelpText>The parent Order of this Solution.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product configuration that initiated creation of this Solution</description>
        <inlineHelpText>Product configuration that initiated creation of this Solution</inlineHelpText>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_InflightConfigurationController.cls
global class LG_InflightConfigurationController {
    private final ApexPages.StandardController stdcontroller;
    public Case caseRecord {get ; set;}
    private RecordType recordType {get ; set;}
    private csord__Solution__c solution {get ; set ;}
    private List<csord__Service__c> services {get;set;}
    private csord__Service__c service {get;set;}
    private List<DisplayValues> displayValues {get;set;}
    private LG_ProductConfigurationUtil util {get;set;}

    private String getScreenFlowUri { get; private set; }
    private String getProductConfigurationId { get; private set; }

    public String productDefinition{get;set;}
    public id screenflowid {get;set;}

    public string cRecordType {get;set;}
    public String screenFlowPath {
       get {

       return '/apex/cscfga__ConfigureProduct?configId=' + getProductConfigurationId + this.getScreenFlowUri;


       }
    }


    public csord__Solution__c getRelatedSolution(){
        if(this.solution == null){
            populateRelatedSolution();
        }
        return this.solution;
    }
    public void populateRelatedSolution()
    {
        if(caseRecord.LG_Solution__c!=null){
            List<csord__Solution__c> solutionList= [select Id,
                             Name,
                             csord__Order__c,
                             LG_ProvisioningWorkOrder__c,
                             LG_Jeopardy__c,
                             LG_TargetDate__c,
                             LG_EarliestPortingWishDate__c,
                             LG_LatestPortingWishDate__c
                             from csord__Solution__c where Id=:caseRecord.LG_Solution__c LIMIT 1];
            if(!solutionList.isEmpty()){
                this.solution = solutionList.get(0);
            }
        }
    }

    public List<DisplayValues> getRelatedServices(){

        if(this.displayValues==null){
            populateRelatedServices();
        }system.debug('--top'+screenFlowPath );
        return displayValues;
    }

    /**
     * Updated field value of DisplayValues class (deltaStatus)
     *
     * @author Ankur Gupta
     * @story SFOM-647
     * @since 20/04/2017
    */
    public void populateRelatedServices(){
        List<Id> prodConfigIds = new List<Id>();
        displayValues = new List<displayValues>();
        if(this.services!=null)
        {
            for(csord__Service__c s : this.services){
                prodConfigIds.add(s.csordtelcoa__Product_Configuration__c);
                system.debug(s.csordtelcoa__Product_Configuration__c);
            }
            util = new LG_ProductConfigurationUtil(prodConfigIds);
            system.debug('Services '+ this.services);
            for(csord__Service__c s : this.services){

                String address = s.LG_Address__r.LG_FullAddressDetails__c;
                DisplayValues d = new DisplayValues();
                d.service = s;
                d.keyAttribute = util.getKeyAttributesPerProdConf(s.csordtelcoa__Product_Configuration__c);
                d.status = s.LG_ServiceStatus__c ;
                d.address = address;
                d.startDate = s.csord__Activation_Date__c;
                d.deltaStatus = s.csordtelcoa__Delta_Status__c;    //SFOM-647
                system.debug(s.csordtelcoa__Product_Configuration__c);
                productDefinition = s.csordtelcoa__Product_Configuration__r.cscfga__Product_Definition__r.Name;

                RecordType CRT = getCaseRecordType();
                cRecordType = CRT.Name;//String.valueOf(CRT);
                this.getScreenFlowUri = LG_Util.getScreenFlowFullName(cRecordType, productDefinition);
                this.getProductConfigurationId = s.csordtelcoa__Product_Configuration__c;

                cscfga__Screen_Flow__c screen= [select id from cscfga__Screen_Flow__c where Name=:cRecordType+' - '+productDefinition limit 1];
                //d.screenFlowUri = this.screenFlowPath;

                d.screenFlowUri='/'+screen.id;
                displayValues.add(d);
            }
        }
    }

    public RecordType getCaseRecordType(){
        if(this.recordType == null){
            populateCaseRecordType();
        }
        return this.recordType;
    }
    public void populateCaseRecordType(){
        if(this.caseRecord.RecordTypeId!=null){
        List<RecordType> recordTypeList = [select Id,
                           Name,
                           Description from RecordType where Id=:this.caseRecord.RecordTypeId];
            if(!recordTypeList.isEmpty()){
                this.recordType = recordTypeList.get(0);
            }
        }
    }


    @TestVisible
    private String FrameAddressInFormat(String hsNo, String street, String city, String country, String postalCode) {
        String address = '';

        if (hsNo != null && hsNo != '') {
            address = address + hsNo + ', ';
        }
        if (street != null && street != '') {
            address = address + street + ', ';
        }
        if (city != null && city != '') {
            address = address + city + ', ';
        }

        if (postalCode != null && postalCode != '') {
            address = address + postalCode + ', ';
        }

        if (country != null && country != '') {
            address = address + country;
        }

        return address;
    }

    /**
     * New field added to the query for services (csordtelcoa__Delta_Status__c)
     *
     * @author Ankur Gupta
     * @story SFOM-647
     * @since 20/04/2017
    */
    public LG_InflightConfigurationController(ApexPages.StandardController stdcontroller){
        this.stdcontroller = stdcontroller;
        if (!Test.isRunningTest())
        {
            List<String> defaultFields = new List<String>();
            defaultFields.add('LG_Service__c');
            defaultFields.add('LG_Solution__c');
            defaultFields.add('LG_Order__c');
            defaultFields.add('Id');
            defaultFields.add('CaseNumber');
            defaultFields.add('ContactId');
            defaultFields.add('AccountId');
            defaultFields.add('RecordTypeId');
            defaultFields.add('Type');
            defaultFields.add('Status');
            defaultFields.add('LG_AccountId__c');
            stdController.addFields(defaultFields);
            this.caseRecord = (Case)stdController.getRecord();
        } else{
            List<Case> caseList = [select Id,LG_Service__c,LG_Solution__c,LG_Order__c,CaseNumber,ContactId,AccountId,RecordTypeId,
                               Type,Status,LG_AccountId__c from Case where Id=:stdcontroller.getRecord().Id];
            if(!caseList.isEmpty()){
                this.caseRecord = caseList.get(0);
            }
        }
        if(this.caseRecord.LG_Service__c!=null)
        {
            List<csord__Service__c> serviceList = [select Id,
                                                Name,csord__Order__c,LG_Suborder__c,csordtelcoa__Product_Configuration__c,
                                                csord__Status__c,LG_ServiceStatus__c,csord__Activation_Date__c from csord__Service__c where LG_Suborder__c=:this.caseRecord.LG_Solution__c limit 1];
            if(!serviceList.isEmpty()){
                service = serviceList.get(0);
            }
        }
        this.solution = getRelatedSolution();
        //system.debug('Solution '+ this.solution.Id);
        if(this.solution!=null){
        this.services = [select Id,
                    Name,
                    csord__Order__c,
                    LG_Address__c,
                    LG_Address__r.Name,
                    LG_Address__r.LG_HouseNumber__c,
                    LG_Address__r.cscrm__Street__c,
                    LG_Address__r.cscrm__City__c,
                    LG_Address__r.cscrm__Zip_Postal_Code__c,
                    LG_Address__r.cscrm__Country__c,
                    LG_Address__r.LG_FullAddressDetails__c,
                    LG_Suborder__c,LG_ServiceStatus__c,
                    csordtelcoa__Product_Configuration__c,
                    csordtelcoa__Product_Configuration__r.cscfga__Product_Definition__r.Name,
                    csord__Status__c,
                    csordtelcoa__Delta_Status__c,  // SFOM-647
                    csord__Activation_Date__c from csord__Service__c where LG_Suborder__c=:this.solution.Id];
        }
    }

    /**
     * New field added to the clas (deltaStatus)
     *
     * @author Ankur Gupta
     * @story SFOM-647
     * @since 20/04/2017
    */
    public class DisplayValues{
        public csord__Service__c service {get;set;}
        public String keyAttribute {get;set;}
        public String status {get;set;}
        public String address {get;set;}
        public String screenFlowUri {get;set;}
        public string screenFlowPath{get;set;}
        public String deltaStatus{get;set;}    //SFOM-647
        public Date startDate {get;set;}
    }
}