src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSPOFA__Orchestration_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orchestration Step</label>
        <referenceTo>CSPOFA__Orchestration_Step__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
   
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>LG_InstallationNeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Installation Needed</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Activationneeded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activation Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_InstallationNeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Installation Needed</label>
        <type>Checkbox</type>
    </fields>
    
    <fields>
        <fullName>LG_Suborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services (Suborder)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_ActivationNeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If any of the related services requires activation, this field will be set to true</description>
        <label>Activation Needed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_InstallationNeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Installation Needed</label>
        <type>Checkbox</type>
    </fields>
    
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Solution in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product configuration that initiated creation of this Solution</description>
        <inlineHelpText>Product configuration that initiated creation of this Solution</inlineHelpText>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSPOFA__Orchestration_Process__c.object
<CustomObject>
    <fields>
        <fullName>CSPOFA__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initializing</fullName>
                    <default>true</default>
                    <label>Initializing</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Service on which process instance was invoked</description>
        <inlineHelpText>Lookup to the Service on which process instance was invoked</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_ScheduleAppointment__c.object
<CustomObject>
    <description>This object is used to capture the Appointment details during Order management orchestration process</description>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Schedule Appointment</relationshipLabel>
        <relationshipName>Schedule_Appointment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Schedule Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_RequiresInstallationOrActivation.cls
/**
 * Used as a custom orchestator step.
 * Check if Product requires installation/activtion and the appointment has not already been arranged
 * In that case Schedule Engineer Visit must be created (appointment object with appropriate appointment status)
 * 
 * @author Petar Miletic
 * @ticket SFOM-207
 * @since  21/12/2016
*/
global class LG_RequiresInstallationOrActivation implements CSPOFA.ExecutionHandler {

	public List<sObject> process(List<SObject> data)
	{
		List<sObject> result = new List<sObject>();

 		List<CSPOFA__Orchestration_Step__c> stepList = (List<CSPOFA__Orchestration_Step__c>)data;
				
		Set<Id> processesIds = new Set<Id>();
		for (CSPOFA__Orchestration_Step__c step : stepList)
		{
			processesIds.add(step.CSPOFA__Orchestration_Process__c);
		}
		
		// Check installation
		checkInstallationAndActivation(processesIds);
		
		for (CSPOFA__Orchestration_Step__c step : stepList)
		{
			//mark step Status, Completed Date
			step.CSPOFA__Status__c = 'Complete';
			step.CSPOFA__Completed_Date__c = Date.today();
			result.add(step);
		}

		return result;
	}
	
	/*
	 * Check if Product requires installation/activtion and the appointment has not already been arranged
	 * In that case Schedule Engineer Visit must be created (appointment object with appropriate appointment status)
	*/
	@TestVisible
    private void checkInstallationAndActivation(Set<Id> processesIds) {
        
        Set<Id> serviceIds = new Set<Id>();

		// Get all Service Ids associated with the processes
		for(CSPOFA__Orchestration_Process__c process : [SELECT Id, csordtelcoa__Service__c, LG_Solution__c
		                                                FROM CSPOFA__Orchestration_Process__c 
		                                                WHERE Id IN :processesIds AND LG_Solution__c != null]) 
        {
			serviceIds.add(process.csordtelcoa__Service__c);
		}

        // Get only relevant services
        List<csord__Service__c> services = [SELECT Id, Name, LG_Suborder__c, LG_Suborder__r.Name, 
                                                csordtelcoa__Product_Configuration__r.LG_InstallationNeeded__c
                                                FROM csord__Service__c 
                                                WHERE Id IN :serviceIds 
                                                AND LG_Suborder__r.LG_ActivationNeeded__c = true 
                                                AND csordtelcoa__Product_Configuration__r.LG_InstallationNeeded__c = true];
                                                // TO DD
                                                // LG_ActivationNeeded__c is located on the definition
                                                // service -> Activation Needed, Installation needed
		
        if (services.isEmpty()) {
            return;
        }
        
        Map<Id, csord__Solution__c> solutions = new Map<Id, csord__Solution__c>();
        
        // Get all solutions and set status in advance
        for (csord__Service__c service :services) {
            
            csord__Solution__c sol = service.LG_Suborder__r;
            sol.csord__Status__c = 'Schedule Appointment required!';
            // TO DD
            // Add new field schedule appointment
            
            solutions.put(sol.Id, sol);
        }

		// TO DD
		// Statuses are still undefined (we need to check if it is in correct Status)
        // Filter out all solutions that allready have shceduled appointments
        List<LG_ScheduleAppointment__c> appointments = [SELECT Id, LG_Solution__c, LG_Solution__r.csord__Status__c FROM LG_ScheduleAppointment__c WHERE LG_Solution__c IN :solutions.keySet()];
        
        List<csord__Solution__c> solutionsUpdate = new List<csord__Solution__c>();
        
        // Check Solutions that allready have appoint assigned and remove them from update list
        for (LG_ScheduleAppointment__c app :appointments) {
            
            if (solutions.containsKey(app.LG_Solution__c)) {
                
                solutions.remove(app.LG_Solution__c);
            }
        }
        
        // If all solutions have appointments then this list is empty, If not update
        if (!solutions.values().isEmpty()) {
             update solutions.values()  ;
        }
    }
}