src/objects/cscfga__Product_Basket__c.object
<CustomObject>
    <description>Basket to supercede bundles...</description>
    <fields>
        <fullName>cscfga__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Opportunity this Basket is associated with.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product Baskets</relationshipLabel>
        <relationshipName>Product_Baskets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Basket</label>
    <nameField>
        <label>Product Basket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Baskets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomButtonReturnToOpportunity.cls
global with sharing class CustomButtonReturnToOpportunity extends csbb.CustomButtonExt
{
    // Perform action implementation
    public String performAction(String basketId)
    {
        String newUrl = CustomButtonReturnToOpportunity.openOpportunity(basketId);
        return '{"status":"ok","redirectURL":"' + newUrl + '"}';
    }
    
    // Set url for redirect after action
    public static String openOpportunity(String basketId)
    {
        // Retrieve the basket
        cscfga__Product_Basket__c basket = [select id, name, cscfga__opportunity__c from cscfga__product_basket__c where id = :basketId];
        // Set page reference to the opportunity
        String baseUrl = '';
        if (UserInfo.getUserType() == 'Standard')
        {
            baseUrl = '/';
        }
        else if (UserInfo.getUserType() == 'PowerPartner')
        {
            baseUrl = '/partners/';
        }
       PageReference redirectPage = new PageReference(baseUrl + basket.cscfga__Opportunity__c);     
       return redirectPage.getUrl();
    }
}