src/objects/cscfga__Attribute__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Attribute_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Attribute Definition which describes this Attribute.</inlineHelpText>
        <label>Attribute Definition</label>
        <referenceTo>cscfga__Attribute_Definition__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Configuration__c</fullName>
        <inlineHelpText>The Product Configuration to which this Attribute belongs.</inlineHelpText>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cscfga__Attribute_Definition__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <inlineHelpText>The Product Definition to which this Attribute Definition belongs.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Attribute Definitions</relationshipLabel>
        <relationshipName>Attribute_Definitions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Basket__c.object
<CustomObject>
    <description>Basket to supercede bundles...</description>
    <label>Product Basket</label>
    <nameField>
        <label>Product Basket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Baskets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Basket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of associated Product Basket.</inlineHelpText>
        <label>Product Basket</label>
        <referenceTo>cscfga__Product_Basket__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Product Definition from which this Configuration was derived.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Definition__c.object
<CustomObject>
    <label>Product Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_Discount__c.object
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_OpportunityLineItemTriggerHandlerTest.cls
@isTest
public class LG_OpportunityLineItemTriggerHandlerTest 
{
    /*
    static testMethod void Test()
    {
        Account tmpAccount = LG_GeneralTest.CreateAccount('Test Acc');
        
        Opportunity tmpOpp = LG_GeneralTest.CreateOpportunity(tmpAccount);
        
        LG_Discount__c tmpDiscountAmountOff = LG_GeneralTest.createDiscount(10,'ABC123',3,'Discount Amount Off');
        
        cscfga__Product_Definition__c tmpProductDefinition = LG_GeneralTest.createProductDefinition('Internet');
        
        cscfga__Attribute_Definition__c tmpProductAttributeDefinitionTotal = LG_GeneralTest.createAttributeDefinition('Total Basic Price', tmpProductDefinition, 'Display Value');
        cscfga__Attribute_Definition__c tmpProductAttributeDefinitionDiscount = LG_GeneralTest.createAttributeDefinition('Discount', tmpProductDefinition, 'Lookup');
        cscfga__Attribute_Definition__c tmpProductAttributeDefinitionOneOff = LG_GeneralTest.createAttributeDefinition('Install', tmpProductDefinition, 'Display Value');
        
        cscfga__Attribute_Field_Definition__c tmpAttributeFieldDefinition = LG_GeneralTest.createAttributeFieldDefinition('Main','Yes',tmpProductAttributeDefinitionTotal);
        
        //not synced with Opp first
        cscfga__Product_Basket__c tmpProductBasket = LG_GeneralTest.createProductBasket('Basket', tmpAccount, tmpOpp, false);
        

        cscfga__Product_Configuration__c tmpProductConfiguration = LG_GeneralTest.createProductConfiguration('Internet', 12, tmpProductBasket, tmpProductDefinition);
        
        cscfga__Attribute__c tmpProductAttributeTotal = LG_GeneralTest.createAttribute('Total Basic Price',tmpProductAttributeDefinitionTotal,true,100,
            tmpProductConfiguration, true,'100');

        cscfga__Attribute__c tmpProductAttributeDiscount = LG_GeneralTest.createAttribute('Discount',tmpProductAttributeDefinitionDiscount,true,0,
            tmpProductConfiguration, false, string.valueOf(tmpDiscountAmountOff.Id));
            
        cscfga__Attribute__c tmpProductAttributeOneOff = LG_GeneralTest.createAttribute('Install',tmpProductAttributeDefinitionOneOff,true,10,
            tmpProductConfiguration, false,'10');
        
        
        No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
        noTriggers.Flag__c = false;
        noTriggers.SetupOwnerId = UserInfo.getUserId();
        upsert noTriggers;
         
        
        Synchronize controller = new Synchronize(new ApexPages.StandardController(tmpProductBasket));
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id', tmpProductBasket.Id);
        controller.SynchronizeRedirect();
        Test.stopTest();
        
            
    }
    */
}