src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>LG_PlanningDetailsStatus__c</fullName>
        <description>Planning Details Status</description>
        <inlineHelpText>Planning Details Status</inlineHelpText>
        <label>LG PlanningDetailsStatus</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Configuration_Status__c</fullName>
        <description>Describes if a configuration contains errors or not</description>
        <inlineHelpText>Status of the Product Configuration. Automatically set when Product Configuration is saved.</inlineHelpText>
        <label>Configuration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                    <default>true</default>
                    <label>Valid</label>
                </value>
                <value>
                    <fullName>Requires Update</fullName>
                </value>
                <value>
                    <fullName>Is Valid</fullName>
                </value>
                <value>
                    <fullName>Contains Errors or Incomplete</fullName>
                </value>
                <value>
                    <fullName>Contains Expired Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InstallationSiteDetailRemoterTest.cls
@isTest
public class InstallationSiteDetailRemoterTest{

    static testmethod void testProductConfiguration(){
        cscfga__Product_Configuration__c pc = new cscfga__Product_Configuration__c();
        pc.Name='testPCName';
        pc.LG_PlanningDetailsStatus__c='Complete';
        pc.cscfga__Configuration_Status__c ='Valid';
        insert pc;
        
        LG_InstallationInformationController obj = new LG_InstallationInformationController();
        InstallationSiteDetailRemoter cntrl = new InstallationSiteDetailRemoter(obj);
        InstallationSiteDetailRemoter.getProductConfigurations(pc.Id);  
        
                
    }

}