src/objects/cscfga__Attribute__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Attribute_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Attribute Definition which describes this Attribute.</inlineHelpText>
        <label>Attribute Definition</label>
        <referenceTo>cscfga__Attribute_Definition__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscfga__Display_Value__c</fullName>
        <inlineHelpText>The value of this Attribute displayed to the user during configuration. Only relevant to Select List or Radio Button type Attributes.</inlineHelpText>
        <label>Display Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Configuration__c</fullName>
        <inlineHelpText>The Product Configuration to which this Attribute belongs.</inlineHelpText>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>cscfga__Value__c</fullName>
        <inlineHelpText>The value of this Attribute captured during the configuration process.</inlineHelpText>
        <label>Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cscfga__Attribute_Definition__c.object
<CustomObject>
    <fields>
        <fullName>LG_KeyAttributeSequence__c</fullName>
        <description>The weight to be assigned to the Attribute when sorting key attributes for display. Only relevant to key attributes.</description>
        <inlineHelpText>The weight to be assigned to the Attribute when sorting key attributes for display. Only relevant to key attributes.</inlineHelpText>
        <label>Key Attribute Sequence</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_KeyAttribute__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, attribute will be considered as one of the key attributes, and will be used for presentation purposes on the UI.</description>
        <inlineHelpText>If checked, attribute will be considered as one of the key attributes, and will be used for presentation purposes on the UI.</inlineHelpText>
        <label>Key Attribute</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <inlineHelpText>The Product Definition to which this Attribute Definition belongs.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Attribute Definitions</relationshipLabel>
        <relationshipName>Attribute_Definitions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Product Definition from which this Configuration was derived.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Definition__c.object
<CustomObject>
    <label>Product Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_ProductConfigurationUtil.cls
/**
* Used as a utility class for Product Configurations.
* Using CS API retrieves all the data related to product configuration,
* including the attributes that are stored as JSON attachements.
*
* @author Tomislav Blazek
* @ticket SFOM-85
* @since  4/12/2016
*/
public class LG_ProductConfigurationUtil {

    private List<Id> prodConfIds;
    private Map<Id, List<KeyAttribute>> prodDefKeyAttsMap {
        set;
        get
        {
            if (prodDefKeyAttsMap == null)
            {
                populateProdDefKeyAttsMap();
            }
            return prodDefKeyAttsMap;
        }
    }
    private Map<Id, ProductConfiguration> prodConfsMap {
        set;
        get
        {
            if (prodConfsMap == null)
            {
                loadProductConfigurations();
            }
            return prodConfsMap;
        }
    }

    public LG_ProductConfigurationUtil(List<Id> prodConfIds)
    {
        this.prodConfIds = prodConfIds;
    }

    /**
     * Retrieves the product configurations data and returns
     * a map with Product Configuration Id as a key, and ProductConfiguration
     * object wrapper instance
     *
     * @author Tomislav Blazek
     * @ticket SFOM-85
     * @since  4/12/2016
     */
    public Map<Id, ProductConfiguration> getProductConfigurations()
    {
        return prodConfsMap;
    }

    /**
     * Retrieves the product configurations key attribute display values
     * sorted by key attribute sequence, and concatinated in one string.
     * For display/UI purpouses.
     *
     * @author Tomislav Blazek
     * @ticket SFOM-85
     * @since  4/12/2016
     */
    public String getKeyAttributesPerProdConf(Id prodConfId)
    {
        return prodConfsMap.get(prodConfId).keyAttributes;
    }

    /**
     * Loads the product configuration data using CS API.
     * Populates the ProductConfiguration wrapper objects, and the related
     * Attribute and AttributeFields wrapper objects.
     *
     * @author Tomislav Blazek
     * @ticket SFOM-85
     * @since  4/12/2016
     */
    private void loadProductConfigurations()
    {
        prodConfsMap = new Map<Id, ProductConfiguration>();

        Map<String, Object> mapProdConfs = cscfga.API_1.getProductConfigurations(prodConfIds);

        for (Id prodConfId : prodConfIds)
        {
            List<Attribute> atts = new List<Attribute>();
            List<cscfga__Attribute__c> attList = (List<cscfga__Attribute__c>)mapProdConfs.get(prodConfId + '-attributes');

            for (cscfga__Attribute__c att : attList)
            {
                List<cscfga__Attribute_Field__c> attFields = new List<cscfga__Attribute_Field__c>();
                if (mapProdConfs.containsKey(prodConfId + '-' + att.cscfga__Attribute_Definition__c + '-attributeFields'))
                {
                    attFields = (List<cscfga__Attribute_Field__c>)mapProdConfs.get(prodConfId + '-'
                                                                        + att.cscfga__Attribute_Definition__c
                                                                        + '-attributeFields');
                }
                atts.add(new Attribute(att, attFields));
            }
            prodConfsMap.put(prodConfId, new ProductConfiguration((cscfga__Product_Configuration__c)mapProdConfs.get(prodConfId), atts));

            //Populate the key attributes variable on the product configuration
            populateProdConfKeyAttributes(prodConfId);
        }
    }

    /**
     * Populates the Product Definition map of Key Attributes.
     * Map is used to see if the attribute is a key attribute for a particular
     * product configuration.
     *
     * @author Tomislav Blazek
     * @ticket SFOM-85
     * @since  4/12/2016
     */
    private void populateProdDefKeyAttsMap()
    {
        prodDefKeyAttsMap = new Map<Id, List<KeyAttribute>>();
        if (!prodConfIds.isEmpty())
        {
            Set<Id> prodDefIds = new Set<Id>();
            List<cscfga__Product_Configuration__c> prodConfs = [SELECT Id, cscfga__Product_Definition__c
                                                                FROM cscfga__Product_Configuration__c
                                                                WHERE Id IN :prodConfIds];

            for(cscfga__Product_Configuration__c prodConf : prodConfs)
            {
                prodDefIds.add(prodConf.cscfga__Product_Definition__c);
            }

            List<cscfga__Product_Definition__c> prodDefs = [SELECT Id,
                                                            (SELECT Name, LG_KeyAttribute__c, LG_KeyAttributeSequence__c
                                                             FROM cscfga__Attribute_Definitions__r
                                                             WHERE LG_KeyAttribute__c = true)
                                                            FROM cscfga__Product_Definition__c
                                                            WHERE Id IN :prodDefIds];

            for(cscfga__Product_Definition__c prodDef : prodDefs)
            {
                if (!prodDef.cscfga__Attribute_Definitions__r.isEmpty())
                {
                    prodDefKeyAttsMap.put(prodDef.Id, new List<KeyAttribute>());

                    for(cscfga__Attribute_Definition__c attDef : prodDef.cscfga__Attribute_Definitions__r)
                    {
                        prodDefKeyAttsMap.get(prodDef.Id).add(new KeyAttribute(attDef.Name, attDef.LG_KeyAttributeSequence__c));
                    }
                }
            }
        }
    }

    /**
     * Populates the keyAttributes string variable on the product configuration
     * wrapper object.
     *
     * @author Tomislav Blazek
     * @ticket SFOM-85
     * @since  4/12/2016
     */
    private void populateProdConfKeyAttributes(Id prodConfId)
    {
        ProductConfiguration prodConf = prodConfsMap.get(prodConfId);
        prodConf.keyAttributesList = prodDefKeyAttsMap.get(prodConf.prodConfiguration.cscfga__Product_Definition__c);
        if (prodConf.keyAttributesList == null)
        {
            prodConf.keyAttributesList = new List<KeyAttribute>();
        }

        for(KeyAttribute keyAtt : prodConf.keyAttributesList)
        {
            for (Attribute att : prodConf.attributes)
            {
                if (keyAtt.Name == att.attribute.Name)
                {
                    keyAtt.value = att.attribute.cscfga__Value__c;
                    keyAtt.displayValue = att.attribute.cscfga__Display_Value__c;
                    break;
                }
            }
        }

        //sort key attributes by sequence
        prodConf.keyAttributesList.sort();
        prodConf.keyAttributes = '';
        for(KeyAttribute keyAttribute : prodConf.keyAttributesList)
        {
            if (String.isNotBlank(keyAttribute.displayValue))
            {
                prodConf.keyAttributes = prodConf.keyAttributes + keyAttribute.displayValue.unescapeHtml4() + ', ';
            }
        }
        if (prodConf.keyAttributes.length() >=2)
        {
            prodConf.keyAttributes = prodConf.keyAttributes.substring(0, prodConf.keyAttributes.length() - 2);
        }
    }

    //Wrapper classes

    public class KeyAttribute implements Comparable {
        public String name;
        public String value;
        public String displayValue;
        public Decimal sequence;

        public KeyAttribute(String name, Decimal sequence)
        {
            this.name = name;
            this.sequence = sequence;
        }

        public Integer compareTo(Object compareTo)
        {
            KeyAttribute compareToKey = (KeyAttribute)compareTo;
            if (sequence == compareToKey.sequence) return 0;
            if (sequence > compareToKey.sequence) return 1;
            return -1;
        }
    }

    public class ProductConfiguration {
        public cscfga__Product_Configuration__c prodConfiguration;
        public String keyAttributes;
        public List<KeyAttribute> keyAttributesList;
        public List<Attribute> attributes;

        public ProductConfiguration(cscfga__Product_Configuration__c prodConf, List<Attribute> atts)
        {
            this.prodConfiguration = prodConf;
            this.attributes = atts;
        }
    }

    public class Attribute {
        public cscfga__Attribute__c attribute;
        public List<cscfga__Attribute_Field__c> attFields;

        public Attribute(cscfga__Attribute__c attribute, List<cscfga__Attribute_Field__c> attFields)
        {
            this.attribute = attribute;
            this.attFields = attFields;
        }
    }
}