src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Add_On__c</fullName>
        <label>Add On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Description__c</fullName>
        <inlineHelpText>Description of the Product Configuration. Automatically set when Product Configuration is saved.</inlineHelpText>
        <label>Description</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Product Definition from which this Configuration was derived.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Add_On__c</fullName>
        <label>Add On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Item_Attribute__c</fullName>
        <label>Price Item Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Card__c</fullName>
        <label>Rate Card</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Description__c</fullName>
        <inlineHelpText>Description of the product visible to the sales user in the configuration process.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cspmb__Price_Item__c.object
<CustomObject>
    <description>Describes the pricing and commercial aspects of any product, service, tariff, price plan etc. which can be sold.</description>
    
    <fields>
        <fullName>cspmb__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If unchecked, this Price Item is not in effect (overrides start/end dates).</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Price Item</label>
    <nameField>
        <label>Price Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cspmb__Rate_Card__c.object
<CustomObject>
    <description>Describes a Rate Card. Can be used in association with a Price Item or standalone. If linked to an Account, it is only available for use by that Account.</description>
    <fields>
        <fullName>cspmb__Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Card_Widget_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Editable_Rate_Card_Line_Fields__c</fullName>
        <description>List of editable rate card line fields</description>
        <label>Editable Rate Card Line Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Card_Fields__c</fullName>
        <label>Rate Card Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Card_Line_Fields__c</fullName>
        <label>Rate Card Line Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Save_as_JSON__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Custom rate card will be saved as JSON attachment</inlineHelpText>
        <label>Save as JSON</label>
        <type>Checkbox</type>
    </fields>
    <label>Rate Card Widget Settings</label>
</CustomObject>

src/classes/TestRateCardWidgetController.cls
@isTest
public class TestRateCardWidgetController {

	static testmethod void testRateCardMethods() {
		cspmb__Rate_Card__c rc = new cspmb__Rate_Card__c(
			Name = 'Test'
		);
		insert rc;

		cspmb__Rate_Card_Line__c rcl = new cspmb__Rate_Card_Line__c(
			Name = 'Test',
			cspmb__Off_Peak__c = 10,
			cspmb__Rate_Card__c = rc.Id
		);
		insert rcl;

		cspmb__Price_Item__c priceItem = new cspmb__Price_Item__c(
			Name = 'Test'
		);
		insert priceItem;

		cspmb__Price_Item_Rate_Card_Association__c rcAssoc = new cspmb__Price_Item_Rate_Card_Association__c(
			cspmb__Price_Item__c = priceItem.Id,
			cspmb__Rate_Card__c = rc.Id
		);
		insert rcAssoc;

		Rate_Card_Widget_Settings__c rcSettings = new Rate_Card_Widget_Settings__c(
			Name = 'Test',
			Rate_Card_Fields__c = 'cspmb__Is_Active__c',
			Rate_Card_Line_Fields__c = 'cspmb__Rate_Card_Line_Unit__c,cspmb__Weekend__c,cspmb__Off_Peak__c,cspmb__Peak__c',
			Editable_Rate_Card_Line_Fields__c = 'cspmb__Rate_Card_Line_Unit__c,cspmb__Weekend__c,cspmb__Off_Peak__c,cspmb__Peak__c'
		);
		insert rcSettings;

		Rate_Card_Widget_Settings__c rcSettings1 = new Rate_Card_Widget_Settings__c(
			Name = 'Test1',
			Rate_Card_Line_Fields__c = 'cspmb__Rate_Card_Line_Unit__c,cspmb__Weekend__c,cspmb__Off_Peak__c,cspmb__Peak__c',
			Editable_Rate_Card_Line_Fields__c = 'cspmb__Rate_Card_Line_Unit__c,cspmb__Weekend__c,cspmb__Off_Peak__c,cspmb__Peak__c',
			Save_as_JSON__c = true
		);
		insert rcSettings1;

		cscfga__Product_Definition__c pd = new cscfga__Product_Definition__c(
			Name = 'Test',
			cscfga__Description__c = 'Test',
			Add_On__c = 'Test',
			Feature__c = 'Test',
			Rate_Card__c = 'Test',
			Price_Item_Attribute__c = 'Test'
		);
		insert pd;

		cscfga__Product_Configuration__c pc = new cscfga__Product_Configuration__c(
			cscfga__Product_Definition__c = pd.Id,
			Name = 'Test'
		);
		insert pc;

		Map<String, Object> rcMap = new Map<String, Object>();
		rcMap.put('Name', 'Test');
		rcMap.put('rateCardLines', JSON.serialize(rcl));

		List<Object> objList = new List<Object>{rcMap};

		Test.startTest();

		RateCardWidgetController.ParsedRateCardWrapper rcWrapper = new RateCardWidgetController.ParsedRateCardWrapper();
		rcWrapper.rateCardId = rc.Id;
		rcWrapper.rateCard = rc;
		rcWrapper.rateCardLines = new List<cspmb__Rate_Card_Line__c>{rcl};

		// test rc get method
		String rateCards = RateCardWidgetController.getAvailableRateCards(null, priceItem.Id, null, 'Test');

		// test cloning
		String cloneResult = RateCardWidgetController.cloneRateCard(pc.Id, priceItem.Id, null, 'Test', JSON.serialize(objList));
		String cloneResult2 = RateCardWidgetController.cloneRateCard(pc.Id, priceItem.Id, null, 'Test1', JSON.serialize(objList));

		// test edit
		String editResult = RateCardWidgetController.editRateCard(pc.Id, priceItem.Id, null, 'Test', JSON.serialize(objList));
		String editResult2 = RateCardWidgetController.editRateCard(pc.Id, priceItem.Id, null, 'Test1', JSON.serialize(objList));

		// test delete
		String deleteResult = RateCardWidgetController.deleteRateCard('Test', rc.Id);
		String deleteResult2 = RateCardWidgetController.deleteRateCard('Test1', rc.Id);

		Test.stopTest();

	}

}