src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Add_On__c</fullName>
        <label>Add On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Description__c</fullName>
        <inlineHelpText>Description of the Product Configuration. Automatically set when Product Configuration is saved.</inlineHelpText>
        <label>Description</label>
        <length>2048</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Product Definition from which this Configuration was derived.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Add_On__c</fullName>
        <label>Add On</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature__c</fullName>
        <label>Feature</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Item_Attribute__c</fullName>
        <label>Price Item Attribute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate_Card__c</fullName>
        <label>Rate Card</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Description__c</fullName>
        <inlineHelpText>Description of the product visible to the sales user in the configuration process.</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cspmb__Price_Item__c.object
<CustomObject>
    <description>Describes the pricing and commercial aspects of any product, service, tariff, price plan etc. which can be sold.</description>
    
    <label>Price Item</label>
    <nameField>
        <label>Price Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feature_Widget_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Custom_Object__c</fullName>
        <label>Custom Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feature_Fields__c</fullName>
        <label>Feature Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Feature Widget Settings</label>
</CustomObject>

src/classes/TestFeatureWidgetController.cls
@isTest
public class TestFeatureWidgetController {

	static testmethod void testFeatureMethods() {
		cspmb__Feature__c feature = new cspmb__Feature__c(
			Name = 'Test',
			cspmb__Feature_Description__c = 'Test'
		);
		insert feature;

		cspmb__Price_Item__c priceItem = new cspmb__Price_Item__c(
			Name = 'Test'
		);
		insert priceItem;

		cspmb__Price_Item_Feature_Association__c featureAssoc = new cspmb__Price_Item_Feature_Association__c(
			cspmb__Price_Item__c = priceItem.Id,
			cspmb__Feature__c = feature.Id
		);
		insert featureAssoc;

		Feature_Widget_Settings__c featureSettings = new Feature_Widget_Settings__c(
			Name = 'Test',
			Feature_Fields__c = 'cspmb__Feature_Description__c',
			Custom_Object__c = 'cspmb__Feature__c'
		);
		insert featureSettings;

		cscfga__Product_Definition__c pd = new cscfga__Product_Definition__c(
			Name = 'Test',
			cscfga__Description__c = 'Test',
			Add_On__c = 'Test',
			Feature__c = 'Test',
			Rate_Card__c = 'Test',
			Price_Item_Attribute__c = 'Test'
		);
		insert pd;

		cscfga__Product_Configuration__c pc = new cscfga__Product_Configuration__c(
			cscfga__Product_Definition__c = pd.Id,
			Name = 'Test'
		);
		insert pc;

		// test feature retrieval
		String features = FeatureWidgetController.getAvaialbleFeatures(priceItem.Id, 'Test');

		// test delete -> cannot test properly due to missing relationship
		FeatureWidgetController.deletefeatures(pc.Id, 'Test');

		// test save -> cannot test properly due to missing relationship
		FeatureWidgetController.saveFeatures(pc.Id, new List<Id>{feature.Id}, 'Test');


	}

}