src/objects/cscfga__Attribute_Definition__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <inlineHelpText>The Product Definition to which this Attribute Definition belongs.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Attribute Definitions</relationshipLabel>
        <relationshipName>Attribute_Definitions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attribute Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Definitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Basket__c.object
<CustomObject>
    <description>Basket to supercede bundles...</description>
    <fields>
        <fullName>csbb__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Baskets</relationshipLabel>
        <relationshipName>Product_Baskets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Change_Type__c</fullName>
        <label>Change Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change</fullName>
                </value>
                <value>
                    <fullName>Migrate</fullName>
                </value>
                <value>
                    <fullName>Terminate</fullName>
                </value>
                <value>
                    <fullName>Clone</fullName>
                </value>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
                <value>
                    <fullName>Relocation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Basket</label>
    <nameField>
        <label>Product Basket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Baskets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_InstallationWishDate__c</fullName>
        <label>Installation Wish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Basket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of associated Product Basket.</inlineHelpText>
        <label>Product Basket</label>
        <referenceTo>cscfga__Product_Basket__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Product Definition from which this Configuration was derived.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Definition__c.object
<CustomObject>
    <fields>
        <fullName>LG_ProductSubtype__c</fullName>
        <label>Product Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Termination</fullName>
                </value>
                <value>
                    <fullName>Penalty Fee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Product_Basket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Basket</label>
        <referenceTo>cscfga__Product_Basket__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Account that governs this Subscription.</description>
        <inlineHelpText>The Account that governs this Subscription.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Change_Type__c</fullName>
        <label>Change Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
                <value>
                    <fullName>Relocation</fullName>
                </value>
                <value>
                    <fullName>Cease</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>csordtelcoa__Closed_Replaced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed Replaced</label>
        <type>Checkbox</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_EnvironmentVariables__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Storage of system variables and hard-coded IDs.</description>
    <fields>
        <fullName>LG_CloudSenceAnywhereIconID__c</fullName>
        <description>Document ID for &apos;Open Cloudsense Anywhere&apos; icon displayed on D2D page layouts.</description>
        <label>CloudSence Anywhere Icon ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_SalesforceBaseURL__c</fullName>
        <label>Salesforce Base URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LG_ServiceAvailabilityIconID__c</fullName>
        <description>Document ID for Service Availability icon displayed on D2D page layouts.</description>
        <label>Service Availability Icon ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_VisualForceBaseURL__c</fullName>
        <label>VisualForce Base URL</label>
        <type>Url</type>
    </fields>
    <label>Environment Variables</label>
</CustomObject>

src/objects/LG_TerminationSpecificVariables__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds the variable related to the Termination MACD process.
Used for calculating the penalty fees, etc.</description>
    <fields>
        <fullName>LG_NumberOfToleratedDays__c</fullName>
        <description>Holds the value of tolerated days. Users who have a contract that expires in less then the number of days set on this field, will not be eligible for a penalty fee.</description>
        <label>Number of Tolerated Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Termination Specific Variables</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>csordtelcoa__Change_Type__c</fullName>
        <label>Change Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Change</fullName>
                </value>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>Terminate</fullName>
                </value>
                <value>
                    <fullName>Migrate</fullName>
                </value>
                <value>
                    <fullName>Clone</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Upgrade</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
                <value>
                    <fullName>Relocation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Terminate</fullName>
        <active>true</active>
        <businessProcess>OppStage</businessProcess>
        <label>Terminate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LG_TerminationDetailsControllerTest.cls
@isTest
private class LG_TerminationDetailsControllerTest {

	private static String vfBaseUrl   = 'vforce.url';
	private static String sfdcBaseUrl = 'sfdc.url';
	private static Date wishDate      = Date.newInstance(2016, 3, 20);
	private static Date plannedDate   = Date.newInstance(2016, 3, 18);

	@testsetup
	private static void setupTestData()
	{
		No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
		noTriggers.Flag__c      = true;
		noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
		upsert noTriggers;

		LG_EnvironmentVariables__c envVariables = new LG_EnvironmentVariables__c();
		envVariables.LG_SalesforceBaseURL__c         = sfdcBaseUrl;
		envVariables.LG_VisualForceBaseURL__c        = vfBaseUrl;
		envVariables.LG_CloudSenceAnywhereIconID__c  = 'csaID';
		envVariables.LG_ServiceAvailabilityIconID__c = 'saIconId';
		insert envVariables;

		LG_TerminationSpecificVariables__c termSpecifics = new LG_TerminationSpecificVariables__c();
		termSpecifics.LG_NumberOfToleratedDays__c = 30;
		insert termSpecifics;

		List<cscrm__Address__c> addresses = new List<cscrm__Address__c>();
		cscrm__Address__c addressOne = new cscrm__Address__c(Name = 'AddressOne');
		cscrm__Address__c addressTwo = new cscrm__Address__c(Name = 'AddressTwo');
		addresses.add(addressOne);
		addresses.add(addressTwo);
		insert addresses;

		Account account = LG_GeneralTest.CreateAccount('Account', '12345678', 'Ziggo', true);

		Opportunity opp = LG_GeneralTest.CreateOpportunity(account, true);

		cscfga__Product_Basket__c basket = LG_GeneralTest.createProductBasket('BAsket58', account, null, opp, false);
		basket.csbb__Account__c            = account.Id;
		basket.csordtelcoa__Change_Type__c = 'Terminate';
		insert basket;

		csord__Order_Request__c coreq = new csord__Order_Request__c(csord__Module_Name__c = 'Test', csord__Module_Version__c = '1.0');
		insert coreq;

		csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = 'TestIdent', csord__Order_Request__c = coreq.Id, Name = 'Product1',
																csord__Account__c = basket.csbb__Account__c, LG_Address__c = addressOne.Id, csordtelcoa__Closed_Replaced__c = false);
		csord__Subscription__c sub2 = new csord__Subscription__c(csord__Identification__c = 'TestIdent2', csord__Order_Request__c = coreq.Id, Name = 'Product2',
																 csord__Account__c = basket.csbb__Account__c, LG_Address__c = addressOne.Id, csordtelcoa__Closed_Replaced__c = false);
		insert sub;
		insert sub2;

		List<csordtelcoa__Subscr_MACDProductBasket_Association__c> subBasketRelations
			= new List<csordtelcoa__Subscr_MACDProductBasket_Association__c>();
		subBasketRelations.add(new csordtelcoa__Subscr_MACDProductBasket_Association__c(csordtelcoa__Subscription__c = sub.Id,
																						csordtelcoa__Product_Basket__c = basket.Id));
		subBasketRelations.add(new csordtelcoa__Subscr_MACDProductBasket_Association__c(csordtelcoa__Subscription__c = sub2.Id,
																						csordtelcoa__Product_Basket__c = basket.Id));
		insert subBasketRelations;

		cscfga__Product_Definition__c prodDef = LG_GeneralTest.createProductDefinition('Termination', false);
		prodDef.LG_ProductSubtype__c = 'Termination';
		insert prodDef;

		List<cscfga__Product_Configuration__c> prodConfs = new List<cscfga__Product_Configuration__c>();
		cscfga__Product_Configuration__c prodConf = LG_GeneralTest.createProductConfiguration('ProdConf58', 3, basket, prodDef, false);
		prodConf.LG_Address__c                         = addressOne.Id;
		prodConf.LG_InstallationWishDate__c            = Date.today();
		prodConf.csordtelcoa__Replaced_Subscription__c = sub.Id;

		cscfga__Product_Configuration__c prodConf1 = LG_GeneralTest.createProductConfiguration('ProdConf581', 3, basket, prodDef, false);
		prodConf1.LG_Address__c                         = addressOne.Id;
		prodConf1.LG_InstallationNeeded__c              = true;
		prodConf1.csordtelcoa__Replaced_Subscription__c = sub2.Id;

		cscfga__Product_Configuration__c prodConf2 = LG_GeneralTest.createProductConfiguration('ProdConf582', 3, basket, prodDef, false);
		prodConf2.LG_Address__c = addressTwo.Id;

		cscfga__Product_Configuration__c prodConf3 = LG_GeneralTest.createProductConfiguration('ProdConf5823', 3, basket, prodDef, false);
		prodConf3.LG_Address__c = addressTwo.Id;

		prodConfs.add(prodConf);
		prodConfs.add(prodConf1);
		prodConfs.add(prodConf2);
		prodConfs.add(prodConf3);
		insert prodConfs;

		csord__Service__c service = new csord__Service__c(csord__Identification__c = 'TestTelServ', csord__Order_Request__c = coreq.Id,
														  csord__Subscription__c = sub.Id, csordtelcoa__Product_Configuration__c = prodConf.Id);
		insert service;

		cscfga__Attribute_Definition__c attDef = LG_GeneralTest.createAttributeDefinition('AttDef', prodDef, 'User Input', 'String',
																						  null, null, null, true);
		LG_GeneralTest.createAttribute('Installation Wish Date', attDef, false, null, prodConf, false, null, true);

		noTriggers.Flag__c = false;
		upsert noTriggers;
	}

	private static testmethod void testRedirectToReturnId()
	{
		cscfga__Product_Basket__c basket = [SELECT Id FROM cscfga__Product_Basket__c WHERE Name = 'BAsket58'];
		Account account                  = [SELECT Id FROM Account WHERE Name = 'Account'];

		PageReference pageRef = Page.LG_TerminationDetails;
		pageRef.getParameters().put('basketId', basket.Id);
		pageRef.getParameters().put('returnId', account.Id);
		Test.setCurrentPageReference(pageRef);

		Test.startTest();

		LG_TerminationDetailsController controller = new LG_TerminationDetailsController();
		pageRef = controller.redirectToReturnId();

		Test.stopTest();

		System.assertEquals( sfdcBaseUrl+ '/' + account.Id, pageRef.getUrl(),
							 'Url should be ' + sfdcBaseUrl + '/' + account.Id);
	}

	private static testmethod void testSave()
	{
		cscfga__Product_Basket__c basket = [SELECT Id FROM cscfga__Product_Basket__c WHERE Name = 'BAsket58'];
		cscrm__Address__c addressOne     = [SELECT Id FROM cscrm__Address__c WHERE Name = 'AddressOne'];
		Set<Id> subIds = new Set<Id>();
		for (csord__Subscription__c sub : [SELECT Id FROM csord__Subscription__c]) {
			subIds.add(sub.Id);
		}

		PageReference pageRef = Page.LG_TerminationDetails;
		pageRef.getParameters().put('basketId', basket.Id);
		Test.setCurrentPageReference(pageRef);

		Test.startTest();

		LG_TerminationDetailsController controller = new LG_TerminationDetailsController();
		controller.premiseIdToWishDates = addressOne.Id + '~20-03-2016';
		controller.terminatedSubs       = subIds;

		pageRef = controller.save();

		Test.stopTest();

		List<csordtelcoa__Subscr_MACDProductBasket_Association__c> subBasketJuncs = [SELECT LG_DeactivationWishDate__c
																					 FROM csordtelcoa__Subscr_MACDProductBasket_Association__c
																					 WHERE csordtelcoa__Product_Basket__c = :basket.Id];
		for (csordtelcoa__Subscr_MACDProductBasket_Association__c subBasketJunc : subBasketJuncs) {
			System.assertEquals(wishDate, subBasketJunc.LG_DeactivationWishDate__c, 'Deactivation wish date should be 20/3/2016');
		}
	}
}