src/objects/cscfga__Product_Basket__c.object
<CustomObject>
    <description>Basket to supercede bundles...</description>
    <fields>
        <fullName>csbb__Synchronised_With_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Synchronised With Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cscfga__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Opportunity this Basket is associated with.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Product Baskets</relationshipLabel>
        <relationshipName>Product_Baskets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Basket</label>
    <nameField>
        <label>Product Basket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Baskets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>House_Number_Extension__c</fullName>
        <label>House Number Extension</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>House_Number__c</fullName>
        <label>House Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Id__c</fullName>
        <label>Site Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>SPT Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomCallouts.cls
/*

    This web service is used to query external data source

*/
global class CustomCallouts {

    webservice static String getCustomAddresses(String postcode) {
            
        String query;
        List<string> params = new List<string>();
        
        if (String.isNotBlank(postcode)) {
            params.add('Postcode__c LIKE \'%' + String.escapeSingleQuotes(postcode) + '%\'');
        }

        if (params.size() == 0) {
            query = 'SELECT Id, Site_Id__c, Postcode__c, Address_Line_1__c, Address_Line_2__c, House_Number__c, House_Number_Extension__c, Town__c FROM Site__c LIMIT 25';
        }
        else {
            String allParams = String.join(params, ' AND ');
            query = 'SELECT Id, Site_Id__c, Postcode__c, Address_Line_1__c, Address_Line_2__c, House_Number__c, House_Number_Extension__c, Town__c FROM Site__c WHERE ' + allParams;
        }
        
        List<Site__c> sl = Database.query(query);
        system.debug('+++address list is: ' + sl);

        return JSON.serialize(sl);
    }

    webservice static String synchronizeBasket(String basketId) {
        
        cscfga__Product_Basket__c basket = [SELECT csbb__synchronised_with_opportunity__c, cscfga__opportunity__c FROM cscfga__Product_Basket__c WHERE id = :basketId];
        basket.csbb__synchronised_with_opportunity__c = true;
        // any other sync logic goes here
        update basket;
        
        Opportunity oppToGoBackTo = [select id from Opportunity where id = :basket.cscfga__Opportunity__c];
        PageReference oppPage = new ApexPages.StandardController(oppToGoBackTo).view();
        return oppPage.getUrl();
    }
}