src/objects/cscfga__Attribute__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Configuration__c</fullName>
        <inlineHelpText>The Product Configuration to which this Attribute belongs.</inlineHelpText>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>cscfga__Value__c</fullName>
        <inlineHelpText>The value of this Attribute captured during the configuration process.</inlineHelpText>
        <label>Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Basket__c.object
<CustomObject>
    <description>Basket to supercede bundles...</description>
    <label>Product Basket</label>
    <nameField>
        <label>Product Basket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Baskets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscfga__Configuration_Status__c</fullName>
        <description>Describes if a configuration contains errors or not</description>
        <inlineHelpText>Status of the Product Configuration. Automatically set when Product Configuration is saved.</inlineHelpText>
        <label>Configuration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                    <default>true</default>
                    <label>Valid</label>
                </value>
                <value>
                    <fullName>Requires Update</fullName>
                </value>
                <value>
                    <fullName>Is Valid</fullName>
                </value>
                <value>
                    <fullName>Contains Errors or Incomplete</fullName>
                </value>
                <value>
                    <fullName>Contains Expired Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cscfga__Product_Basket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of associated Product Basket.</inlineHelpText>
        <label>Product Basket</label>
        <referenceTo>cscfga__Product_Basket__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BdsAccessProductsInBasket.cls
/**************************************************************************************************************************
* Name         : BdsAccessProductsInBasket
* Created      : 14/12/2017
* Description  : Performs lookups search for based on the Basketid, premise id and access products selected
* Author       : BDS Dev Team
* Called From  : BdsAccessProductsInBasketConfig Lookup Configs
*************************************************************************************************************************/
global class BdsAccessProductsInBasket extends cscfga.ALookupSearch {

    
    /******************************************************************************************************
    * Input parameter  :   --     
    * Return Type      :   String
    *****************************************************************************************************/
    public override String getRequiredAttributes(){
        return '["Valid Access Products","Basket Id","Premise Id"]';
    }
    
    
    /******************************************************************************************************
    * Input parameter  :   Map<String, String> searchFields, String productDefinitionId     
    * Return Type      :   List<Object>
    * Description      :   peforms search lookup based on the input criteria 
    *****************************************************************************************************/
    public override Object[] doDynamicLookupSearch(Map<String, String> searchFields, String productDefinitionId) {
        
        
        String basketId = searchFields.get('Basket Id');
        String accessProducts = searchFields.get('Valid Access Products');
        String premiseId = searchFields.get('Premise Id');
        
        String connectProduct = 'Company Cloud Connect';
        String fiberProduct = 'Company Fiber';
        String serviceProduct = 'Company Cloud Fiber';
        
        List<String> acessProductList = accessProducts.split(','); 
        
        /*fetch product configuration based on the basket id , premise id and access product*/
        List<cscfga__Product_Configuration__c> validPcInBasket = [select Id,Name from cscfga__Product_Configuration__c 
                                                                  where cscfga__Configuration_Status__c = 'Valid' AND cscfga__Product_Basket__c =:basketId
                                                                  AND LG_Address__c =:premiseId AND Name In:acessProductList Limit 1];
        
        if (validPcInBasket.size() == 0) {
            return null;
        }
        
        /*if access product is 'Company Cloud Connect' then return fetched product configuration*/
        if (validPcInBasket[0].Name == connectProduct) {
            return validPcInBasket;
        }
        
        /* if access product are fiber products and their isCCFPresent attribute value is 'Yes' then return fetched product configuration*/
        if (validPcInBasket[0].Name == fiberProduct) {
            List<cscfga__Attribute__c> services = [select cscfga__Value__c 
                                                  from cscfga__Attribute__c
                                                  where Name = 'isCCFPresent' AND cscfga__Product_Configuration__c = :validPcInBasket[0].Id];
            if (services.size()>0 && services[0].cscfga__Value__c == 'Yes') {
                return validPcInBasket;
            }
            
        }        
        return null;
        
    }//end of method
    
}