src/objects/cscfga__Attribute__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Product_Configuration__c</fullName>
        <inlineHelpText>The Product Configuration to which this Attribute belongs.</inlineHelpText>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>cscfga__Recurring__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this Attribute should be treated as a recurring line item. If unchecked, this Attribute should be treated as a one-off line item. Only relevant to line item Attributes.</inlineHelpText>
        <label>Recurring</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cscfga__Value__c</fullName>
        <inlineHelpText>The value of this Attribute captured during the configuration process.</inlineHelpText>
        <label>Value</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>cscfga__Contract_Term__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Contract Term for this Product Configuration. It can be derived from Product‘s Contract Term or with Set Contract Term action during configuration process. It is a number which combined with Contract Term Period value defines the contract-binding period.</inlineHelpText>
        <label>Contract Term</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_Discount__c.object
<CustomObject>
    <fields>
        <fullName>LG_Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_ContractTerm__c</fullName>
        <label>Contract Term (months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_DiscountCode__c</fullName>
        <label>Discount Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_DiscountMessage__c</fullName>
        <label>Discount Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Months__c</fullName>
        <label>Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Promotion Code</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>LG_ContractTerm__c</fullName>
        <label>Contract Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_DiscountAmount__c</fullName>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_DiscountCode__c</fullName>
        <label>Discount Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_DiscountMessage__c</fullName>
        <label>Discount Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_DiscountMonths__c</fullName>
        <label>Discount Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_MainOLI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Main OLI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_OneOffPrice__c</fullName>
        <label>One-Off Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LG_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>One Off</fullName>
                </value>
                <value>
                    <fullName>Promotional Discount</fullName>
                </value>
                <value>
                    <fullName>Promotional Action</fullName>
                </value>
                <value>
                    <fullName>Closing Deal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cscfga__Attribute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attribute</label>
        <referenceTo>cscfga__Attribute__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/LG_OpportunityLineItemTriggerHandler.cls
public class LG_OpportunityLineItemTriggerHandler 
{
    public static void AfterInsertHandle(List<OpportunityLineItem> newOLI)
    {
    	//TransformOLIs(newOLI);
    }
    
    /*
    private static void TransformOLIs(List<OpportunityLineItem> newOLI)
    {
    	
    	set<string> setAttributeId = new set<string>();
    	map<Id,cscfga__Attribute__c> mapAttribute;
    	map<Id,cscfga__Attribute_Field__c> mapAttributeField;
    	list<OpportunityLineItem> lstOLIUpdate = new list<OpportunityLineItem>();
    	map<string,string> mapPCIdMainAttribId = new map<string,string>(); 
    	map<string,string> mapAttributeIdOLIId = new map<string,string>();
    	set<string> setOpportunityLineItemId = new set<string>();
    	
    	
    	
    	for (OpportunityLineItem tmpOLI : newOLI)
        {
        	if (tmpOLI.cscfga__Attribute__c!=null)	
        	{
        		setAttributeId.add(tmpOLI.cscfga__Attribute__c);
        		mapAttributeIdOLIId.put(tmpOLI.cscfga__Attribute__c,tmpOLI.Id);
        		
        		setOpportunityLineItemId.add(tmpOLI.Id);
        	}
        }
        
        if (setAttributeId.size()>0)
        {
        	
        	map<Id,OpportunityLineItem> mapOLIUpdate = new map<Id,OpportunityLineItem>([select Id, LG_OneOffPrice__c, UnitPrice, LG_Type__c, 
        		LG_MainOLI__c
        		from OpportunityLineItem
        		where Id in : setOpportunityLineItemId]); 
        	
        	mapAttribute  = new map<Id,cscfga__Attribute__c>([select Id, cscfga__Recurring__c, Name, cscfga__Value__c, cscfga__Product_Configuration__c,
        		cscfga__Product_Configuration__r.cscfga__Contract_Term__c
        		from cscfga__Attribute__c 
        		where Id in : setAttributeId]);
        		
        	
        	mapAttributeField = new map<Id,cscfga__Attribute_Field__c>([select Id,Name,cscfga__Value__c, cscfga__Attribute__c, 
        		cscfga__Attribute__r.cscfga__Product_Configuration__c
        		from cscfga__Attribute_Field__c
        		where Name='Main' and cscfga__Value__c='Yes' and cscfga__Attribute__c in : setAttributeId]);
        		
        	for (cscfga__Attribute_Field__c tmpAttributeField : mapAttributeField.values())
        	{
        		mapPCIdMainAttribId.put(tmpAttributeField.cscfga__Attribute__r.cscfga__Product_Configuration__c,tmpAttributeField.cscfga__Attribute__c);
        	}
        		
        	set<string> setDiscountId = new set<string>();
        	
        	for (cscfga__Attribute__c tmpAttribute : mapAttribute.values())
        	{
        		if (tmpAttribute.Name=='Discount')
        		{
        			setDiscountId.add(tmpAttribute.cscfga__Value__c);
        		}
        	}
        	
        	map<Id,LG_Discount__c> mapDiscount;
        	
        	if (setDiscountId.size()>0)
        		mapDiscount = new map<Id,LG_Discount__c>([select Id,LG_Amount__c, LG_Months__c, LG_Type__c
        			from LG_Discount__c where Id in : setDiscountId]); 
        		
        	
        	for (OpportunityLineItem tmpOLIOriginal : newOLI)
        	{	
        		if (tmpOLIOriginal.cscfga__Attribute__c!=null)	
        		{
        			cscfga__Attribute__c tmpAttribute = mapAttribute.get(tmpOLIOriginal.cscfga__Attribute__c);
        			
        			OpportunityLineItem tmpOLI = mapOLIUpdate.get(tmpOLIOriginal.Id);
        			
        			
        			if (!tmpAttribute.cscfga__Recurring__c)
        			{
        				tmpOLI.LG_OneOffPrice__c=tmpOLI.UnitPrice;
        				tmpOLI.UnitPrice=0;
        				
        				
        				if (tmpAttribute.Name=='Discount')
        				{
        					tmpOLI.LG_Type__c = mapDiscount.get(tmpAttribute.cscfga__Value__c).LG_Type__c;
        					tmpOLI.LG_DiscountAmount__c = mapDiscount.get(tmpAttribute.cscfga__Value__c).LG_Amount__c;
        					tmpOLI.LG_DiscountCode__c =  mapDiscount.get(tmpAttribute.cscfga__Value__c).LG_DiscountCode__c;
        					tmpOLI.LG_DiscountMonths__c =  mapDiscount.get(tmpAttribute.cscfga__Value__c).LG_Months__c;
        					tmpOLI.LG_DiscountMessage__c =  mapDiscount.get(tmpAttribute.cscfga__Value__c).LG_DiscountMessage__c;
        					
							string tmpPCId = tmpAttribute.cscfga__Product_Configuration__c;
							if (mapPCIdMainAttribId.containsKey(tmpPCId))
							{
								string mainAttributeId = mapPCIdMainAttribId.get(tmpPCId);
								if (mapAttributeIdOLIId.containsKey(mainAttributeId))
								{
									string mainOLIId = mapAttributeIdOLIId.get(mainAttributeId);
									tmpOLI.LG_MainOLI__c=mainOLIId;
								}
							}
							
        				}
        				else
        				{
        					tmpOLI.LG_Type__c='One Off';
        				}
        				
        			}
        			else
        			{
        				tmpOLI.LG_Type__c='Recurring';
        			}
        			
        			
        			if (tmpAttribute.cscfga__Product_Configuration__r.cscfga__Contract_Term__c!=null)
        				tmpOLI.LG_ContractTerm__c=tmpAttribute.cscfga__Product_Configuration__r.cscfga__Contract_Term__c;
        			
        			
        			lstOLIUpdate.add(tmpOLI);
        			
        		}	
        	}
        	
        	if (lstOLIUpdate.size()>0) update lstOLIUpdate;
        	
        }
        
    }
    */
   
}