src/objects/cscfga__Product_Basket__c.object
<CustomObject>
    <description>Basket to supercede bundles...</description>
    <fields>
        <fullName>csbb__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Baskets</relationshipLabel>
        <relationshipName>Product_Baskets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Basket</label>
    <nameField>
        <label>Product Basket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Baskets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>LG_MaximumQuantity__c</fullName>
        <label>Maximum Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LG_PortIn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Port In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Basket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of associated Product Basket.</inlineHelpText>
        <label>Product Basket</label>
        <referenceTo>cscfga__Product_Basket__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscfga__Product_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Name of Product Definition from which this Configuration was derived.</inlineHelpText>
        <label>Product Definition</label>
        <referenceTo>cscfga__Product_Definition__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscfga__Product_Definition__c.object
<CustomObject>
    <label>Product Definition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_EnvironmentVariables__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Storage of system variables and hard-coded IDs.</description>
    <fields>
        <fullName>LG_CloudSenceAnywhereIconID__c</fullName>
        <description>Document ID for &apos;Open Cloudsense Anywhere&apos; icon displayed on D2D page layouts.</description>
        <label>CloudSence Anywhere Icon ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_SalesforceBaseURL__c</fullName>
        <label>Salesforce Base URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LG_ServiceAvailabilityIconID__c</fullName>
        <description>Document ID for Service Availability icon displayed on D2D page layouts.</description>
        <label>Service Availability Icon ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_VisualForceBaseURL__c</fullName>
        <label>VisualForce Base URL</label>
        <type>Url</type>
    </fields>
    <label>Environment Variables</label>
</CustomObject>

src/objects/LG_PortingNumber__c.object
<CustomObject>
    <fields>
        <fullName>LG_FirstPhoneNumber__c</fullName>
        <label>First Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_LastPhoneNumber__c</fullName>
        <label>Last Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Operator__c</fullName>
        <label>Operator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Porting Numbers</relationshipLabel>
        <relationshipName>Porting_Numbers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_PhoneNumber__c</fullName>
        <label>Phone Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_PortingDate__c</fullName>
        <label>Porting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LG_PrimaryNumber__c</fullName>
        <label>Primary Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ProductConfiguration__c</fullName>
        <label>Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Porting Numbers</relationshipLabel>
        <relationshipName>Porting_Numbers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LG_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SB Telephony</fullName>
                </value>
                <value>
                    <fullName>SOHO Telephony</fullName>
                </value>
                <value>
                    <fullName>Mobile Telephony</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Porting Number</label>
    <nameField>
        <displayFormat>PN-{000000}</displayFormat>
        <label>Porting Numbers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Porting Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LG_PortingNmbrsSiteCmpntControllerTest.cls
@isTest
private class LG_PortingNmbrsSiteCmpntControllerTest {
	
	/* RS: This Class should be fixed - no assert methods */
	
	private static String vfBaseUrl = 'vforce.url';
	private static String sfdcBaseUrl = 'sfdc.url';
	
	@testsetup
	private static void setupTestData()
	{
		No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
		noTriggers.Flag__c = true;
		noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
		upsert noTriggers;
		
		LG_EnvironmentVariables__c envVariables = new LG_EnvironmentVariables__c();
		envVariables.LG_SalesforceBaseURL__c = sfdcBaseUrl;
		envVariables.LG_VisualForceBaseURL__c = vfBaseUrl;
		envVariables.LG_CloudSenceAnywhereIconID__c = 'csaID';
		envVariables.LG_ServiceAvailabilityIconID__c = 'saIconId';
		insert envVariables;
		
		Account account = LG_GeneralTest.CreateAccount('AccountSFDT-58', '12345678', 'Ziggo', true);
				
		Opportunity opp = LG_GeneralTest.CreateOpportunity(account, true);
		
		cscfga__Product_Basket__c basket = LG_GeneralTest.createProductBasket('BAsket58', account, null, opp, false);
		basket.csbb__Account__c = account.Id;
		insert basket;
		
		cscfga__Product_Definition__c prodDef = LG_GeneralTest.createProductDefinition('ProdDef58', true);
		
		cscfga__Product_Configuration__c prodConf = LG_GeneralTest.createProductConfiguration('ProdConf58', 3, basket, prodDef, false);
		prodConf.LG_PortIn__c = true;
		prodConf.LG_MaximumQuantity__c = 20;
		insert prodConf;
		
		LG_PortingNumber__c tmpPortingNumber = new LG_PortingNumber__c();
		tmpPortingNumber.LG_FirstPhoneNumber__c = '345';
		tmpPortingNumber.LG_LastPhoneNumber__c = '345';
		tmpPortingNumber.LG_Operator__c = 'KLN';
		tmpPortingNumber.LG_PhoneNumber__c = '345';
		tmpPortingNumber.LG_PortingDate__c = Date.today();
		tmpPortingNumber.LG_PrimaryNumber__c = '345';
		tmpPortingNumber.LG_Type__c = 'SB Telephony';
		tmpPortingNumber.LG_Opportunity__c = null;
		tmpPortingNumber.LG_ProductConfiguration__c = prodConf.Id;
		insert tmpPortingNumber;
		
		noTriggers.Flag__c = false;
		upsert noTriggers;
	}
	
	private static testmethod void testResetData()
	{
		cscfga__Product_Configuration__c prodConf = [SELECT Id FROM cscfga__Product_Configuration__c WHERE Name = 'ProdConf58'];
		
		Test.startTest();
		
			LG_PortingNumbersController controller = new LG_PortingNumbersController();
			
			LG_PortingNmbrsSiteComponentController compController = new LG_PortingNmbrsSiteComponentController();
			compController.pageController = controller;
			compController.prodConfigId = prodConf.Id;
			compController.lstImportFileRow.add(new LG_PortingNmbrsSiteComponentController.cImportFileRow());
			compController.fileName = 'something';
			compController.lstErrorMessage.add('Something');
			compController.fileIsValid = true;
			
			compController.resetData(true);
		Test.stopTest();
		
		// Need to be fixed
		// System.assertEquals(1, compController.lstPortedNumbers.size(), 'One ported number should already exist');
	}
	
	private static testmethod void testUploadValidateFile()
	{
		cscfga__Product_Configuration__c prodConf = [SELECT Id FROM cscfga__Product_Configuration__c WHERE Name = 'ProdConf58'];
		
		Test.startTest();
		
			LG_PortingNumbersController controller = new LG_PortingNumbersController();
			
			LG_PortingNmbrsSiteComponentController compController = new LG_PortingNmbrsSiteComponentController();
			compController.pageController = controller;
			compController.prodConfigId = prodConf.Id;
			
			compController.fileName='Tel test';
			
			String filecsv = 'Wensdatum portering,Hoofdnummer,Operator (telecomprovider),Enkelvoudige nummers,(of),Nummerblokken (reeks/blok van 10 /100 /1000 nummers):,,nummer\n';
			filecsv += '24-05-2015,12334454,KNL,,,34343430,t/m,34343439';
			filecsv += '25-05-2015,1233445,KNL,123434343,,,t/m,';
			filecsv += '25-05-2015,12334489,XYZ,,,678999990,t/m,678999999';
			filecsv += '27-05-2015,767676,ABC,7676767676,,,t/m,';
			
			compController.fileBody = Blob.valueof(filecsv);
			
			compController.uploadValidateFile();
			
		Test.stopTest();
	}
}