src/objects/cscfga__Product_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Product Configurations</relationshipLabel>
        <relationshipName>Product_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_PlanningDetailsStatus__c</fullName>
        <description>Planning Details Status</description>
        <inlineHelpText>Planning Details Status</inlineHelpText>
        <label>LG PlanningDetailsStatus</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscfga__Configuration_Status__c</fullName>
        <description>Describes if a configuration contains errors or not</description>
        <inlineHelpText>Status of the Product Configuration. Automatically set when Product Configuration is saved.</inlineHelpText>
        <label>Configuration Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                    <default>true</default>
                    <label>Valid</label>
                </value>
                <value>
                    <fullName>Requires Update</fullName>
                </value>
                <value>
                    <fullName>Is Valid</fullName>
                </value>
                <value>
                    <fullName>Contains Errors or Incomplete</fullName>
                </value>
                <value>
                    <fullName>Contains Expired Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InstallationSiteDetailRemoter.cls
/************************************************************
* File Name     :  InstallationSiteDetailRemoter
* Description   :  This class is created as part of QNT-441
=====================================================================
* Ver.    Date          Author                         Modification
-------------------------------------------------------------------------
* 1.0     30/11/2017    Debasish                File Created.
 
*************************************************************/

global class InstallationSiteDetailRemoter {
    public InstallationSiteDetailRemoter (LG_InstallationInformationController isdController) {}

    @RemoteAction
    global static List<cscfga__Product_Configuration__c> getProductConfigurations (String configID) {
        /*
        Long totalTime;
        Long startTime = DateTime.now().getTime();
        Long endTime = DateTime.now().getTime();
        totalTime = endTime - startTime;
        //System.debug('Execution Time getProductConfigurations: '+ (endTime - startTime));
        */
        List<cscfga__Product_Configuration__c> pcs = [SELECT Id,LG_Address__c, LG_PlanningDetailsStatus__c,cscfga__Configuration_Status__c FROM cscfga__Product_Configuration__c WHERE Id =: configID];
        return pcs;
    }
    
}