src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>LG_MyBillAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MyBill Account Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.csconta__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts (Contact)</relationshipLabel>
        <relationshipName>Billing_Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_MyBillAddress__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MyBill Address</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>cscrm__Address__c.cscrm__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.csconta__Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Billing Accounts (MyBill Address)</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_MyBillBillingSysAccId__c</fullName>
        <externalId>true</externalId>
        <label>Billing System Account Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_MyBillExists__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MyBill Exists?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>csconta__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>cscrm__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cscrm__Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_ValidateMyBillDetailsTest.cls
/*
 * Test class for LG_ValidateMyBillDetails
 @ Author : Shruthi Gopal
 @ Date   : 23/10/2017
*/

@isTest
public class LG_ValidateMyBillDetailsTest {
    
	public static testmethod void handleTest(){
        
        
		Account acc = LG_GeneralTest.CreateAccount('Test Acc', '12345678', 'Ziggo', false);
		insert acc;		

        cscrm__Address__c address = new cscrm__Address__c(cscrm__Street__c = 'TestStreet');
        address.cscrm__Account__c = acc.id;
        insert address;
        
		Contact tmpContact = new Contact();
        tmpContact.AccountId=acc.Id;
        tmpContact.Firstname='Firstname';
        tmpContact.LastName='LastName';
        tmpContact.Salutation='Mr.';
        tmpContact.MobilePhone = '9876543211';
        tmpContact.Phone = '12345678';
        tmpContact.Email = 'test@infy.com';
        tmpContact.cscrm__Address__c = address.id;
        tmpContact.LG_IsFinContact__c = true;
        insert tmpContact;

       
        //Billing Account with proper data
		List<csconta__Billing_Account__c> newData = new List<csconta__Billing_Account__c>();
		csconta__Billing_Account__c b = LG_GeneralTest.createBillingAccount('SFDT-59 Bill1', acc.Id, true, false);
        b.LG_MyBillAccount__c = tmpContact.id;
        b.LG_MyBillAddress__c = address.id;
        b.LG_MyBillBillingSysAccId__c = 'Test_ID';
        b.csconta__Account__c = acc.id;
        b.LG_MyBillExists__c = true;
		newData.add(b);
		insert newData;
        
        //Billing Account with LG_MyBillBillingSysAccId__c = null
        List<csconta__Billing_Account__c> nullsync = new List<csconta__Billing_Account__c>();
		csconta__Billing_Account__c bill = LG_GeneralTest.createBillingAccount('SFDT-59 Bill1', acc.Id, true, false);
        bill.LG_MyBillAccount__c = tmpContact.id;
        bill.LG_MyBillAddress__c = address.id;
        bill.LG_MyBillBillingSysAccId__c = null;
        bill.csconta__Account__c = acc.id;
        bill.LG_MyBillExists__c = true;
		nullsync.add(bill);
		insert nullsync;
        
        //Billing Account with LG_MyBillAddress__c = null
        List<csconta__Billing_Account__c> nulladdr = new List<csconta__Billing_Account__c>();
		csconta__Billing_Account__c b2 = LG_GeneralTest.createBillingAccount('SFDT-59 Bill1', acc.Id, true, false);
        b2.LG_MyBillAccount__c = tmpContact.id;
        b2.LG_MyBillAddress__c = null;
        b2.LG_MyBillBillingSysAccId__c = 'Test_ID';
        b2.csconta__Account__c = acc.id;
        b2.LG_MyBillExists__c = true;
		nulladdr.add(b2);
		insert nulladdr;
        
        //Billing Account with LG_MyBillAccount__c = null
        List<csconta__Billing_Account__c> nullacc = new List<csconta__Billing_Account__c>();
		csconta__Billing_Account__c b3 = LG_GeneralTest.createBillingAccount('SFDT-59 Bill1', acc.Id, true, false);
        b3.LG_MyBillAccount__c = null;
        b3.LG_MyBillAddress__c = address.id;
        b3.LG_MyBillBillingSysAccId__c = 'Test_ID';
        b3.csconta__Account__c = acc.id;
        b3.LG_MyBillExists__c = true;
		nullacc.add(b3);
		insert nullacc;
        
        
        test.startTest();
        LG_ValidateMyBillDetails.handle(newData);
        LG_ValidateMyBillDetails.handle(nullsync);
        LG_ValidateMyBillDetails.handle(nulladdr);
        LG_ValidateMyBillDetails.handle(nullacc);
        test.stopTest();
        
    }
}