src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>csconta__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending activation</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending disconnection</fullName>
                </value>
                <value>
                    <fullName>Disconnected</fullName>
                </value>
		<value>
                    <fullName>Deactivation Requested</fullName>
                </value>
		<value>
                    <fullName>Deactivation Pending</fullName>
                </value>
		<value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>LG_ServiceStatus__c</fullName>
        <description>Pick-list to save the status of the service provisioning.</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                  <fullName>LG_SecondaryProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services (Secondary Product Configuration)</relationshipLabel>
        <relationshipName>Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Activation_Date__c</fullName>
        <description>The date of activation.</description>
        <inlineHelpText>The date of activation.</inlineHelpText>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csord__Deactivation_Date__c</fullName>
        <description>The date of deactivation.</description>
        <inlineHelpText>The date of deactivation.</inlineHelpText>
        <label>Deactivation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csconta__Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Billing Account to use for this Subscription.</description>
        <inlineHelpText>The Billing Account to use for this Subscription.</inlineHelpText>
        <label>Billing Account</label>
        <referenceTo>csconta__Billing_Account__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UM_Deactivate_Billing_Account.cls
global class UM_Deactivate_Billing_Account{

 public static String deactivateStr = 'DeactivateBA';

    /**Method for changing the status of BA object as 'Deactivation Requested' (BU-234)**/
    webservice static String deactivateBA(String billingId){
        
        System.debug('InsideDeactivateMethod@@'+billingId);   
        Boolean deactivationReq =false;
        Boolean invalidServices =true;
        list<csord__Service__c> serviceList = [SELECT id, csord__Activation_Date__c, csord__Deactivation_Date__c
                                                       FROM csord__service__c
                                                       WHERE csord__Subscription__r.csconta__Billing_Account__c =:billingId];
        System.debug('serviceList@@'+serviceList.size()); 
        
 
                                                       
        list<csord__Service__c> filteredServiceList = [SELECT id, csord__Activation_Date__c, csord__Deactivation_Date__c
                                                       FROM csord__service__c
                                                       WHERE csord__Subscription__r.csconta__Billing_Account__c =:billingId
                                                       AND (LG_ServiceStatus__c != 'Active')  AND (csord__Deactivation_Date__c!=null)];                                                      
        System.debug('filteredServiceList @@'+filteredServiceList.size());
       
       csconta__Billing_Account__c billingObj = [Select id,csconta__Status__c from csconta__Billing_Account__c where Id =:billingId];
       
           if (!serviceList.isEmpty() )
           {
          
                   if ((serviceList.size() == filteredServiceList.size()) && (billingObj.csconta__Status__c != 'Deactivation Requested') 
                   && (billingObj.csconta__Status__c != 'Deactivation Pending') && (billingObj.csconta__Status__c != 'Inactive'))
                   {
                      System.debug('@if');
                      billingObj.csconta__Status__c = 'Deactivation Requested';
                      update billingObj;
                      deactivateStr = 'Deactivate';
                      deactivationReq = true;
                   }
                   else if (serviceList.size() != filteredServiceList.size()){
                        System.debug('@1stElseif');
                        deactivateStr = 'Error';
                   }
                   else if ((serviceList.size() == filteredServiceList.size()) && (billingObj.csconta__Status__c == 'Deactivation Requested')){
                        System.debug('@2ndElseif');
                        deactivateStr = 'Already Deactivated';
                        deactivationReq = true;
                   } 
                   else if ((serviceList.size() == filteredServiceList.size()) && (billingObj.csconta__Status__c == 'Deactivation Pending')){
                        System.debug('@3rdElseif');
                        deactivateStr = 'Already Deact Pending';
                        deactivationReq = true;
                   } 
                     else if ((serviceList.size() == filteredServiceList.size()) && (billingObj.csconta__Status__c == 'Inactive')){
                        System.debug('@4thElseif');
                        deactivateStr = 'Already Inactive';
                        deactivationReq = true;
                   } 
         
         csconta__Billing_Account__c billingAccObj = [Select id,csconta__Status__c from csconta__Billing_Account__c where Id =:billingId];
              
                   if (deactivationReq == true )
                   {
                     System.debug('@deactivationReqif-->');
                         for(csord__Service__c serviceObj: filteredServiceList )
                         {
                               if (serviceObj.csord__Deactivation_Date__c >=Date.today())
                               {
                                 System.debug('@DATE_SERVDEACTIVATION-->');
                                 invalidServices = false;
                               }
                         } 
                         
                         if (invalidServices == true && (billingAccObj.csconta__Status__c == 'Deactivation Requested'))
                         {
                           System.debug('@invalidServicesIf-->');
                          // UM_KenanAccountSyncCtrl.createCeaseKenanBillinAcc(billingId);
                          deactivateStr = 'Invoke API';
                          
                         }
                       
                   }
                   
                } 
           else 
            {
              System.debug('@No Subscriptions/Services present');
              deactivateStr = 'No linked Services';
            }
            
           /*  if (deactivationReq == true ){
             UM_DeactivateBA_Batch batch = new UM_DeactivateBA_Batch(billingId);
             Database.executeBatch(batch);
             } */
    return deactivateStr;
    }
}