src/objects/csconta__Billing_Account__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_IsAccountSynced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Account Synced</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <displayFormat>BA-{0000000}</displayFormat>
        <label>Billing Account Sequence</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UM_ContactTriggerHandler.cls
public class UM_ContactTriggerHandler {

    public static void executeAfterUpdate(list<Contact> newContacts, map<Id,Contact> oldContacts){
        set<id> updatedContacts = new set<id>();
        for(contact c : newContacts){
        	if((c.FirstName!= oldContacts.get(c.id).Firstname) || (c.LastName!= oldContacts.get(c.id).Lastname))    
            	updatedContacts.add(c.id);	
        }
        updateBillingAccountFlag(newContacts);
    }
    
    private static void updateBillingAccountFlag(list<Contact> contacts){
        list<csconta__Billing_Account__c> billingAccounts = [select id,UM_IsAccountSynced__c from csconta__Billing_Account__c
                                                            	where Billing_Contact__c in :contacts];
        for(csconta__Billing_Account__c ba : billingAccounts)
            ba.UM_IsAccountSynced__c=true;
        
        update billingAccounts;
        
    }
}