src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>cscrm__City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__State_Province__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_PhoneNumbersIntegrationVariables__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for keeping a settings of Phone Numbers Integration for fetching Available Numbers - number of Phone Numbers fetched from the Kramer system.. etc.</description>
    <fields>
        <fullName>LG_Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Phone Numbers Integration Variables</label>
</CustomObject>

src/classes/UM_NetworkOperatorsListCtrlTest.cls
@isTest
public class UM_NetworkOperatorsListCtrlTest {

	@testSetup private static void setupData(){
		cscrm__Address__c address = new cscrm__Address__c();
		address.cscrm__City__c = 'Test';
		address.cscrm__Country__c= 'Test';
		address.cscrm__State_Province__c= 'Test';
		address.cscrm__Street__c= 'Test';
		address.cscrm__Zip_Postal_Code__c= 'Test';
		insert address;
		list<LG_PhoneNumbersIntegrationVariables__c> variables = new list<LG_PhoneNumbersIntegrationVariables__c>();

		LG_PhoneNumbersIntegrationVariables__c setting = new LG_PhoneNumbersIntegrationVariables__c();
		setting.name = 'LG_NumberStatusAvailable';
		setting.LG_Value__c = 'AVAILABLE';

		variables.add(setting);

		setting = new LG_PhoneNumbersIntegrationVariables__c();
		setting.name = 'LG_NumberStatusAllocated';
		setting.LG_Value__c = 'ALLOCATED';
		variables.add(setting);

		setting = new LG_PhoneNumbersIntegrationVariables__c();
		setting.name = 'LG_NumberOfShownNumbers';
		setting.LG_Value__c = '20';
		variables.add(setting);
		insert variables;

	}

	public static testMethod void testGetOperatorList() {
		cscrm__Address__c addr = [select id from cscrm__Address__c limit 1];
		ApexPages.currentPage().getParameters().put('premiseId',addr.id);
		UM_NetworkOperatorsListCtrl controller = new UM_NetworkOperatorsListCtrl();

		map<string,wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier> operators = new map<string,wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier> ();

		list<wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier> carriers = getOperatorData();
		operators.put(carriers[0].mainPortId,carriers[0]);

		controller.networkOperators = operators;

		System.assertEquals(carriers[0].mainPortId,controller.getNetworkOperatorsList()[0].mainPortId);
	}

	public static list<wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier> getOperatorData(){
		list<wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier> carriers = new list<wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier>();
		wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier carrier = new wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier();
		carrier.mainPortId = '123123';
		carrier.longName = 'Test Operator';
		carriers.add(carrier);
		return carriers;
	}


}