src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>cscrm__Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>UM_NumberOfOpenPortingProcesses__c</fullName>
        <label>Number of Open Porting Processes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csordtelcoa__Orders_Subscriptions_Options__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>csordtelcoa__Service_Number_Prefix__c</fullName>
        <defaultValue>&quot;SVC-&quot;</defaultValue>
        <label>Service Number Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Subscription_Number_Prefix__c</fullName>
        <defaultValue>&quot;SN-&quot;</defaultValue>
        <label>Subscription Number Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Orders &amp; Subscriptions Options</label>
</CustomObject>

src/objects/UM_PortingProcess__c.object
<CustomObject>
    <fields>
        <fullName>UM_Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UM_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal Clarification</fullName>
                    <default>true</default>
                    <label>Internal Clarification</label>
                </value>
                <value>
                    <fullName>Waiting for Customer</fullName>
                </value>
                <value>
                    <fullName>Order Complete</fullName>
                </value>
                <value>
                    <fullName>Waiting for Carrier</fullName>
                </value>
                <value>
                    <fullName>Response from Carrier</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_SubStage__c</fullName>
        <label>Sub-Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UM_Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal Clarification</fullName>
                    <default>true</default>
                    <label>Internal Clarification</label>
                </value>
                <value>
                    <fullName>Waiting for Customer</fullName>
                </value>
                <value>
                    <fullName>Response from Customer Pending</fullName>
                </value>
                <value>
                    <fullName>Response from Customer Pending Overdue</fullName>
                </value>
                <value>
                    <fullName>Period for Response from Customer Expired</fullName>
                </value>
                <value>
                    <fullName>Ready for Porting</fullName>
                </value>
                <value>
                    <fullName>Ready for Data Transmission</fullName>
                </value>
                <value>
                    <fullName>Installation not Performed</fullName>
                </value>
                <value>
                    <fullName>Transmission Failed</fullName>
                </value>
                <value>
                    <fullName>Waiting for Carrier</fullName>
                </value>
                <value>
                    <fullName>Period for Response from Carrier Expired</fullName>
                </value>
                <value>
                    <fullName>Period for Response from Carrier Expired Overdue</fullName>
                </value>
                <value>
                    <fullName>Positive Confirmation</fullName>
                </value>
                <value>
                    <fullName>Temporal rejection</fullName>
                </value>
                <value>
                    <fullName>Final rejection</fullName>
                </value>
                <value>
                    <fullName>Closed by Agent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Processing Overdue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Porting Process</label>
    <nameField>
        <label>Porting Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porting Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UM_PortingProcessTriggerHandlerTest.cls
@isTest
public with sharing class UM_PortingProcessTriggerHandlerTest {
    
    @testsetup
	private static void setupTestData()
	{
		No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
		noTriggers.Flag__c = true;
		noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
		upsert noTriggers;

		csord__Order_Request__c coreq = new csord__Order_Request__c(csord__Module_Name__c = 'Test', csord__Module_Version__c = '1.0');
		insert coreq;
		
		csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = 'TestIdent', csord__Order_Request__c = coreq.Id);
		insert sub;
		
		cscrm__Address__c add=new cscrm__Address__c(cscrm__Street__c = 'TestStreet');
		insert add;
		
        csordtelcoa__Orders_Subscriptions_Options__c osOptions = new csordtelcoa__Orders_Subscriptions_Options__c();
		osOptions.csordtelcoa__Subscription_Number_Prefix__c = 'SN-';
		osOptions.csordtelcoa__Service_Number_Prefix__c = 'SVC-';
		insert osOptions;
	
		csord__Service__c service = new csord__Service__c(csord__Identification__c = 'TestIdentSub', csord__Order_Request__c = coreq.Id,
																csord__Subscription__c = sub.Id, LG_Address__c = add.Id);
		insert service;
		
		noTriggers.Flag__c = false;
		upsert noTriggers;
	}
	
	private static testmethod void testUpdatePortingProcessCountOnService(){
		csord__Service__c service=[select Id from csord__Service__c limit 1];
		test.startTest();
		UM_PortingProcess__c portProcess= LG_GeneralTest.createPortingProcess(service,'Test PP', 'open', true);
		csord__Service__c queriedService=[Select Id, UM_NumberOfOpenPortingProcesses__c from csord__Service__c where Id=:service.Id];
		system.assertEquals(1,queriedService.UM_NumberOfOpenPortingProcesses__c);
		delete portProcess;
		csord__Service__c reQueriedService=[Select Id, UM_NumberOfOpenPortingProcesses__c from csord__Service__c where Id=:service.Id];
		system.assertEquals(0,reQueriedService.UM_NumberOfOpenPortingProcesses__c);
		
		test.stopTest();
		
	}
	
	private static testMethod void testCreateKenanIDs(){
		csord__Service__c service=[select Id from csord__Service__c limit 1];
		UM_PortingProcess__c portProcess= LG_GeneralTest.createPortingProcess(service,'Test PP', 'open', true);
		test.startTest();
		portProcess.UM_Status__c='Closed';
		portProcess.UM_Stage__c='Closed';
		portProcess.UM_SubStage__c='Confirmed';		
		update portProcess;
		test.stopTest();
		
	}
}