src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>cscrm__Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>LG_ProductFamily__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Delta_Status__c</fullName>
        <label>Delta Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Continuing In Subscription</fullName>
                </value>
                <value>
                    <fullName>Added To Subscription</fullName>
                </value>
                <value>
                    <fullName>Deleted From Subscription</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>LG_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Address</label>
        <referenceTo>cscrm__Address__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order_Request__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Order Request object which introduced the latest changes to this object.</description>
        <inlineHelpText>Order Request object which introduced the latest changes to this object.</inlineHelpText>
        <label>Order Request</label>
        <referenceTo>csord__Order_Request__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KenanServiceConnection__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Authentication_Token__c</fullName>
        <label>Authentication Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_URL__c</fullName>
        <label>Connection URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>REST_Application_Base__c</fullName>
        <defaultValue>&quot;/kenan-salesforce-api&quot;</defaultValue>
        <inlineHelpText>must start with /</inlineHelpText>
        <label>REST Application Base</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Timeout__c</fullName>
        <defaultValue>&quot;120000&quot;</defaultValue>
        <inlineHelpText>Number in milliseconds</inlineHelpText>
        <label>Session Timeout</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>KenanServiceConnection</label>
</CustomObject>

src/objects/UM_NumberBlock__c.object
<CustomObject>
    <fields>
        <fullName>UM_BillingStatus__c</fullName>
        <label>Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Active in Billing</fullName>
                    <default>true</default>
                    <label>Not Active in Billing</label>
                </value>
                <value>
                    <fullName>Active in Billing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_CDRIDNumber__c</fullName>
        <label>CDR ID Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_NumberRangeService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Number Range Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Number Blocks</relationshipLabel>
        <relationshipName>Number_Blocks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Provisioning</fullName>
                </value>
                <value>
                    <fullName>Porting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Number Block</label>
    <nameField>
        <label>Number Block Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Number Blocks</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UM_PortingProcess__c.object
<CustomObject>
    <fields>
        <fullName>UM_NumberRangeService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Number Range Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Porting Processes (Number Range Service)</relationshipLabel>
        <relationshipName>Porting_Processes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UM_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal Clarification</fullName>
                    <default>true</default>
                    <label>Internal Clarification</label>
                </value>
                <value>
                    <fullName>Waiting for Customer</fullName>
                </value>
                <value>
                    <fullName>Order Complete</fullName>
                </value>
                <value>
                    <fullName>Waiting for Carrier</fullName>
                </value>
                <value>
                    <fullName>Response from Carrier</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_SubStage__c</fullName>
        <label>Sub-Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>UM_Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal Clarification</fullName>
                    <default>true</default>
                    <label>Internal Clarification</label>
                </value>
                <value>
                    <fullName>Waiting for Customer</fullName>
                </value>
                <value>
                    <fullName>Response from Customer Pending</fullName>
                </value>
                <value>
                    <fullName>Response from Customer Pending Overdue</fullName>
                </value>
                <value>
                    <fullName>Period for Response from Customer Expired</fullName>
                </value>
                <value>
                    <fullName>Ready for Porting</fullName>
                </value>
                <value>
                    <fullName>Ready for Data Transmission</fullName>
                </value>
                <value>
                    <fullName>Installation not Performed</fullName>
                </value>
                <value>
                    <fullName>Transmission Failed</fullName>
                </value>
                <value>
                    <fullName>Waiting for Carrier</fullName>
                </value>
                <value>
                    <fullName>Period for Response from Carrier Expired</fullName>
                </value>
                <value>
                    <fullName>Period for Response from Carrier Expired Overdue</fullName>
                </value>
                <value>
                    <fullName>Positive Confirmation</fullName>
                </value>
                <value>
                    <fullName>Temporal rejection</fullName>
                </value>
                <value>
                    <fullName>Final rejection</fullName>
                </value>
                <value>
                    <fullName>Closed by Agent</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Processing Overdue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Porting Process</label>
    <nameField>
        <label>Porting Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porting Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UM_KenanIDTerminatorTest.cls
@isTest
public class UM_KenanIDTerminatorTest {
    
    @testsetup
    private static void setupTestData()
    {
        No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
        noTriggers.Flag__c = true;
        noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
        upsert noTriggers;
        
        csord__Order_Request__c coreq = new csord__Order_Request__c(csord__Module_Name__c = 'TestM', csord__Module_Version__c = '1.0');
        insert coreq;
        
        csord__Subscription__c sub = new csord__Subscription__c(csord__Identification__c = 'TestIdentM', csord__Order_Request__c = coreq.Id);
        insert sub;
        
        cscrm__Address__c add= new cscrm__Address__c(cscrm__Street__c = 'TestStreetM');
        insert add;
        csord__Service__c intService = new csord__Service__c(csord__Identification__c = 'TestIdentSubM', csord__Order_Request__c = coreq.Id,
                                                             csord__Subscription__c = sub.Id, LG_Address__c = add.Id, LG_ProductFamily__c = 'Internet');
        insert intService;
        
        csord__Service__c numRangeService = new csord__Service__c(csord__Identification__c = 'TestIdentSubM', csord__Order_Request__c = coreq.Id,
                                                                  csord__Subscription__c = sub.Id, LG_Address__c = add.Id,csord__Service__c=intService.id, LG_ProductFamily__c = 'Number Range');
        insert numRangeService;
        
        UM_NumberBlock__c numberBlock = new UM_NumberBlock__c(UM_NumberRangeService__c = numRangeService.id);
        numberBlock.UM_CDRIDNumber__c = '20(0123) 123 1231';
        insert numberBlock;
        
        Id portInRecordType = Schema.SObjectType.UM_PortingProcess__c.getRecordTypeInfosByName().get('Port-In').getRecordTypeId();
        UM_PortingProcess__c portingProcess = new UM_PortingProcess__c( UM_NumberRangeService__c = numRangeService.id,RecordTypeId=portInRecordType );
		portingProcess.UM_Status__c = 'Closed';
        portingProcess.UM_Stage__c = 'Closed';
        portingProcess.UM_SubStage__c = 'Confirmed';
        insert portingProcess;
        
        noTriggers.Flag__c = false;
        
        KenanServiceConnection__c ksc = new KenanServiceConnection__c();
        ksc.Authentication_Token__c = 'Basic YWRtaW46YWRtaW4=';
        ksc.Session_Timeout__c = '120000';
        ksc.Connection_URL__c = 'https://kenan-dev-pubelb-amdocs-1924041402.eu-central-1.elb.amazonaws.com';
        ksc.REST_Application_Base__c = '/kenan-salesforce-api/rest';
        insert ksc;
        
        Account a = new Account();
        a.Name = 'Sample Test AccountM';
        insert a;
        
        upsert noTriggers;
    }
    
    public static testMethod void testExecute(){
    	csord__Service__c numService = [select id,csordtelcoa__Delta_Status__c from csord__Service__c where LG_ProductFamily__c = 'Number Range' limit 1 ];
        numService.csordtelcoa__Delta_Status__c = 'Deleted From Subscription';
            
        Test.startTest();
        
        update numService;
        
        Test.stopTest();
        
        System.assertEquals('Not Active in Billing', [select id, UM_BillingStatus__c from UM_NumberBlock__c limit 1].UM_BillingStatus__c);
        
    }

}