src/objects/cscrm__Address__c.object
<CustomObject>
    <description>The Address object holds details of addresses associated with an Account.  An Address can be used for multiple purposes. In a B2B example an Address could be all of the following:
- the registered office address for the Account;
- the billing address; and
- an installation address for a specific technical service.</description>
    <fields>
        <fullName>cscrm__Address_Details__c</fullName>
        <formula>IF( ISBLANK(cscrm__Street__c) , &apos;&apos;, cscrm__Street__c +&apos;,&apos;) + 
IF( ISBLANK(cscrm__State_Province__c) , &apos;&apos;, &apos; &apos; + cscrm__State_Province__c +&apos;,&apos;) + 
IF( ISBLANK(cscrm__City__c) , &apos;&apos;, &apos; &apos; + cscrm__City__c +&apos;,&apos;) + 
IF( ISBLANK(cscrm__Zip_Postal_Code__c) , &apos;&apos;, &apos; &apos; + cscrm__Zip_Postal_Code__c +&apos;,&apos;) + 
IF( ISBLANK(cscrm__Country__c) , &apos;&apos;, &apos; &apos; + cscrm__Country__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__State_Province__c</fullName>
        <label>State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cscrm__Zip_Postal_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UM_NetworkOperatorsListCtrl.cls
public with sharing class UM_NetworkOperatorsListCtrl {
	public string region {get;set;}
	public map<string,wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier> networkOperators{get;set;}

	public UM_NetworkOperatorsListCtrl() {
		if(ApexPages.currentPage().getParameters().get('premiseId')!=null){
			Id premiseId = ApexPages.currentPage().getParameters().get('premiseId');
			if(premiseId!=null){
	       		cscrm__Address__c premiseaddress=[SELECT cscrm__Address_Details__c,cscrm__Zip_Postal_Code__c,cscrm__State_Province__c FROM cscrm__Address__c WHERE ID = :premiseId];
	        	region = premiseaddress.cscrm__State_Province__c;
			}
		}
	}

	public list<wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier> getNetworkOperatorsList(){
		list<wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier> operators = new list<wwwDialogikaDeWsdlInfportSchemasSf.tFnCarrier>();
		networkOperators = LG_NumberReservationUtil.fetchNetworkOperatorsList(region);

		if(networkOperators!=null && !networkOperators.isEmpty()){
			operators = networkOperators.values();
			operators.sort();
			return operators;
		}else{
			return null;
		}

	}
}