src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_DecompositionCriteria__c</fullName>
        <description>Used as a criteria for grouping the services to the suborders</description>
        <label>Decomposition Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LG_DecompositionCriteria</valueSetName>
        </valueSet>
    </fields>
    
    <fields>
        <fullName>LG_Suborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services (Suborder)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_Cancellation__c</fullName>
        <label>Cancellation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Daily</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_DependsOnService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Depends On Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Services (Depends On)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Activation_Date__c</fullName>
        <description>The date of activation.</description>
        <inlineHelpText>The date of activation.</inlineHelpText>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_DecompositionCriteria__c</fullName>
        <label>Decomposition Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LG_DecompositionCriteria</valueSetName>
        </valueSet>
    </fields>
    
     <fields>
        <fullName>LG_type_Of_Services__c</fullName>
        <label>Type Of Services</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Solution in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSPOFA__Orchestration_Process__c.object
<CustomObject>
    <fields>
        <fullName>CSPOFA__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initializing</fullName>
                    <default>true</default>
                    <label>Initializing</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_DecompositionCriteria__c.object
<CustomObject>
    <fields>
        <fullName>LG_DecompositionCriteria__c</fullName>
        <description>Used as a criteria for grouping the services to the suborders</description>
        <label>Decomposition Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Set 1 - On-Net</fullName>
                </value>
                <value>
                    <fullName>Set 2 - Legacy</fullName>
                </value>
                <value>
                    <fullName>Set 3 - Mobile</fullName>
                </value>
                <value>
                    <fullName>Set 4</fullName>
                </value>
                <value>
                    <fullName>Set 5 - CaMa Internet</fullName>
                </value>
                <value>
                    <fullName>Set 6 - CaMa Dependent</fullName>
                </value>
                <value>
                    <fullName>Set 7 - JIRA Fiber</fullName>
                </value>
                <value>
                    <fullName>Set 8 - CS Voice</fullName>
                </value>
                <value>
                    <fullName>Set 9 - CaMa Bearer</fullName>
                </value>
                <value>
                    <fullName>Set 10 - VoiceWorks</fullName>
                </value>
                <value>
                    <fullName>Set 11 - Engineers</fullName>
                </value>
                <value>
                    <fullName>Set 12 - JIRA Orchestrated</fullName>
                </value>
                <value>
                    <fullName>Set 13 - JIRA Bearer</fullName>
                </value>
                <value>
                    <fullName>Set 14 - CaMa Mobile</fullName>
                </value>
                <value>
                    <fullName>Set 15 - CaMa Manual</fullName>
                </value>
                <value>
                    <fullName>Set 16 - CaMa OI Manual</fullName>
                </value>
                <value>
                    <fullName>Set 17 - Charges</fullName>
                </value>
                <value>
                    <fullName>Set 18 - Direct to Kenan</fullName>
                </value>
                <value>
                    <fullName>Set 19 - Additional Charges</fullName>
                </value>
                <value>
                    <fullName>Set 20 - BDS Site Process</fullName>
                </value>
                <value>
                    <fullName>Set 21 - VPN Process</fullName>
                </value>
                <value>
                    <fullName>Set 22 - Parent/Category Only</fullName>
                </value>
                <value>
                    <fullName>Set 23 - UM CaMa Bridge Mode</fullName>
                </value>
                <value>
                    <fullName>Set 24 - UM JIRA Fiber Bridge Mode</fullName>
                </value>
                <value>
                    <fullName>Set 17 - BDS Charges</fullName>
                </value>
                <value>
                    <fullName>Set 17 - HPBX Charges</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Decomposition Criteria</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>Decomposition Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Decomposition Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/LG_DecompositionCriteria.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Set 1 - On-Net</fullName>
    </customValue>
    <customValue>
        <fullName>Set 2 - Off-Net</fullName>
    </customValue>
    <customValue>
        <fullName>Set 3 - Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Set 4</fullName>
    </customValue>
    <customValue>
        <fullName>Set 6 - CaMa Dependent</fullName>
    </customValue>
    <customValue>
        <fullName>Set 7 - JIRA Fiber</fullName>
    </customValue>
    <customValue>
        <fullName>Set 10 - VoiceWorks</fullName>
    </customValue>
    <customValue>
        <fullName>Set 11 - Engineers</fullName>
    </customValue>
    <customValue>
        <fullName>Set 5 - CaMa Internet</fullName>
    </customValue>
    <customValue>
        <fullName>Set 8 - CS Voice</fullName>
    </customValue>
    <customValue>
        <fullName>Set 9 - CaMa Bearer</fullName>
    </customValue>
    <customValue>
        <fullName>Set 5 - No Grouping</fullName>
    </customValue>
    <customValue>
        <fullName>Set 12 - JIRA Orchestrated</fullName>
    </customValue>
    <customValue>
        <fullName>Set 13 - JIRA Bearer</fullName>
    </customValue>
    <customValue>
        <fullName>Set 14 - CaMa Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Set 15 - CaMa Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Set 16 - CaMa OI Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Set 17 - Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 18 - Direct to Kenan</fullName>
    </customValue>
    <customValue>
        <fullName>Set 22 - Parent/Category Only</fullName>
    </customValue>
    <customValue>
        <fullName>Set 24 - UM JIRA Fiber Bridge Mode</fullName>
    </customValue>
    <customValue>
        <fullName>Set 23 - UM CaMa Bridge Mode</fullName>
    </customValue>
    <customValue>
        <fullName>Set 21 - VPN Process</fullName>
    </customValue>
    <customValue>
        <fullName>Set 20 - BDS Site Process</fullName>
    </customValue>
    <customValue>
        <fullName>Set 19 - Additional Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 25 - Business Anywhere</fullName>
    </customValue>
    <customValue>
        <fullName>Set 17 - HBPX Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 26 - UM Managed WLAN</fullName>
    </customValue>
    <customValue>
        <fullName>Set 17 - BDS Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 10 - SIPWISE</fullName>
    </customValue>
    <description>Used as a criteria for grouping the services to the suborders</description>
    <masterLabel>Decomposition Criteria</masterLabel>
</GlobalValueSet>

src/classes/LG_ServiceCancellableTypeStep.cls
/**
* This class is to check if HPBX servcies are Cancellable daily or Monthly
* 
* @author Alisha
* @ticket SFOM-2566
* @since  21/2/2018
*/
global class LG_ServiceCancellableTypeStep implements CSPOFA.ExecutionHandler{    

    public  List<sObject> process(List<SObject> data) {
       List<sObject> result = new List<sObject>();
       
        //collect the data for all steps passed in, if needed process steps
        List<CSPOFA__Orchestration_Step__c> stepList =  (List<CSPOFA__Orchestration_Step__c>)data;
    
        Set<Id> processesIds = new Set<Id>();
        for (CSPOFA__Orchestration_Step__c step : stepList) {
          processesIds.add(step.CSPOFA__Orchestration_Process__c);
        }

    updateCancellableType(processesIds);

    for (CSPOFA__Orchestration_Step__c step : stepList) {
      step.CSPOFA__Status__c         = 'Complete';
      step.CSPOFA__Completed_Date__c = Date.today();
      result.add(step);
    }

    return result;
    }
    
    /**
   * Scans the Service records related to the processes/solutions
   * being executed/processed and check if HPBX servcies are Cancellable daily or Monthly or Both
   * @param  Set<Id> processesIds
   * @author Alisha
   * @ticket SFOM-2566
   * @since  21/2/2018
   */
  
  @TestVisible
  public void updateCancellableType(Set<Id> processesIds){
        List<csord__Service__c> servicesToUpdate = new List<csord__Service__c>();
        list<csord__Solution__c> solutionListToUpdate = new list<csord__Solution__c>();
        list<csord__Solution__c> solutionList = new list<csord__Solution__c>();
       	Set<String> setOfService=new Set<String>();
       	String Daily='';
       	String Monthly='';
        solutionList = [SELECT Id,LG_type_Of_Services__c,
                      (SELECT Id,csord__Status__c,csord__Activation_Date__c,UM_Cancellation__c,LG_DecompositionCriteria__c FROM Services__r
                      )
                      FROM csord__Solution__c
                      WHERE Id IN (SELECT LG_Solution__c
                             FROM CSPOFA__Orchestration_Process__c
                             WHERE Id IN :processesIds)];                      
   if(solutionList.size()>0)
        {
          for (csord__Solution__c sol : solutionList )
          {
            if (sol.Services__r.size() > 0)
            {
                for (csord__Service__c service : sol.Services__r)
                {
                    if(service.LG_DecompositionCriteria__c!=null){
                        setOfService.add(service.LG_DecompositionCriteria__c);
                    }
                    if(service.UM_Cancellation__c!=null && service.UM_Cancellation__c=='Daily'){
                       Daily='Daily';
                      
                    }      
                    else if(service.UM_Cancellation__c!=null && service.UM_Cancellation__c=='Monthly'){
                       Monthly='Monthly';
                    }
                }
            }
                for(String s:setOfService)
                 {
                     if(sol.LG_type_Of_Services__c==null){
                     	sol.LG_type_Of_Services__c ='['+s+']'+',';
                     }
                     else{
                         sol.LG_type_Of_Services__c +='['+s+']'+',';
                     }
                 }
                if(!String.isBlank(daily))
                {
                     	sol.LG_type_Of_Services__c+=daily+',';   
                }
                if(!String.isBlank(Monthly))
                {
                     sol.LG_type_Of_Services__c+=Monthly+',';   
                }
                sol.LG_type_Of_Services__c=sol.LG_type_Of_Services__c.removeEnd(',');
                solutionListToUpdate.add(sol);
            }
        }
    if (solutionListToUpdate.size() > 0) {
            Update solutionListToUpdate;
        }
    }
    
}