src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>csordtelcoa__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_ValidateOpportunity__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Validate Opportunity</label>
</CustomObject>

src/classes/LG_SubmitOrderPreCheck.cls
/**
 * Class for Validation before SUbmit Order
 * called (on click of Validate order Button on Oppty Detail Page.
 *part of SFOM-81 
 * @author Alisha
 * @since  27/02/2017
 */


global class LG_SubmitOrderPreCheck{
    //added as part of sfom-81
    public static LG_ValidateOpportunityUtil validatorClass=null;
    public static LG_ValidateOpportunity__c val = LG_ValidateOpportunity__c.getInstance(UserInfo.getUserId());
    public static string getClass_name(){
      if(val!=null &&val.Class_Name__C!=null){
          Type appropriateClass = Type.forName(val.Class_Name__C);
          validatorClass= (LG_ValidateOpportunityUtil) appropriateClass.newInstance();
         
          system.debug('validator=='+validatorClass);
            }
        return null;
    }
    webservice static Integer countOrder(Id recId){
        Integer orderCount =0;
        System.debug('------Method called on button click.....');
        orderCount=[select count() from csord__Order__c where csordtelcoa__Opportunity__c=:recId];
    
        return orderCount;
    }

   
    webservice static Integer prodBaksetPresent(Id recId){
       getClass_name(); 
       Integer prodBasketCount=1; 
       prodBasketCount=validatorClass.checkProductBasket(recId);
       
       system.debug('prodBasketCount=='+prodBasketCount);
       
       return prodBasketCount;

    }
}