src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>LG_MarketSegment__c</fullName>
        <label>Market Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>DEPRECATED. Defines the status of the order through fulfilment to delivery.</description>
        <inlineHelpText>DEPRECATED. Use Status2__c.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Provisioning</fullName>
                    <default>true</default>
                    <label>In Provisioning</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Not Provisioned</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_MarketSegment__c</fullName>
        <label>Market Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
	<fields>
        <fullName>LG_RootOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services (Root Order)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Service.</description>
        <inlineHelpText>The parent Order of this Service.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LG_RootOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Root Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services (Root Order)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Subscription.</description>
        <inlineHelpText>The parent Order of this Subscription.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Subscription in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_ScheduledServiceBulkDelete.cls
/**
* Remove Orders and Line Items for Soho and Mobile
* 
* @author Petar Miletic
* @ticket SFDT-581 - Remove Orders and Line Items for Soho and Mobile
* @since  30/03/2016
*/
global class LG_ScheduledServiceBulkDelete implements Database.Batchable<sObject>, Schedulable {

    // Constructor
    global LG_ScheduledServiceBulkDelete () {
        
    }

    // Schedulable interface method
    global void execute(SchedulableContext SC) {
        Database.executeBatch(new LG_ScheduledServiceBulkDelete(), 200);
    }

    // Database.Batchable methods
    global Database.QueryLocator start(Database.BatchableContext batchableContext) {
        
        Set<string> deleteName = new Set<string> { 'Mobile' };
        Set<string> deleteStatus = new Set<string> { 'Service In Delivery' };
        Set<string> deleteSegment = new Set<string> { 'SoHo' };
        Set<string> toBeDeleted = new Set<string> { 'SoHo - To Be Deleted' };
        
        String query = 'SELECT Id, Name, csord__Subscription__c, csord__Order__c, LG_RootOrder__c, csord__Status__c, LG_MarketSegment__c FROM csord__Service__c WHERE (csord__Subscription__r.csord__Status__c IN :toBeDeleted) OR ((Name IN :deleteName AND LG_MarketSegment__c IN :deleteSegment) OR (Name IN :deleteName AND LG_MarketSegment__c NOT IN :deleteSegment AND csord__Status__c IN :deleteStatus))';
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext batchableContext, List<csord__Service__c> scope) {

        Set<Id> orderIds = new Set<Id>();
        Set<Id> subscriptionIds = new Set<Id>();
        
        for (csord__Service__c s :scope) {
            
            if (s.LG_RootOrder__c != null) {
                orderIds.add(s.LG_RootOrder__c);
            }
            
            if (s.csord__Subscription__c != null) {
                subscriptionIds.add(s.csord__Subscription__c);
            }
        }

        delete scope;
        
        // Data Cleanup
        DeleteEmptySubscriptions(subscriptionIds);
        DeleteEmptyOrders(orderIds);
    }

    global void finish(Database.BatchableContext batchableContext) {
        
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :batchableContext.getJobId()];

        // Send an email to the Apex job's submitter notifying of job completion.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        String[] toAddresses = new String[] {a.CreatedBy.Email};
        mail.setToAddresses(toAddresses);
        mail.setSubject('Service Bulk Delete, status: ' + a.Status);
        mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems + ' batches with '+ a.NumberOfErrors + ' failures.');
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    /*
     * Delete empty Subscriptions, that is Subscriptions with zero children
    */
    private void DeleteEmptySubscriptions(Set<Id> subscriptionIds) {
        
        Set<Id> currentSubscriptionIds = new Set<Id>();
        for (csord__Service__c s : [SELECT Id, csord__Subscription__c FROM csord__Service__c WHERE csord__Subscription__c IN :subscriptionIds]){
            currentSubscriptionIds.add(s.csord__Subscription__c);
        }

        // Remove Ids that are in use, Subscriptions that still have children
        subscriptionIds.removeAll(currentSubscriptionIds);

        if (subscriptionIds.size() > 0) {
            
            List<csord__Subscription__c> subscriptions = [SELECT Id, Name FROM csord__Subscription__c WHERE Id IN :subscriptionIds];
            
            delete subscriptions;
        }
    }
    
    /*
     * Delete empty Orders, that is Orders with zero children
    */
    private void DeleteEmptyOrders(Set<Id> orderIds) {
        
        Set<Id> currentOrderIds = new Set<Id>();
        for (csord__Subscription__c s : [SELECT Id, csord__Order__c FROM csord__Subscription__c WHERE csord__Order__c IN :orderIds]){
            currentOrderIds.add(s.csord__Order__c);
        }

        // Remove Ids that are in use, Orders that still have children
        orderIds.removeAll(currentOrderIds);

        // Check if ordre is used in Services
        currentOrderIds.clear();
        for (csord__Service__c se : [SELECT Id, csord__Order__c, LG_RootOrder__c FROM csord__Service__c WHERE LG_RootOrder__c IN :orderIds]){
            currentOrderIds.add(se.LG_RootOrder__c);
        }

        // Remove the ones that are still in use
        orderIds.removeAll(currentOrderIds);

        // Delete the rest
        if (orderIds.size() > 0) {
            
            List<csord__Order__c> orders = [SELECT Id, Name FROM csord__Order__c WHERE Id IN :orderIds];
            
            delete orders;
        }
    }
}