src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Action__c</fullName>
        <formula>IF( ISPICKVAL(csordtelcoa__Delta_Status__c, &apos;Continuing In Subscription&apos;) &amp;&amp; ISPICKVAL(csord__Subscription__r.csordtelcoa__Change_Type__c, &apos;Move&apos;)  , &apos;Add&apos;, IF(ISBLANK( TEXT(csordtelcoa__Delta_Status__c)) &amp;&amp; LG_AttributeValuesChanged__c, &apos;Change&apos;, IF(ISBLANK( TEXT(csordtelcoa__Delta_Status__c)), &apos;Add&apos;, IF( ISPICKVAL(csordtelcoa__Delta_Status__c, &apos;Continuing In Subscription&apos;) &amp;&amp; csordtelcoa__Product_Configuration__r.LG_AttributeValuesChanged__c , &apos;Change&apos;, CASE(TEXT(csordtelcoa__Delta_Status__c), &apos;Added To Subscription&apos;, &apos;Add&apos;, &apos;Deleted From Subscription&apos;, &apos;Delete&apos;, &apos;None&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Action</label>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>LG_ProvisioningAccountNo__c</fullName>
        <label>Provisioning Account No</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ServiceStatus__c</fullName>
        <description>Pick-list to save the status of the service provisioning.</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                  <fullName>LG_SecondaryProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services (Secondary Product Configuration)</relationshipLabel>
        <relationshipName>Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Suborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services (Suborder)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_DependsOnService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Depends On Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Services (Depends On)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
     <fields>
        <fullName>LG_DependsOnSecondaryService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Depends On Secondary Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Services (Service)</relationshipLabel>
        <relationshipName>Services3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Replaced_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replaced Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Replacement Services</relationshipLabel>
        <relationshipName>Replaced_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Replacement_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replacement Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Replaced Services</relationshipLabel>
        <relationshipName>Replacement_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_DependsOnSecondary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is set to true if the Site Service has secondary service for a solution</description>
        <label>LG_DependsOnSecondary</label>
        <type>Checkbox</type>
    </fields>
    
    <fields>
        <fullName>LG_ProvisioningAccountNo__c</fullName>
        <label>Provisioning Account No</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Solution in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <recordTypes>
        <fullName>Suborder</fullName>
        <active>true</active>
        <description>Used for decomposing order and grouping Services that can be provisioned together</description>
        <label>Suborder</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSPOFA__Orchestration_Process__c.object
<CustomObject>
    <fields>
        <fullName>CSPOFA__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initializing</fullName>
                    <default>true</default>
                    <label>Initializing</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_checkSecondaryDependentService.cls
/**
 * Check if secondary dependent service exists and accordingly
 * update the field on solution object
 * 
 * @param  Set<Id> processesIds
 * @author Navneet Sanotra
 * @ticket SFOM-2766
 * @since  12/03/2018
 */
global class LG_checkSecondaryDependentService implements CSPOFA.ExecutionHandler {

    public List<sObject> process(List<SObject> data)
    {
        List<sObject> result = new List<sObject>();

        List<CSPOFA__Orchestration_Step__c> stepList = (List<CSPOFA__Orchestration_Step__c>)data;

        Set<Id> processesIds = new Set<Id>();
        for (CSPOFA__Orchestration_Step__c step : stepList) {
            processesIds.add(step.CSPOFA__Orchestration_Process__c);
        }

        // Call method
        scanDependentServices(processesIds);

        for (CSPOFA__Orchestration_Step__c step : stepList) {
            //mark step Status, Completed Date
            step.CSPOFA__Status__c         = 'Complete';
            step.CSPOFA__Completed_Date__c = Date.today();
            result.add(step);
        }

        return result;
    }

    /**
     * Check if secondary dependent service exists for the solution and accordingly
     * update the field(LG_DependsOnSecondary__c) on solution object
     *
     * @param  Set<Id> processesIds
     * @author Navneet Sanotra
     * @ticket SFOM-2766
     * @since  12/03/2018
     */
    @TestVisible
    private void scanDependentServices(Set<Id> processesIds) {
       
        Boolean updateSol = false;
        List<csord__Solution__c> solutionsToUpdate= new List<csord__Solution__c>();
        List<csord__Solution__c> secondarySolutionsToUpdate= new List<csord__Solution__c>();
        List <Id> secondaryDependentSolutions= new List<Id>();
        List<csord__Service__c> secondaryDependentServices = new List<csord__Service__c>();
    
        List<Id> solutionIds = new List<Id>();
        List<Id> serviceIds = new List<Id>();
        List<csord__Service__c> linebackupServiceList= new List<csord__Service__c>();
        List<csord__Service__c> changedServicesList= new List<csord__Service__c>();

        // Get all data
        for (CSPOFA__Orchestration_Process__c process : [SELECT Id,
                                                         LG_Solution__c                                                         
                                                         FROM CSPOFA__Orchestration_Process__c
                                                         WHERE Id IN :processesIds AND LG_Solution__c != null]) {
            solutionIds.add(process.LG_Solution__c);
        }
        system.debug('current Solutions:' + solutionIds);
        
        
        if (!solutionIds.isEmpty()) {
            for (csord__Service__c services : [SELECT Id, Name  from csord__Service__c WHERE LG_Suborder__c IN :solutionIds]){
                serviceIds.add(services.Id);
            }
        }

        System.debug('all Services' + serviceIds);
        secondaryDependentServices = [Select Id, LG_Suborder__c, LG_Suborder__r.csord__Status__c from csord__Service__c where ID IN :serviceIds AND LG_DependsOnSecondaryService__c != null];
        System.debug('filtered Services' + secondaryDependentServices);
        for (csord__Service__c secondaryDependentService:secondaryDependentServices) {
            if (secondaryDependentService.LG_Suborder__r.csord__Status__c == 'In Progress') {
                secondaryDependentSolutions.add(secondaryDependentService.LG_Suborder__c);
            }
        }
        system.debug('secondaryDependentSolutions to check' + secondaryDependentSolutions);
        for (csord__Solution__c sols: [Select Id,LG_dependsOnSecondary__c from csord__Solution__c where Id IN:secondaryDependentSolutions]) {
            sols.LG_DependsOnSecondary__c = True;
            solutionsToUpdate.add(sols);
        }
                   //as part of DGT-118 starts
               
          if (!solutionIds.isEmpty()) {
            for (csord__Service__c services : [SELECT Id, Name, LG_Suborder__c, UM_DependsOnService__c, UM_DependsOnService__r.LG_ServiceStatus__c, UM_DependsOnService__r.LG_ProvisioningAccountNo__c,
                                                 LG_DependsOnSecondaryService__c, LG_DependsOnSecondaryService__r.LG_ServiceStatus__c, LG_DependsOnSecondaryService__r.LG_ProvisioningAccountNo__c,LG_Action__c,
                                                 csordtelcoa__Replaced_Service__r.LG_DependsOnSecondaryService__c,
                                                 csordtelcoa__Replaced_Service__r.LG_Suborder__c from csord__Service__c
                                                 WHERE LG_Suborder__c IN :solutionIds AND (UM_DependsOnService__c != null OR LG_DependsOnSecondaryService__c != null)]){
        
        
            if(services.LG_Action__c=='Change' && services.csordtelcoa__Replaced_Service__r.LG_DependsOnSecondaryService__c!=null && services.LG_DependsOnSecondaryService__c==null){
                
                system.debug('services='+services.name+' id:'+services.id);
                changedServicesList.add(services.csordtelcoa__Replaced_Service__r);
                }  
               }
            }
            if(!changedServicesList.isEmpty()){
                           system.debug('changedServicesList'+changedServicesList);

            for(csord__Service__c s:[select id, name,LG_Suborder__c,csordtelcoa__Replacement_Service__r.LG_Suborder__c,csord__service__r.csordtelcoa__Replacement_Service__r.LG_Suborder__c from csord__Service__c where csord__Service__c in :changedServicesList]){
             
                if(s.name=='Line Backup Service'){     
                        system.debug('assiging old line backup under new suborder=='+s.csord__service__r.csordtelcoa__Replacement_Service__r.LG_Suborder__c);
                        s.LG_Suborder__c=s.csord__service__r.csordtelcoa__Replacement_Service__r.LG_Suborder__c;
                        linebackupServiceList.add(s);
                    }
                 }
            }           //as part of DGT-118 ends
            
               //as part of DGT-118 starts
         
        if (!linebackupServiceList.isEmpty()) {
            system.debug('linebackupServiceList:' + linebackupServiceList);
            update linebackupServiceList;
        }  
          //as part of DGT-118 ends
         
        
        system.debug('solutionsToUpdate:' + solutionsToUpdate);
        system.debug('secondarySolutionsToUpdate:' + secondarySolutionsToUpdate);
        if (!solutionsToUpdate.isEmpty()) {
            update solutionsToUpdate;
        }      
       
    }
}