src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_Action__c</fullName>
        <formula>IF( ISPICKVAL(csordtelcoa__Delta_Status__c, &apos;Continuing In Subscription&apos;) &amp;&amp; ISPICKVAL(csord__Subscription__r.csordtelcoa__Change_Type__c, &apos;Move&apos;)  , &apos;Add&apos;, IF(ISBLANK( TEXT(csordtelcoa__Delta_Status__c)) &amp;&amp; LG_AttributeValuesChanged__c, &apos;Change&apos;, IF(ISBLANK( TEXT(csordtelcoa__Delta_Status__c)), &apos;Add&apos;, IF( ISPICKVAL(csordtelcoa__Delta_Status__c, &apos;Continuing In Subscription&apos;) &amp;&amp; csordtelcoa__Product_Configuration__r.LG_AttributeValuesChanged__c , &apos;Change&apos;, CASE(TEXT(csordtelcoa__Delta_Status__c), &apos;Added To Subscription&apos;, &apos;Add&apos;, &apos;Deleted From Subscription&apos;, &apos;Delete&apos;, &apos;None&apos;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Action</label>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>LG_ProductDefinitionName__c</fullName>
        <formula>csordtelcoa__Product_Configuration__r.cscfga__Product_Definition__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Definition Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ProvisioningAccountNo__c</fullName>
        <label>Provisioning Account No</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ServiceStatus__c</fullName>
        <description>Pick-list to save the status of the service provisioning.</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                  <fullName>LG_SecondaryProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services (Secondary Product Configuration)</relationshipLabel>
        <relationshipName>Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Suborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services (Suborder)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_DependsOnService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Depends On Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Services (Depends On)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
     <fields>
        <fullName>LG_DependsOnSecondaryService__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Depends On Secondary Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Services (Service)</relationshipLabel>
        <relationshipName>Services3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Replaced_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replaced Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Replacement Services</relationshipLabel>
        <relationshipName>Replaced_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_AccessAvailable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to identify whether we can initiate MWLAN Jira flow</description>
        <label>LG_AccessAvailable</label>
        <type>Checkbox</type>
    </fields>
    
    <fields>
        <fullName>LG_ProvisioningAccountNo__c</fullName>
        <label>Provisioning Account No</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_SecondaryAccessAvailable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this field will be marked true in case Site service under the solution object has secondary access available.</description>
        <label>LG_SecondaryAccessAvailable</label>
        <type>Checkbox</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSPOFA__Orchestration_Process__c.object
<CustomObject>
    <fields>
        <fullName>CSPOFA__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initializing</fullName>
                    <default>true</default>
                    <label>Initializing</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_checkDependsOnServiceStatus.cls
/**
 * Check the status of depends On service OR secondaryDependsOnService and accordingly
 * update the field on solution object
 * 
 * @param  Set<Id> processesIds
 * @author Ravi Choudhary
 * @ticket OMB-1567
 * @since  18/01/2018
 */
global class LG_checkDependsOnServiceStatus implements CSPOFA.ExecutionHandler {

    public List<sObject> process(List<SObject> data)
    {
        List<sObject> result = new List<sObject>();

        List<CSPOFA__Orchestration_Step__c> stepList = (List<CSPOFA__Orchestration_Step__c>)data;

        Set<Id> processesIds = new Set<Id>();
        for (CSPOFA__Orchestration_Step__c step : stepList) {
            processesIds.add(step.CSPOFA__Orchestration_Process__c);
        }

        // Call method
        scanDependsOnService(processesIds);

        for (CSPOFA__Orchestration_Step__c step : stepList) {
            //mark step Status, Completed Date
            step.CSPOFA__Status__c         = 'Complete';
            step.CSPOFA__Completed_Date__c = Date.today();
            result.add(step);
        }

        return result;
    }

    /**
     * Check the status of solution of DependsOnService or secondaryDependsOnService and accordingly
     * update the field(LG_AccessAvailable__c) on solution object
     *
     * @param  Set<Id> processesIds
     * @author Ravi Choudhary
     * @ticket OMB-1567
     * @since  18/01/2018
     * 
     * modified: 2-3-2017
     * @ticket SFOM-2753
     * @modification: Modified the code to handle child Services along with the existing Primary & Secondary dependent Services
     */
    @TestVisible
    private void scanDependsOnService(Set<Id> processesIds) {
       
        Boolean updateSol = false;
        List<csord__Solution__c> solutionsToUpdate= new List<csord__Solution__c>();
        List<csord__Solution__c> secondarySolutionsToUpdate= new List<csord__Solution__c>();
        List<csord__Solution__c> parentSolutionsToUpdate= new List<csord__Solution__c>();
        List<Id> dependsOnSolutions= new List<Id>();
        List<Id> secondaryDependsOnSolutions= new List<Id>();
        List<Id> parentSolutions= new List<Id>();
        List<Id> solutionIds = new List<Id>();
        Set<String> serviceStatus = new Set<String>{'Activation Completed', 'Ready for Billing', 'Active'}; 

        // Get all data
        for (CSPOFA__Orchestration_Process__c process : [SELECT Id,
                                                         LG_Solution__c                                                         
                                                         FROM CSPOFA__Orchestration_Process__c
                                                         WHERE Id IN :processesIds AND LG_Solution__c != null]) {
            solutionIds.add(process.LG_Solution__c);
        }
        system.debug('current Solutions:' + solutionIds);
        
        
        if (!solutionIds.isEmpty()) {
            for (csord__Service__c services : [SELECT Id, Name, LG_Suborder__c, UM_DependsOnService__c, UM_DependsOnService__r.LG_ServiceStatus__c, UM_DependsOnService__r.LG_ProvisioningAccountNo__c,
                                                 LG_DependsOnSecondaryService__c, LG_DependsOnSecondaryService__r.LG_ServiceStatus__c, LG_DependsOnSecondaryService__r.LG_ProvisioningAccountNo__c,LG_Action__c,
                                                 csordtelcoa__Replaced_Service__r.LG_DependsOnSecondaryService__c,
                                                 csordtelcoa__Replaced_Service__r.LG_Suborder__c, csord__Service__c, csord__Service__r.LG_ServiceStatus__c, csord__Service__r.LG_ProvisioningAccountNo__c from csord__Service__c
                                                 WHERE LG_Suborder__c IN :solutionIds AND (UM_DependsOnService__c != null OR LG_DependsOnSecondaryService__c != null OR (csord__Service__c != null AND LG_ProductDefinitionName__c != 'Hardware'))]){
               
                if (services.UM_DependsOnService__c != null && (serviceStatus.contains(services.UM_DependsOnService__r.LG_ServiceStatus__c) || services.UM_DependsOnService__r.LG_ProvisioningAccountNo__c != null )) {
                    system.debug('service has UM_DependsOnService__c:' +services.UM_DependsOnService__c);
                    dependsOnSolutions.add(services.LG_Suborder__c);
                }
                
                if (services.LG_DependsOnSecondaryService__c != null && (serviceStatus.contains(services.LG_DependsOnSecondaryService__r.LG_ServiceStatus__c) || services.LG_DependsOnSecondaryService__r.LG_ProvisioningAccountNo__c != null)) {
                    system.debug('service has LG_DependsOnSecondaryService__c:' + services.LG_DependsOnSecondaryService__c);
                    secondaryDependsOnSolutions.add(services.LG_Suborder__c);
                }
                
                //SFOM-2753
                if (services.csord__Service__c != null && (serviceStatus.contains(services.csord__Service__r.LG_ServiceStatus__c) || services.csord__Service__r.LG_ProvisioningAccountNo__c != null)) {
                    system.debug('service has Parent Service :' + services.csord__Service__c);
                    parentSolutions.add(services.LG_Suborder__c);
                }
                   
               }
            }
        
         
        if (!dependsOnSolutions.isEmpty()) {
            
            system.debug('inside dependsOnSolutions:' + dependsOnSolutions);
            for (csord__Solution__c sols: [Select Id,LG_AccessAvailable__c from csord__Solution__c where Id IN:dependsOnSolutions]) {
            sols.LG_AccessAvailable__c = true;
            solutionsToUpdate.add(sols);
             }
        }
        
        if (!secondaryDependsOnSolutions.isEmpty()) {
            system.debug('inside secondaryDependsOnSolutions:' + secondaryDependsOnSolutions);
            for (csord__Solution__c sols: [Select Id,LG_SecondaryAccessAvailable__c from csord__Solution__c where Id IN:secondaryDependsOnSolutions]) {
            sols.LG_SecondaryAccessAvailable__c = true;
            secondarySolutionsToUpdate.add(sols);
             }
        }
        
        //SFOM-2753
        if(!parentSolutions.isEmpty()){
            system.debug('inside parentSolutions:' + parentSolutions);
            for (csord__Solution__c sols: [Select Id,LG_SecondaryAccessAvailable__c from csord__Solution__c where Id IN:parentSolutions]) {
                sols.LG_AccessAvailable__c = true;
                parentSolutionsToUpdate.add(sols);
            }
        }
        
    
        system.debug('solutionsToUpdate:' + solutionsToUpdate);
        system.debug('secondarySolutionsToUpdate:' + secondarySolutionsToUpdate);
        system.debug('parentSolutionsToUpdate:' + parentSolutionsToUpdate);
        
        if (!solutionsToUpdate.isEmpty()) {
            update solutionsToUpdate;
        }  
        
        if (!secondarySolutionsToUpdate.isEmpty()) {
            update secondarySolutionsToUpdate;
        }  
         
        //SFOM-2753
        if (!parentSolutionsToUpdate.isEmpty()) {
            update parentSolutionsToUpdate;
        }
         
    }
}