src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Order</description>
        <inlineHelpText>The parent Solution of this Order</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status2__c</fullName>
        <description>The status of the Order in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>DEPRECATED. Defines the status of the order through fulfilment to delivery.</description>
        <inlineHelpText>DEPRECATED. Use Status2__c.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Provisioning</fullName>
                    <default>true</default>
                    <label>In Provisioning</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Not Provisioned</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    
    <fields>
        <fullName>csord__Identification__c</fullName>
        <description>Identification string for the object, used as the reference from external systems.</description>
        <inlineHelpText>E.g. &quot;spokeServiceAmsterdam&quot; in Hub&amp;Spokes scenario.</inlineHelpText>
        <label>Identification</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Solution.</description>
        <inlineHelpText>The parent Order of this Solution.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Solution in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csordtelcoa__Orders_Subscriptions_Options__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>LG_OrderCanceledStatus__c</fullName>
        <defaultValue>&quot;Canceled&quot;</defaultValue>
        <description>Holds the value that would be set on the Order Status2 field when the Order is canceled.</description>
        <inlineHelpText>Holds the value that would be set on the Order Status2 field when the Order is canceled.</inlineHelpText>
        <label>Order Canceled Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_OrderCompleteStatus__c</fullName>
        <defaultValue>&quot;Closed&quot;</defaultValue>
        <description>Holds the value that will be set on the Status2 field of the Order when all suborders are complete.</description>
        <inlineHelpText>Holds the value that will be set on the Status2 field of the Order when all suborders are complete.</inlineHelpText>
        <label>Order Complete Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_OrderPartiallyCompletedStatus__c</fullName>
        <defaultValue>&quot;Some Suborders Completed&quot;</defaultValue>
        <description>Holds the value that would be set on the Order Status2 field when some of the suborders are complete, but not all of them.</description>
        <inlineHelpText>Holds the value that would be set on the Order Status2 field when some of the suborders are complete, but not all of them.</inlineHelpText>
        <label>Order Partially Completed Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Orders &amp; Subscriptions Options</label>
</CustomObject>

src/objects/CSPOFA__Orchestration_Process__c.object
<CustomObject>
    <fields>
        <fullName>CSPOFA__Orchestration_Process_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Orchestration Process Template</label>
        <referenceTo>CSPOFA__Orchestration_Process_Template__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSPOFA__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Initializing</fullName>
                    <default>true</default>
                    <label>Initializing</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orchestration Processes</relationshipLabel>
        <relationshipName>Orchestration_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Orchestration Process</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSPOFA__Orchestration_Process_Template__c.object
<CustomObject>
    <label>Orchestration Process Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_NotifyOrderProcessTest.cls
/**
 * Test class for LG_NotifyOrderProcess
 *
 * @author Petar Miletic
 * @ticket SFOM-233
 * @since  07/02/2017
 */
@isTest
public class LG_NotifyOrderProcessTest {

	@testSetup
	private static void setupTestData() {

		No_Triggers__c noTriggers = No_Triggers__c.getInstance(UserInfo.getUserId());
		noTriggers.Flag__c      = true;
		noTriggers.SetupOwnerId = UserInfo.getOrganizationId();
		upsert noTriggers;

		csordtelcoa__Orders_Subscriptions_Options__c osOptions = new csordtelcoa__Orders_Subscriptions_Options__c();
		osOptions.LG_OrderPartiallyCompletedStatus__c = 'Some Suborders Completed';
		osOptions.LG_OrderCompleteStatus__c           = 'Completed';
		osOptions.LG_OrderCanceledStatus__c           = 'Canceled';
		insert osOptions;

		// Insert two Orders
		List<csord__Order__c> orders = new List<csord__Order__c>();

		orders.add(new csord__Order__c(Name = 'Test Order First', csord__Status2__c = 'In Provisioning', csord__Identification__c = '123456789'));
		orders.add(new csord__Order__c(Name = 'Test Order Second', csord__Status2__c = 'In Provisioning', csord__Identification__c = '123456799'));

		insert orders;

		List<csord__Solution__c> solutions = new List<csord__Solution__c>();

		for (Integer i = 0; i < 10; i++) {

			if (math.mod(i, 2) == 0) {
				solutions.add(new csord__Solution__c(Name = 'Test Solution First', csord__Order__c = orders[0].Id, csord__Status__c = 'New', csord__Identification__c = '333555888' + String.valueOf(i)));
			} else {
				solutions.add(new csord__Solution__c(Name = 'Test Solution Second', csord__Order__c = orders[1].Id, csord__Status__c = 'Complete', csord__Identification__c = '333555888' + String.valueOf(i)));
			}
		}

		insert solutions;

		// This one will be overriden by next in line
		solutions[0].csord__Status__c = 'Complete';
		update solutions[0];

		// Orcestrator stuff
		CSPOFA__Orchestration_Process_Template__c orcTemplate = new CSPOFA__Orchestration_Process_Template__c();
		insert orcTemplate;

		// Process first Solution, first Order
		CSPOFA__Orchestration_Process__c process = new CSPOFA__Orchestration_Process__c(CSPOFA__Orchestration_Process_Template__c = orcTemplate.Id, LG_Solution__c = solutions[0].Id);
		insert process;

		CSPOFA__Orchestration_Step__c step = new CSPOFA__Orchestration_Step__c(CSPOFA__Orchestration_Process__c = process.Id);
		insert step;

		// Process second Solution, second Order
		CSPOFA__Orchestration_Process__c process2 = new CSPOFA__Orchestration_Process__c(CSPOFA__Orchestration_Process_Template__c = orcTemplate.Id, LG_Solution__c = solutions[1].Id);
		insert process2;

		CSPOFA__Orchestration_Step__c step2 = new CSPOFA__Orchestration_Step__c(CSPOFA__Orchestration_Process__c = process2.Id);
		insert step2;

		noTriggers.Flag__c = false;
		upsert noTriggers;
	}

	@isTest
	private static void processTest() {

		List<SObject> steps = [SELECT Id, CSPOFA__Orchestration_Process__c, CSPOFA__Status__c FROM CSPOFA__Orchestration_Step__c];

		for (SObject obj : steps) {

			CSPOFA__Orchestration_Step__c step = (CSPOFA__Orchestration_Step__c) obj;
			System.assertNotEquals('Complete', step.CSPOFA__Status__c, 'Status should not be complete');
		}

		Test.startTest();

		LG_NotifyOrderProcess notify = new LG_NotifyOrderProcess();
		steps = notify.process(steps);

		Test.stopTest();

		for (SObject obj : steps) {

			CSPOFA__Orchestration_Step__c step = (CSPOFA__Orchestration_Step__c) obj;
			System.assertEquals('Complete', step.CSPOFA__Status__c, 'Status should be complete');
		}
	}

	@IsTest
	public static void notifyOrderProcessTest() {

		Map<Id, CSPOFA__Orchestration_Process__c> processMap = new Map<Id, CSPOFA__Orchestration_Process__c>([SELECT Id FROM CSPOFA__Orchestration_Process__c]);

		csord__Order__c firstOrder  = [SELECT Id, csord__Status2__c FROM csord__Order__c WHERE Name = 'Test Order First' LIMIT 1];
		csord__Order__c secondOrder = [SELECT Id, csord__Status2__c FROM csord__Order__c WHERE Name = 'Test Order Second' LIMIT 1];

		Test.startTest();

		LG_NotifyOrderProcess notify = new LG_NotifyOrderProcess();
		notify.notifyOrderProcess(processMap.keySet());

		Test.stopTest();

		// Assert before
		System.assertEquals('In Provisioning', firstOrder.csord__Status2__c, 'Invalid data');
		System.assertEquals('In Provisioning', secondOrder.csord__Status2__c, 'Invalid data');

		// Reload data
		firstOrder  = [SELECT Id, csord__Status2__c FROM csord__Order__c WHERE Name = 'Test Order First' LIMIT 1];
		secondOrder = [SELECT Id, csord__Status2__c FROM csord__Order__c WHERE Name = 'Test Order Second' LIMIT 1];

		// Assert after
		System.assertEquals('Some Suborders Completed', firstOrder.csord__Status2__c, 'Invalid data');
		System.assertEquals('Completed', secondOrder.csord__Status2__c, 'Invalid data');
	}
}