src/objects/csord__Order__c.object
<CustomObject>
    <description>The central object in the process of setting up the whole solution. Lives only as long as is needed for the fulfillment process to finish.</description>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Order</description>
        <inlineHelpText>The parent Solution of this Order</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>DEPRECATED. Defines the status of the order through fulfilment to delivery.</description>
        <inlineHelpText>DEPRECATED. Use Status2__c.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Provisioning</fullName>
                    <default>true</default>
                    <label>In Provisioning</label>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Not Provisioned</fullName>
                </value>
                <value>
                    <fullName>Pending Closure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    <fields>
        <fullName>LG_DecompositionCriteria__c</fullName>
        <description>Used as a criteria for grouping the services to the suborders</description>
        <label>Decomposition Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LG_DecompositionCriteria</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_From_Service__c</fullName>
        <description>This field is used to capture the FROM Service for BDS</description>
        <label>From Service</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    
    <fields>
        <fullName>LG_ServiceStatus__c</fullName>
        <description>Pick-list to save the status of the service provisioning.</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                  <fullName>LG_SecondaryProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services (Secondary Product Configuration)</relationshipLabel>
        <relationshipName>Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_To_Service__c</fullName>
        <label>To Service</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Service.</description>
        <inlineHelpText>The parent Order of this Service.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Solution of this Service</description>
        <inlineHelpText>The parent Solution of this Service</inlineHelpText>
        <label>Solution</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Solution__c.object
<CustomObject>
    <description>A grouping object for a set of Subscriptions and other objects within a related group.</description>
    <fields>
        <fullName>LG_AccessAvailable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to identify whether we can initiate MWLAN Jira flow</description>
        <label>LG_AccessAvailable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_DecompositionCriteria__c</fullName>
        <label>Decomposition Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LG_DecompositionCriteria</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_InflightChange__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Last minute changes from customer which have manageable impact on ongoing fulfilment process</description>
        <inlineHelpText>Check this flag if we need to redirect the process from happy path to Jeopardy / Exception handling after Inflight Change (Appointment / Numbers / Configuration) was captured</inlineHelpText>
        <label>Inflight Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_Integration_Status__c</fullName>
        <label>Integration Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Work Order Created</fullName>
                </value>
                <value>
                    <fullName>Request Acknowledged</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Timeout</fullName>
                </value>
                <value>
                    <fullName>SFDC failure</fullName>
                </value>
                <value>
                    <fullName>Order Creation Failed</fullName>
                </value>
                <value>
                    <fullName>Pending Work Order Created</fullName>
                </value>
                <value>
                    <fullName>Billing Integration Timeout</fullName>
                </value>
                <value>
                    <fullName>Middleware Request Failed</fullName>
                </value>
                <value>
                    <fullName>Installation Complete</fullName>
                </value>
                <value>
                    <fullName>Installation Details Missing</fullName>
                </value>
                <value>
                    <fullName>Cancellation Requested</fullName>
                </value>
                <value>
                    <fullName>Install Survey Failed</fullName>
                </value>
                <value>
                    <fullName>Install Survey Successful</fullName>
                </value>
                <value>
                    <fullName>Installation In-Progress</fullName>
                </value>
                <value>
                    <fullName>JIRA Work Order Created</fullName>
                </value>
                <value>
                    <fullName>JIRA Order Creation Failed</fullName>
                </value>
                <value>
                    <fullName>JIRA Initiated Cancellation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_IsFirstDayofNextMonth__c</fullName>
        <formula>TEXT(TODAY())</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsFirstDayofNextMonth</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Jeopardy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Jeopardy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LG_Jira_Status__c</fullName>
        <label>Jira Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_OldSuborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Old Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    
    <fields>
        <fullName>LG_OrderChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Changed</label>
        <type>Checkbox</type>
    </fields>
	<fields>
        <fullName>LG_Activated_New_Site__c</fullName>
        <label>Activated New Site</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Order of this Solution.</description>
        <inlineHelpText>The parent Order of this Solution.</inlineHelpText>
        <label>Order</label>
        <referenceTo>csord__Order__c</referenceTo>
        <relationshipLabel>Solutions</relationshipLabel>
        <relationshipName>Solutions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Solution in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution</label>
    <nameField>
        <label>Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <recordTypes>
        <fullName>Suborder</fullName>
        <active>true</active>
        <description>Used for decomposing order and grouping Services that can be provisioned together</description>
        <label>Suborder</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_DecompositionCriteria__c.object
<CustomObject>
    <fields>
        <fullName>LG_DecompositionCriteria__c</fullName>
        <description>Used as a criteria for grouping the services to the suborders</description>
        <label>Decomposition Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Set 1 - On-Net</fullName>
                </value>
                <value>
                    <fullName>Set 2 - Legacy</fullName>
                </value>
                <value>
                    <fullName>Set 3 - Mobile</fullName>
                </value>
                <value>
                    <fullName>Set 4</fullName>
                </value>
                <value>
                    <fullName>Set 5 - CaMa Internet</fullName>
                </value>
                <value>
                    <fullName>Set 6 - CaMa Dependent</fullName>
                </value>
                <value>
                    <fullName>Set 7 - JIRA Fiber</fullName>
                </value>
                <value>
                    <fullName>Set 8 - CS Voice</fullName>
                </value>
                <value>
                    <fullName>Set 9 - CaMa Bearer</fullName>
                </value>
                <value>
                    <fullName>Set 10 - VoiceWorks</fullName>
                </value>
                <value>
                    <fullName>Set 11 - Engineers</fullName>
                </value>
                <value>
                    <fullName>Set 12 - JIRA Orchestrated</fullName>
                </value>
                <value>
                    <fullName>Set 13 - JIRA Bearer</fullName>
                </value>
                <value>
                    <fullName>Set 14 - CaMa Mobile</fullName>
                </value>
                <value>
                    <fullName>Set 15 - CaMa Manual</fullName>
                </value>
                <value>
                    <fullName>Set 16 - CaMa OI Manual</fullName>
                </value>
                <value>
                    <fullName>Set 17 - Charges</fullName>
                </value>
                <value>
                    <fullName>Set 18 - Direct to Kenan</fullName>
                </value>
                <value>
                    <fullName>Set 19 - Additional Charges</fullName>
                </value>
                <value>
                    <fullName>Set 20 - BDS Site Process</fullName>
                </value>
                <value>
                    <fullName>Set 21 - VPN Process</fullName>
                </value>
                <value>
                    <fullName>Set 22 - Parent/Category Only</fullName>
                </value>
                <value>
                    <fullName>Set 23 - UM CaMa Bridge Mode</fullName>
                </value>
                <value>
                    <fullName>Set 24 - UM JIRA Fiber Bridge Mode</fullName>
                </value>
                <value>
                    <fullName>Set 17 - BDS Charges</fullName>
                </value>
                <value>
                    <fullName>Set 17 - HPBX Charges</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Decomposition Criteria</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>Decomposition Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Decomposition Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/LG_DecompositionCriteria.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Set 1 - On-Net</fullName>
    </customValue>
    <customValue>
        <fullName>Set 2 - Off-Net</fullName>
    </customValue>
    <customValue>
        <fullName>Set 3 - Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Set 4</fullName>
    </customValue>
    <customValue>
        <fullName>Set 6 - CaMa Dependent</fullName>
    </customValue>
    <customValue>
        <fullName>Set 7 - JIRA Fiber</fullName>
    </customValue>
    <customValue>
        <fullName>Set 10 - VoiceWorks</fullName>
    </customValue>
    <customValue>
        <fullName>Set 11 - Engineers</fullName>
    </customValue>
    <customValue>
        <fullName>Set 5 - CaMa Internet</fullName>
    </customValue>
    <customValue>
        <fullName>Set 8 - CS Voice</fullName>
    </customValue>
    <customValue>
        <fullName>Set 9 - CaMa Bearer</fullName>
    </customValue>
    <customValue>
        <fullName>Set 5 - No Grouping</fullName>
    </customValue>
    <customValue>
        <fullName>Set 12 - JIRA Orchestrated</fullName>
    </customValue>
    <customValue>
        <fullName>Set 13 - JIRA Bearer</fullName>
    </customValue>
    <customValue>
        <fullName>Set 14 - CaMa Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Set 15 - CaMa Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Set 16 - CaMa OI Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Set 17 - Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 18 - Direct to Kenan</fullName>
    </customValue>
    <customValue>
        <fullName>Set 22 - Parent/Category Only</fullName>
    </customValue>
    <customValue>
        <fullName>Set 24 - UM JIRA Fiber Bridge Mode</fullName>
    </customValue>
    <customValue>
        <fullName>Set 23 - UM CaMa Bridge Mode</fullName>
    </customValue>
    <customValue>
        <fullName>Set 21 - VPN Process</fullName>
    </customValue>
    <customValue>
        <fullName>Set 20 - BDS Site Process</fullName>
    </customValue>
    <customValue>
        <fullName>Set 19 - Additional Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 25 - Business Anywhere</fullName>
    </customValue>
    <customValue>
        <fullName>Set 17 - HBPX Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 26 - UM Managed WLAN</fullName>
    </customValue>
    <customValue>
        <fullName>Set 17 - BDS Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 10 - SIPWISE</fullName>
    </customValue>
    <description>Used as a criteria for grouping the services to the suborders</description>
    <masterLabel>Decomposition Criteria</masterLabel>
</GlobalValueSet>

src/classes/LG_SolutionTriggerHandler.cls
public class LG_SolutionTriggerHandler {
	/**
	 * If there is a change in the Solution/Suborder Jeopardy, Inflight Change or Order
	 * Changed fields - the orchestrator Evented Monitor field should be notified.
	 *
	 * @param  List<csord__Solution__c> suborders
	 * @param  Map<Id, csord__Solution__c> oldMap
	 * @author Tomislav Blazek
	 * @ticket SFOM-359
	 * @since  3/3/2017
	 */
	public static void notifyMonitorField(List<csord__Solution__c> suborders, Map<Id, csord__Solution__c> oldMap) {
		Set<Id> eligibleSuborderIds = new Set<Id>();

		/*
		 * Decide which solutions/suborders should be processed:
		 * - only suborders that had a change in the LG_Jeopardy__c, LG_InflightChange__c
		 * or LG_OrderChanged__c fields
		 */
		for (csord__Solution__c newSuborder : suborders) {
			csord__Solution__c oldSuborder = oldMap == null ? null : oldMap.get(newSuborder.Id);
           // added one more condition for adding solution status for defect OMB-827 in line 26
			if (oldSuborder != null &&
				(oldSuborder.LG_IsFirstDayofNextMonth__c != newSuborder.LG_IsFirstDayofNextMonth__c
				 || oldSuborder.LG_Jeopardy__c != newSuborder.LG_Jeopardy__c
				 || oldSuborder.LG_InflightChange__c != newSuborder.LG_InflightChange__c
                 || oldSuborder.LG_OrderChanged__c != newSuborder.LG_OrderChanged__c||oldSuborder.LG_Integration_Status__c!= newSuborder.LG_Integration_Status__c || oldSuborder.LG_AccessAvailable__c!= newSuborder.LG_AccessAvailable__c  
                 || oldSuborder.LG_Jira_Status__c != newSuborder.LG_Jira_Status__c
                 || oldSuborder.csord__Status__c!= newSuborder.csord__Status__c)) {
				eligibleSuborderIds.add(newSuborder.Id);
			}
		}

		if (!eligibleSuborderIds.isEmpty()) {
			CSPOFA.Events.emit('update', eligibleSuborderIds);
		}
	}
    
    /**
    public static void checkVPNAndConnectionStatus(List<csord__Solution__c> suborders, Map<Id, csord__Solution__c> oldMap) {
    	
        Set<Id> eligibleSuborderIds = new Set<Id>();

        for (csord__Solution__c newSuborder : suborders) {
        	csord__Solution__c oldSubOrder = oldMap.get(newSubOrder.Id);
            if(newSubOrder.LG_DecompositionCriteria__c == 'Set 21 - VPN Process' && oldSubOrder.LG_Activated_New_Site__c  != newSuborder.LG_Activated_New_Site__c && newSuborder.LG_Activated_New_Site__c == 'Check Services'){
                eligibleSuborderIds.add(newSuborder.Id);
            }
        }
        
        if(!eligibleSuborderIds.isEmpty()){
            set<Id> configIds = new Set<Id>();
            Map<Id, csord__service__c> connectionServiceMap = new Map<id, csord__service__c>();
            //   Map<Id, List<csord__service__c>> suborderServiceMap = new Map<Id, List<csord__service__c>>();
            //   Map<Id, List<csord__service__c>> vpnServiceMap = new Map<Id, List<csord__service__c>>();
            csord__service__c vpnSrvToUpdate;
            List<csord__service__c> serviceToUpdate = new List<csord__service__c>();
            Set<Id> orderIds = new Set<Id>();
            try{
                for (csord__solution__c sol : [SELECT Id,csord__Order__c, (SELECT Id FROM Solutions__r), (SELECT Id,csord__Status__c,LG_ServiceStatus__c,LG_From_Service__c,LG_To_Service__c,Persistent_Id__c FROM Services__r) FROM csord__Solution__c
                              WHERE Id IN :eligibleSuborderIds] ){
                    System.debug('check# ' + sol.services__r);
                    //  suborderServiceMap.put(sol.Id, sol.services__r);
                    //Iterating the Services related to the suborder
                    for(csord__service__c srv : sol.services__r){
            
                        //Condition to check for connection service
                        if(srv.LG_To_Service__c !=null){//  connection service
                            connectionServiceMap.put(srv.LG_To_Service__c, srv); 
                        }
            
                        //Condition to Identify the VPN service
                        if(srv.LG_To_Service__c ==null && srv.LG_From_Service__c ==null){ //vpn service
                            vpnSrvToUpdate = srv;
                            System.debug('vpn service is' + vpnSrvToUpdate);
                        }
                    }// suborder map
                    System.debug('map# ' + connectionServiceMap);
                    orderIds.add(sol.csord__Order__c);
                    System.debug('>>>>'+sol.csord__Order__c);
                }//orch process map
                //Added field in the query for sfom-2455
                List<csord__Service__c> srvcbds = [SELECT Id, Name ,LG_ServiceStatus__c,Persistent_Id__c,csord__Activation_Date__c,csord__Deactivation_Date__c from csord__Service__c where Persistent_Id__c in :connectionServiceMap.keySet() AND csord__Order__c IN :orderIds AND csordtelcoa__Replaced_Service__c = null];
                System.debug('srvcbds# ' + srvcbds);
                Integer activeServicecount=0;
                Integer inProgressServicecount=0;
                Map<Id, csord__service__c> bdsSiteDiscoMap = new Map<Id, csord__service__c>();
                // removed  || srv.LG_ServiceStatus__c =='Provisioned' from below
                for(csord__Service__c srv: srvcbds){
                    system.debug ('BDS Service is' +srv);
                    if(srv.csord__Deactivation_Date__c != null){ // Added this if condition for sfom-2455
                        if(srv.LG_ServiceStatus__c =='inactive' || srv.LG_ServiceStatus__c =='Ready for Billing' || srv.LG_ServiceStatus__c =='Activation Completed'){
                            bdsSiteDiscoMap.put(srv.Id, srv);
                        }                   
                    } else {
                        if(srv.LG_ServiceStatus__c =='Active' || srv.LG_ServiceStatus__c =='Ready for Billing' || srv.LG_ServiceStatus__c =='Activation Completed'){
                            activeServicecount++;
                        }
                        else
                            inProgressServicecount++;
                        
                    }
                }
                    
        
                System.debug('BDSActiveService# ' + activeServicecount);
                System.debug('InProgressService# ' + inProgressServicecount);
                //removed  || vpnSrvToUpdate.LG_ServiceStatus__c !='Provisioned' from below
                if (vpnSrvToUpdate != null && activeServicecount>=1 && (vpnSrvToUpdate.LG_ServiceStatus__c !='Active' && vpnSrvToUpdate.LG_ServiceStatus__c !='Ready for Billing' && vpnSrvToUpdate.LG_ServiceStatus__c !='Activation Completed')){
                    System.debug('VPN service getting updated is ' + vpnSrvToUpdate);
                    vpnSrvToUpdate.LG_ServiceStatus__c ='Activation Completed';
                    vpnSrvToUpdate.csord__Status__c ='Activation Completed';
                    vpnSrvToUpdate.csord__Activation_Date__c = Date.today(); 
                    update vpnSrvToUpdate;
                }
                for(csord__Service__c srv: srvcbds){
                    System.debug('LG Service status is ' +srv.LG_ServiceStatus__c +  ' -- ' + srv.Name);
                    csord__service__c srvToUpdate = connectionServiceMap.get(srv.Persistent_Id__c);
    
                    if((srv.LG_ServiceStatus__c =='Active' || srv.LG_ServiceStatus__c =='Ready for Billing' || srv.LG_ServiceStatus__c =='Activation Completed') && (activeServicecount>1 || inProgressServicecount==0) && (srvToUpdate.LG_ServiceStatus__c !='Active' && srvToUpdate.LG_ServiceStatus__c !='Ready for Billing' && srvToUpdate.LG_ServiceStatus__c !='Activation Completed')) {
    //                    csord__service__c srvToUpdate = connectionServiceMap.get(srv.Persistent_Id__c);
                        srvToUpdate.LG_ServiceStatus__c = 'Activation Completed';
                        srvToUpdate.csord__Status__c = 'Activation Completed';
                        if(srv.csord__Activation_Date__c == null || srv.csord__Activation_Date__c < Date.today()){
                            srvToUpdate.csord__Activation_Date__c = Date.today();
               
                        } else {
                            srvToUpdate.csord__Activation_Date__c = srv.csord__Activation_Date__c;
                        }
                        serviceToUpdate.add(srvToUpdate);
                    }
                }
        
                System.debug('check# ' + serviceToUpdate);
                //Added for SFOM-2455
                for(Id bdsSiteId : bdsSiteDiscoMap.keySet()){
                    if(connectionServiceMap.get(bdsSiteId) != null){
                        csord__Service__c connService = connectionServiceMap.get(bdsSiteId);
                        connService.LG_ServiceStatus__c = 'Activation Completed';
                        connService.csord__Deactivation_Date__c = bdsSiteDiscoMap.get(bdsSiteId).csord__Deactivation_Date__c;
                        serviceToUpdate.add(connService);
                    }
                }
                update serviceToUpdate;
    
            }//try
            catch(Exception e){
                System.debug('Exception: ' + e.getMessage());
            }
            
        }
       
    }
	**/
    
}