src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>LG_ServiceStatus__c</fullName>
        <description>Pick-list to save the status of the service provisioning.</description>
        <label>Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Requested</fullName>
                    <default>true</default>
                    <label>Requested</label>
                  <fullName>LG_SecondaryProductConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Product Configuration</label>
        <referenceTo>cscfga__Product_Configuration__c</referenceTo>
        <relationshipLabel>Services (Secondary Product Configuration)</relationshipLabel>
        <relationshipName>Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_BillingProductId__c</fullName>
        <label>Billing Product Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_DeactivationReason__c</fullName>
        <label>Deactivation Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Deactivation_Date__c</fullName>
        <description>The date of deactivation.</description>
        <inlineHelpText>The date of deactivation.</inlineHelpText>
        <label>Deactivation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Service in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Subscription__c</fullName>
        <description>The parent Subscription of this Service.</description>
        <inlineHelpText>The parent Subscription of this Service.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Service_Number_Sequence__c</fullName>
        <displayFormat>{000000000}</displayFormat>
        <label>Service Number Sequence</label>
        <type>AutoNumber</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Service_Line_Item__c.object
<CustomObject>
    <description>A billable component of a Service.</description>
    <fields>
        <fullName>LG_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Discount</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                </value>
                <value>
                    <fullName>Termination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_BillingProductId__c</fullName>
        <label>Billing Product Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_DeactivationReason__c</fullName>
        <label>Deactivation Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UM_Price_Override__c</fullName>
        <label>Price Override</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UM_ServiceItemType__c</fullName>
        <label>Service Item Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Line_Description__c</fullName>
        <label>Line Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <description>The parent Service of this ServiceLineItem.</description>
        <inlineHelpText>The parent Service of this ServiceLineItem.</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Service line Items</relationshipLabel>
        <relationshipName>Service_line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>csord__Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Line Item</label>
    <nameField>
        <label>Service Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Subscription__c.object
<CustomObject>
    <description>An accessibility model to a Service (or Services). Governs the rights to access and use a Service.</description>
    <fields>
        <fullName>Billing_Termination_Date__c</fullName>
        <label>Billing Termination Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Kenan_Response__c</fullName>
        <label>Kenan Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>csord__Status__c</fullName>
        <description>The status of the Subscription in the fulfillment process.</description>
        <inlineHelpText>Used for state transitions.</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Replaced_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replaced Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Replacement Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>csordtelcoa__Replacement_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replacement Subscription</label>
        <referenceTo>csord__Subscription__c</referenceTo>
        <relationshipLabel>Replaced Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/csordtelcoa__Orders_Subscriptions_Options__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>LG_ServiceDeactivatedStatus__c</fullName>
        <defaultValue>&quot;Inactive&quot;</defaultValue>
        <description>Value of the Service Status that defines Service is Deactivated</description>
        <label>Service Deactivated Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Orders &amp; Subscriptions Options</label>
</CustomObject>

src/classes/UM_ServiceTerminator.cls
public with sharing class UM_ServiceTerminator implements UM_KenanSyncBatch.IServiceConnect{

    public void execute(list<sObject> servicesList){
        list<csord__Service__c> services = (list<csord__Service__c>) servicesList;
        list<task> taskList = new list<task>();
        list<csord__Subscription__c> subsList = new list<csord__Subscription__c>();
        list<csord__Service_Line_Item__c> lineItems = new list<csord__Service_Line_Item__c>();
        list<csord__Service__c> servicesToBeDeleted = new list<csord__Service__c>();
        list<csord__Subscription__c> subsToBeDeleted = new list<csord__Subscription__c>();
        // list<csord__Service__c> terminationServices = new list<csord__Service__c>();
        // list<csord__Subscription__c> terminationSubs = new list<csord__Subscription__c>();
        map<id,string> serviceDeactivationReasonMap = new map<id,string>();

        csordtelcoa__Orders_Subscriptions_Options__c osp = csordtelcoa__Orders_Subscriptions_Options__c.getOrgDefaults();
        String inactiveStatus = osp.LG_ServiceDeactivatedStatus__c;

        if(inactiveStatus==null)
            inactiveStatus = 'Inactive';

        System.debug('*** services: '+services);
        //Commented as part of SFOM-1555 Start
        // for(csord__service__c s : services){
        //     if(s.csord__Subscription__r.csordtelcoa__Replacement_Subscription__c!=null){
        //         terminationSubs.add(new csord__Subscription__c(id=s.csord__Subscription__r.csordtelcoa__Replacement_Subscription__c));
        //         terminationSubServiceMap.put(s.csord__Subscription__r.csordtelcoa__Replacement_Subscription__c,s.id);
        //     }
        // }

        // if(!terminationSubs.isEmpty()){
        //     terminationServices = [select id,UM_DeactivationReason__c,csord__Subscription__c from csord__service__c where csord__Subscription__c in :terminationSubs];
        //     for(csord__service__c s : terminationServices){
        //         Id serviceId = terminationSubServiceMap.get(s.csord__Subscription__c);
        //         serviceDeactivationReasonMap.put(serviceId,s.UM_DeactivationReason__c);
        //     }
        // }
        //Commented as part of SFOM-1555 End

        //GetTermination Line Items
        lineItems = [select id,name,UM_DeactivationReason__c,UM_ServiceItemType__c,UM_BillingProductId__c,UM_Price_Override__c,csord__Total_Price__c,
                        csord__Line_Description__c,csord__service__r.csord__subscription__r.csordtelcoa__Replaced_Subscription__c,
                        csord__Service__c,csord__Service__r.csord__Subscription__c,csord__Service__r.csord__Deactivation_Date__c
                        from csord__Service_Line_Item__c
                        where LG_Type__c like 'Termination'
                            AND csord__service__c in :services];

        //Send Termination Line Items to Kenan
        KenanConnectorService service = new KenanConnectorService();

        for(csord__Service_Line_Item__c item : lineItems){

            KenanServiceItem kItem =  new KenanServiceItem();
            kItem.serviceExternalId = item.csord__Service__c;
            kItem.salesforceId = item.id;
            kItem.activeDate = item.csord__Service__r.csord__Deactivation_Date__c;

            if(item.UM_ServiceItemType__c!=null)
                kItem.itemType = Integer.valueOf(item.UM_ServiceItemType__c);

            kItem.currencyCode = UserInfo.getDefaultCurrency() ;
            if(item.UM_BillingProductId__c!=null)
                kItem.itemId = Integer.valueOf(item.UM_BillingProductId__c) ;

            if(item.UM_Price_Override__c!='No')
                kItem.rate = item.csord__Total_Price__c*100;

            kItem.extData = new Map<String, Object>();
            string itemDescription = item.csord__Line_Description__c;

            if(!String.isBlank(itemDescription)){
                integer size = itemDescription.length();

                if(size>50)
                    itemDescription = itemDescription.subString(0,50);

                kItem.extData.put('15',itemDescription);
            }

            //SFOM-1555 Deactivation reason is the same on all line items of the same service (and the service itself)
            serviceDeactivationReasonMap.put(item.csord__Service__c, item.UM_DeactivationReason__c);

            //if(item.UM_DeactivationReason__c!=null)
            //    kItem.extData.put('9',item.UM_DeactivationReason__c);

            try{
                list<KenanServiceItem> ksiBack = service.serviceItemCreate(kItem);
                system.debug('*** Added Termination Item ksiBack='+ksiBack);
            }catch(Exception e){
                System.debug('*** Error while creating Termination Item in Kenan '+e.getMessage());
            }
        }

        for(csord__Service__c s : services){
	        Date terminationDate = Date.today();

            if(s.csord__Deactivation_Date__c!=null)
                terminationDate = s.csord__Deactivation_Date__c;

            string deactivationReason = serviceDeactivationReasonMap.get(s.id);
            //Commented out for now as there is issue with Back Dated Termination when serviceModify is set with current date.
            //UM_KenanSubscriptionSyncCtrl.updateDeactivationReason(s.id,deactivationReason);
            // --TODO
            if(!UM_KenanSubscriptionSyncCtrl.terminateServices(s.csord__Subscription__c,terminationDate,null)){
                Task errTask = createErrorTask(s);
                taskList.add(errTask);
            }else{
                s.csord__Status__c = inactiveStatus;
                s.LG_ServiceStatus__c = inactiveStatus;
                csord__Subscription__c sub = new csord__Subscription__c(id=s.csord__Subscription__c);
                sub.Billing_Termination_Date__c = DateTime.now();
                sub.Kenan_Response__c=null;
                subsList.add(sub);
            }

        }
        update services;
        update subsList;

        //UMR-885 Delete Termination Sbuscription and Service created by MACD Terminate
        //Commented out as part of SFOM-1555
        // delete terminationServices;
        // delete terminationSubs;

        //Create task for error resolution
        if(!taskList.isEmpty())
			insert taskList;
    }

    private Task createErrorTask(csord__Service__c service){
        Task t = new Task(Subject='Error while terminating a service: '+service.csordtelcoa__Service_Number_Sequence__c);
        t.OwnerId = service.LastModifiedById;
        t.Description = service.csord__Subscription__r.Kenan_Response__c;
        t.ActivityDate = Date.today();
        return t;
    }

}