src/objects/csord__Service__c.object
<CustomObject>
    <description>A model of a service provided to a customer. A Service has a recurring component.</description>
    
    <fields>
        <fullName>LG_Suborder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Suborder</label>
        <referenceTo>csord__Solution__c</referenceTo>
        <relationshipLabel>Services (Suborder)</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_DownloadSpeed__c</fullName>
        <label>Download Speed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Service of this Service.</description>
        <inlineHelpText>The parent Service of this Service.</inlineHelpText>
        <label>Parent Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Child Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/csord__Service_Line_Item__c.object
<CustomObject>
    <description>A billable component of a Service.</description>
    <fields>
        <fullName>csord__End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>csord__Service__c</fullName>
        <description>The parent Service of this ServiceLineItem.</description>
        <inlineHelpText>The parent Service of this ServiceLineItem.</inlineHelpText>
        <label>Service</label>
        <referenceTo>csord__Service__c</referenceTo>
        <relationshipLabel>Service line Items</relationshipLabel>
        <relationshipName>Service_line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>csord__Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Line Item</label>
    <nameField>
        <label>Service Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LG_ScheduleAppComponentController.cls
/******** Controller class for VF component ScheduleAppComponent****
 ***** Author: Neha Arora **********
*********SFOM - 122***********
 * ****************************************************************/

public class LG_ScheduleAppComponentController {
    public Id solId{get;set;}
    public String attribName{get;set;}
    
    public List<csord__Service_Line_Item__c> getserviceLineItems()
    {
        List<csord__Service_Line_Item__c> objs = [SELECT Id, Name, csord__Start_Date__c, csord__End_Date__c 
                                                  FROM csord__Service_Line_Item__c 
                                                  WHERE csord__Service__r.LG_Suborder__c = :solId];

        return objs;

        
    }
    
    //SFOM-2577 - Method to fetch the Service
    public csord__Service__c getProdConfDetails()
    {
        csord__Service__c objs = [SELECT Name, UM_DownloadSpeed__c FROM csord__Service__c WHERE LG_Suborder__c = :solId LIMIT 1];
                                
        return objs;
    }
    
    
}