src/objects/CSPOFA__Orchestration_Process_Template__c.object
<CustomObject>
    <fields>
        <fullName>LG_DecompositionCriteria__c</fullName>
        <description>Used as a criteria for grouping the services to the suborders</description>
        <label>Decomposition Criteria</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>LG_DecompositionCriteria</valueSetName>
        </valueSet>
    </fields>
    <label>Orchestration Process Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Process Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LG_DecompositionCriteria__c.object
<CustomObject>
    <fields>
        <fullName>LG_DecompositionCriteria__c</fullName>
        <description>Used as a criteria for grouping the services to the suborders</description>
        <label>Decomposition Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Set 1 - On-Net</fullName>
                </value>
                <value>
                    <fullName>Set 2 - Legacy</fullName>
                </value>
                <value>
                    <fullName>Set 3 - Mobile</fullName>
                </value>
                <value>
                    <fullName>Set 4</fullName>
                </value>
                <value>
                    <fullName>Set 5 - CaMa Internet</fullName>
                </value>
                <value>
                    <fullName>Set 6 - CaMa Dependent</fullName>
                </value>
                <value>
                    <fullName>Set 7 - JIRA Fiber</fullName>
                </value>
                <value>
                    <fullName>Set 8 - CS Voice</fullName>
                </value>
                <value>
                    <fullName>Set 9 - CaMa Bearer</fullName>
                </value>
                <value>
                    <fullName>Set 10 - VoiceWorks</fullName>
                </value>
                <value>
                    <fullName>Set 11 - Engineers</fullName>
                </value>
                <value>
                    <fullName>Set 12 - JIRA Orchestrated</fullName>
                </value>
                <value>
                    <fullName>Set 13 - JIRA Bearer</fullName>
                </value>
                <value>
                    <fullName>Set 14 - CaMa Mobile</fullName>
                </value>
                <value>
                    <fullName>Set 15 - CaMa Manual</fullName>
                </value>
                <value>
                    <fullName>Set 16 - CaMa OI Manual</fullName>
                </value>
                <value>
                    <fullName>Set 17 - Charges</fullName>
                </value>
                <value>
                    <fullName>Set 18 - Direct to Kenan</fullName>
                </value>
                <value>
                    <fullName>Set 19 - Additional Charges</fullName>
                </value>
                <value>
                    <fullName>Set 20 - BDS Site Process</fullName>
                </value>
                <value>
                    <fullName>Set 21 - VPN Process</fullName>
                </value>
                <value>
                    <fullName>Set 22 - Parent/Category Only</fullName>
                </value>
                <value>
                    <fullName>Set 23 - UM CaMa Bridge Mode</fullName>
                </value>
                <value>
                    <fullName>Set 24 - UM JIRA Fiber Bridge Mode</fullName>
                </value>
                <value>
                    <fullName>Set 17 - BDS Charges</fullName>
                </value>
                <value>
                    <fullName>Set 17 - HPBX Charges</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Decomposition Criteria</label>
    <nameField>
        <displayFormat>DC-{0000}</displayFormat>
        <label>Decomposition Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Decomposition Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/LG_DecompositionCriteria.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Set 1 - On-Net</fullName>
    </customValue>
    <customValue>
        <fullName>Set 2 - Off-Net</fullName>
    </customValue>
    <customValue>
        <fullName>Set 3 - Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Set 4</fullName>
    </customValue>
    <customValue>
        <fullName>Set 6 - CaMa Dependent</fullName>
    </customValue>
    <customValue>
        <fullName>Set 7 - JIRA Fiber</fullName>
    </customValue>
    <customValue>
        <fullName>Set 10 - VoiceWorks</fullName>
    </customValue>
    <customValue>
        <fullName>Set 11 - Engineers</fullName>
    </customValue>
    <customValue>
        <fullName>Set 5 - CaMa Internet</fullName>
    </customValue>
    <customValue>
        <fullName>Set 8 - CS Voice</fullName>
    </customValue>
    <customValue>
        <fullName>Set 9 - CaMa Bearer</fullName>
    </customValue>
    <customValue>
        <fullName>Set 5 - No Grouping</fullName>
    </customValue>
    <customValue>
        <fullName>Set 12 - JIRA Orchestrated</fullName>
    </customValue>
    <customValue>
        <fullName>Set 13 - JIRA Bearer</fullName>
    </customValue>
    <customValue>
        <fullName>Set 14 - CaMa Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Set 15 - CaMa Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Set 16 - CaMa OI Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Set 17 - Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 18 - Direct to Kenan</fullName>
    </customValue>
    <customValue>
        <fullName>Set 22 - Parent/Category Only</fullName>
    </customValue>
    <customValue>
        <fullName>Set 24 - UM JIRA Fiber Bridge Mode</fullName>
    </customValue>
    <customValue>
        <fullName>Set 23 - UM CaMa Bridge Mode</fullName>
    </customValue>
    <customValue>
        <fullName>Set 21 - VPN Process</fullName>
    </customValue>
    <customValue>
        <fullName>Set 20 - BDS Site Process</fullName>
    </customValue>
    <customValue>
        <fullName>Set 19 - Additional Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 25 - Business Anywhere</fullName>
    </customValue>
    <customValue>
        <fullName>Set 17 - HBPX Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 26 - UM Managed WLAN</fullName>
    </customValue>
    <customValue>
        <fullName>Set 17 - BDS Charges</fullName>
    </customValue>
    <customValue>
        <fullName>Set 10 - SIPWISE</fullName>
    </customValue>
    <description>Used as a criteria for grouping the services to the suborders</description>
    <masterLabel>Decomposition Criteria</masterLabel>
</GlobalValueSet>

src/classes/LG_OrchProcessTemplateTriggerHandler.cls
public class LG_OrchProcessTemplateTriggerHandler {
	/**
	 * Checks that the selected value of the LG_DecompositionCriteria__c
	 * field is not already selected on some other Orch. Process Template record.
	 * If so, throws the error.
	 *
	 * @param  List<CSPOFA__Orchestration_Process_Template__c> templates
	 * @param  Map<Id, CSPOFA__Orchestration_Process_Template__c> oldMap
	 * @author Tomislav Blazek
	 * @ticket SFOM-202
	 * @since  15/12/2016
	 */
	public static void checkDecompositionCriteria(List<CSPOFA__Orchestration_Process_Template__c> templates,
												  Map<Id, CSPOFA__Orchestration_Process_Template__c> oldMap)
	{
		Set<CSPOFA__Orchestration_Process_Template__c> applicableTemplates = new Set<CSPOFA__Orchestration_Process_Template__c>();
		Set<String> decompositionCriteriasForQuery                         = new Set<String>();
		/*
		 * Decide which templates should be processed:
		 * - only new templates
		 *      or the ones having a change in the LG_DecompositionCriteria__c field
		 */
		for (CSPOFA__Orchestration_Process_Template__c newTemplate : templates) {
			if (String.isBlank(newTemplate.LG_DecompositionCriteria__c)) {
				continue;
			}
			CSPOFA__Orchestration_Process_Template__c oldTemplate = oldMap == null ? null : oldMap.get(newTemplate.Id);

			if (oldTemplate == null || (oldTemplate.LG_DecompositionCriteria__c != newTemplate.LG_DecompositionCriteria__c)) {
				applicableTemplates.add(newTemplate);
				decompositionCriteriasForQuery.addAll(LG_Util.semicolonSeparatedStringToSet(newTemplate.LG_DecompositionCriteria__c));
			}
		}

		if (!applicableTemplates.isEmpty()) {
			String decCriterias = String.join(new List<String>(decompositionCriteriasForQuery), '\',\'');

			List<CSPOFA__Orchestration_Process_Template__c> existingTemplates;
			String queryString = 'SELECT Id, Name, LG_DecompositionCriteria__c '
								 + 'FROM CSPOFA__Orchestration_Process_Template__c '
								 + 'WHERE LG_DecompositionCriteria__c INCLUDES(\'' + decCriterias +'\')';

			List<CSPOFA__Orchestration_Process_Template__c> orchProcessTemplates =
				(List<CSPOFA__Orchestration_Process_Template__c>)Database.query(queryString);

			//ugly, but had to iterate through all the multiselect picklist values
			for (CSPOFA__Orchestration_Process_Template__c newTemplate : applicableTemplates) {
				for (CSPOFA__Orchestration_Process_Template__c existingTemplate : orchProcessTemplates) {
					if (newTemplate.Id != existingTemplate.Id) {
						boolean errored = false;
						for (String decompCriteria : LG_Util.semicolonSeparatedStringToSet(newTemplate.LG_DecompositionCriteria__c)) {
							if (existingTemplate.LG_DecompositionCriteria__c.contains(decompCriteria)) {
								newTemplate.addError(Label.LG_OrchProcessDecCriteriaError.replace('{templateName}', existingTemplate.Name));
								errored = true;
								break;
							}
						}
						if (errored) {
							break;
						}
					}
				}
			}
		}
	}
}