src/objects/InvoiceItem__x.object
<CustomObject>
    <description>Invoice Line Items from Kenan FX</description>
    <externalDataSource>Kenan_FX_Connection</externalDataSource>
    <externalName>InvoiceItem</externalName>
    <fields>
        <fullName>InvoiceHeader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Header</label>
        <referenceTo>UM_InvoiceHeader__c</referenceTo>
        <relationshipLabel>Invoice Headers</relationshipLabel>
        <relationshipName>Invoice_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>accountExternalId__c</fullName>
        <description>accountExternalId</description>
        <externalDeveloperName>accountExternalId</externalDeveloperName>
        <label>Account External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>amount__c</fullName>
        <description>amount</description>
        <externalDeveloperName>amount</externalDeveloperName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>billRefNo__c</fullName>
        <description>billRefNo</description>
        <externalDeveloperName>billRefNo</externalDeveloperName>
        <label>Bill Ref Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fromDate__c</fullName>
        <description>fromDate</description>
        <externalDeveloperName>fromDate</externalDeveloperName>
        <label>From Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>serviceExternalId__c</fullName>
        <description>serviceExternalId</description>
        <externalDeveloperName>serviceExternalId</externalDeveloperName>
        <label>serviceExternalId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>toDate__c</fullName>
        <description>toDate</description>
        <externalDeveloperName>toDate</externalDeveloperName>
        <label>To Date</label>
        <type>DateTime</type>
    </fields>
    <label>Invoice Item</label>
    <pluralLabel>Invoice Items</pluralLabel>
</CustomObject>

src/classes/KenanInvoiceSearchService.cls
/**
 * Main invoice item search service class
 */
public class KenanInvoiceSearchService implements KenanInvoiceSearch {
	public static final String KEYWORD_WHERE = ' WHERE ';
	public static final String KEYWORD_AND = ' AND ';

	/**
	 * Searches invoices based on certain search criteria 
	 * @param request the request containing the criteria to search
	 * @return a response containing matched invoice items
	 */
	public KenanInvoiceSearchResponse searchInvoices(KenanInvoiceSearchRequest request) {
		KenanInvoiceSearchResponse response = new KenanInvoiceSearchResponse();

		String fieldStr = buildFieldStr(request.invoiceFields);
		String whereClause = buildWhereClause(request);

		String query = 'SELECT InvoiceHeader__c, ' +
						String.escapeSingleQuotes(fieldStr) +
						' FROM InvoiceItem__x' +
						whereClause;
		System.debug(LoggingLevel.WARN, 'QUERY --> ' + query);
		try {
			List<sObject> searchResults;

			// Because we cannot test insert external objects
			if (!Test.isRunningTest()) {
				searchResults = Database.query(query);
			} else {
				searchResults = KenanSampleCode.createSoqlMockedInvoices();
			}
			
			response = buildInvoiceSearchResponse(searchResults);	
		} catch (Exception e) {
			response.success = false;
			response.error = e.getMessage();
		}

		return response;
	}

	/**
	 * Build a comma separated list of field names
	 * @param fields the list of fields to query
	 * @return String
	 */
	private String buildFieldStr(List<String> fields) {
		return String.join(fields, ', ');
	}

	/**
	 * Build a SOSL where clause that contains the object to query and the field filters
	 * @param request the request object containing filter criteria
	 * @return String
	 */
	private String buildWhereClause(KenanInvoiceSearchRequest request) {
		if (String.isEmpty(request.billingAccount) && String.isEmpty(request.invoiceService) && 
			request.fromDate == null && request.toDate == null && 
			request.lowAmount == null && request.highAmount == null &&
			request.billRefNo == null) {
			return '';
		}

		List<String> fieldValues = new List<String>();

		/* 
		 * Once we know where the service is coming from, we can include the search option in the query
		 * Also need to pass in serviceExternalIdType
		 */

		/* 
		if (!String.isEmpty(request.invoiceService)) {
			fieldValues.add('serviceExternalId__c = \'' + String.escapeSingleQuotes(request.invoiceService) + '\'');
		}
		*/

		/*
		 * Once we know where billing account is coming from, we can include the search option in the query
		 * Also need to pass in acctExternalIdType
		 */
		/* 
		if (!String.isEmpty(request.billingAccount)) {
			fieldValues.add('accountExternalId__c = \'' + String.escapeSingleQuotes(request.billingAccount) + '\'');
		}
		*/

		if (!String.isEmpty(request.billRefNo)) {
			fieldValues.add('billRefNo__c = ' + request.billRefNo);
		}

		if (request.fromDate != null) {
			fieldValues.add('fromDate__c = ' + String.escapeSingleQuotes(Datetime.newInstance(request.fromDate.year(),request.fromDate.month(),request.fromDate.day()).format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'')));
		}

		if (request.toDate != null) {
			fieldValues.add('toDate__c = ' + String.escapeSingleQuotes(Datetime.newInstance(request.toDate.year(),request.toDate.month(),request.toDate.day()).format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'')));
		}
		
		if (!String.isEmpty(request.lowAmount)) {
			fieldValues.add('amount__c >= ' + request.lowAmount);
		}
		
		if (!String.isEmpty(request.highAmount)) {
			fieldValues.add('amount__c <= ' + request.highAmount);
		}

		String whereClause = KEYWORD_WHERE + String.join(fieldValues, KEYWORD_AND);

		return whereClause;
	}

	/**
	 * Build the response containing the results of the SOSL query
	 * @param searchResults the list of objects and records as the result of SOSL query
	 * @return KenanInvoiceSearchResponse
	 */
	private KenanInvoiceSearchResponse buildInvoiceSearchResponse(List<sObject> searchResults) {
		KenanInvoiceSearchResponse response = new KenanInvoiceSearchResponse();

		response.invoiceItems = (List<InvoiceItem__x>) searchResults;

		return response;
	}
}