src/objects/KenanServiceConnection__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Authentication_Token__c</fullName>
        <label>Authentication Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_URL__c</fullName>
        <label>Connection URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>REST_Application_Base__c</fullName>
        <defaultValue>&quot;/kenan-salesforce-api&quot;</defaultValue>
        <inlineHelpText>must start with /</inlineHelpText>
        <label>REST Application Base</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Timeout__c</fullName>
        <defaultValue>&quot;120000&quot;</defaultValue>
        <inlineHelpText>Number in milliseconds</inlineHelpText>
        <label>Session Timeout</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>KenanServiceConnection</label>
</CustomObject>

src/classes/KenanEnumerationLoadBatchTest.cls
/**
* @author Copyright(c) Amdocs Development Limited 2016. All rights reserved.
* @date 2016
* @description Kenan Unit Test for use in Salesforce Kenan Connection Service
*/
@isTest
private class KenanEnumerationLoadBatchTest {
	
	@testSetup
	static void setup() {
		// Create common test accounts
        Account samAct = new Account();
		samAct.Name = 'Sample Account';
		insert samAct; 

        KenanServiceConnection__c ksc = new KenanServiceConnection__c();
		ksc.Authentication_Token__c = 'Basic YWRtaW46YWRtaW4=';
		ksc.Session_Timeout__c = '120000';
		ksc.Connection_URL__c = 'https://kenan-dev-pubelb-amdocs-1924041402.eu-central-1.elb.amazonaws.com';
		ksc.REST_Application_Base__c = '/kenan-salesforce-api/rest';
		insert ksc; 
	}

	@isTest
	static void testEnumerationLoadBatch_LoadData() {
		String enumName = 'UnitsTypeBean';

		KenanEnumerationServiceCalloutMock enumerationMock = new KenanEnumerationServiceCalloutMock();
        enumerationMock.enumName = enumName;
        Test.setMock(HttpCalloutMock.class, enumerationMock);
        Test.setMock(WebServiceMock.class, new KenanEnumLoaderCustomMetaDataMock());

		String sessionId = UserInfo.getSessionId(); 

		KenanEnumerationLoadBatch loadBatch = new KenanEnumerationLoadBatch(sessionId, true);

		Test.startTest();
		Database.executeBatch(loadBatch, 200);
		Test.stopTest();
	}

	@isTest
	static void testEnumerationLoadBatch_DoNotLoadData() {
		String enumName = 'UnitsTypeBean';

		KenanEnumerationServiceCalloutMock enumerationMock = new KenanEnumerationServiceCalloutMock();
        enumerationMock.enumName = enumName;
        Test.setMock(HttpCalloutMock.class, enumerationMock);
        Test.setMock(WebServiceMock.class, new KenanEnumLoaderCustomMetaDataMock());

		String sessionId = UserInfo.getSessionId(); 

		KenanEnumerationLoadBatch loadBatch = new KenanEnumerationLoadBatch(sessionId, false);

		Test.startTest();
		Database.executeBatch(loadBatch, 200);
		Test.stopTest();
	}
}