src/objects/Kenan_Adjustment__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Reason__c</fullName>
        <label>Adjustment Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Goodwill credit invoice Complaints</fullName>
                </value>
                <value>
                    <fullName>Goodwill credited disorder</fullName>
                </value>
                <value>
                    <fullName>Goodwill credit counseling</fullName>
                </value>
                <value>
                    <fullName>Goodwill credited Installation</fullName>
                </value>
                <value>
                    <fullName>Cancellation / Termination</fullName>
                </value>
                <value>
                    <fullName>False entry in the system (correction)</fullName>
                </value>
                <value>
                    <fullName>Non provided SLA Entstֲfrist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Adjustment_Type__c</fullName>
        <label>Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>miscellaneous adjustment</fullName>
                </value>
                <value>
                    <fullName>adjustment against recurring charge</fullName>
                </value>
                <value>
                    <fullName>adjustment against non-recurring charge</fullName>
                </value>
                <value>
                    <fullName>adjustment against an adjustment</fullName>
                </value>
                <value>
                    <fullName>adjustment against nondistributed taxes</fullName>
                </value>
                <value>
                    <fullName>adjustment against usage charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>UM_InvoiceHeader__c</referenceTo>
        <relationshipLabel>Adjustments</relationshipLabel>
        <relationshipName>Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>requestStatus__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>disputed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KenanServiceConnection__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Authentication_Token__c</fullName>
        <label>Authentication Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillRefNo_BillRefResets_delimiter__c</fullName>
        <defaultValue>&quot;.&quot;</defaultValue>
        <label>BillRefNo BillRefResets delimiter</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_URL__c</fullName>
        <label>Connection URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>REST_Application_Base__c</fullName>
        <defaultValue>&quot;/kenan-salesforce-api&quot;</defaultValue>
        <inlineHelpText>must start with /</inlineHelpText>
        <label>REST Application Base</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Timeout__c</fullName>
        <defaultValue>&quot;120000&quot;</defaultValue>
        <inlineHelpText>Number in milliseconds</inlineHelpText>
        <label>Session Timeout</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stored_Language_Code__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <description>When an enumeration is converted to display value, we need to understand what the stored language value is.</description>
        <label>Stored Language Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>KenanServiceConnection</label>
</CustomObject>

src/objects/UM_InvoiceHeader__c.object
<CustomObject>
    <description>Extract from Kenan</description>
    <fields>
        <fullName>UM_Customer_SF_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Headers1</relationshipLabel>
        <relationshipName>Invoice_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_InvoiceNumber__c</fullName>
        <description>Unique Kenan 10 digit Invoice Number</description>
        <externalId>true</externalId>
        <label>Invoice Number</label>
        <length>14</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Gross_Currency__c</fullName>
        <description>Outstanding Invoice Amount</description>
        <label>Outstanding Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Gross__c</fullName>
        <description>Outstanding Invoice Amount</description>
        <label>Outstanding Invoice Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Net_Currency__c</fullName>
        <description>Field to show real value of Invoice Amount sent by Kenan</description>
        <label>Gross Total Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Net__c</fullName>
        <description>gross total due</description>
        <label>Gross Total Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Date__c</fullName>
        <description>Date when invoice was issued</description>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UM_Payment_Due_Date__c</fullName>
        <label>Payment Due Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice Header</label>
    <nameField>
        <label>Invoice Headers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KenanAdjustmentServiceTest.cls
/**
* @author Copyright(c) Amdocs Development Limited 2016. All rights reserved.
* @date 2016
* @description KenanAdjustmentService Unit Tests
*/
@isTest
private class KenanAdjustmentServiceTest {
    
    @testSetup
    static void setup() {
        KenanServiceConnection__c ksc = new KenanServiceConnection__c();
        ksc.Authentication_Token__c = 'Basic YWRtaW46YWRtaW4=';
        ksc.Session_Timeout__c = '120000';
        ksc.Connection_URL__c = 'https://dev-aws-oag-pe.upc.biz';
        ksc.REST_Application_Base__c = '/kenan-salesforce-api/rest';
        ksc.Stored_Language_Code__c = '1';
        insert ksc;

        //Account acct = new Account();
        //acct.Name = 'Test Account Name';
        //insert acct;

        //UM_InvoiceHeader__c invoiceHeader = new UM_InvoiceHeader__c();
        //invoiceHeader.UM_Customer_SF_ID__c = acct.Id;
        //invoiceHeader.UM_Invoice_Date__c = Date.today().addDays(-5);
        //invoiceHeader.UM_InvoiceNumber__c = '1.0';
        //invoiceHeader.UM_Invoice_Amount_Gross_Currency__c = 100.00;
        //invoiceHeader.UM_Invoice_Amount_Net_Currency__c = 75.00;
        //invoiceHeader.UM_Invoice_Amount_Gross__c = 100;
        //invoiceHeader.UM_Invoice_Amount_Net__c = 75;
        //invoiceHeader.UM_Payment_Due_Date__c = Date.today().addDays(30);
        //insert invoiceHeader;

        //Kenan_Adjustment__c adj = new Kenan_Adjustment__c();
        //adj.Adjustment_Reason__c = 'Incorrect or unapplied charges';
  //    adj.Adjustment_Type__c = 'miscellaneous adjustment';
  //    adj.requestStatus__c = 'requested';
        //adj.Total_Amount__c = 25;
        //adj.Invoice_Header__c = invoiceHeader.Id;

        //insert adj;
    }

    @isTest
    static void testQuery() {
        KenanAdjustmentService service = new KenanAdjustmentService();

        Test.startTest();
        try {
            DataSource.TableResult result = service.query(null);
            System.assert(false, 'Exception should have been thrown');
        } catch (KenanException ke) {
            System.assert(true, 'Exception was thrown and caught');
            System.assertEquals('KenanAdjustmentService.query has not been implemented', ke.errorName);
            System.assertEquals('KenanAdjustmentService.query has not been implemented', ke.errorMessage);
        }
        Test.stopTest();
    }

    @isTest
    static void testSearch() {
        KenanAdjustmentService service = new KenanAdjustmentService();

        Test.startTest();
        try {
            DataSource.TableResult result = service.search(null, 'Search Phrase');
            System.assert(false, 'Exception should have been thrown');
        } catch (KenanException ke) {
            System.assert(true, 'Exception was thrown and caught');
            System.assertEquals('KenanAdjustmentService.search has not been implemented', ke.errorName);
            System.assertEquals('KenanAdjustmentService.search has not been implemented', ke.errorMessage);
        }
        Test.stopTest();
    }

    @isTest
    static void testDeleteRows() {
        KenanAdjustmentService service = new KenanAdjustmentService();

        Test.startTest();
        try {
            List<DataSource.DeleteResult> result = service.deleteRows(null);
            System.assert(false, 'Exception should have been thrown');
        } catch (KenanException ke) {
            System.assert(true, 'Exception was thrown and caught');
            System.assertEquals('KenanAdjustmentService.deleteRows has not been implemented', ke.errorName);
            System.assertEquals('KenanAdjustmentService.deleteRows has not been implemented', ke.errorMessage);
        }
        Test.stopTest();
    }

    @isTest 
    static void testInsertRow() {
        KenanAdjustmentService service = new KenanAdjustmentService();

        KenanAdjustmentCalloutMock adjustmentMock = new KenanAdjustmentCalloutMock();
        adjustmentMock.numberOfRecords = 1;
        Test.setMock (HttpCalloutMock.class, adjustmentMock);

        Test.startTest();
        KenanAdjustment adjustment = new KenanAdjustment();
        Date curDate = Date.today();
        Decimal amt = 300;
               
        adjustment.accountExternalId = 'accountExternalId';
        adjustment.accountExternalIdType = 1;
        adjustment.accountInternalId = 2;
        adjustment.adjReasonCode = 'Goodwill credited disorder';
        adjustment.billRefNo = 13.0;
        adjustment.billRefResets = 14.0;
        adjustment.currencyCode = 'KRW';
        adjustment.effectiveDate = curDate;
        adjustment.invoiceItem = 'invoiceItem.123.023';
        adjustment.fraudIndicator = 'anotherFraud';
        adjustment.trackingId = 'trackingId';
        adjustment.trackingIdServ = 'trackingIdServ';
        adjustment.totalAmt = amt;
        adjustment.approvedBy = 'Me';
        adjustment.approvalStatus = 'approved';

        KenanObject ko = service.insertRow(adjustment, 'POST', 'CREATE');
        Test.stopTest();

        KenanAdjustment kaInserted = (KenanAdjustment)ko;
        System.assertEquals('extId', kaInserted.accountExternalId);
        System.assertEquals('fraudIndicator', kaInserted.fraudIndicator);
        System.assertEquals('trackingId', kaInserted.trackingId);
        System.assertEquals('trackingIdServ', kaInserted.trackingIdServ);
    }

    @isTest 
    static void testInsertRowDashes() {
        KenanServiceConnection__c settings = KenanServiceConnection__c.getInstance();
        KenanAdjustmentService service = new KenanAdjustmentService();

        KenanAdjustmentCalloutMock adjustmentMock = new KenanAdjustmentCalloutMock();
        adjustmentMock.numberOfRecords = 1;
        Test.setMock (HttpCalloutMock.class, adjustmentMock);

        Test.startTest();
        KenanAdjustment adjustment = new KenanAdjustment();
        Date curDate = Date.today();
        Decimal amt = 300;
               
        adjustment.accountExternalId = 'accountExternalId';
        adjustment.accountExternalIdType = 1;
        adjustment.accountInternalId = 2;
        adjustment.adjReasonCode = 'Goodwill credited disorder';
        adjustment.billRefNo = 13.0;
        adjustment.billRefResets = 14.0;
        adjustment.currencyCode = 'KRW';
        adjustment.effectiveDate = curDate;
        adjustment.invoiceItem = 'invoiceItem' + settings.BillRefNo_BillRefResets_delimiter__c + '123' + settings.BillRefNo_BillRefResets_delimiter__c + '023';
        adjustment.fraudIndicator = 'anotherFraud';
        adjustment.trackingId = 'trackingId';
        adjustment.trackingIdServ = 'trackingIdServ';
        adjustment.totalAmt = amt;
        adjustment.approvedBy = 'Me';
        adjustment.approvalStatus = 'approved';

        KenanObject ko = service.insertRow(adjustment, 'POST', 'CREATE');
        Test.stopTest();

        KenanAdjustment kaInserted = (KenanAdjustment)ko;
        System.assertEquals('extId', kaInserted.accountExternalId);
        System.assertEquals('fraudIndicator', kaInserted.fraudIndicator);
        System.assertEquals('trackingId', kaInserted.trackingId);
        System.assertEquals('trackingIdServ', kaInserted.trackingIdServ);
    }

    @isTest 
    static void testInsertRowError() {
        KenanAdjustmentService service = new KenanAdjustmentService();

        KenanAdjustmentCalloutMockError adjustmentMock = new KenanAdjustmentCalloutMockError();
        Test.setMock (HttpCalloutMock.class, adjustmentMock);

        KenanAdjustment adjustment = new KenanAdjustment();
        Date curDate = Date.today();
        Decimal amt = 300;
               
        adjustment.accountExternalId = 'accountExternalId';
        adjustment.accountExternalIdType = 1;
        adjustment.accountInternalId = 2;
        adjustment.adjReasonCode = 'Goodwill credited disorder';
        adjustment.billRefNo = 13.0;
        adjustment.billRefResets = 14.0;
        adjustment.currencyCode = 'KRW';
        adjustment.effectiveDate = curDate;
        adjustment.fraudIndicator = 'anotherFraud';
        adjustment.trackingId = 'trackingId';
        adjustment.trackingIdServ = 'trackingIdServ';
        adjustment.totalAmt = amt;
        adjustment.approvedBy = 'Me';
        adjustment.approvalStatus = 'approved';


        Test.startTest();
        try {
            KenanObject ko = service.insertRow(adjustment, 'POST', 'CREATE');
            System.assert(false, 'Exception should have been thrown');
        } catch (KenanException ke) {
            System.assert(true, 'Exception was thrown and caught');
        }
        Test.stopTest();
    }

    @isTest 
    static void testUpdateRow() {
        KenanAdjustmentService service = new KenanAdjustmentService();

        KenanAdjustmentCalloutMock adjustmentMock = new KenanAdjustmentCalloutMock();
        adjustmentMock.numberOfRecords = 1;
        Test.setMock (HttpCalloutMock.class, adjustmentMock);

        Test.startTest();
        KenanAdjustment adjustment = new KenanAdjustment();
        Date curDate = Date.today();
               
        adjustment.accountExternalId = 'accountExternalId';
        adjustment.accountExternalIdType = 1;
        adjustment.accountInternalId = 2;
        adjustment.adjReasonCode = 'Goodwill credited disorder';
        adjustment.billRefNo = 13.0;
        adjustment.billRefResets = 14.0;
        adjustment.currencyCode = 'KRW';
        adjustment.effectiveDate = curDate;
        adjustment.fraudIndicator = 'anotherFraud';
        adjustment.trackingId = 'trackingId';
        adjustment.trackingIdServ = 'trackingIdServ';
        adjustment.approvedBy = 'Me';
        adjustment.approvalStatus = 'approved';

        KenanObject ko = service.updateRow(adjustment, 'PUT', 'MODIFY');
        Test.stopTest();

        KenanAdjustment kaUpserted = (KenanAdjustment)ko;
        System.assertEquals('accountExternalId', kaUpserted.accountExternalId);
        System.assertEquals('anotherFraud', kaUpserted.fraudIndicator);
        System.assertEquals('trackingId', kaUpserted.trackingId);
        System.assertEquals('trackingIdServ', kaUpserted.trackingIdServ);
    }

    @isTest 
    static void testUpdateRowError() {
        KenanAdjustmentService service = new KenanAdjustmentService();

        KenanAdjustmentCalloutMockError adjustmentMock = new KenanAdjustmentCalloutMockError();
        Test.setMock (HttpCalloutMock.class, adjustmentMock);

        KenanAdjustment adjustment = new KenanAdjustment();
        Date curDate = Date.today();
               
        adjustment.accountExternalId = 'accountExternalId';
        adjustment.accountExternalIdType = 1;
        adjustment.accountInternalId = 2;
        adjustment.adjReasonCode = 'Goodwill credited disorder';
        adjustment.billRefNo = 13.0;
        adjustment.billRefResets = 14.0;
        adjustment.currencyCode = 'KRW';
        adjustment.effectiveDate = curDate;
        adjustment.fraudIndicator = 'anotherFraud';
        adjustment.trackingId = 'trackingId';
        adjustment.trackingIdServ = 'trackingIdServ';
        adjustment.approvedBy = 'Me';
        adjustment.approvalStatus = 'approved';

        Test.startTest();
        try {
            KenanObject ko = service.updateRow(adjustment, 'PUT', 'MODIFY');
            System.assert(false, 'Exception should have been thrown');
        } catch (KenanException ke) {
            System.assert(true, 'Exception was thrown and caught');
        }
        Test.stopTest();
    }


    @isTest
    static void testDeleteRow() {
        KenanAdjustmentService service = new KenanAdjustmentService();

        Test.startTest();
        try {
            Boolean result = service.deleteRow(null);
            System.assert(false, 'Exception should have been thrown');
        } catch (KenanException ke) {
            System.assert(true, 'Exception was thrown and caught');
            System.assertEquals('KenanAdjustmentService.deleteRow has not been implemented', ke.errorName);
            System.assertEquals('KenanAdjustmentService.deleteRow has not been implemented', ke.errorMessage);
        }
        Test.stopTest();
    }

    @isTest 
    static void testUpsertRows() {
        KenanAdjustmentService service = new KenanAdjustmentService();

        KenanAdjustmentCalloutMock adjustmentMock = new KenanAdjustmentCalloutMock();
        adjustmentMock.numberOfRecords = 1;
        Test.setMock (HttpCalloutMock.class, adjustmentMock);
        
        DataSource.UpsertContext context = new DataSource.UpsertContext();
        List<Map<String,Object>> valuesList = new List<Map<String,Object>>();
        Map<String,Object> objectMap = new Map<String,Object>();
        Date curDate = Date.today();
        Decimal amt = 300;

        objectMap.put('accountExternalId', 'accountExternalId');
        objectMap.put('accountExternalIdType', 1);
        objectMap.put('accountInternalId', 2);
        objectMap.put('adjReasonCode', 'Goodwill credited disorder');
        objectMap.put('billRefNo', 3.0);
        objectMap.put('billRefResets', 4.0);
        objectMap.put('currencyCode', 'KRW');
        objectMap.put('effectiveDate', curDate);
        objectMap.put('fraudIndicator', 'fraudIndicator');
        objectMap.put('invoiceItem', 'invoiceItem.123.023');
        objectMap.put('origType', 'adjustment against an adjustment');
        objectMap.put('openItemId', 'Invoice total');
        objectMap.put('primaryUnits', 'primaryUnits');
        objectMap.put('requestStatus', 'approved');
        objectMap.put('revRcvCostCtr', 'revRcvCostCtr');
        objectMap.put('totalAmt', amt);
        objectMap.put('trackingId', 'trackingId');
        objectMap.put('trackingIdServ', 'trackingIdServ');

        valuesList.add(objectMap);
        Map<String,Object> objectMap2 = new Map<String,Object>();
        objectMap2.put('invoiceItem', 'invoiceItem.134.023');
        valuesList.add(objectMap2);

        context.rows = valuesList;

        Test.startTest();
        List<DataSource.UpsertResult> upsertResult = service.upsertRows(context);
        Test.stopTest();

        System.assertNotEquals(null, upsertResult);
    }

    @isTest 
    static void testUpsertRowsError() {
        KenanAdjustmentService service = new KenanAdjustmentService();

        KenanAdjustmentCalloutMockError adjustmentMock = new KenanAdjustmentCalloutMockError();
        Test.setMock (HttpCalloutMock.class, adjustmentMock);
        
        DataSource.UpsertContext context = new DataSource.UpsertContext();
        List<Map<String,Object>> valuesList = new List<Map<String,Object>>();
        Map<String,Object> objectMap = new Map<String,Object>();
        Date curDate = Date.today();
        Decimal amt = 300;

        objectMap.put('accountExternalId', 'accountExternalId');
        objectMap.put('accountExternalIdType', 1);
        objectMap.put('accountInternalId', 2);
        objectMap.put('adjReasonCode', 'Goodwill credited disorder');
        objectMap.put('billRefNo', 3.0);
        objectMap.put('billRefResets', 4.0);
        objectMap.put('currencyCode', 'KRW');
        objectMap.put('effectiveDate', curDate);
        objectMap.put('fraudIndicator', 'fraudIndicator');
        objectMap.put('invoiceItem', '000000000000000');
        objectMap.put('origType', 'adjustment against an adjustment');
        objectMap.put('openItemId', 'Invoice total');
        objectMap.put('primaryUnits', 'primaryUnits');
        objectMap.put('requestStatus', 'approved');
        objectMap.put('revRcvCostCtr', 'revRcvCostCtr');
        objectMap.put('totalAmt', amt);
        objectMap.put('trackingId', 'trackingId');
        objectMap.put('trackingIdServ', 'trackingIdServ');

        valuesList.add(objectMap);
        Map<String,Object> objectMap2 = new Map<String,Object>();
        objectMap2.put('invoiceItem', 'invoiceItem.134.023');
        valuesList.add(objectMap2);

        context.rows = valuesList;

        Test.startTest();
        List<DataSource.UpsertResult> upsertResult = service.upsertRows(context);
        Test.stopTest();

        System.assertNotEquals(null, upsertResult);
    }
    
}