src/objects/KenanServiceConnection__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Authentication_Token__c</fullName>
        <label>Authentication Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_URL__c</fullName>
        <label>Connection URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>REST_Application_Base__c</fullName>
        <defaultValue>&quot;/kenan-salesforce-api&quot;</defaultValue>
        <inlineHelpText>must start with /</inlineHelpText>
        <label>REST Application Base</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Timeout__c</fullName>
        <defaultValue>&quot;120000&quot;</defaultValue>
        <inlineHelpText>Number in milliseconds</inlineHelpText>
        <label>Session Timeout</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stored_Language_Code__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <description>When an enumeration is converted to display value, we need to understand what the stored language value is.</description>
        <label>Stored Language Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>KenanServiceConnection</label>
</CustomObject>

src/classes/KenanServiceExternalIdMapperTest.cls
@isTest
private class KenanServiceExternalIdMapperTest {
	
	
	@testSetup
	static void setup() {
		KenanServiceConnection__c settings = new KenanServiceConnection__c(
			Authentication_Token__c = 'Basic YWRtaW46YWRtaW4=',
			Session_Timeout__c = '120000',
			Connection_URL__c = 'https://kenan-dev-pubelb-amdocs-1924041402.eu-central-1.elb.amazonaws.com',
			REST_Application_Base__c = '/kenan-salesforce-api/rest',
			Stored_Language_Code__c = '1'
		);

		insert settings;
	}
	
	@isTest
	static void getEnumeratedValuesTest(){
		
		KenanServiceExternalId externalId = new KenanServiceExternalId();
		Datetime curDate = Datetime.now();
		       
        externalId.activeDate = curDate;
        externalId.createDt = curDate;
        externalId.inactiveDate = curDate;
        externalId.intendedViewEffectiveDt = curDate;
        externalId.isCurrent = true;
        externalId.isFromInventory = true;
        externalId.prevViewId = 3;
        externalId.serviceExternalId = 'serviceExternalId';
        externalId.serviceExternalIdType = 2;
        externalId.oldServiceExternalId = 'oldId';
        externalId.oldServiceExternalIdType = 3;
        externalId.serviceInternalId = 30;
        externalId.serviceInternalIdResets = 0;
        externalId.viewId = 4;
        externalId.viewStatus = 5;

		Test.startTest();
		KenanServiceExternalIdMapper mapper = new KenanServiceExternalIdMapper();
		Map<String,Object> objectMap = mapper.getEnumeratedValues(externalId);
		Test.stopTest();
				
		System.assertEquals(objectMap.get('activeDate'), curDate, '');
		System.assertEquals(objectMap.get('createDt'), curDate, '');
		System.assertEquals(objectMap.get('inactiveDate'), curDate, '');
		System.assertEquals(objectMap.get('intendedViewEffectiveDt'), curDate, '');
		System.assertEquals(objectMap.get('isCurrent'), true, '');
		System.assertEquals(objectMap.get('isFromInventory'), true, '');
		System.assertEquals(objectMap.get('prevViewId'), 3, '');
		System.assertEquals(objectMap.get('serviceExternalId'), 'serviceExternalId', '');
		System.assertEquals(objectMap.get('serviceExternalIdType'), 2, '');
		//System.assertEquals(objectMap.get('oldServiceExternalId'), 'oldId', '');
		//System.assertEquals(objectMap.get('oldServiceExternalIdType'), 3, '');
		System.assertEquals(objectMap.get('serviceInternalId'), 30, '');
		System.assertEquals(objectMap.get('serviceInternalIdResets'), 0, '');
		System.assertEquals(objectMap.get('viewId'), 4, '');
		System.assertEquals(objectMap.get('viewStatus'), 5, '');
	}
	
	@isTest
	static void getDisplayValuesTest(){
		
		Map<String,Object> objectMap = new Map<String,Object>();
        Datetime curDate = Datetime.now();
		String curDateString = curDate.format('yyyy-MM-dd\'T\'HH:mm:ss.SSS');

        objectMap.put('activeDate', curDateString);
		objectMap.put('createDt', curDateString);
		objectMap.put('inactiveDate', curDateString);
		objectMap.put('intendedViewEffectiveDt', curDateString);
		objectMap.put('isCurrent', true);
		objectMap.put('isFromInventory', true);
		objectMap.put('prevViewId', 3);
		objectMap.put('serviceExternalId', 'serviceExternalId');
		objectMap.put('serviceExternalIdType', 2);
		objectMap.put('oldServiceExternalId', 'oldId');
		objectMap.put('oldServiceExternalIdType', 3);
		objectMap.put('serviceInternalId', 30);
		objectMap.put('serviceInternalIdResets', 0);
		objectMap.put('viewId', 4);
		objectMap.put('viewStatus', 5);

        Test.startTest();
        KenanServiceExternalIdMapper mapper = new KenanServiceExternalIdMapper();
        KenanServiceExternalId externalId = mapper.getDisplayValues(objectMap);
        Test.stopTest();

		System.assertEquals(externalId.activeDate, curDate, '');
        System.assertEquals(externalId.createDt, curDate, '');
        System.assertEquals(externalId.inactiveDate, curDate, '');
        System.assertEquals(externalId.intendedViewEffectiveDt, curDate, '');
        System.assertEquals(externalId.isCurrent, true, '');
        System.assertEquals(externalId.isFromInventory, true, '');
        System.assertEquals(externalId.prevViewId, 3, '');
        System.assertEquals(externalId.serviceExternalId, 'serviceExternalId', '');
        System.assertEquals(externalId.serviceExternalIdType, 2, '');
        //System.assertEquals(externalId.oldServiceExternalId, 'oldId', '');
        //System.assertEquals(externalId.oldServiceExternalIdType, 3, '');
        System.assertEquals(externalId.serviceInternalId, 30, '');
        System.assertEquals(externalId.serviceInternalIdResets, 0, '');
        System.assertEquals(externalId.viewId, 4, '');
        System.assertEquals(externalId.viewStatus, 5, '');
	}
}