src/objects/Kenan_Adjustment__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Reason__c</fullName>
        <label>Adjustment Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Goodwill credit invoice Complaints</fullName>
                </value>
                <value>
                    <fullName>Goodwill credited disorder</fullName>
                </value>
                <value>
                    <fullName>Goodwill credit counseling</fullName>
                </value>
                <value>
                    <fullName>Goodwill credited Installation</fullName>
                </value>
                <value>
                    <fullName>Cancellation / Termination</fullName>
                </value>
                <value>
                    <fullName>False entry in the system (correction)</fullName>
                </value>
                <value>
                    <fullName>Non provided SLA Entstֲfrist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Adjustment_Type__c</fullName>
        <label>Adjustment Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>miscellaneous adjustment</fullName>
                </value>
                <value>
                    <fullName>adjustment against recurring charge</fullName>
                </value>
                <value>
                    <fullName>adjustment against non-recurring charge</fullName>
                </value>
                <value>
                    <fullName>adjustment against an adjustment</fullName>
                </value>
                <value>
                    <fullName>adjustment against nondistributed taxes</fullName>
                </value>
                <value>
                    <fullName>adjustment against usage charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>UM_InvoiceHeader__c</referenceTo>
        <relationshipLabel>Adjustments</relationshipLabel>
        <relationshipName>Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>requestStatus__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>disputed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>trackingIdServ__c</fullName>
        <label>trackingIdServ</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>trackingId__c</fullName>
        <externalId>true</externalId>
        <label>trackingId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KenanServiceConnection__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Authentication_Token__c</fullName>
        <label>Authentication Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Connection_URL__c</fullName>
        <label>Connection URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>REST_Application_Base__c</fullName>
        <defaultValue>&quot;/kenan-salesforce-api&quot;</defaultValue>
        <inlineHelpText>must start with /</inlineHelpText>
        <label>REST Application Base</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Timeout__c</fullName>
        <defaultValue>&quot;120000&quot;</defaultValue>
        <inlineHelpText>Number in milliseconds</inlineHelpText>
        <label>Session Timeout</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stored_Language_Code__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <description>When an enumeration is converted to display value, we need to understand what the stored language value is.</description>
        <label>Stored Language Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>KenanServiceConnection</label>
</CustomObject>

src/objects/UM_InvoiceHeader__c.object
<CustomObject>
    <description>Extract from Kenan</description>
    <fields>
        <fullName>UM_Customer_SF_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Headers1</relationshipLabel>
        <relationshipName>Invoice_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UM_InvoiceNumber__c</fullName>
        <description>Unique Kenan 10 digit Invoice Number</description>
        <externalId>true</externalId>
        <label>Invoice Number</label>
        <length>14</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Gross_Currency__c</fullName>
        <description>Outstanding Invoice Amount</description>
        <label>Outstanding Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Gross__c</fullName>
        <description>Outstanding Invoice Amount</description>
        <label>Outstanding Invoice Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Net_Currency__c</fullName>
        <description>Field to show real value of Invoice Amount sent by Kenan</description>
        <label>Gross Total Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Amount_Net__c</fullName>
        <description>gross total due</description>
        <label>Gross Total Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UM_Invoice_Date__c</fullName>
        <description>Date when invoice was issued</description>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UM_Payment_Due_Date__c</fullName>
        <label>Payment Due Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice Header</label>
    <nameField>
        <label>Invoice Headers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KenanAdjustmentProcessBuilderTest.cls
@isTest
private class KenanAdjustmentProcessBuilderTest {
    
    @testSetup
    static void setup() {
        KenanServiceConnection__c settings = new KenanServiceConnection__c(
            Authentication_Token__c = 'Basic YWRtaW46YWRtaW4=',
            Session_Timeout__c = '120000',
            Connection_URL__c = 'https://kenan-dev-pubelb-amdocs-1924041402.eu-central-1.elb.amazonaws.com',
            REST_Application_Base__c = '/kenan-salesforce-api/rest',
            Stored_Language_Code__c = '1'
        );
        insert settings;

        Account acct = new Account();
        acct.Name = 'Test Account Name';
        insert acct;


        UM_InvoiceHeader__c invoiceHeader = new UM_InvoiceHeader__c();
        invoiceHeader.UM_Customer_SF_ID__c = acct.Id;
        invoiceHeader.UM_Invoice_Date__c = Date.today().addDays(-5);
        invoiceHeader.UM_InvoiceNumber__c = '1.0';
        invoiceHeader.UM_Invoice_Amount_Gross_Currency__c = 100.00;
        invoiceHeader.UM_Invoice_Amount_Net_Currency__c = 75.00;
        invoiceHeader.UM_Invoice_Amount_Gross__c = 100;
        invoiceHeader.UM_Invoice_Amount_Net__c = 75;
        invoiceHeader.UM_Payment_Due_Date__c = Date.today().addDays(30);
        insert invoiceHeader;

        Kenan_Adjustment__c adj = new Kenan_Adjustment__c();
        adj.trackingId__c = '123';
        adj.trackingIdServ__c = '1';
        adj.Adjustment_Reason__c = 'Incorrect or unapplied charges';
        adj.Adjustment_Type__c = 'miscellaneous adjustment';
        adj.RequestStatus__c = 'requested';
        adj.Total_Amount__c = 25;
        adj.Invoice_Header__c = invoiceHeader.Id;

        insert adj;
    }

    @isTest
    static void testUpdateAdjustment() {
        List<Kenan_Adjustment__c> adjustments = new List<Kenan_Adjustment__c>([SELECT Id, trackingId__c, trackingIdServ__c FROM Kenan_Adjustment__c]);
        Exception ke;
        Test.startTest();
        try {
            KenanAdjustmentProcessBuilder.updateAdjustment(adjustments);    
        }
        catch (Exception e){
            ke = e;
        }
        
        Test.stopTest();
        System.assertEquals(null, ke);
    }

    @isTest
    static void testUpdateAdjustmentCallout() {
        Kenan_Adjustment__c adjustment = [SELECT Id, trackingId__c, trackingIdServ__c FROM Kenan_Adjustment__c LIMIT 1];
        Exception ke;
        Test.startTest();
        try {
            KenanAdjustmentProcessBuilder.updateAdjustmentCallout(adjustment.Id);
        }
        catch (Exception e){
            ke = e;
        }

        Test.stopTest();
        System.assertEquals(null, ke);
    }

    @isTest
    static void testUpdateAdjustmentCalloutError() {
        Kenan_Adjustment__c adjustment = [SELECT Id, trackingId__c, trackingIdServ__c FROM Kenan_Adjustment__c LIMIT 1];
        Exception ke;
        Test.startTest();
        try {
            KenanAdjustmentProcessBuilder.updateAdjustmentCallout(adjustment.Id);
        }
        catch (Exception e){
            ke = e;
        }
        Test.stopTest();
        System.assertEquals(null, ke);
    }

    @isTest
    static void testSendEmailNotification() {
        Kenan_Adjustment__c adjustment = [SELECT Id, trackingId__c, trackingIdServ__c FROM Kenan_Adjustment__c LIMIT 1];
        KenanException ke = new KenanException();
        Test.startTest();
        KenanAdjustmentProcessBuilder.sendEmailNotification(adjustment, ke);
        Test.stopTest();
    }
    
}