src/objects/LG_CalloutSystemFailures__c.object
<CustomObject>
    <description>This object will have all the technical failures of services in ESS journey</description>
    <fields>
        <fullName>LG_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Callout System Failures</relationshipLabel>
        <relationshipName>LG_CalloutSystemFailures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_ErrorCode__c</fullName>
        <inlineHelpText>Service Call System Error Code</inlineHelpText>
        <label>Error Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_ErrorDescription__c</fullName>
        <inlineHelpText>Service Callout System error code description</inlineHelpText>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LG_OpportunityOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LG_CalloutSystemFailures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Callout System Failures</relationshipLabel>
        <relationshipName>LG_CalloutSystemFailures</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LG_RequestMessage__c</fullName>
        <inlineHelpText>Refers to the request message of the service call</inlineHelpText>
        <label>Request Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LG_ResponseMessage__c</fullName>
        <label>Response Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>LG_ServiceName__c</fullName>
        <label>Service Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LG_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LG_TypeOfService__c</fullName>
        <inlineHelpText>Refers to identifying the service which has failed</inlineHelpText>
        <label>Type of Service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debt Check</fullName>
                </value>
                <value>
                    <fullName>Equifax Company Lookup</fullName>
                </value>
                <value>
                    <fullName>Equifax Address Lookup</fullName>
                </value>
                <value>
                    <fullName>DNA Address</fullName>
                </value>
                <value>
                    <fullName>Credit Check Result</fullName>
                </value>
                <value>
                    <fullName>Credit Check Business</fullName>
                </value>
                <value>
                    <fullName>Payment Direct Debit</fullName>
                </value>
                <value>
                    <fullName>Initiate Card Payment</fullName>
                </value>
                <value>
                    <fullName>Card Payment Result</fullName>
                </value>
                <value>
                    <fullName>Refund Card Payment</fullName>
                </value>
                <value>
                    <fullName>Reverse Card Payment</fullName>
                </value>
                <value>
                    <fullName>Fraud Check</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Callout System Failure</label>
    <nameField>
        <displayFormat>CFR-{000000000}</displayFormat>
        <label>Callout Failure Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout System Failures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_ServiceTechnicalFailure.cls
/************************************************************
* File Name     : LG_ServiceTechnicalFailure
* Description   : This class creates Callout System Failure records based on the serives failures

* @author       :  Infosys limited
* Modification Log
* version 1.1   : Team Assisted Care (14th AUG 2017) -- UM  
*****************************************************************/
public Class LG_ServiceTechnicalFailure{
    //8 arguments -- AC team need last three everything else will be null for the record.
    public Static void createCalloutFailureResult(String oppid,String oppOwnerID, String accountID,String serviceName,String code,String description,String request,String response){
        System.debug(oppid +'-*-'+oppOwnerID+'-*-'+accountID+'-*-'+serviceName+'-*-'+code+'-*-'+description);
        System.debug('request#--'+request );
        System.debug(' response#--'+response );
        /* Not needed for care track
if(oppid!=null && serviceName!=null && Code!=null && description!=null && oppid!='' && serviceName!='' && Code!='' && description!=''){
map<String,LG_CalloutTechnicalFailure__c> allTechnicalFailuresMap=LG_CalloutTechnicalFailure__c.getall();
if(allTechnicalFailuresMap.containsKey(serviceName+':'+Code)){
LG_CalloutTechnicalFailure__c CallOutFail=allTechnicalFailuresMap.get(serviceName+':'+Code);
Group ITTeamQueue= [Select iD from Group where Name='IT Team Queue' and Type = 'Queue' lIMIT 1]; */
        LG_CalloutSystemFailures__c callSysFail=new LG_CalloutSystemFailures__c();
        //callSysFail.OwnerID=CallOutFail.LG_Queueid__c;
        callSysFail.LG_Status__c='Open';
        if(oppid != null && oppid != '')
            callSysFail.LG_Opportunity__c=oppid;
        if(oppOwnerID!=null && oppOwnerID!=''){
            callSysFail.LG_OpportunityOwner__c=oppOwnerID;
        }
        if(accountID!=null && accountID!=''){
            callSysFail.LG_Account__c=accountID;
        }
        if(request != null && request != '')
            callSysFail.LG_RequestMessage__c=request;
        if(response != null && response != '')
            callSysFail.LG_ResponseMessage__c=response;
        //callSysFail.LG_TypeOfService__c=CallOutFail.LG_ServiceType__c;
        if(code != null && code != '')
            callSysFail.LG_ErrorCode__c=code;
        if(description != null && description != '')
            callSysFail.LG_ErrorDescription__c=description;
        if(serviceName != null && serviceName != '')
            callSysFail.LG_ServiceName__c=serviceName;
        /* Not needed for care track
updating Opportunity Status and Dashboard error meassage field
opportunity opp=new opportunity();
opp.id=oppid;
opp.LG_Opportunity_Status__c=CallOutFail.LG_ConditionFieldValue__c;
opp.LG_DashboardTechnicalError__c=code+' '+CallOutFail.LG_Description__c+' : '+CallOutFail.LG_ErrorMessage__c;
*/
        System.debug('####### callSysFail'+callSysFail);
        try{
            insert callSysFail;
            //update opp;
        }catch(Exception ex){
            System.debug('## Exception in LG_ServiceTechnicalFailure:'+ex);
        }
        //}
        //}  
        
    }
    
    
}