src/objects/LG_QOS_Template__c.object
<CustomObject>
    <description>This object has the QOS template fields which are used in products for mapping the fields like bandwidth etc...</description>
    <fields>
        <fullName>Low_Loss_Traffic_MB_Sec__c</fullName>
        <label>Low Loss Traffic MB/Sec</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Definition_Name__c</fullName>
        <label>Product Definition Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BDS Standort</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qos_Type__c</fullName>
        <label>Qos Type</label>
        <length>49</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Downstream_Bandwidth_MB_Sec__c</fullName>
        <label>Total Downstream Bandwidth MB/Sec</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Upstream_Bandwidth_MB_Sec__c</fullName>
        <label>Total Upstream Bandwidth MB/Sec</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Voice_Traffic__c</fullName>
        <label>Voice Traffic MB/Sec</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>LG_QOS_Template</label>
    <nameField>
        <displayFormat>QOS-{0000}</displayFormat>
        <label>LG_QOS_Template Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QosTemplates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_QOSTemplateController.cls
public class LG_QOSTemplateController
{

    public List<LG_QOS_Template__c> standortqosList = new List<LG_QOS_Template__c>();
    public String standortproductDefName = 'BDS Standort';
    
    
     public List<LG_QOS_Template__c> getStandortqosList(){
     
     
         List<LG_QOS_Template__c> qos =  [select id, Qos_Type__c,Low_Loss_Traffic_MB_Sec__c, Total_Downstream_Bandwidth_MB_Sec__c, Total_Upstream_Bandwidth_MB_Sec__c, Voice_Traffic__c from LG_QOS_Template__c where Product_Definition_Name__c=:standortproductDefName order by Total_Downstream_Bandwidth_MB_Sec__c ];
         
         System.debug('Aswin QOS is:'+qos +' And prodName is:'+standortproductDefName);
         
         return qos;
     }



}