src/objects/LG_QOS_Template__c.object
<CustomObject>
    <description>This object has the QOS template fields which are used in products for mapping the fields like bandwidth etc...</description>
    <fields>
        <fullName>Product_Definition_Name__c</fullName>
        <label>Product Definition Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BDS Standort</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qos_Type__c</fullName>
        <label>Qos Type</label>
        <length>49</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LG_QOS_Template</label>
    <nameField>
        <displayFormat>QOS-{0000}</displayFormat>
        <label>LG_QOS_Template Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QosTemplates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LG_QOSTemplateControllerTest.cls
@isTest 
public class LG_QOSTemplateControllerTest 
{
	static testMethod void testMethod1() 
	{
		LG_QOS_Template__c  qos = new LG_QOS_Template__c();
        qos.Product_Definition_Name__c='BDS Standort';
		qos.Qos_Type__c	='Classic';

		insert qos;
		
		Test.StartTest(); 

			ApexPages.currentPage().getParameters().put('id', String.valueOf(qos.Id));
			LG_QOSTemplateController  testqostemp = new LG_QOSTemplateController();
			testqostemp.getStandortqosList();
			

		Test.StopTest();
	}
}