src/objects/LG_ServiceRequestUrl__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>URL for REST API call from Service Availability Visualforce Page</description>
    <fields>
        <fullName>LG_LocalizationClass__c</fullName>
        <description>Holds the name of the implementation class that extends the LG_EndpointResolver class and that holds the overridden getAddressCheckEndpoint and getAvailabilityCheckEndpoint methods responsible for concatenating and creating the complete endpoint url.</description>
        <label>Localization class</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Service Request URL</label>
</CustomObject>

src/classes/LG_EndpointResolverTest.cls
/**
 *Test Class for LG_EndpointResolver
 * 
 * @author Preetha N
 * @since  24/10/2017
*/
@isTest
public class LG_EndpointResolverTest {
    public static testmethod void resoltest(){
      test.startTest();
      LG_ServiceRequestUrl__c req=new LG_ServiceRequestUrl__c();
     req.LG_LocalizationClass__c='LG_EndpointResolver';
     insert req;
     LG_EndpointResolver.getInstance();
    test.stopTest();
        
    }
}